MM-41244: Simplify run status post
mattermost/mattermost-plugin-playbooks pull request #1007
Opened 2022-01-26 17:18 UTC by lieut-data

#### Summary
Further simplifications to the run status post to optimize for threads view:

<img width="413" alt="CleanShot 2022-01-26 at 13 16 43@2x" src="https://user-images.githubusercontent.com/1023171/151213154-01dbf047-c3cd-44bf-97ee-25e4e4b999a1.png">

<img width="420" alt="CleanShot 2022-01-26 at 13 17 03@2x" src="https://user-images.githubusercontent.com/1023171/151213196-f8578005-8dcb-4b58-bf95-8aeea5bb0cbe.png">

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41244

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2022-01-27 16:16 UTC, iomodo approved these changes

2022-01-27 17:45 UTC, gbochora approved these changes
Just one question. It seems status posts will not contain a public channel link anymore. 
Is there another way to join the channel from threads, or there is no need for such link?

2022-01-27 20:41 UTC, abhijit-singh requested changes
It personally throws me off when I mean to check an update and the text I see is `@someone ran this playbook`. I just checked and if we make it an h5 (#####), it has almost the same sizing but doesn't show the second line of text in the thread list view. I'd prefer it and it also looks less cluttered like that.
![image](https://user-images.githubusercontent.com/14369607/151440147-f035912f-5c80-4bf6-a18c-22632e32346d.png)


@gbochora, I think it is okay to let the users go to the `run page` from the message and then join the channel from there.

2022-01-28 06:13 UTC, gbochora commented
> @gbochora, I think it is okay to let the users go to the `run page` from the message and then join the channel from there.
Cool, thanks for the answer : )

2022-03-03 00:58 UTC, abhijit-singh approved these changes

2022-03-03 14:13 UTC, merged