MM-41036: Render update request post in threads
mattermost/mattermost-plugin-playbooks pull request #1008
Opened 2022-01-26 20:28 UTC by lieut-data

#### Summary
The update request custom post failed to render in the threads view because it depended on `currentPlaybookRun`, of which there isn't one outside of a playbook run channel.

**Before:**
<img width="1184" alt="CleanShot 2022-01-26 at 16 27 15@2x" src="https://user-images.githubusercontent.com/1023171/151241675-1b69bea3-c0f7-4179-b06e-34897bc01243.png">

**After:**
<img width="1187" alt="CleanShot 2022-01-26 at 16 27 31@2x" src="https://user-images.githubusercontent.com/1023171/151241687-ad65f4d4-e44d-459d-992d-38e0757f7375.png">

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-41036

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2022-01-26 21:11 UTC, cpoile approved these changes
Cool!

2022-01-26 22:41 UTC, calebroseland approved these changes

2022-02-28 20:47 UTC, lieut-data commented
/update-branch

2022-03-01 15:55 UTC, Phrynobatrachus requested changes

2022-03-01 15:55 UTC, Phrynobatrachus commented on tests-e2e/cypress/support/api/user.js
> +            cy.apiSaveUserPreference([{user_id: createdUser.id, category: 'crt_tutorial_triggered', name: createdUser.id, value: '999'}], createdUser.id);
Can you put this in `apiDisableTutorials` instead please? Or if there's enough overlap between `hideOnboarding` and `bypassTutorial`, maybe all of that could be combined?

2022-03-02 16:39 UTC, lieut-data commented on tests-e2e/cypress/support/api/user.js
> +            cy.apiSaveUserPreference([{user_id: createdUser.id, category: 'crt_tutorial_triggered', name: createdUser.id, value: '999'}], createdUser.id);
Ooh, good catch -- much cleaner! I opted to inline into `apiDisableTutorials` for now.

2022-03-02 19:06 UTC, Phrynobatrachus approved these changes

2022-03-02 19:07 UTC, merged