Prefer native `href` links where possible
mattermost/mattermost-plugin-playbooks pull request #1011
Opened 2022-01-31 04:19 UTC by Pinjasaur

#### Summary
I manually audited instances of `navigateToUrl` _and_ `navigateToPluginUrl` to see where it would be straightforward to drop-in a native `<a href="...">`-style link. The benefit being native hyperlinks allow for "open in new tab" workflows which is a better UX.

Unfortunately, many of the programmatic `onClick`-style still remain. This is due to the notion of "changing the URL" to be tied to other things e.g. `dispatch`-ing the Redux store and/or firing off telemetry events. Also, many of the components are styled at a high-level to be `<button>`s and swapping in a `<a>` isn't a 1:1.

I think it's certainly do-able to swap over the majority of `navigate{Plugin}ToUrl` instances to be `href`s but would be a considerably larger task given the need to refactor some of the components to _accept_ an `href` prop.

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/19169

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
~~- [ ] Unit tests updated~~

2022-01-31 04:19 UTC, mattermod commented
Hello @Pinjasaur,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-02-03 11:01 UTC, agarciamontoro reviewed
Thank you for taking a look at this, @Pinjasaur, it's a lot of work to review those one by one. The code you added looks good, although the `RHSListView` component seems to be unused code, actually. I'll open a PR to remove it.

Did you have a chance to look at the Run details link in the RHS header (the one in the screenshot)? If so, what was the problem with that one?

![image](https://user-images.githubusercontent.com/3924815/152330302-4d169506-d8ae-44dd-84eb-b98f37934e2a.png)

2022-02-03 15:00 UTC, lieut-data requested changes
Thanks, @Pinjasaur, especially for the overview on the other places in the code where these changes weren't as straightforward. A few comments below.

2022-02-03 18:10 UTC, agarciamontoro commented
@Pinjasaur, the PR #1018 created some conflicts here, as expected. If you're ok with it, I can fix them myself tomorrow :)

2022-02-03 19:00 UTC, Pinjasaur commented
> @Pinjasaur, the PR #1018 created some conflicts here, as expected. If you're ok with it, I can fix them myself tomorrow :)

Good with me—thanks @agarciamontoro. Aiming to get the rest of the feedback on this PR buttoned up by then. 🙂

2022-02-03 23:55 UTC, Pinjasaur commented
> The code you added looks good, although the `RHSListView` component seems to be unused code, actually. I'll open a PR to remove it.

Good catch, thanks.

> Did you have a chance to look at the Run details link in the RHS header (the one in the screenshot)? If so, what was the problem with that one?
> 
> ![image](https://user-images.githubusercontent.com/3924815/152330302-4d169506-d8ae-44dd-84eb-b98f37934e2a.png)

I revisited this with fresh eyes and was able to come up with a reasonable solution by creating a `<RHSTitleLink>` component based off of the `<RHSTitleText>` but styles a `<Link>` instead of a `<button>`. I also took the opportunity to remove a `fill: ...` CSS statement as those are only relevant for SVG, not 'normal' HTML elements.

2022-02-03 23:58 UTC, Pinjasaur commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +                            <Link
Sorry, realized I forgot to remove the now-unused `PlaybookDiv`. 🤦🏻

I used the same strategy as `RHSTitleLink` and renamed `PlaybookDiv` -> `PlaybookLink` which is a styled `Link`. This also removes those 2 inlined CSS statements.

2022-02-04 00:00 UTC, Pinjasaur commented on server/app/playbook_run_service.go
> +		return errors.Wrap(err, "failed to write status post to store. There is now inconsistent state")
Yeah, 100% agree. I tried to be proactive by having the change as a single commit but I also realize, as you mentioned, it's not a related change. My reasoning was `make check-style` wasn't working without the change and that was documented as one of the pre-reqs for opening a PR.

What's the recommendation? Off the top of my head, I could cherry pick that commit into a separate PR and revert it from _this_ PR.

2022-02-04 10:40 UTC, agarciamontoro commented
@Pinjasaur, heads-up that I merged master, removing the file that was deleted in #1018 and fixing a conflict with the error message in playbook_run_service, which was actually fixed in master a couple of days ago, in #937 :)

2022-02-04 10:41 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +		return errors.Wrap(err, "failed to write status post to store. There is now inconsistent state")
This was actually fixed in #937, so no need to do anything else here!

2022-02-04 11:06 UTC, agarciamontoro requested changes
Looks great, thank you for all your work on this, @Pinjasaur!

I only left one comment below about the use of important in the CSS.

2022-02-04 11:06 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_title.tsx
> +    color: var(--center-channel-color) !important;
Do we need the `!important` here? If so, styled-components usually tackle these type of issues by incrementing specificity by doing something like
```css
&&& {
    color: var(--center-channel-color) !important;
}
```

2022-02-04 13:29 UTC, lieut-data commented on server/app/playbook_run_service.go
> +		return errors.Wrap(err, "failed to write status post to store. There is now inconsistent state")
Oh wow, I had no idea `make check-style` was broken here -- your reasoning for including totally made sense. Thanks, @Pinjasaur!

2022-02-04 13:30 UTC, lieut-data approved these changes

2022-02-04 15:45 UTC, Pinjasaur commented on webapp/src/components/rhs/rhs_title.tsx
> +    color: var(--center-channel-color) !important;
Thanks for the suggestion. `&&` did the trick. 🙂

2022-02-04 15:59 UTC, agarciamontoro approved these changes
I was going to say that we needed three `&`, not two, but you beat me to it!

Great work, @Pinjasaur, thank you again for your contribution!

2022-02-04 16:00 UTC, agarciamontoro commented
/update-branch

2022-02-04 16:06 UTC, merged