MM-40841, MM-40916: Templates Selector, FTUE flow
mattermost/mattermost-plugin-playbooks pull request #1014
Opened 2022-01-31 23:30 UTC by calebroseland

#### Summary
- Updated Template Selector
- FTUE contents and flow improvements

![CleanShot 2022-01-31 at 17 07 10](https://user-images.githubusercontent.com/11724372/151889900-6e9a6441-8962-4d95-987b-0418e5847532.gif)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-40841
- https://mattermost.atlassian.net/browse/MM-40916

#### Checklist

Item | Y / N / NA [^1]
---|---
Telemetry updated? | 
Gated by experimental feature flag? | N
Unit/E2E tests updated? | 

[^1]: Yes / No / Not Applicable.

2022-02-03 17:44 UTC, crspeller approved these changes
Nice! Just a couple nits.

2022-02-03 17:44 UTC, crspeller commented on webapp/src/components/backstage/playbook_list.tsx
> +const PlaybookList = (props: {ftue?: boolean}) => {
Confusing if I don't know what `ftue` stands for. Maybe do `firstTimeUser`?

2022-02-03 17:44 UTC, crspeller commented on webapp/src/components/templates/template_selector.tsx
> +	/* grid-template-rows: repeat(auto-fill, minmax(256px, 1fr)); */
Nit: remove

2022-02-03 17:44 UTC, crspeller commented on webapp/src/components/templates/template_selector.tsx
> +export function isPlaybookCreationAllowed(allowPlaybookCreationInTeams: Map<string, boolean>) {
Probably doesn't belong here.

2022-02-07 10:08 UTC, iomodo commented on webapp/src/components/assets/illustrations/dumpster_fire_svg.tsx
> +            fill='#1F5C43'
Should these colours be theme independent?

2022-02-07 10:27 UTC, iomodo commented on webapp/src/components/backstage/runs_page.tsx
> +    if (showNoPlaybookRuns === true) {
Do we need `true` here?

2022-02-07 13:27 UTC, abhijit-singh requested changes
Looks great @calebroseland! Added some minor comments and a couple more requests:
1. Can we add a hover state to the cards like in the designs:
![image](https://user-images.githubusercontent.com/14369607/152795566-d105e15c-2804-448d-bbae-391bd7e6bee6.png)
2. For the `Recommended for beginners` tag, can we hardcode the text color to `#CC8F00`. It should work in light and dark themes based on my tests in Figma. If not, we can leave it as is.

2022-02-07 13:27 UTC, abhijit-singh commented on webapp/src/components/templates/template_item.tsx
> +    aspect-ratio: 284 / 320;
We can make this `aspect-ratio: 284 / 300;`
The cards seem too tall right now with the higher width.

2022-02-08 22:31 UTC, calebroseland commented on webapp/src/components/backstage/runs_page.tsx
> +    if (showNoPlaybookRuns === true) {
Not anymore (did when the return null was after these redirect checks)

2022-02-08 22:36 UTC, calebroseland commented
re: 1. Will add hover state ✓.
re: 2. I can, but it in dark themes it feels a bit too low-contrast (ratio: 3.12)
<img width="365" alt="CleanShot 2022-02-08 at 16 24 26@2x" src="https://user-images.githubusercontent.com/11724372/153086024-5de5ee99-8ca7-44d7-bc7c-33b995f524bf.png">

2022-02-10 00:18 UTC, calebroseland commented on webapp/src/components/assets/illustrations/dumpster_fire_svg.tsx
> +            fill='#1F5C43'
I didn't see any themed colors specifically re: these template illustrations, but I did make the rocket_man shadow themed which wasn't showing earlier. Thanks for mentioning!
<img width="203" alt="CleanShot 2022-02-09 at 18 17 45@2x" src="https://user-images.githubusercontent.com/11724372/153312700-0ce5d999-3524-443e-a1df-c5ef2e33ace4.png">

2022-02-10 00:21 UTC, calebroseland commented
@abhijit-singh cc @iomodo to keep things moving I'm going to go ahead and merge now after the latest revisions—thanks for the callouts! Any follow up changes/iterations can be done as-needed.

2022-02-10 00:27 UTC, merged