[MM-41261] Add toast functionality
mattermost/mattermost-plugin-playbooks pull request #1016
Opened 2022-02-02 14:26 UTC by iomodo

#### Summary
This PR adds Toast banner functionality. 
You can use like 
```js
const {add, remove} = useToast();

add('some text', some_duration);
```
Toast will be removed after `some_duration` automatically. If duration is less than or equal to 0, toast will not be removed, you can remove it by calling the `remove` function or by clicking the `X` in the UI.
Multiple toasts are supported at the same time.
Current PR only addresses the "duplicate" playbook flow. If we need toasts on other places I'll push separate PR for those.

https://user-images.githubusercontent.com/2340127/152172119-a919f1cc-880c-4fa1-b0b7-1deae54c5534.mp4

#### Ticket Link

  Fixes: https://mattermost.atlassian.net/browse/MM-41261

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-02-02 20:11 UTC, crspeller requested changes
This is great! Just a few nits.

2022-02-02 20:11 UTC, crspeller commented on webapp/src/components/backstage/toast_banner.tsx
> +    const add = useCallback(
Seems like over-optimization maybe?

2022-02-02 20:11 UTC, crspeller commented on webapp/src/components/backstage/toast_banner.tsx
> +    useEffect(() => {
Instead of using useEffect maybe we can create a helper for setToasts that calls this? That way we don't get a double re-render.

2022-02-02 20:11 UTC, crspeller commented on webapp/src/components/backstage/backstage.tsx
> +                                    to={`${match.url}/runs`}
Are these extra changes here intentional?

2022-02-02 20:11 UTC, crspeller commented on webapp/src/hooks/crud.ts
> +        addToast('successfully duplicated playbook', DuplicateBannerTimeout);
This API makes me happy 😄

2022-02-03 06:17 UTC, abhijit-singh reviewed
This is awesome, thanks @iomodo! Would it be possible to [animate](https://www.figma.com/proto/kAV9UFVPRUXknFrydMc3qK/3.0-Ideas-%26-Mocks?page-id=310%3A184862&node-id=310%3A184917&viewport=489%2C48%2C0.31&scaling=min-zoom&starting-point-node-id=310%3A184917&show-proto-sidebar=1) the toast up and then back down? I think it should be possible with CSS transitions and not need anything fancier. 

Also, can we capitalize the 'S' in the message `Successfully duplicated playbook`. Thanks!

2022-02-07 09:40 UTC, iomodo commented on webapp/src/components/backstage/toast_banner.tsx
> +    useEffect(() => {
Without `useEffect` I'm getting wired concurrency bug since `setToasts` is not a synchronous operation. When we have 2 active toasts, `toasts` array might not be up to date and `setToasts` leaves inconsistent state by not removing the toast at all or seemingly removing several toasts at once.

2022-02-07 09:43 UTC, iomodo commented on webapp/src/components/backstage/backstage.tsx
> +                                    to={`${match.url}/runs`}
there are no changes here except wrapping everything inside `<ToastProvider>`, just a wired rendering

2022-02-07 09:49 UTC, iomodo commented
Added animation

https://user-images.githubusercontent.com/2340127/152764476-9795c387-a9c2-4ae3-a775-ce774ce47ff0.mp4

2022-02-07 17:50 UTC, crspeller commented on webapp/src/components/backstage/backstage.tsx
> +                                    to={`${match.url}/runs`}
@iomodo Are you sure? For example it shows the icon size changing from `1` to `1.4`.

2022-02-07 17:53 UTC, iomodo commented on webapp/src/components/backstage/backstage.tsx
> +                                    to={`${match.url}/runs`}
Yep sure, still the github rendering thing. That icon size actually is `1.4`

2022-02-07 17:58 UTC, crspeller requested changes
Also not sure if I like that animation. I feel like it's worse then no animation. Maybe a quick fade in?

2022-02-07 17:58 UTC, crspeller commented on webapp/src/components/backstage/toast_banner.tsx
> +    useEffect(() => {
Using `setToasts((toasts) => toasts.splice(i, 1))` should fix that? That's supposed to be able to be called asynchronously if you use the function form.

2022-02-07 21:49 UTC, calebroseland approved these changes
Long-term, I might prefer to see something like [react-toastify](https://github.com/fkhadra/react-toastify) at the suite or platform level, but for a minimalist no-deps implementation, this is really great!

Optional suggestions: 
- alternate animation timings
- some ideas for possible changes that could be done later to enhance reusability (e.g. not hardcoded as `success`-like)

2022-02-07 21:49 UTC, calebroseland commented on webapp/src/components/backstage/toast_banner.tsx
> +    duration: number;
Post-MVP
```suggestion
    id: number;
    content: React.ReactNode;
    duration: number;
    type: 'success' | 'warning' | 'error' | 'info'
```

2022-02-07 21:49 UTC, calebroseland commented on webapp/src/components/backstage/toast_banner.tsx
> +                                <StyledCheck className={'icon icon-check'}/>
Post-MVP; icon according to type
```suggestion
                                <StyledIcon className={`icon icon-${icons[type]}`}/>
```

2022-02-07 21:49 UTC, calebroseland commented on webapp/src/components/backstage/toast_banner.tsx
> +    const add = (content: string, duration: number) => {
Post-MVP; perhaps a default duration for ease &/ consistency
```suggestion
    const add = (content: React.ReactNode, type: ToastType['type'], duration = DEFAULT_DURATION) => {
```

2022-02-07 21:49 UTC, calebroseland commented on webapp/src/components/backstage/backstage.tsx
> +                                    to={`${match.url}/runs`}
👍 Yep, shows correctly in an IDE diff

2022-02-07 21:49 UTC, calebroseland commented on webapp/src/components/backstage/toast_banner.tsx
> +    }
I agree linear on the entrance probably isn't the best, but not a huge deal. Here's a possible alt. set of timings.

https://user-images.githubusercontent.com/11724372/152876957-9714ac9e-8e5d-4a84-bd66-3c6359e6a8b1.mp4

```suggestion
    &.fade-enter {
        transform: translateY(80px);
    }

    &.fade-enter-active {
        transform: translateY(0);
        transition: transform 0.5s cubic-bezier(.44,.13,.42,1.43)
    }

    &.fade-exit {
        transform: translateY(0);
    }

    &.fade-exit-active {
        transform: translateY(280px);
        transition: transform 0.75s cubic-bezier(.59,-0.23,.42,1.43);
    }
```

2022-02-08 10:10 UTC, iomodo commented on webapp/src/components/backstage/toast_banner.tsx
> +    useEffect(() => {
Aah you are so correct, was not using the functions form here 🧑‍🎓

2022-02-08 10:14 UTC, iomodo commented
Thanks for the suggestions @calebroseland <3
I added the default duration and used your animation consts :)
Skipping the `type` for now, It might need some additional ui changes(colours and such). Let's defer it for future.

2022-02-08 11:37 UTC, abhijit-singh approved these changes
💯

2022-02-09 15:26 UTC, crspeller approved these changes

2022-02-09 16:00 UTC, merged