MM-41055: RHS Run Details Tutorial
mattermost/mattermost-plugin-playbooks pull request #1023
Opened 2022-02-07 06:29 UTC by calebroseland

#### Summary
Create RHS Run Details tour/tutorial.

![CleanShot 2022-02-07 at 00 01 11](https://user-images.githubusercontent.com/11724372/152735685-a566068b-05da-4507-9e9a-a29645981154.gif)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-41055

#### Checklist

Item | Y / N / NA [^1]
---|---
Telemetry updated? | N—Deferred until integration with/after #1014 
Gated by experimental feature flag? | N—Deferred until integration with/after #1014
Unit/E2E tests updated? | N—Deferred until integration with/after #1014 

[^1]: Yes / No / Not Applicable.

2022-02-07 19:14 UTC, crspeller requested changes

2022-02-07 19:14 UTC, crspeller commented on webapp/src/components/rhs/rhs_run_details.tsx
> +        const isRunDetailTour = false;
Just highlighting this as where the conditions would go to start the tour.

2022-02-07 19:14 UTC, crspeller commented on webapp/src/components/tutorial/tutorial_tour_tip/hooks.ts
> +export const useShowTutorialStep = (stepToShow: number, category: string, defaultAutostart = true): boolean => {
So this uses the fact that you can distinguish between 0 and not set. Not sure if we can rely on that depending on the reset mechanism?  Could we hide the tutorial tip until the conditions are met? (see my PR for an example)

2022-02-07 22:00 UTC, calebroseland commented on webapp/src/components/tutorial/tutorial_tour_tip/hooks.ts
> +export const useShowTutorialStep = (stepToShow: number, category: string, defaultAutostart = true): boolean => {
I didn't want to require a second piece of state for the modal visibility to keep it under control, so that it could survive a refresh or tab-change. 

I also don't see the need to re-show the modal on subsequent/reruns of the tour—if this tour were manually restarted, the title "We’ve auto-created your first run" wouldn't make sense—so reseting back to step 0 (skipping the modal) makes sense to me.

2022-02-08 15:19 UTC, crspeller approved these changes

2022-02-08 15:19 UTC, crspeller commented on webapp/src/components/tutorial/tutorial_tour_tip/hooks.ts
> +export const useShowTutorialStep = (stepToShow: number, category: string, defaultAutostart = true): boolean => {
Ah I see how that helps. Basically null becomes the show the modal state. It could be clearer if we just had a state value for the modal. But 0/5 I get it now.

2022-02-08 21:13 UTC, abhijit-singh approved these changes
Looks good 👍

2022-02-09 12:16 UTC, iomodo approved these changes
Looks Great!

2022-02-10 03:27 UTC, merged