[MM-41150] Add playbook edit tour
mattermost/mattermost-plugin-playbooks pull request #1027
Opened 2022-02-08 09:11 UTC by iomodo

#### Summary
This PR adds playbook edit tour

https://user-images.githubusercontent.com/2340127/152954480-ca2db96b-0ea9-4b44-a247-904868945989.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-41150

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-02-08 15:15 UTC, crspeller approved these changes

2022-02-08 21:12 UTC, abhijit-singh approved these changes
Looks good 👍

2022-02-10 03:51 UTC, calebroseland requested changes
LGTM, just a small tweak for the dots

2022-02-10 03:51 UTC, calebroseland commented on webapp/src/components/tutorial/tours.ts
> +    Retrospective: 3,
Just needs a `FINISHED` to get the 4th dot to show. Not sure why this isn't just built in if it's expected 🤷‍♂️!

```suggestion
    Retrospective: 3,
    FINISHED,
```
<img width="300" alt="CleanShot 2022-02-09 at 21 43 46@2x" src="https://user-images.githubusercontent.com/11724372/153333584-8006e0cf-46ca-4574-814e-a89b63fd6b40.png">

<img width="300" alt="CleanShot 2022-02-09 at 21 42 43@2x" src="https://user-images.githubusercontent.com/11724372/153333418-34fa27db-b1c4-4aa5-a93a-20dfe6cf978f.png">

2022-02-10 03:52 UTC, calebroseland approved these changes

2022-02-10 03:58 UTC, merged