[MM-41057] Wire up tutorial flow
mattermost/mattermost-plugin-playbooks pull request #1033
Opened 2022-02-11 15:27 UTC by iomodo

#### Summary
This PR wires up tutorial flow.

https://user-images.githubusercontent.com/2340127/153619566-daef7cee-18fd-43d5-80ca-3c6031314850.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-41057

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-02-14 08:22 UTC, abhijit-singh approved these changes
Looks good overall. Still not able to get the tour working properly on my local env though so approving based on the screencap.

2022-02-14 22:31 UTC, calebroseland requested changes

2022-02-14 22:31 UTC, calebroseland commented on webapp/src/components/backstage/playbooks/playbook.tsx
> +                                const search = '?forceRHSOpen&&openTakeATourDialog';
extra `&`
```suggestion
                                const search = '?forceRHSOpen&openTakeATourDialog';
```

2022-02-14 23:05 UTC, calebroseland commented on webapp/src/components/rhs/rhs_run_details.tsx
> +        if ((runDetailsStep === null || parseInt(runDetailsStep, 10) === FINISHED) && isRunDetailTour) {
Ahh, the initial routing over in `playbook.tsx` hits `/<team>/channels/channel_id`, and a mattermost-webapp redirect grabs it and discards the search params before `rhs_run_details` get's a chance to see them.


<img width="552" alt="CleanShot 2022-02-14 at 17 00 39@2x" src="https://user-images.githubusercontent.com/11724372/153961619-237e3bc3-ab3f-4d4f-9d88-50148d8ea853.png">
<img width="232" alt="CleanShot 2022-02-14 at 17 00 56@2x" src="https://user-images.githubusercontent.com/11724372/153961628-adafcb35-2b56-445f-9d70-ff7512ac6ac7.png">

2022-02-15 15:29 UTC, crspeller commented on webapp/src/components/backstage/playbooks/playbook.tsx
> +                        {playbook.title === 'Learn how to use playbooks' ? formatMessage({defaultMessage: 'Start a test run'}) : formatMessage({defaultMessage: 'Run'})}
Here and above maybe naming the string constant would make it clearer what is happening here?

2022-02-15 16:04 UTC, calebroseland commented on webapp/src/components/rhs/rhs_run_details.tsx
> +        if ((runDetailsStep === null || parseInt(runDetailsStep, 10) === FINISHED) && isRunDetailTour) {
It was only reproducible when the current channel was _not_ an onboarding run channel

2022-02-15 16:10 UTC, calebroseland approved these changes

2022-02-16 15:29 UTC, crspeller approved these changes

2022-02-16 17:55 UTC, Phrynobatrachus approved these changes

2022-02-16 20:09 UTC, calebroseland commented on webapp/src/components/templates/template_selector.tsx
> +                }
@iomodo Is this going to undo https://github.com/mattermost/mattermost-plugin-playbooks/pull/1034/files#diff-ff3ba23a0c4550c04d46f67b7e68a9a5c9e08f785a6193d8238640fdd1be7804R95-R100 ?

2022-02-17 15:32 UTC, merged