MM-41266: Welcome message action frontend
mattermost/mattermost-plugin-playbooks pull request #1037
Opened 2022-02-14 16:33 UTC by agarciamontoro

#### Summary
This PR implements the frontend counterpart of #1036. Read the description of that PR for a bit of context.

Feel free to review this PR by commit. I've tried to make them self-explanatory, but here's some big-picture context:

- The first 5 commits add/adapt external functions of components for the needs of the actions modal. Just some prep work.
- The next 3 commits implement all the boilerplate regarding client functions, redux for the modal show/hide actions, and the needed types.
- The actual work comes then in:
  - https://github.com/mattermost/mattermost-plugin-playbooks/commit/36b898415819c4dabeae5c450b88e6b8c2b452f4, that implements the modal component and all of its subcomponents (I've tried to keep components length at a minimum)
  - https://github.com/mattermost/mattermost-plugin-playbooks/commit/cc7113c9cb6578ca2ec2ae76e91b454ad5d385ee, that connects it all up registering the modal as a root component and registering the menu entry in the channel header menu to open it
  - https://github.com/mattermost/mattermost-plugin-playbooks/commit/a944fabc477105b1fcc2de04db46dff44a282eb5, that slightly changes the logic to process the CHANNEL_VIEWED websocket event for all channels that have a welcome message action enabled, instead that doing so only for playbook runs.

Although this branch is independent from #1036's branch, we should only merge it when that one's merged.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41266

#### Checklist

- [ ] ~~Telemetry updated~~ Covered by https://mattermost.atlassian.net/browse/MM-41801
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-02-19 21:01 UTC, agarciamontoro commented
Latest commits address feedback received during the Actions meeting. Namely:
- Add a placeholder to the welcome message textbox. @justinegeffen, do you think the copy is good? See the first screenshot to see it in context, but the sentence is "Define a message to welcome users joining the channel".
- Remove the chevron to expand/collapse the trigger body. Visible in all screenshots.
- Preview the markdown for regular members, who cannot edit the message, leaving the textbox in edit mode by default for channel admins. See the screenshots in the table.

### Placholder screenshot
![image](https://user-images.githubusercontent.com/3924815/154818794-5a9ef362-efe2-434c-8f04-3cea1f386117.png)

### Previewing for regular members

| Channel admin 	| Regular member 	|
|---	|---	|
| ![image](https://user-images.githubusercontent.com/3924815/154818608-d8dc152f-d0a5-4a97-a7ff-1de9e888e90d.png) 	| ![image](https://user-images.githubusercontent.com/3924815/154818678-0d2c6dd5-29b5-4c49-8c3d-3c6224687d85.png) 	|

2022-02-19 21:01 UTC, agarciamontoro commented
@abhijit-singh, this is ready for review now :)

2022-02-23 12:37 UTC, abhijit-singh approved these changes
This is awesome @agarciamontoro!

Just a couple of changes on the copy based on @cwarnermm's comments in Figma:
1. Make the word `Trigger` in title-case instead of [upper-case](https://www.figma.com/file/NQXVa4S4VUgqVsX0GHOPli?node-id=272:89786#148167556).
2. Change the [action](https://www.figma.com/file/NQXVa4S4VUgqVsX0GHOPli?node-id=272:89786#148168328) text to `Send a temporary welcome message to the user`.

2022-02-23 12:37 UTC, abhijit-singh commented on webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
>      margin: 0 12px 0 0;
Can we make the `margin-right: 0px` here to right-align the toggle with the text box below it?
<img width="97" alt="image" src="https://user-images.githubusercontent.com/14369607/155319261-87298efb-9a4f-4a65-9538-4b8e1d0fd138.png">

2022-02-28 20:58 UTC, calebroseland requested changes
(Sorry for the long delay @agarciamontoro)

LGTM! Just one conditional bug for `sysAdmin && !channelAdmin` and some assorted thoughts around `markdown_textbox`.

2022-02-28 20:58 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +            }
I don't think `hideButtonsRow` is very useful in this case, if `hideButtonsRow` and `disabled` follow the same condition, this is extraneous IMO as `disabled` already nullifies this internally.

2022-02-28 20:58 UTC, calebroseland commented on webapp/src/components/actions_modal_action_children.tsx
> +            disabled={!editable}
Shouldn't these follow the same condition? As-is, if I'm a `sysadmin`, but also not explicitly a `channeladmin`, I'm stuck in preview-only mode even though I technically have perms to change it.
(Also see related re: potentially extraneous `hideButtonsRow`)

```suggestion
            previewByDefault={!editable}
            disabled={!editable}
```

2022-02-28 20:58 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +    const [showPreview, setShowPreview] = useState(previewByDefault);
👍

2022-02-28 20:58 UTC, calebroseland commented on webapp/src/components/actions_modal_action.tsx
> +    };
(Potential for later) This could be made static by using `FormattedMessage` kind of like in https://github.com/mattermost/mattermost-plugin-playbooks/blob/MM-41266.welcome-msg-frontend/webapp/src/components/backstage/playbook_edit/playbook_edit.tsx#L78-L83

2022-03-01 10:01 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
>      margin: 0 12px 0 0;
- Copy fixed in https://github.com/mattermost/mattermost-plugin-playbooks/pull/1037/commits/e6f969078608fb4414ec45a4b359d95093bb9e30 and https://github.com/mattermost/mattermost-plugin-playbooks/pull/1037/commits/863a7861518380b5bf9ce762b009a47546fd5df0
- Toggle aligned in https://github.com/mattermost/mattermost-plugin-playbooks/pull/1037/commits/e187c272165b90a1c8157a8d44f42d1981bec423

It looks like this now:
![image](https://user-images.githubusercontent.com/3924815/156147499-18622bf5-986b-43bf-9ce8-ce4503b64b42.png)

2022-03-01 10:01 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +            }
You're right! Fixed in https://github.com/mattermost/mattermost-plugin-playbooks/pull/1037/commits/037bfe0ed1c938daa913d124ef4388956f07df26

2022-03-01 10:02 UTC, agarciamontoro commented on webapp/src/components/actions_modal_action_children.tsx
> +            disabled={!editable}
Oooh, great eye! Thank you, fixed in https://github.com/mattermost/mattermost-plugin-playbooks/pull/1037/commits/a532e72b7855f272a92c0a53e64d23e64e7ab777

2022-03-01 10:11 UTC, agarciamontoro commented
@gbochora, Shota is out, can you take a look at this PR instead? Thanks!

2022-03-01 15:49 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +    const [showPreview, setShowPreview] = useState(previewByDefault);
![image](https://user-images.githubusercontent.com/11724372/156201376-7c088e63-148a-4512-beb4-780dab18d5de.png)

2022-03-01 17:20 UTC, calebroseland approved these changes

2022-03-02 10:05 UTC, gbochora approved these changes
Great work!

2022-03-02 10:07 UTC, agarciamontoro commented on webapp/src/components/actions_modal_action.tsx
> +    };
@gbochora, do you mean storing it in the backend? I think this is UI-specific, so I'd lean towards keeping it here. What I'll do is what Caleb suggested, making this static as in https://github.com/mattermost/mattermost-plugin-playbooks/blob/MM-41266.welcome-msg-frontend/webapp/src/components/backstage/playbook_edit/playbook_edit.tsx#L78-L83.
Does that sound good?

2022-03-02 10:26 UTC, gbochora commented on webapp/src/components/actions_modal_action.tsx
> +    };
Yep, it sounds good. We will have a single source of titles and reuse them.

2022-03-02 10:27 UTC, agarciamontoro commented
/update-branch

2022-03-02 10:33 UTC, merged