Mm 41037 update retro published channel message UI
mattermost/mattermost-plugin-playbooks pull request #1038
Opened 2022-02-14 20:02 UTC by gbochora

#### Summary
This PR updates `retrospective published` post UI. When a user provides metrics data for playbook run and publishes retrospective, all metrics values are included in the channel post.

- Add a custom post component for `retrospective published` post. The component receives metric data and metric configs as JSON strings.
- Add passing metrics data to the `publishRetrospective` API.

https://user-images.githubusercontent.com/4368372/153937561-2a03cae9-d6b7-40b0-b6a6-3f7670dc1f85.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41037

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-02-15 21:48 UTC, cpoile commented
I changed the base to MM-40932 -- I assumed that's what you wanted, right?

2022-02-15 22:08 UTC, cpoile approved these changes
This is really nice George! I liked the responsiveness of the grid, it looks wonderful. Great work!

2022-02-15 22:08 UTC, cpoile commented on webapp/src/components/retrospective_post.tsx
> +                {metricsConfigs && <>
nit: I think the `<>` has to be on the next line.

2022-02-15 22:08 UTC, cpoile commented on webapp/src/components/retrospective_post.tsx
> +                            metricsConfigs?.map((mc) => {
nit: I don't think you need the `?.map` here, since you test that `metricsConfig` is not undefined/null on line 39. (unless the typescript linter is complaining, in which case ignore me :)

2022-02-16 01:36 UTC, abhijit-singh requested changes
Looks amazing @gbochora! Just one request - would it be possible to truncate the metric title in the post after a certain point?
Current:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/14369607/154179396-4e208130-eb12-46fe-bf7a-42262c3751b4.png">
Suggested:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/14369607/154179433-3f9aa3c6-36d2-4cd5-8714-e89d49325158.png">

2022-02-16 08:40 UTC, gbochora commented
@abhijit-singh added truncating metric title and duration.

2022-02-16 12:51 UTC, abhijit-singh approved these changes
Perfect, thank you!

2022-02-20 06:58 UTC, calebroseland approved these changes
LGTM!

2022-02-21 12:11 UTC, merged