MM-40934 - Playbook metrics dashboard view - frontend
mattermost/mattermost-plugin-playbooks pull request #1042
Opened 2022-02-16 15:08 UTC by cpoile

#### Summary
- This is using dev data, and not ready for merging the master, but I wanted to get reviews started since we're getting close to the code complete date.
- I didn't realize that we're not actually sending metrics data with the `GET /runs` endpoint, so I need to add that next. :)
- @abhijit-singh I decided to add an error-text colored `N/A` if the run was finished but the retro/metrics had not be published yet. This will highlight the lack of metrics and encourage people to fill them out (it's better than hiding them, I think).

![CleanShot 2022-02-16 at 10 07 21@2x](https://user-images.githubusercontent.com/1490756/154293504-05f734fd-af52-42c8-af14-5a3ffa4cdfd4.png)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-40926

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-02-17 15:55 UTC, cpoile commented
Okay, looks like we're ready for this PR -- added metrics to the `GET /runs` and added sorting by metric -- the column headers are now clickable. But they won't work if a second (or more) page of the infinite scroll has been loaded (https://mattermost.atlassian.net/browse/MM-41862)

2022-02-17 22:38 UTC, cpoile commented
Improved the look of the graphs:
![CleanShot 2022-02-17 at 17 34 59@2x](https://user-images.githubusercontent.com/1490756/154582840-a46040a2-ee7c-42fc-b9d3-aa17963fb870.png)

2022-02-17 22:46 UTC, crspeller requested changes
Looks good! Just a couple nits and a reminder.

2022-02-17 22:46 UTC, crspeller commented on server/sqlstore/playbook_run.go
> +	fmt.Printf("<><> SQL: %s ARGS: %v", sqlStmnt, args)
Test code?

2022-02-17 22:46 UTC, crspeller commented on webapp/src/components/backstage/playbooks/metrics/metrics_run_list.tsx
> +            className='PlaybookRunList'
`className`?

2022-02-17 22:46 UTC, crspeller commented on webapp/src/components/backstage/playbooks/metrics/metrics_stats_view.tsx
> +                            // TODO: for development only; replace {...stats, ...metrics} with stats
Don't forget to fix this.

2022-02-17 23:25 UTC, cpoile commented on webapp/src/components/backstage/playbooks/metrics/metrics_run_list.tsx
> +            className='PlaybookRunList'
Leftovers. Removed it, thanks

2022-02-17 23:25 UTC, cpoile commented on webapp/src/components/backstage/playbooks/metrics/metrics_stats_view.tsx
> +                            // TODO: for development only; replace {...stats, ...metrics} with stats
Yep, after merging all of George's PRs. Thanks!

2022-02-18 00:22 UTC, crspeller approved these changes

2022-02-18 17:12 UTC, gbochora approved these changes
Great work! 🎉

2022-02-18 17:12 UTC, gbochora commented on server/sqlstore/playbook_run.go
> +					Where(sq.Eq{"mc.Ordering": ordering}),
Do we need to add here `Where(sq.Eq{"m.Published": true})` to select only published metrics.

2022-02-18 18:31 UTC, cpoile commented on webapp/src/components/backstage/playbooks/line_graph.tsx
> +            {/*@ts-ignore*/}
yep, the chartjs and react chartjs packages are not in sync and the types don't match, so I'm ignoring the error.

2022-02-18 18:34 UTC, cpoile commented on server/sqlstore/playbook_run.go
> +					Where(sq.Eq{"mc.Ordering": ordering}),
@abhijit-singh It's up to you -- the question is: in the run list in the Key Metrics tab, do you want the metrics that people have entered to show up in the run list only /after/ the retro has been published? I thought it would be fine to see the metrics in the list even if the retro hasn't been published. 
To be clear, metrics that have not been published will /not/ be included in the summary statistics (above the runs list).

2022-02-22 09:49 UTC, abhijit-singh commented on server/sqlstore/playbook_run.go
> +					Where(sq.Eq{"mc.Ordering": ordering}),
@cpoile I think it makes sense to show `finished runs` with unpublished retros in that list but not active runs. We do not expect active runs to have values for the metrics or have a retrospective published in the happy flow. And they'll probably just end up adding fluff and not give people looking at the list any valuable info.

2022-02-22 10:32 UTC, abhijit-singh reviewed
Looks good! A few minor nits:
1. In the statistics section, add space above the metric title and reduce space between the metric title and statistics.
2. The % change chip probably needs a little `padding-right`

2022-02-22 23:15 UTC, merged