Send ephemeral post to user on channel when `/playbooks todo` command is called
mattermost/mattermost-plugin-playbooks pull request #1053
Opened 2022-02-20 04:05 UTC by 97amarnathk

#### Summary
Currently, running /playbook todo currently posts from the playbooks bot as a DM to the user.
This PR makes the response an Ephemeral Post on the channel where the command is called.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-40504

#### Checklist

- [ ] Telemetry updated
- [ ] ~~Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-02-20 04:05 UTC, mattermod commented
Hello @97amarnathk,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-02-26 12:16 UTC, gbochora commented on server/app/playbook_run.go
> +	EphermalPostTodoDigestToUser(userID string, channelID string, force bool) error
Just a typo. Missing space, should be 'post to'

2022-02-26 12:24 UTC, gbochora approved these changes
This is excellent @97amarnathk. Thanks!

2022-02-28 14:41 UTC, Phrynobatrachus requested changes
Hi @97amarnathk, thanks again for the PR! I fixed a couple tests that were affected by this, but it looks solid otherwise. I just have one more minor spelling nit:

`ephermal` should be `ephemeral` for all occurrences in the PR

2022-02-28 15:54 UTC, 97amarnathk commented
@Phrynobatrachus thanks for the test fixes.
I have fixed the typo as required.

2022-02-28 16:10 UTC, Phrynobatrachus approved these changes

2022-02-28 16:11 UTC, merged