Mm 40337 name desc confirm when cancelling changes
mattermost/mattermost-plugin-playbooks pull request #1065
Opened 2022-03-01 19:17 UTC by trilopin

#### Summary
From past [conversation](https://community-daily.mattermost.com/core/pl/1koe691bsbb99phfoyyu5kharw) a dialog to confirm that a user could confirm to discard unsaved changes was requested.

Design by Abhijit Singh
![Image Pasted at 2021-11-24 21-58](https://user-images.githubusercontent.com/4096774/156232772-14b36a19-524a-4e5c-8990-e724ff4b1f88.jpg)

With these changes, we prompt with the unsaved-changes-modal if the user changed name or description and then canceled ( by clicking on cancel, cross at top right or outside the modal). Once the unsaved modal appears we have two choices: cancel which will go back to edit and confirm "Discard and Leave" to finally discard the changes.

In order to preserve consistency, another existent confirmation modal for unsaved changes has been migrated at `webapp/src/components/backstage/route_leaving_guard.tsx`  moving from `ConfirmModal` to the new component `UnsavedChangesModal`.

<a href="https://www.loom.com/share/642946e6cace4b0c89659206ba5f3919">
    <p>Playbooks - Dream Team - 20 February 2022 - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/642946e6cace4b0c89659206ba5f3919-with-play.gif">
  </a>

#### Ticket Link
  Fixes:  https://github.com/mattermost/mattermost-server/issues/19172 
  JIRA: https://mattermost.atlassian.net/browse/MM-40337

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated
- [ ] i18n extract
- [ ] e2e test included
- [ ] style checked
- [ ] imports order mess

2022-03-01 19:17 UTC, mattermod commented
Hello @trilopin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-03-01 19:22 UTC, trilopin commented
Hey, this is still a draft. Please wait for the review.

2022-03-02 16:44 UTC, lieut-data commented
Ooh, nice spelunking through some past efforts @trilopin! I've asked @agarciamontoro and @calebroseland to review, in addition to @abhijit-singh himself :)

2022-03-02 17:13 UTC, trilopin commented
Thanks!

Looking at other issues I've just seen calls to telemetry and I start wondering if I should have included it here. 

any thoughts?

2022-03-02 19:56 UTC, lieut-data commented
@trilopin, I'd be inclined to omit any extra telemetry for this change: it's not something I'd expect we would make decisions around, vs. for example, product adoption. Thanks for double checking!

2022-03-08 14:01 UTC, abhijit-singh approved these changes
Thanks @trilopin! 

The flashing of modals does make a weird effect when the user clicks on `Discard & leave` but if it's a problem with the generic modal component, I think it's okay if we prioritize and take it up as a separate effort. Everything else looks great based on the loom video, thanks for adding that in! 👍

2022-03-08 14:50 UTC, trilopin commented
Thank you @abhijit-singh !

2022-03-08 15:09 UTC, calebroseland requested changes
Just a couple of whitespace nits. Otherwise LGTM, thanks @trilopin!

2022-03-08 15:09 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +    z-index: 1040;
👍

2022-03-09 07:21 UTC, trilopin commented on webapp/src/components/backstage/playbook_edit_title_description_modal.tsx
> +                    }
Sorry @calebroseland, I started with an old prettier mixed with eslint and did weird things.
it should be fixed now

2022-03-10 09:03 UTC, agarciamontoro approved these changes
I've been trying to fix the modal flickering locally, but I have no idea what's happening :eyes: Let's merge this as is and we can revisit when we fix the modals holistically.

Thank you for your work, @trilopin! :tada:

2022-03-10 15:35 UTC, calebroseland commented on webapp/src/components/backstage/playbook_edit_title_description_modal.tsx
> +        ) {
> (I guess we need to revisit the linter so that it does catch these things)

Either way, indeed—these sorts of things should be in the linter.

2022-03-11 13:44 UTC, trilopin commented on webapp/src/components/backstage/playbook_edit_title_description_modal.tsx
> +        ) {
Personally, I prefer it in one line until it's too long, change was not intentional
I'm going to change it

2022-03-11 21:13 UTC, calebroseland approved these changes
Thanks, @trilopin!

2022-03-11 21:13 UTC, merged