Gh 19168 List autofollowers in playbook preview
mattermost/mattermost-plugin-playbooks pull request #1070
Opened 2022-03-03 17:50 UTC by trilopin

#### Summary
Users who decided to auto-follow for a playbook will be shown in  playbook actions preview, specifically at "When a run starts" section. 

This PR covers the preview information, auto-follow behavior has not changed.

#### Details

At server side:
- Created new API handler getAutoFollows in a new route `GET /playbook/<playbookID>/autofollows`. 
- OpenAPI updated
- client related funcs added
- Tests added

In webapp several actions have been addressed:
- Retrieve list of userIds who autofollow in useEffect at playbook.tsx
- Stop using IsAutoFollow to manage autofollow checkbox, managed directly looking for current user in the list of followers
- Removed a double fetch for playbook that happened at the preview page. The expected use was at useEffect in `backstage/playbooks/playbook.tsx`. However, there was an unexpected use at `playbook_preview_navbar.tsx` by using `useHasPlaybookPermissionById` hook that also called useHasPlaybook which fetch playbook. I changed the props to navbar from playbookId to playbook and replaced `useHasPlaybookPermissionById` by `useHasPlaybookPermission`.
- cypress tests added, I guess it should be a cleaner way to deal with multiple users. Suggestions more than welcome

Questions:
-  IsAutoFollow endpoint since is now unused, should we remove it?
- I changed the copy that was suggested in the issue because it was weird to me. Since I'm non-native English speaker, let me know if I should keep the suggested one or the current one :)
- What's the expected number of autofollowers in real cases? I'm wondering if I should I care more about bigger numbers

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/19168

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [X] Unit tests updated
- [X] Run i18 extract

2022-03-03 17:50 UTC, mattermod commented
Hello @trilopin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-03-03 18:06 UTC, agarciamontoro commented
Thanks for your work on this, @trilopin! I'll take a look (at this PR and your other one!) as soon as I can :pray: 

Answering your questions:

> IsAutoFollow endpoint is now unused, should we remove it?

I'd vote for removing it, I don't like keeping dead code around. Thoughts against that, @crspeller?

> I changed the copy that was suggested in the issue because it was weird to me. Since I'm non-native English speaker, let me know if I should keep the suggested one or the current one :)

As a fellow non-native English speaker, it sounds good. Hopefully we have technical writers we can ask! @justinegeffen, do you think the sentence `X users automatically following this run` is correct?

> What's the expected number of autofollowers in real cases? I'm wondering if I should I care more about bigger numbers

I don't have data to answer this question properly, but I think that the users component already takes care of that for more than 6 users, isn't it? Or are you concerned for something else?

2022-03-03 18:12 UTC, trilopin commented
> I don't have data to answer this question properly, but I think that the users component already takes care of that for more than 6 users, isn't it? Or are you concerned for something else?

On one hand, it was curiosity and the understanding of the real use-case. On the other hand, I wanted to know if I should take more care with tests than 0-1-2 followers.

2022-03-03 18:12 UTC, agarciamontoro commented
Now that I re-read the sentence, it does read a bit weird. It should make sense prefixed by the `When a run starts` part. cc/ @justinegeffen

2022-03-03 19:02 UTC, justinegeffen reviewed
A few minor changes. :)

2022-03-03 19:06 UTC, justinegeffen commented
Great question, @agarciamontoro! 

I think the sentence "X users automatically following this run" could be made a bit easier to read if we said:
"One user is..." and then from two upwards "x users are". I don't know whether this is possible but it's not a deal-breaker and if not, the current content work fine. :)

2022-03-03 19:29 UTC, crspeller commented
> I'd vote for removing it, I don't like keeping dead code around. Thoughts against that, @crspeller?

Agreed. Let's remove it.

2022-03-03 19:42 UTC, crspeller requested changes
Thanks for the contribution. Great PR! Just a couple suggestions.

2022-03-03 19:42 UTC, crspeller commented on server/api_playbooks_test.go
> +	for _, c := range testCases {
We usually like to use `t.Run` to namespace our table tests. You can see that happening here: https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/api_runs_test.go#L146

2022-03-03 19:42 UTC, crspeller commented on server/sqlstore/playbook.go
> +	autoFollows := make([]string, 0)
Wondering why you made this change?

2022-03-03 22:09 UTC, agarciamontoro requested changes
Really good work, @trilopin! I liked how comprehensive the tests are and how you added methods to the client, and even updated the `api.yaml` file, thanks!

I left some nits in the comments below, and a couple of things about two more important changes:
- I think some of the code can be simplified by making the API endpoint return only the items, instead of the object with the items and the length. I left comments in a few places, but maybe there are other places to simplify.
- The entry in the card should only show when there is at least one auto-follower. I also left a comment about this in the specific place to change it.

Thanks again for your work!

2022-03-03 22:13 UTC, agarciamontoro commented
> I think the sentence "X users automatically following this run" could be made a bit easier to read if we said:
"One user is..." and then from two upwards "x users are". I don't know whether this is possible but it's not a deal-breaker and if not, the current content work fine. :)

Thanks, @justinegeffen, I like it being simpler, but I think we still need to be consistent with the other sentences in that card. All entries finish the heading `When a run starts`. For example, `When a run starts create a public channel` or `When a run starts invite 2 members to the channel`. The new entry here now reads `When a run starts 2 users automatically following this run`. How can we make that more idiomatic?

You can see those sentences in context in @trilopin's screenshot in the PR description.

2022-03-04 07:54 UTC, trilopin commented on client/playbook.go
> +}
Good point! we only need the []string to have the whole thing working correctly.

The only reason why I would keep this struct is to have some flexibility for adding more fields in the future. With the slice at top of the response body, you will have little space to grow without breaking backwards compact. With the json dictionary you will increase a little the complexity but also it will be easier to extend. 

So, before I simplify this, let me ask some questions:
- is the API used by more clients than the webapp code delivered inside the plugin? 
- I also don't like premature optimization/abstraction, and it'd help me to have more context. what's your opinion about V0 API strategy regarding extensibility vs complexity?

2022-03-04 07:55 UTC, trilopin commented on server/api/playbooks.go
> +	}
agree, totalCount does not add value here

2022-03-04 07:56 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/overview_spec.js
> +    it.only('show followers in actions preview', () => {
good catch!

2022-03-04 08:02 UTC, trilopin commented on webapp/src/components/backstage/playbooks/playbook.tsx
> +    }, [match.params.playbookId, currentUserId, isFollowed]);
yes, if we include isFollowed we can have re-fetch when you click on the autofollow checkbox and preview is rendered again with the new data. if we skip this, data in the preview won't change  live.

Apart from that, there is a tradeoff between being simple and more efficient. When isFollowed changes, we repeat all useEffect block that includes the playbookFetch, when we only need to fetch the followers. Since it's not that usual (only when user clicks on checkbox) I preferred to keep code together instead of doing two different useEffect blocks with different fetchs.

What's your opinion on that? Are you more concerned about readability or accuracy?

2022-03-04 08:20 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/overview_spec.js
> +    it.only('show followers in actions preview', () => {
I promise it wasn't to pass CI 😂😂😂

2022-03-04 08:30 UTC, agarciamontoro commented on client/playbook.go
> +}
That's a good point, actually, and you're right that keeping the struct would allow for more flexibility in the future.
Although the API may be used by more clients, there won't be more than a handful of them (I don't have specific data off the top of my head). In any case, the expectations set by the API version being v0 are clear: we don't yet guarantee any backwards compatibility.
In that context, I'd err on the side of simplicity here at the cost of possible future extensibility. I'll be glad if at some point we end up needing pagination here (that'll mean we have playbooks with *a lot* of autofollowers). At that point, we can improve this endpoint.

2022-03-04 08:30 UTC, agarciamontoro commented on tests-e2e/cypress/integration/playbooks/overview_spec.js
> +    it.only('show followers in actions preview', () => {
There are no test failures if there are no tests! :joy:

2022-03-04 08:33 UTC, agarciamontoro commented on webapp/src/components/backstage/playbooks/playbook.tsx
> +    }, [match.params.playbookId, currentUserId, isFollowed]);
> yes, if we include isFollowed we can have re-fetch when you click on the autofollow checkbox and preview is rendered again with the new data. if we skip this, data in the preview won't change live.

Oooh, I see, I had missed that. Thanks for the context!

> Apart from that, there is a tradeoff between being simple and more efficient. When isFollowed changes, we repeat all useEffect block that includes the playbookFetch, when we only need to fetch the followers. Since it's not that usual (only when user clicks on checkbox) I preferred to keep code together instead of doing two different useEffect blocks with different fetchs. What's your opinion on that? Are you more concerned about readability or accuracy?

Another interesting question. I actually think that shorter useEffect blocks with a single purpose are more clear (and of course more efficient, as you pointed out), so I'd be in favour of splitting it, if you agree. Up to you!

2022-03-04 08:34 UTC, trilopin commented on server/api_playbooks_test.go
> +	for _, c := range testCases {
👍

2022-03-04 09:36 UTC, trilopin commented on client/playbook.go
> +}
👍 Super clear to me

I'm going to simplify this since the context of V0 is that one.

2022-03-04 11:13 UTC, trilopin commented on server/sqlstore/playbook.go
> +	autoFollows := make([]string, 0)
I wanted to force an empty slice instead of a nil slice to match webapp expectations regarding json `[]` vs json `null`. 

I've seen that this is usually managed through custom MarshallJSON for types like Playbook. Given this is a standard type I need to do it explicitly. It's true that this might not be the best place since it's more a serialization thing that affects mostly HTTP (in contrast with the server code, which will handle correctly the nil slice).

My thought on this is, that it depends :) I don't have a strong opinion:
- if there is a struct, manage it through custom MarshallJSON
- I could do a type alias to []string like FollowerIDs and do its custom MarshallJSON
- I could do it only in the handler. it's good enough if we don't serialize in more places (grpc, websockets, other transport ways additional to plain HTTP)
- I could keep it in the sqlstore to guarantee any possible serialization, even if it's not needed itself in the rest of the server code and we are allocating some memory (not needed in some cases)

IMHO, if we don't have any other transport, the simplest way is doing it in the handler. The most elegant (but slightly overengineered) the type alias.

What do you think @crspeller ?

2022-03-04 11:41 UTC, agarciamontoro commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +    const autofollowsEnabled = props.followerIds.length > 0;
You'll need to add this `autofollowsEnabled` to the `showRunStartCardEntry` variable, too. I want to refactor this code at some point, because it's very error-prone.

2022-03-04 11:49 UTC, trilopin commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +    const autofollowsEnabled = props.followerIds.length > 0;
oops, you are right

2022-03-04 11:54 UTC, trilopin commented on webapp/i18n/en.json
>    "YMrTRm": "Run Summary",
@justinegeffen  I'd prefer to avoid changing this one here, because it's not part of the set of changes of its PR.

2022-03-04 11:58 UTC, trilopin commented on webapp/src/components/backstage/playbooks/playbook.tsx
> +    }, [match.params.playbookId, currentUserId, isFollowed]);
I did the split, now when you click on autofollow only getFollowers endpoint will be called 

Thanks for your tips

2022-03-04 13:44 UTC, justinegeffen commented
@agarciamontoro, AH! thank you for that. I should learn to read. :) 

That is a tricky one indeed. We can add it to the preceding step, as a statement:
"Invite two members to the channel; invited members automatically follow the run"

That said, if this is new content I recommend not including it at all - it's automatic and the next steps aren't dependent on it (i.e., it can't be a blocker as it's not opt-out) so we don't need to mention it here. In the section where this action is added (screenshot below), we can mention "Invited users automatically follow the run" in the UI.

![Screen Shot 2022-03-04 at 15 43 34](https://user-images.githubusercontent.com/4223530/156774082-d8b39872-9f01-483b-a042-c64f66c83129.png)

Thoughts?

2022-03-04 14:13 UTC, agarciamontoro commented
@justinegeffen, thanks!  Unfortunately, they are independent. Autofollowers are not invited members by default, they only follow the run created from the playbook but they may not be automatically added to the channel. For context, the original sentence proposed in the ticket was "Begin following for XX users". If that one works for you, we can keep it.

2022-03-04 14:25 UTC, justinegeffen commented
Right. I'm happy with "x members automatically following this run." (members instead of users for consistency with the previous sentence, unless members and users are specifically different).

2022-03-04 15:11 UTC, trilopin commented
@agarciamontoro @crspeller I removed the IsAutofollowing logic at handler,service,store and interfaces. 

it's an individual commit to revert it  if we wanted it in a fresh PR.

2022-03-07 09:36 UTC, agarciamontoro commented on webapp/i18n/en.json
>    "YMrTRm": "Run Summary",
I agree with Jose here, we can change that in another PR!

2022-03-07 10:46 UTC, agarciamontoro approved these changes
Looks great, @trilopin, thanks for your work here!

I left a couple more of typos I saw, but nothing blocking. Thank you!

2022-03-07 10:46 UTC, agarciamontoro commented on tests-e2e/cypress/integration/playbooks/overview_spec.js
> +    })
```suggestion
    });
```

2022-03-07 10:46 UTC, agarciamontoro commented on tests-e2e/cypress/integration/playbooks/overview_spec.js
> +    it('show followers in actions preview', () => {
```suggestion
    it('shows followers in actions preview', () => {
```

2022-03-07 13:39 UTC, justinegeffen commented
@trilopin, thanks for your patience. @agarciamontoro and I had a chat about this and I agree that the original suggestion is best: "Begin following for XX users."

Sorry about the long discussion - thanks for your patience!

2022-03-07 16:13 UTC, crspeller commented on server/sqlstore/playbook.go
> +	autoFollows := make([]string, 0)
Makes sense. I wasn't thinking of serialization here!

2022-03-07 16:14 UTC, crspeller approved these changes

2022-03-08 08:11 UTC, trilopin commented on server/sqlstore/playbook.go
> +	autoFollows := make([]string, 0)
Thanks!

2022-03-08 09:06 UTC, trilopin commented
@justinegeffen No prob at all. It was my mistake since I change the requested copy.

I've updated with the chosen one "Begin following for XX users"

Thank you all for your help

2022-03-08 12:29 UTC, justinegeffen approved these changes

2022-03-08 12:30 UTC, agarciamontoro commented
/update-branch

2022-03-08 12:36 UTC, merged