MM-41950 New playbooks permissions
mattermost/mattermost-plugin-playbooks pull request #1071
Opened 2022-03-03 19:44 UTC by crspeller

#### Summary
Adding some permissions for playbooks. See details in the linked ticket. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41950

2022-03-07 11:23 UTC, gbochora commented on webapp/src/components/backstage/select_users_below.tsx
> +    if (props.hasPermissionsToEditRoles && props.member.user_id !== props.currentUserId) {
Why doesn't UI allow a user to edit his role? If I'm not mistaken, the backend doesn't have such restriction.

2022-03-07 11:45 UTC, gbochora approved these changes
Looks great! Just a few questions.

2022-03-07 11:45 UTC, gbochora commented on server/app/permissions_service.go
> +
Is it possible that a user has `PlaybookManageRoles` permission and doesn't have `PlaybookManageMembers` permission?
If yes, it seems such users will not be able to edit roles.

2022-03-07 19:19 UTC, agarciamontoro requested changes
Looks great :) Thank you, Christopher!

I am a bit confused about some tests, and left some nits below.

2022-03-07 19:19 UTC, agarciamontoro commented on server/app/permissions_service.go
> +			if oldRoles, ok := oldMemberRoles[member.UserID]; !((!ok && len(member.Roles) == 1 && member.Roles[0] == PlaybookRoleMember) || (ok && strings.Join(member.Roles, ",") == oldRoles)) {
Nit: can we move this condition to a named variable to understand what it is without having to parse it in one's head?

2022-03-07 19:19 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +		})
Not sure if I'm parsing this right, but there it goes:
When this test case finishes, `e.BasicPlaybook` has been successfully updated, so the following test cases do not attempt to change anything in the playbook. If that's right, I'm not sure whether the following test cases function properly.
I'd be in favor of making the tests completely independent of each other, if that's possible.

2022-03-07 19:19 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +	})
The same may happen here (and in the following one) if in the future we add test cases below the one that successfully edit the playbook.

2022-03-10 16:35 UTC, crspeller commented on webapp/src/components/backstage/select_users_below.tsx
> +    if (props.hasPermissionsToEditRoles && props.member.user_id !== props.currentUserId) {
Correct. This actually matches the behavior of channels. The idea is you want to prevent the user from demoting themselves.

2022-03-10 16:36 UTC, crspeller commented on server/app/permissions_service.go
> +
It's technically possible but there isn't any way to make that happen in the UI. I also don't think that configuration makes a whole lot of sense.

2022-03-10 16:52 UTC, crspeller commented on server/api_playbooks_test.go
> +	})
These work fine because there are failures than successes. I agree it might not be totally clear what is happening. We could just make everything a separate test if you think that would clear it up.

2022-03-10 17:59 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +		})
Aaaaah, I see now. Thanks for the clarification.

2022-03-10 17:59 UTC, agarciamontoro commented on server/app/permissions_service.go
> +			if oldRoles, ok := oldMemberRoles[member.UserID]; !((!ok && len(member.Roles) == 1 && member.Roles[0] == PlaybookRoleMember) || (ok && strings.Join(member.Roles, ",") == oldRoles)) {
It definitely is, thanks!

2022-03-10 18:01 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +	})
Yup, it works now. I'm concerned that we inadvertently break them (as in making them useless because they always pass) in the future. We can solve it then if it happens, though, I'm not proposing to do it now preemptively.

2022-03-10 18:01 UTC, agarciamontoro approved these changes
:rocket:

2022-03-11 01:13 UTC, crspeller commented
Not sure why errcheck from golangci-lint decided that this PR needed to make that change. But I have made it happy.

2022-03-11 01:13 UTC, merged