e2e: CircleCI housekeeping
mattermost/mattermost-plugin-playbooks pull request #1093
Opened 2022-03-21 20:31 UTC by Phrynobatrachus

I added the license upload success/fail check back in now that the server issue there is fixed, and also updated legacy convenience images to new versions as [recommended by Circle](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034).

2022-03-22 13:45 UTC, Phrynobatrachus commented
Yeah I'm not sure what's up with that, I'm re-running it to see if it'll complete this time. The postgres logs for the Cypress jobs looked normal otherwise, which should be the only thing affected on those particular ones.

2022-03-23 12:58 UTC, lieut-data requested changes
Thanks, @Phrynobatrachus! Just a few thoughts on image version selection below.

2022-03-23 12:58 UTC, lieut-data commented on .circleci/config.yml
>    test-MySQL-Postgres-latest:
Seems like this target was exclusively for `-latest`? Is there an equivalent for `cimg`?

2022-03-23 12:58 UTC, lieut-data commented on .circleci/config.yml
> +      - image: cimg/mariadb:10.6
I like the idea of pinning MariaDB here. Should we rename the target as `test-MariaDB10-Postgres12`?

2022-03-23 12:58 UTC, lieut-data commented on .circleci/config.yml
> +      - image: cimg/postgres:11.13
Is there a way to avoid the minimum version specification, and just target the latest `11.x`? (here, and elsewhere)

2022-03-23 13:30 UTC, Phrynobatrachus commented on .circleci/config.yml
>    test-MySQL-Postgres-latest:
They appear to have gotten rid of latest tagging in the new batch of images.

2022-03-23 16:59 UTC, lieut-data commented
It might be in GitHub, yes. @crspeller, do you have admin access here? Can you take a look?

2022-03-23 17:10 UTC, crspeller commented
@lieut-data @Phrynobatrachus I removed that one as a required check.

2022-03-24 15:42 UTC, lieut-data approved these changes
Thanks, @Phrynobatrachus!

2022-03-24 19:34 UTC, merged