Add overdue tasks filter
mattermost/mattermost-plugin-playbooks pull request #1095
Opened 2022-03-22 14:09 UTC by gbochora

#### Summary
This PR adds `overdue tasks` filter to the RHS checklist. A special indicator is shown near the `Checklist` title if there are overdue tasks. Clicking on the indicator turns on/off the filter. Overdue tasks filter works together with existing filters.

https://user-images.githubusercontent.com/4368372/159499097-b3bd1c25-9743-4b5b-a043-2b358c9bdc7d.mp4

I'll add e2e tests after merging with the checklist new UI.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42399

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-03-22 16:36 UTC, crspeller approved these changes
Nice.  
FYI @iomodo since you are working on this component.

2022-03-22 16:36 UTC, crspeller commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +            if (item.due_date > 0 && DateTime.fromMillis(item.due_date) <= DateTime.now()) {
Nit: Might be just a bit nicer if this used a constant `DateTime.now()` instead of smearing it.

2022-03-23 09:51 UTC, agarciamontoro requested changes
Looks great! :tada:

A couple of suggestions below.

2022-03-23 09:51 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +                            {formatMessage({defaultMessage: '{num} tasks overdue'}, {num: overdueTasksNum})}
You can use the [plural format](https://formatjs.io/docs/core-concepts/icu-syntax#plural-format) here to cover the case where there is a single task overdue:
```suggestion
                            {formatMessage({defaultMessage: '{num} {num, plural, =1 {task} other {tasks}} overdue'}, {num: overdueTasksNum})}
```

2022-03-23 09:54 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +            if (item.due_date > 0 && DateTime.fromMillis(item.due_date) <= now) {
The second suggestion, that I somehow forgot to add before:
Should we count only unchecked items here?
```suggestion
            if (item.state !== ChecklistItemState.Open && item.state !== ChecklistItemState.InProgress && item.due_date > 0 && DateTime.fromMillis(item.due_date) <= now) {
```

2022-03-23 10:31 UTC, gbochora commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +            if (item.due_date > 0 && DateTime.fromMillis(item.due_date) <= now) {
Yes, we are not interested in finished tasks. We want to show number of tasks that are open/in progress and are overdue.

2022-03-23 10:32 UTC, gbochora commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +                            {formatMessage({defaultMessage: '{num} tasks overdue'}, {num: overdueTasksNum})}
Great catch! Also didn't know about plural support, thanks ;)

2022-03-23 10:54 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +            if (item.due_date > 0 && DateTime.fromMillis(item.due_date) <= now) {
Ugh, sorry, my suggestion above was wrong, I should have used `===` instead of `!==`. I tested the PR and overdue *checked* tasks are still counted, so I think we still need to fix this, right?
This is what I meant before, sorry for the confusion:
```suggestion
            if ((item.state === ChecklistItemState.Open || item.state === ChecklistItemState.InProgress) && item.due_date > 0 && DateTime.fromMillis(item.due_date) <= now) {
```

2022-03-23 11:21 UTC, agarciamontoro approved these changes
Perfect, thank you! :tada:

2022-03-23 11:22 UTC, gbochora commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +            if (item.due_date > 0 && DateTime.fromMillis(item.due_date) <= now) {
Oh, now I see what you meant. Nice catch! Fixed it.

2022-03-25 12:21 UTC, abhijit-singh approved these changes
Looks great @gbochora! Just one small nit - when just 1 task is overdue, can the text be `1 task overdue` instead of `1 tasks overdue`? Just have to remove the `s`.

2022-03-30 07:45 UTC, merged