MM-40820, MM-40857: Translate datetime_input
mattermost/mattermost-plugin-playbooks pull request #1107
Opened 2022-03-29 14:54 UTC by calebroseland

#### Summary
- Translates datetime_input
- Converts a few strings

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-40820
- https://mattermost.atlassian.net/browse/MM-40857

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-04-04 14:24 UTC, crspeller requested changes

2022-04-04 14:24 UTC, crspeller commented on webapp/src/components/formatted_duration.tsx
> +    //! start:backwards-compat luxon < 2.3
Is this some sort of standard comment?

2022-04-04 14:24 UTC, crspeller commented on webapp/src/components/datetime_parsing.ts
> +    DurationRatios[locale] ??= Object.entries(baseUnits).reduce<Ratios>((ratios, [unit, ratio]) => {
This function sets a global instead of returning a value?

2022-04-04 14:24 UTC, crspeller commented on webapp/src/components/datetime_parsing.ts
> +export function infer(locale: string, query: string, mode?: Mode.DateTimeValue): DateTime | null;
What's all this?

2022-04-04 14:24 UTC, crspeller commented on webapp/src/components/datetime_input.tsx
> +    const {locale} = useIntl();
Why does this need to be localized? Isn't this only convenience for code? Which should always be in en?

2022-04-12 09:48 UTC, gbochora approved these changes
Great work!

2022-04-12 15:12 UTC, calebroseland commented
Wait until after 1.27 before merging

2022-04-12 16:46 UTC, crspeller approved these changes
Lots of complexity here. It seems pretty well contained so I think this is fine.

2022-04-14 04:30 UTC, merged