Mm 42153 update daily digest message
mattermost/mattermost-plugin-playbooks pull request #1108
Opened 2022-03-29 16:12 UTC by gbochora

#### Summary
This PR updates the daily digest and `/playbook todo` messages contents.

- The daily digest now only shows tasks that are overdue or due today and just a summary of `x tasks without due date and y tasks due after tomorrow`. The message suggests users use `/playbooks todo` to see all their tasks.
- `/playbook todo` message now includes information about tasks due date.

**`/playbook todo` message**

<img width="912" alt="Screenshot 2022-03-29 at 18 09 37" src="https://user-images.githubusercontent.com/4368372/160656458-23895039-2627-43ca-91c9-867a0d5fa6a1.png">

**Daily digest**

<img width="912" alt="Screenshot 2022-03-29 at 18 26 32" src="https://user-images.githubusercontent.com/4368372/160656548-0c06bde0-d6ca-4c52-aaaa-b7351893d1f9.png">

**Daily digest edge cases:** No tasks with due date

<img width="912" alt="Screenshot 2022-03-29 at 18 31 01" src="https://user-images.githubusercontent.com/4368372/160656851-6d062ad0-6abc-4b6b-958e-115719aae559.png">

**Daily digest edge cases:**  No tasks due today or before today

<img width="912" alt="Screenshot 2022-03-29 at 18 32 23" src="https://user-images.githubusercontent.com/4368372/160656977-0afa9cdb-09bd-4b4f-927c-2b9967f312ca.png">

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42153

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-03-31 20:51 UTC, crspeller approved these changes
Couple of non-blocking suggestions.

2022-03-31 20:51 UTC, crspeller commented on server/app/playbook_run_service_test.go
> +	controller := gomock.NewController(t)
That's a lot of mocking just to get this test. Is there a way we could do this as a test in `server/api_runs_test.go`?

2022-03-31 20:51 UTC, crspeller commented on server/api/bot.go
> +		if err = h.playbookRunService.DMTodoDigestToUser(userID, false, timezone); err != nil {
Don't we want to always use the TZ behavior of the user object? Why do we prefer the browser one?

2022-04-01 08:25 UTC, gbochora commented on server/api/bot.go
> +		if err = h.playbookRunService.DMTodoDigestToUser(userID, false, timezone); err != nil {
You are right. I first implemented the `daily digest` part and didn't know about the existence of user TZ at that point.

2022-04-01 08:55 UTC, gbochora commented on server/app/playbook_run_service_test.go
> +	controller := gomock.NewController(t)
The daily digest message doesn't have an API endpoint, so I think there is no way.

`/playbook todo` has an API endpoint, but it doesn't return post text. Instead, it just posts a message in the channel, so we must retrieve text from the database.

2022-04-01 08:59 UTC, agarciamontoro requested changes
Looks good! Coding this type of logic is always cumbersome, but the result is great :) I just found a couple of typos and I left a suggestion about moving some code, but nothing important.

2022-04-01 08:59 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +func buildAssignedTaskMessageSummery(runs []AssignedRun, locale string, timezone *time.Location, onlyDueUntilToday bool) string {
Typo
```suggestion
func buildAssignedTaskMessageSummary(runs []AssignedRun, locale string, timezone *time.Location, onlyDueUntilToday bool) string {
```

2022-04-01 08:59 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +	currentTime := time.Unix(now/1000, 0).In(timezone)
There is a function in `timeutils` you can use for this type of conversion: `timeutils.GetTimeForMillis`: https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/timeutils/timeutils.go#L9-L11

2022-04-01 08:59 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +	// add summery info for tasks without a due date or due date after today
Typo
```suggestion
	// add summary info for tasks without a due date or due date after today
```

2022-04-01 08:59 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +}
What do you think about moving these utils functions to `timeutils` too? I think they may be useful elsewhere

2022-04-01 08:59 UTC, agarciamontoro commented on server/app/playbook_run_service_test.go
> +		)
I did not know about `DoAndReturn`, that's cool!

2022-04-01 10:11 UTC, gbochora commented on server/app/playbook_run_service.go
> +}
Excellent idea! Didn't know about `timeutils`.

2022-04-01 10:43 UTC, agarciamontoro approved these changes
:tada:

2022-04-04 12:17 UTC, abhijit-singh approved these changes
Looks good!

2022-04-04 12:24 UTC, merged