Mm 42149 rhs add due date info to checklist
mattermost/mattermost-plugin-playbooks pull request #1115
Opened 2022-04-01 13:46 UTC by gbochora

#### Summary
This PR adds due date info to the RHS checklist items. If the task is overdue or due today, it will be displayed in red colors. 
In addition, PR adds license control on the client-side and server-side. The `Task due date` feature will be available on professional and enterprise plans.

https://user-images.githubusercontent.com/4368372/161275269-10444a0d-094a-41b5-b7ee-344f55c48710.mp4

Note: missing texts for the upgrade modal.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42149
https://mattermost.atlassian.net/browse/MM-42151

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-04-05 11:42 UTC, agarciamontoro requested changes
This is a really useful feature, thanks! I left some comments, the only blocking one is the one about the copy in the modal. Great job :)

I also wanted to suggest adding `cursor: pointer` to the `n tasks overdue` badge in the header of the checklists, because I only realized that was clickable when I saw you clicking on it on the video.

2022-04-06 14:21 UTC, gbochora commented on server/telemetry/rudder.go
> -		}
Ups, I deleted it by mistake. Nice catch, thanks.

2022-04-06 14:30 UTC, gbochora commented on webapp/src/components/checklist_item/duedate.tsx
> +            title={dueDateEditAvailable ? formatMessage({defaultMessage: 'Add due date'}) : ''}
Yes, when the due date feature is not available(i.e. Team edition plan) hover menu button should be disabled, like this:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/4368372/161998420-d67cb5ba-b6e9-4923-8073-7b64edcbdc26.png">

So component defines styling according to this parameter.

2022-04-07 04:59 UTC, abhijit-singh requested changes
Thanks, @gbochora! A few requests:
 1. In the due date chip, can we make the calendar icon colour opacity 56%?
 2. For cases when a task is overdue, can we make the text semi-bold?
<img width="366" alt="image" src="https://user-images.githubusercontent.com/14369607/162122561-2136e4d3-a846-4fba-95e8-9ba555c45741.png">
3. Can we change the text `Add time frame` to just `Add due date`? I had `Add time frame` in the playbook edit page because the user cannot really configure an exact due date in the playbook. But in the RHS we can simply call it `Add due date`.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/14369607/162123170-87acf966-0c54-4c23-91b6-86f8d99b5205.png">
4. When the due date/time is more than 24 hours away, do you think we could say `Due tomorrow` instead of showing something like `Due in 38 hours`. It reads easier to me that way but I'm 1/5. Open to feedback. cc @itao

2022-04-07 07:49 UTC, agarciamontoro commented on webapp/src/components/checklist_item/duedate.tsx
> +            title={dueDateEditAvailable ? formatMessage({defaultMessage: 'Add due date'}) : ''}
Oh, I meant in the `title` prop, but I guess that that title would appear below that tooltip, right? Thanks for the context :)

2022-04-07 07:53 UTC, gbochora commented on webapp/src/components/checklist_item/duedate.tsx
> +            title={dueDateEditAvailable ? formatMessage({defaultMessage: 'Add due date'}) : ''}
Yes, when a title is set, it shows both title and tooltip. Unfortunately, I couldn't find a way to disable showing icon title on mouse hover, so I just set empty text.

2022-04-08 05:10 UTC, iomodo requested changes
This is awesome! Great job @gbochora ! 

Minor changes needs for `<AssignTo>` component.

2022-04-08 05:10 UTC, iomodo commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                {(props.checklistItem.due_date > 0 || isEditing) &&
We should probably see `<AssignTo>` component with attribute `withoutName=true` when we render a only 2 components.

2022-04-08 05:10 UTC, iomodo commented on webapp/src/components/checklist_item/duedate.tsx
> +        setShowOnRight(ref.current.offsetLeft > 50);
Where does `50` come from?

2022-04-08 10:14 UTC, gbochora commented on webapp/src/components/checklist_item.tsx
> +                    {
Removed old file.

2022-04-08 10:15 UTC, gbochora commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                {(props.checklistItem.due_date > 0 || isEditing) &&
Fixed.

2022-04-08 10:16 UTC, gbochora commented on webapp/src/components/checklist_item/duedate.tsx
> +        setShowOnRight(ref.current.offsetLeft > 50);
50 is the first button left offset. If due date is first in the row, we should show popup on the right side, otherwise on the left.

2022-04-08 11:31 UTC, iomodo approved these changes
Great, thanks!

2022-04-08 13:38 UTC, agarciamontoro approved these changes
Looks perfect! And great tests :tada:

Thank you, @gbochora

2022-04-08 17:03 UTC, abhijit-singh reviewed
Thanks for addressing the changes @gbochora! 

I stumbled across something weird though, let me try and explain it here — On selecting `Today` from the suggested options, it highlights the chip in red and also bolds the text. In this particular example, it shows `Due in 2 hours`, which is also correct (as there's 1.5 hours in the day to end). 

Now if I manually type in `in 2 hours ` in the input box, it shows `Due in 2 hours` in the chip, which is correct. But it does not highlight the chip in red. This seems weird from the user's perspective. 

Based on this, I think a better logic would be to highlight in red when the due time is less than 12 hours away only.  

![2022-04-08 22 17 14](https://user-images.githubusercontent.com/14369607/162488019-3ba08c2b-8e1f-40d3-b0d5-447b9afb9bca.gif)

I have a couple more minor non-blocking requests as well(sorry for not pointing these out earlier). Summarizing the requests here but as these are all non-blocking in my opinion, I'd be okay with handling these later also:
1. Based on the above scenario, only change colour, to red when due date is less than 12 hours away. 
2. Do not make the text bold unless the task is overdue. If it is due in 12 hours, it should be in red but not bold. 
<img width="184" alt="image" src="https://user-images.githubusercontent.com/14369607/162488278-b8394ebb-8111-441f-9973-ba9f4cb541a2.png">

3. The icon font-size should be 14.4px as per the design. This can be achieved by changing the class on the icon div to `icon-12` from the current `icon-14`.
4. There seems to be some extra space to the left of the icon (inside the chip). It can be reduced by around 4px.

2022-04-08 19:21 UTC, gbochora commented
@abhijit-singh Fixed all 4 issues.

2022-04-08 19:49 UTC, abhijit-singh approved these changes
💯 Perfect! Thank you @gbochora!

2022-04-08 19:54 UTC, merged