[MM-42080] Support item addition
mattermost/mattermost-plugin-playbooks pull request #1122
Opened 2022-04-05 19:48 UTC by iomodo

#### Summary
This PR adds support for item addition.

https://user-images.githubusercontent.com/2340127/161836476-cba470cc-47b6-40d6-8689-f17da680d650.mp4

#### Ticket Link
  Fixes: https://github.com/mattermost/mattermost-server/issues/XXXXX

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-04-07 05:36 UTC, abhijit-singh requested changes
This is great @iomodo! A few minor requests:
1. Can we make the font-weight for `Add a task` normal or 400? It doesn't have to be bold.
2. In the hover state for `Add a task`, can we change the background color to --button-bg with 8% opacity?
3. When a new task is added, the description area seems to have some extra space and then shrinks on focus. The extra space should never be there. 
![2022-04-07 11 03 00](https://user-images.githubusercontent.com/14369607/162127504-8d2c428d-de10-4854-8f9d-b87ebde74985.gif)
4. When switching to the description field by pressing `tab`, it seems to have a border slightly visible. It will be ideal if we can hide it.

2022-04-07 21:43 UTC, crspeller requested changes
Great! Just a couple nits.

2022-04-07 21:43 UTC, crspeller commented on webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
> +                                    cancelAddingItem={() => {}}
Maybe we can just make this parameter optional instead of having to pass an empty function here?

2022-04-08 14:54 UTC, crspeller approved these changes
Great!

2022-04-12 11:20 UTC, abhijit-singh commented on webapp/src/components/rhs/rhs_checklist.tsx
> +        background-color: rgba(var(--center-channel-color-rgb), 0.08);
This should be `background-color: var(--button-bg-08);`

2022-04-12 11:20 UTC, abhijit-singh approved these changes
Just added one small comment. Else looks great!

2022-04-12 16:59 UTC, crspeller approved these changes

2022-04-12 17:08 UTC, gbochora commented on webapp/src/components/checklist_item/assign_to.tsx
> +`;
Nit: newline.

2022-04-12 17:20 UTC, gbochora commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                            withoutName={command !== '' && !isEditing}
Do we hide the `Assign` button name when the second button in the row is the `Due date` button?
If yes, then here we need `|| props.checklistItem.due_date > 0` condition. It seems you removed it during the merge.

2022-04-12 17:32 UTC, gbochora commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                            }
Same is here.

2022-04-12 17:46 UTC, iomodo commented on webapp/src/components/checklist_item/checklist_item.tsx
> +            {(assigneeID !== '' || command !== '' || props.checklistItem.due_date > 0 || isEditing) &&
Empty `Row` is rendered and it messes up the margins

2022-04-12 17:48 UTC, iomodo commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                            withoutName={command !== '' && !isEditing}
Automatic merge failure

2022-04-12 18:30 UTC, gbochora commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                                due_date: 0,
I guess due date needs a state like `assigneID`, which should be set here instead of 0, and also, we will need to update the state in the `onDueDateChange`.

2022-04-12 18:39 UTC, iomodo commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                                due_date: 0,
correct, already pushed the changes

2022-04-12 19:03 UTC, gbochora commented on webapp/src/components/checklist_item/duedate.tsx
> +    color: var(--center-channel-color-32);
if task is overdue or due soon, color should be `rgba(var(--center-channel-color-rgb)`, like calendar icon on the 358 line.

2022-04-12 19:14 UTC, gbochora requested changes
I left some comments. 

Few more:
- Hover menu persists after exiting from the checklist item edit mode
https://user-images.githubusercontent.com/4368372/163035828-7783d992-b030-48d5-ba4f-32f28fe1deb7.mp4

- Checklist item(any) drag causes errors in the console when edit mode is enabled. 
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/4368372/163036142-78a9001f-8329-4e82-97af-3dfb75559774.png">

2022-04-13 11:52 UTC, gbochora approved these changes
Nice!

2022-04-14 12:07 UTC, abhijit-singh approved these changes
Thanks for making the changes @iomodo! Looks so much better 🎉 

I noticed that a few things out of the Figma comments were not resolved. I've marked them in Figma and also listed them here. Approving this PR as they are minor and non-blocking. 

1. The task hover state background should be `center-channel-text` with 4% opacity and not 8%.
2. In the hover actions, the calendar icon button is larger than the rest. The class applied is icon-16 when it should be icon-12 (which makes font-size: 14.4px). The 3 dot icon also looks larger than the rest.
3. On hover, the icon colour should change from `center-channel-text 56% opacity` to `center-channel-text 72% opacity
4. In the edit state, colour of the icon in each chip should be the same — `center-channel-text 56% opacity`

2022-04-14 13:38 UTC, merged