[MM-42080] Skip checklist
mattermost/mattermost-plugin-playbooks pull request #1124
Opened 2022-04-06 11:39 UTC by iomodo

#### Summary
This PR adds support to skip checklist

https://user-images.githubusercontent.com/2340127/161966466-44f68215-8379-496d-849e-1589a08b38bd.mp4

#### Ticket Link
  Fixes: https://github.com/mattermost/mattermost-server/issues/MM-42080

#### Checklist

- [X] Telemetry updated
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-04-07 10:07 UTC, agarciamontoro requested changes
A few nits here and there, but it looks amazing! Thanks :tada:

2022-04-07 10:07 UTC, agarciamontoro commented on webapp/src/components/collapsible_checklist_hover_menu.tsx
> +
Should `#D24B4E` be themed?

2022-04-08 10:30 UTC, iomodo commented on webapp/src/components/collapsible_checklist_hover_menu.tsx
> +
I don't think so, but let's ask @abhijit-singh to be more certain.

2022-04-08 10:30 UTC, iomodo commented on webapp/src/components/collapsible_checklist.tsx
> +    }
nice!

2022-04-08 14:18 UTC, agarciamontoro commented on webapp/src/components/collapsible_checklist_hover_menu.tsx
> +
Maybe `var(--dnd-indicator);`? But yeah, Abhijit has the last word!

2022-04-08 14:21 UTC, agarciamontoro approved these changes
Neat! Thanks, Shota :)

2022-04-12 11:09 UTC, abhijit-singh commented on webapp/src/components/collapsible_checklist_hover_menu.tsx
> +
Yep, it should be the `dnd-indicator` colour. I believe it is same across all themes today, but having the variable instead of the hex code should make it future proof.

2022-04-12 11:09 UTC, abhijit-singh approved these changes
Looks great!

2022-04-13 09:43 UTC, merged