[MM-43429] Fix hover effect for checklist item
mattermost/mattermost-plugin-playbooks pull request #1131
Opened 2022-04-14 19:30 UTC by iomodo

#### Summary
This PR fixes hover effect for checklist item pills

https://user-images.githubusercontent.com/2340127/163462529-e3cbed1f-e7f8-447f-beee-8a66282c9454.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-43429

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-04-15 15:45 UTC, Phrynobatrachus approved these changes

2022-04-18 05:31 UTC, abhijit-singh requested changes
Thanks @iomodo.

Just one thing — in the edit state, while hovering on any of the attributes, the mouse pointer should change to a hand as clicking on any of them opens a popout. Currently it seems to be different for all three.

2022-04-18 16:41 UTC, gbochora approved these changes

2022-04-19 08:30 UTC, iomodo commented
updated design:

https://user-images.githubusercontent.com/2340127/163960014-5a3854c2-b73c-409e-9eea-bf5d184bea71.mp4

2022-04-19 12:03 UTC, abhijit-singh approved these changes
Perfect 💯

2022-04-19 13:34 UTC, merged