Fix private/public icon update issue
mattermost/mattermost-plugin-playbooks pull request #1138
Opened 2022-04-16 17:56 UTC by gbochora

#### Summary
On the `Playbook preview` page, public/private icon did not update automatically when converting a playbook to private. 
A similar case was with the number of members, addin/removing a member did not update the number.
`Playbook access modal` and `Playbook preview` have their own copies of playbook object, so changes in the modal didn't reflect on the preview page. This PR fixes both issues by updating the preview page state from the modal.

Note: New Playbook editor has the same issues. I can't fix it now because it's under development.

https://user-images.githubusercontent.com/4368372/163686074-e9cd6a08-26cd-4c01-bc79-f41ad5e66f16.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41580

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-04-19 14:15 UTC, crspeller requested changes

2022-04-19 14:15 UTC, crspeller commented on webapp/src/components/backstage/playbook_access_modal.tsx
> +    useEffect(() => {
This can cause double renders. Maybe intercepting uses of updatePlaybook would be better?

2022-04-20 16:54 UTC, crspeller approved these changes
Great!

2022-04-21 13:39 UTC, iomodo approved these changes

2022-04-21 13:41 UTC, merged