[MM-42660] Create a timeline event when an update is snoozed.
mattermost/mattermost-plugin-playbooks pull request #1139
Opened 2022-04-17 14:50 UTC by jeffreyssmith2nd

#### Summary

Adds a timeline event to record when a status update reminder is snoozed.

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/19908

#### Checklist

~~- Telemetry updated~~
~~- Gated by experimental feature flag~~
~~- Unit tests updated~~

2022-04-17 14:50 UTC, mattermod commented
Hello @jeffreyssmith2nd,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-04-18 19:53 UTC, lieut-data commented
Sweet, thank you @jeffreyssmith2nd! I've asked two of our core committers to help review :)

2022-04-20 16:45 UTC, jeffreyssmith2nd commented
Hey @agarciamontoro, thanks for the feedback.

I noticed there weren't any tests around the `/reminder` route and I wasn't sure if that was intentional, sounds like it was just yet to be implemented. I'd be happy to add those tests, I'll look into it probably early next week and get this PR updated with them.

2022-04-20 17:48 UTC, agarciamontoro commented
> sounds like it was just yet to be implemented.

Yup, that was it!

> I'd be happy to add those tests, I'll look into it probably early next week and get this PR updated with them.

Great, thank you! Let us know if you have any question :)

2022-04-21 08:31 UTC, trilopin reviewed
Thank you for your help!

I've just added a tiny request.

2022-04-21 08:31 UTC, trilopin commented on server/app/reminder.go
> +func (s *PlaybookRunServiceImpl) ResetReminder(playbookRunID string, newReminder time.Duration) error {
it would be great if you add a comment describing this public func.

2022-05-02 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-05-02 19:44 UTC, lieut-data commented
@jeffreyssmith2nd, can we help with the changes described above?

2022-05-03 12:42 UTC, jeffreyssmith2nd commented
Hey @lieut-data sorry for the delay here, got busy with other stuff. I did have a chance to look at this last night and started making progress on it.

2022-05-03 14:57 UTC, lieut-data commented
Awesome, thank you @jeffreyssmith2nd!

2022-05-04 19:50 UTC, trilopin commented on client/reminders.go
> +	fmt.Println(s.client)
I guess we can remove these prints

```suggestion
```

2022-05-05 13:03 UTC, jeffreyssmith2nd commented on client/reminders.go
> +	fmt.Println(s.client)
Fixed, sorry should have caught that

2022-05-10 11:32 UTC, agarciamontoro approved these changes
This looks great, @jeffreyssmith2nd, thank you!

2022-05-10 11:33 UTC, agarciamontoro commented
I saw that there's a failure in the linter, but it is not from a file in this PR :thinking: I'll merge master into your branch to see if this fixes it.

2022-05-10 11:33 UTC, agarciamontoro commented
/update-branch

2022-05-10 14:29 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-05-10 14:52 UTC, jeffreyssmith2nd commented
> Ugh, that lint error was fixed in the very latest commit. Updating again. @jeffreyssmith2nd, ~~could you also run `make mocks` again to solve the conflict?~~
> 
> EDIT: The automatic `/update-branch` did not work, of course, so I took the liberty to do it manually and push the changes along with the `make mocks`.

Great, thanks for fixing that!

2022-05-16 17:23 UTC, Phrynobatrachus requested changes
This looks pretty good so far, but I think there's still a few things left to handle. In the timeline view, the new events look like this:

![Screenshot from 2022-05-16 12-33-17](https://user-images.githubusercontent.com/3723666/168646204-630a6303-169e-4e54-9fab-d167efdfb79e.png)

These should be filled out. Here's some existing ones for comparison:

![Screenshot from 2022-05-16 13-21-00](https://user-images.githubusercontent.com/3723666/168648429-bd6f32bd-766c-4d33-8e17-a54509c0803e.png)

I think the flag icon would be appropriate for this event as well. There is also a filter for different types of timeline events:

![Screenshot from 2022-05-16 13-08-59](https://user-images.githubusercontent.com/3723666/168646621-144a0997-e944-4b48-8a82-d745403a1993.png)

Currently, these events only show with `All events` checked. To me it would make sense to include these with the `Status updates` checkbox, but 0/5 on that.

So in total, this is what I believe needs to be added.

- [ ] fields on the `TimelineEvent` in `server/app/reminder.go`, probably `Summary` and/or `Details`
- [ ] case handler for the event in the webapp component `webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx`
- [ ] filter handling in `webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx`

cc @agarciamontoro regarding how to include this event in the filters

2022-05-27 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-06-08 11:08 UTC, agarciamontoro commented
@jeffreyssmith2nd, I took a look at this and the missing info seems to be rendered directly by [the webapp code](https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx#L195-L265). You only need to add another case to that switch to handle the new event you added.

By the way, the conflicting files here will be solved by merging master and running `make mocks`. Let us know if there's anything else we can help with!

2022-07-27 15:51 UTC, Phrynobatrachus commented
Closing this in favor of #1350. :tada:

2022-07-27 15:51 UTC, closed without merging