Add endpoint to modify status update broadcast settings
mattermost/mattermost-plugin-playbooks pull request #1140
Opened 2022-04-18 13:10 UTC by gbochora

#### Summary
This PR adds an API endpoint to modify status update broadcast settings. Also does minor refactoring of tests, removed unnecessary code.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43131

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-04-18 14:17 UTC, trilopin commented on server/app/mocks/mock_playbook_run_store.go
> +// MockPlaybookRunStore is a mock of PlaybookRunStore interface.
Is this powered by some automatic linter or manually changed? What's the reason behind the global `.` change?

2022-04-18 14:41 UTC, gbochora commented on server/app/mocks/mock_playbook_run_store.go
> +// MockPlaybookRunStore is a mock of PlaybookRunStore interface.
I think the new version of `GoMock` does this.

2022-04-18 15:01 UTC, trilopin commented on server/app/mocks/mock_playbook_run_service.go
> +	time "time"
are these alias necessary?

2022-04-18 15:02 UTC, trilopin commented on server/app/mocks/mock_playbook_run_store.go
> +// MockPlaybookRunStore is a mock of PlaybookRunStore interface.
ignore my comment if this was autogenerated :)

2022-04-18 17:09 UTC, agarciamontoro requested changes
This looks great, thank you :tada:

The only blocking comment I have is about changing the service test with an "E2E" server test.

2022-04-18 17:09 UTC, agarciamontoro commented on server/sqlstore/playbook_run_test.go
> +		require.Equal(t, []string{"1", "4", "5"}, followers)
Should we use here `followersNew` (probably with a prior sorting, too)?
```suggestion
		require.Equal(t, followersNew, followers)
```

2022-04-18 17:09 UTC, agarciamontoro commented on server/app/playbook_run_service_test.go
> +	t.Run("invalid channel name has only invalid characters", func(t *testing.T) {
Old name not updated?

2022-04-18 17:09 UTC, agarciamontoro commented on server/app/playbook_run_service_test.go
> +		)
I feel like these mocks kind of defeat the purpose of this test. What do you think about updating the `client` package with the new endpoint and using the "E2E" server tests for testing these changes?

2022-04-18 17:28 UTC, agarciamontoro commented on server/app/mocks/mock_playbook_run_service.go
> +	time "time"
These files are automatically generated by gomock.

2022-04-18 18:17 UTC, trilopin commented on server/app/mocks/mock_playbook_run_service.go
> +	time "time"
Thanks, no objection then

2022-04-19 07:10 UTC, gbochora commented on server/app/playbook_run.go
> +	BroadcastChannelIDs       []string `json:"broadcast_channel_ids"`
I think we can discuss this at today's syn meeting. I like the idea of renaming.

2022-04-19 07:18 UTC, gbochora commented on server/app/playbook_run.go
> +	// UpdateFollowers updates run followers list, after call run will have only followers listed in the `followers` array
// UpdateFollowers replaces the run's existing followers list with a new one(followers array)
What do you think about this option? is it better?

2022-04-19 08:18 UTC, agarciamontoro commented on server/app/playbook_run.go
> +	// UpdateFollowers updates run followers list, after call run will have only followers listed in the `followers` array
Yup, I like it better. Thanks, @gbochora :)

2022-04-19 08:49 UTC, trilopin commented on server/app/playbook_run.go
> +	BroadcastChannelIDs       []string `json:"broadcast_channel_ids"`
👍 I like the idea too

2022-04-19 16:35 UTC, agarciamontoro commented on server/app/playbook_run_service_test.go
> +		)
client package in the server code. I mean a test like the ones in this file: https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/api_runs_test.go

2022-04-20 16:59 UTC, gbochora commented on server/app/playbook_run_service_test.go
> +		)
Thanks @agarciamontoro, it's much better now.

2022-04-21 08:39 UTC, trilopin commented on client/playbook_runs.go
> +func (s *PlaybookRunService) UpdateRunActions(ctx context.Context, playbookRunID string, settings RunAction) error {
it would be great if this public func had a docstring comment

2022-04-21 08:43 UTC, trilopin commented on server/api/playbook_runs.go
> +	if err := h.playbookRunService.SetRunActions(playbookRunID, params); err != nil {
would make sense to use SetRunActions or updateActions name in both places? I'm not against one or other names, but I would love to use the same if they are part of the same process.

2022-04-21 08:46 UTC, trilopin commented on server/api_runs_test.go
> +		err := e.PlaybooksClient.PlaybookRuns.UpdateRunActions(context.Background(), e.BasicRun.ID, settings)
I would love to see the same asserts before the update to explicitly check that the value changed and it wasn't already to the same value.

2022-04-21 08:47 UTC, trilopin commented on server/api_runs_test.go
> +		err := e.PlaybooksClient.PlaybookRuns.UpdateRunActions(context.Background(), e.BasicRun.ID, settings)
Sorry, maybe I'm not clear, I would like to see the same block 923:928 lines, asserting the default values to see the difference before&after.

2022-04-21 08:55 UTC, trilopin commented on server/sqlstore/playbook_run_test.go
> +		db := setupTestDB(t, driverName)
would it make sense to do a `t.Run(fmt.Sprtintf("[%s] TestUpdateFollowers", driverName), func() ...` ? It could report the drivername in case of failure.

2022-04-21 08:56 UTC, trilopin approved these changes
Good job @gbochora!

I left some **optional** comments.

2022-04-21 09:08 UTC, gbochora commented on server/sqlstore/playbook_run_test.go
> +		db := setupTestDB(t, driverName)
Yep, It would be helpful.

2022-04-21 10:44 UTC, gbochora commented
@agarciamontoro @trilopin Thanks for the feedback. Fixed issues from comments. 
Note: I'll create separate PR to remove `StatusUpdateBroadcastFollowersEnabled` column.

2022-04-21 17:55 UTC, agarciamontoro requested changes
Much more clear! Thanks, Giorgi :)

The only thing missing would be to remove the followers-related field in the struct.

2022-04-21 17:55 UTC, agarciamontoro commented on client/playbook_runs.go
> +// UpdateRunActions updates run actions settings, e.i. status update broadcast settings
Typo:
```suggestion
// UpdateRunActions updates run actions settings, i.e. status update broadcast settings
```

2022-04-21 17:55 UTC, agarciamontoro commented on server/app/playbook_run.go
> +	StatusUpdateBroadcastWebhooksEnabled  bool `json:"status_update_broadcast_webhooks_enabled"`
Should we remove now the followers-related fields in the struct now?
```suggestion
	BroadcastChannelIDs       []string `json:"broadcast_channel_ids"`
	WebhookOnStatusUpdateURLs []string `json:"webhook_on_status_update_urls"`

	StatusUpdateBroadcastChannelsEnabled  bool `json:"status_update_broadcast_channels_enabled"`
	StatusUpdateBroadcastWebhooksEnabled  bool `json:"status_update_broadcast_webhooks_enabled"`
```

2022-04-22 06:29 UTC, gbochora commented on server/app/playbook_run.go
> +	StatusUpdateBroadcastWebhooksEnabled  bool `json:"status_update_broadcast_webhooks_enabled"`
I've created a separate branch to remove the followers-related fields. Do you think it's better if I include those changes in this PR?

2022-04-22 17:33 UTC, agarciamontoro commented on server/app/playbook_run.go
> +	StatusUpdateBroadcastWebhooksEnabled  bool `json:"status_update_broadcast_webhooks_enabled"`
@gbochora, I'm ok removing the column from the migration in another PR, but I think it's better if we don't add the `Followers` and `StatusUpdateBroadcastFollowersEnabled` to this new struct in this PR.

2022-04-23 06:07 UTC, gbochora commented on server/app/playbook_run.go
> +	StatusUpdateBroadcastWebhooksEnabled  bool `json:"status_update_broadcast_webhooks_enabled"`
Agree. I've removed the followers-related code, you can review just the last commit. Thanks.

2022-04-25 06:36 UTC, agarciamontoro approved these changes
Great! Thank you, Giorgi :)

2022-04-25 07:21 UTC, merged