Remove followers run action flag
mattermost/mattermost-plugin-playbooks pull request #1145
Opened 2022-04-25 07:40 UTC by gbochora

#### Summary
This PR removes the `broadcast to followers` flag from run data mode. There is no need for such a flag based on business requirements. 

#### Ticket Link

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-04-25 07:51 UTC, agarciamontoro requested changes
Looks good! I see that `dropColumnMySQL` and `dropColumnPG` only remove the column if it does exist, according to the code. But what happens when the exception `RAISE NOTICE 'Ignoring ALTER TABLE statement. Column "%s" does not exist in table "%s".';` is raised? Does that return an error? Or does it finish successfully?

I left a couple of typos I found below.

2022-04-25 07:51 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +					return errors.Wrapf(err, "failed droping column StatusUpdateBroadcastFollowersEnabled from table IR_Incident")
Typo
```suggestion
					return errors.Wrapf(err, "failed dropping column StatusUpdateBroadcastFollowersEnabled from table IR_Incident")
```

2022-04-25 07:51 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +					return errors.Wrapf(err, "failed droping column StatusUpdateBroadcastFollowersEnabled from table IR_Incident")
Typo
```suggestion
					return errors.Wrapf(err, "failed dropping column StatusUpdateBroadcastFollowersEnabled from table IR_Incident")
```

2022-04-26 07:28 UTC, gbochora commented
> Looks good! I see that `dropColumnMySQL` and `dropColumnPG` only remove the column if it does exist, according to the code. But what happens when the exception `RAISE NOTICE 'Ignoring ALTER TABLE statement. Column "%s" does not exist in table "%s".';` from `dropColumnPG` is raised? Does that return an error? Or does it finish successfully?

Excellent question. It doesn't return an error. `NOTICE` messages are written to the database log, and the transaction is finished successfully.

2022-04-26 08:17 UTC, agarciamontoro approved these changes
> Excellent question. It doesn't return an error. NOTICE messages are written to the database log, and the transaction is finished successfully.

Perfect! Thanks for confirming :)

2022-04-26 13:57 UTC, trilopin approved these changes
Cool, Thanks @gbochora !

2022-04-26 16:31 UTC, merged