supporting e2e tests for webapp changes
mattermost/mattermost-plugin-playbooks pull request #1146
Opened 2022-04-25 21:27 UTC by lieut-data

#### Summary
Supporting e2e changes for https://github.com/mattermost/mattermost-webapp/pull/10230.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-42755

#### Checklist
- [ ] ~Telemetry updated~
- [ ] ~Gated by experimental feature flag~
- [x] Unit tests updated

2022-04-26 18:39 UTC, Phrynobatrachus requested changes
There's an issue here,

2022-04-26 18:39 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/playbooks/overview_spec.js
> +                cy.findByTestId('playbook-title').click({force: true});
There's an issue with this logic in the context of the overall spec file. When the `it('should duplicate playbook')` test runs it creates `Copy of Public Playbook`, so the search filters down to 2 results instead of 1, and the `cy.findByTestId` fails since there's multiple valid selections. 

Could be another point in favor of isolating `it` block state entirely, see #1101 and #1102 for similar examples of gotchas.

2022-04-27 18:25 UTC, agarciamontoro approved these changes
Tests look good to me (modulo Cass' comment).

2022-04-27 18:52 UTC, lieut-data commented on tests-e2e/cypress/integration/playbooks/overview_spec.js
> +                cy.findByTestId('playbook-title').click({force: true});
Ooh, excellent catch @Phrynobatrachus! Serves me right for only running `describe.only` and then pushing :p -- pushed a fix to use a separate playbook for now.

2022-04-29 15:39 UTC, lieut-data commented
/update-branch

2022-04-29 16:27 UTC, Phrynobatrachus approved these changes
LGTM, thanks!

(I assume cloud tests will pass on Monday's FF, 0/5 if you want to merge now or hold for those)

2022-04-29 17:12 UTC, lieut-data commented
Going to merge now, and I'll own anything that breaks next week :)

2022-04-29 17:12 UTC, merged