Add skipping daiy digest when there are only tasks due after today
mattermost/mattermost-plugin-playbooks pull request #1150
Opened 2022-04-26 17:20 UTC by gbochora

#### Summary
This PR excludes summary info from daily digest message when there are only tasks due in the future and returns empty text. As a result, the daily digest message is skipped when we only have tasks due in the future.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43586

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-04-27 14:45 UTC, crspeller requested changes

2022-04-27 14:45 UTC, crspeller commented on server/app/playbook_run_service.go
> +	if onlyDueUntilToday {
Logic is a bit hard to follow here. We seem to have gotten rid of the behavior where if the `runsInfo` is empty then we skip writing this stuff. Was that intentional?

2022-04-27 15:19 UTC, gbochora commented on server/app/playbook_run_service.go
> +	if onlyDueUntilToday {
Yep, it's pretty complicated. 
Instead of `runsInfo` is empty I've added `tasksDoAfterToday == total` condition, lines 2832-2835. 
The logic here is: If we need only tasks that are due until today and all tasks are due after today(`tasksDoAfterToday == total`), we return an empty message.

2022-04-28 07:53 UTC, agarciamontoro approved these changes
Looks good!

2022-04-28 14:40 UTC, crspeller approved these changes
Looks good!

2022-04-28 14:40 UTC, merged