Add telemetry for run actions
mattermost/mattermost-plugin-playbooks pull request #1157
Opened 2022-04-29 14:19 UTC by gbochora

#### Summary
This PR adds telemetry for run actions. 
Add tracking the following events:
- Status update broadcast to the channels
- Status update broadcast to the webhooks
- Run actions settings update

Also added broadcast to channels/webhooks flags to the `Run create` event.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43175

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-04-29 18:49 UTC, agarciamontoro approved these changes
Looks good! Behaviour-wise it's perfect, but I suggested a slight change on the implementation to use the same telemetry functions both for channel and run actions. Thoughts?
In any case, non-blocking, so approving :)

2022-04-29 18:49 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +	actionRunActionsUpdate = "run_actions_update"
Nit: it's true that it's a bit of a mouthful, but if we want to be consistent with the other events and actions, this should be something like
```suggestion
	eventRunAction         = "run_action"
	actionRunAction        = "run_run_action"
	actionRunActionsUpdate = "update_run_actions"
```

2022-04-29 18:49 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +	actionRunActionsUpdate = "run_actions_update"
Maybe instead of `run_action` it could be `playbookrun_action`, so then it would be
```suggestion
	eventRunAction         = "playbookrun_action"
	actionRunAction        = "run_playbookrun_action"
	actionRunActionsUpdate = "update_playbookrun_actions"
```

2022-04-29 18:49 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +	actionRunActionsUpdate = "run_actions_update"
In any case, it's not that important, so I'll leave it up to you.

2022-04-29 18:49 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +}
Maybe we can refactor the `channelActionProperties` into `actionProperties` to receive just a string and use the same for both channel and run actions? The reason being that product-wise, channel actions and run actions are just actions, the only thing that changes is the type of the trigger and the type of the action.

2022-04-29 18:49 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +}
The same suggestion with `RunChannelAction` to be just this `RunAction`

2022-05-02 12:06 UTC, gbochora commented on server/telemetry/rudder.go
> +	actionRunActionsUpdate = "run_actions_update"
I like this one, thanks.

2022-05-02 13:06 UTC, gbochora commented on server/telemetry/rudder.go
> +}
I like your suggestion.

2022-05-02 13:40 UTC, gbochora commented on server/telemetry/rudder.go
> +}
This one is a little trickier. `RunChannelAction` and `RunAction` have different `properties["Action"]` values . It seems we should remain them different, it's an easy way to define action parent object(channel/run). 
Passing the `Action` property as an argument doesn't seem like a good solution either. I would leave it as is. Thoughts?

2022-05-03 07:24 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +}
Oh, that's true. Leaving it as is sounds good, thanks for the context!

2022-05-04 13:00 UTC, trilopin commented on server/app/playbook_run.go
> +	RunAction(triggerType, actionType, userID string)
triggerType could have any string value but is actually a non implemented enum

No need to action here at all, but I'll send a proposal to discuss an improvement.

2022-05-04 13:01 UTC, trilopin commented on server/app/playbook_run.go
> +	RunAction(triggerType, actionType, userID string)
same with ActionType

2022-05-04 13:27 UTC, trilopin commented on server/app/playbook_run_service.go
> +		s.telemetry.RunAction(TriggerTypeStatusUpdatePosted, ActionTypeBroadcastWebhooks, userID)
If I have enabled channels and webhooks two tracks will be executed through telemetry:
1. TriggerTypeStatusUpdatePosted / ActionTypeBroadcastChannels / USER1
2. TriggerTypeStatusUpdatePosted / ActionTypeBroadcastWebhooks / USER1

Don't we want to know many post-update the user does no matter if they carry 0,1,2 actions?

2022-05-04 13:31 UTC, trilopin commented on server/app/playbook_run_service.go
> +		s.telemetry.RunAction(TriggerTypeStatusUpdatePosted, ActionTypeBroadcastWebhooks, userID)
would it make sense to add to runActionProperties the runID and the playbookID?

That could answer later:
- avg run actions per run (across all playbooks)
- avg run actions per playbook run
- total run actions per run / playbook

2022-05-04 13:44 UTC, trilopin commented on server/app/playbook_run_service.go
> +		s.telemetry.RunAction(TriggerTypeStatusUpdatePosted, ActionTypeBroadcastWebhooks, userID)
I know this could be completely out of scope, just sharing some thoughts.

2022-05-04 13:45 UTC, trilopin approved these changes
Thank you @gbochora, 
 
I shared some non-blocking thoughts, the code is more than ready.

2022-05-05 10:32 UTC, gbochora commented on server/app/playbook_run_service.go
> +		s.telemetry.RunAction(TriggerTypeStatusUpdatePosted, ActionTypeBroadcastWebhooks, userID)
Great suggestions @trilopin, thanks! I've added additional properties.

2022-05-05 10:57 UTC, gbochora commented
@agarciamontoro @trilopin could you please review the last commit.

2022-05-05 11:29 UTC, agarciamontoro requested changes
Just a naming change suggestion.

2022-05-05 11:29 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +		"NumActions":    numActions,
I think I'd name this in a different way. Maybe `NumBroadcasts` or something similar. Otherwise it may be a bit confusing, because the action is only one.

2022-05-05 11:29 UTC, agarciamontoro commented on server/telemetry/rudder.go
> +		"PlaybookID":    playbookRun.PlaybookID,
This is for grouping the actions of the same playbook/run, right? Maybe not something for this PR, but: Should we do the same with channels?

2022-05-10 10:13 UTC, agarciamontoro approved these changes
Thanks, @gbochora! :tada:

2022-05-10 13:39 UTC, merged