update run modal description with broadcast info
mattermost/mattermost-plugin-playbooks pull request #1162
Opened 2022-05-02 09:37 UTC by trilopin

#### Summary
<img width="644" alt="Screenshot 2022-04-28 at 14 08 37" src="https://user-images.githubusercontent.com/4096774/165749006-2f772d83-f1b1-4e8d-aa24-b5c83f730979.png">

From https://github.com/mattermost/mattermost-plugin-playbooks/pull/1155

Brand new description in update run status modal.
This PR covers the new description we want to set in the modal for Run "Post update". The new description informs the user about how many channels and DM will be broadcasted with the update. A tooltip will be shown if the user does hover on the counters. Tooltips show up to 5 names and "and N others" in case we have more than 5.

If there are no channels or followers (DM), a different message will be shown in the description.

From the pure tech perspective, a new hook has been implemented to extract the names of the users from the userIDs. Thanks @calebroseland for your help :)

Additionally, the navigation is now done in the same tab (we force modal close if the user navigates). In a different PR, a mechanism to prevent user from losing unsaved changes will be implemented. https://github.com/mattermost/mattermost-plugin-playbooks/pull/1148 has to be merge first.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43130

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~
- [ ] E2E tests

2022-05-02 09:37 UTC, mattermod commented
Hello @trilopin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-05-03 17:48 UTC, trilopin commented
@agarciamontoro @gbochora Sorry for the new PR.

Suggestions from the dirty PR have been addressed, and additionally:
- No broadcast to 0 channels subtitle
- followers are grey underlined instead of blue, don't navigate to run overview, just show tooltip
- respect run toggle to inform about broadcast channels 
- prevent the user from losing changes if accidentally navigates
- navigation with modal opened prepared but commented until @agarciamontoro merges

2022-05-04 08:20 UTC, gbochora commented on webapp/src/hooks/general.ts
> +    const teamnameNameDisplaySetting = useSelector<GlobalState, string | undefined>(
Should this variable name be `teammateNameDisplaySetting`?

2022-05-04 08:21 UTC, gbochora commented on webapp/src/hooks/general.ts
> +// It will repect teamnameNameDisplaySetting.
Did you mean `respect`?

2022-05-04 08:23 UTC, trilopin commented on webapp/src/hooks/general.ts
> +// It will repect teamnameNameDisplaySetting.
haha yes, fat fingers

2022-05-04 10:30 UTC, gbochora commented on webapp/src/components/modals/update_run_status_modal.tsx
> +
Great job here, it's pretty complex.

2022-05-04 10:49 UTC, gbochora approved these changes
Great work @trilopin! 🥳 
One minor thing: when a status update is broadcasted to the private channels I don't have access to, the tooltip message is a little confusing. We could add hidden channels number to the `others`, i.e. `featureX and 5 others` or `IncidentY and 2 others`. 
In any case, I think it's not that important, so I'll leave it up to you.

<img width="605" alt="Screenshot 2022-05-04 at 14 38 08" src="https://user-images.githubusercontent.com/4368372/166666264-f8bc97fe-4641-45ec-b794-3b99f63fb871.png">

2022-05-04 11:25 UTC, trilopin commented on webapp/src/hooks/general.ts
> +    const teamnameNameDisplaySetting = useSelector<GlobalState, string | undefined>(
maybe, it's more accurate 👍🏽

2022-05-04 20:18 UTC, trilopin commented
> Great work @trilopin! 🥳 One minor thing: when a status update is broadcasted to the private channels I don't have access to, the tooltip message is a little confusing. We could add hidden channels number to the `others`, i.e. `featureX and 5 others` or `IncidentY and 2 others`. In any case, I think it's not that important, so I'll leave it up to you.
> 
> <img alt="Screenshot 2022-05-04 at 14 38 08" width="605" src="https://user-images.githubusercontent.com/4368372/166666264-f8bc97fe-4641-45ec-b794-3b99f63fb871.png">

nice feedback @gbochora you rock 🪨

2022-05-05 12:36 UTC, agarciamontoro approved these changes
Looks great, @trilopin, thank you! :)

I've left only nits and typos, so approving already!

2022-05-05 12:36 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +                    // * Click overview link
Nit:
```suggestion
                    // # Click overview link
```

2022-05-05 12:36 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +                });
This does test that the modal is open, but what about some specific check, as in:

```suggestion
                // * Verify that the confirmation modal is shown
                cy.get('#confirm-modal-light').should('exist').within(() => {
                    // # Go back from unsaved changes modal
                    cy.findByTestId('modal-cancel-button').click();
                });
```

2022-05-05 12:36 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +            it('cancel and discard explicitily', () => {
Typo
```suggestion
            it('cancel and discard explicitly', () => {
```

2022-05-05 12:36 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +            it('click overview link and discard explicitily', () => {
Typo
```suggestion
            it('click overview link and discard explicitly', () => {
```

2022-05-05 12:36 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +                    // * Click overview link
Nit:
```suggestion
                    // # Click overview link
```

2022-05-05 12:36 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +                // * Discard explicitily from unsaved changes
Typo :smile: 
```suggestion
                // * Discard explicitly from unsaved changes
```

2022-05-05 14:16 UTC, trilopin commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +                // * Discard explicitily from unsaved changes
done, Thank you!

2022-05-06 07:57 UTC, trilopin commented
@gbochora I implemented your suggestion, thank you!

@abhijit-singh Please take a look. It's everything ready except the navigation with the modal opened because I'm waiting for another merge.

Behavior:
- tooltips: we get as many names as possible (channels could be hidden or unknown) and show up to 5 + "and N others" 
- 0 channels broadcast text removed
- navigation only from broadcast channels, not followers
- if there is no broadcast nor followers, we just paste the overview link

2022-05-09 11:04 UTC, abhijit-singh requested changes
Thanks, @trilopin! Looks awesome.

A couple of requests: 
1. The `You have unsaved changes` modal seems to overlay on top of the `Post update` modal and both are visible. This is not consistent with how we've been handling multi-modal flows before. When the second modal is open, the first one should not be visible. Just like it works for the `Confirm finish run` modal. Attaching gifs for both cases here.
`Current`:![2022-05-09 16 24 02](https://user-images.githubusercontent.com/14369607/167396244-5536067a-049b-455e-af69-6b4129cb67d7.gif)
`Ideal behaviour`:
![2022-05-09 16 25 04](https://user-images.githubusercontent.com/14369607/167396304-82779511-b1a8-4d8c-81cc-f33e3dfc8d41.gif)
 2. It seems like if you hit `Cancel` or `X` on the "You have unsaved changes" modal, and then try to `Cancel` posting the status update, you get stuck in a loop. 
![2022-05-09 16 28 50](https://user-images.githubusercontent.com/14369607/167397153-e905e4bb-98ea-46f5-899c-11aed2e47619.gif)

 3. This is minor and may already get solved with the first two points above, but it seems like the `N channels` tooltip gets triggered automatically when you hit `Cancel` on the "You have unsaved changes" modal, and does not go away until you click somewhere else. 
![2022-05-09 16 31 02](https://user-images.githubusercontent.com/14369607/167397220-6481a666-506b-4e53-a605-dbbdafc2ccaa.gif)
4. When we only show `This update will be saved to overview page`, can we add a full stop `.` at the end? This'll make it consistent with other cases.

2022-05-10 10:05 UTC, trilopin commented
> 1. The `You have unsaved changes` modal seems to overlay on top of the `Post update` modal and both are visible. This is not consistent with how we've been handling multi-modal flows before. When the second modal is open, the first one should not be visible. Just like it works for the `Confirm finish run` modal. Attaching gifs for both cases here.

I missed this and it was always there :). It's fixed now (not pushed yet).


> 2. It seems like if you hit `Cancel` or `X` on the "You have unsaved changes" modal, and then try to `Cancel` posting the status update, you get stuck in a loop.

When you are in an unsaved modal you have two options:
- go back to edit: triggered by any type of cancel (X, click outside or cancel button)
- dismiss changes and continue

So if you cancel the unsaved, go back and if you cancel again you go again to unsaved-changes modal. In the end we ask the user to do an explicit dismiss or save. 

does it feel weird? What would you expect to happen? @abhijit-singh 

> 3. This is minor and may already get solved with the first two points above, but it seems like the `N channels` tooltip gets triggered automatically when you hit `Cancel` on the "You have unsaved changes" modal, and does not go away until you click somewhere else.

Wow, let me check this detail

> 4. When we only show `This update will be saved to overview page`, can we add a full stop `.` at the end? This'll make it consistent with other cases.

Thanks for the detailed check (done but not pushed yet)

2022-05-10 10:12 UTC, abhijit-singh commented
> So if you cancel the unsaved, go back and if you cancel again you go again to unsaved-changes modal. In the end we ask the user to do an explicit dismiss or save.

@trilopin You're right. I missed the fact that we're showing a `You have unsaved changes` modal if you click on `Cancel` or `X` on the Post Update modal after typing something. Sorry for the confusion here, you can ignore point 2 in my review, that's working as expected.

2022-05-10 10:27 UTC, trilopin commented
> This is minor and may already get solved with the first two points above, but it seems like the N channels tooltip gets triggered automatically when you hit Cancel on the "You have unsaved changes" modal, and does not go away until you click somewhere else.

It seems fixed after properly hiding the main modal when the unsaved one is triggered.

2022-05-10 11:30 UTC, abhijit-singh approved these changes
Perfect 💯!

2022-05-10 11:32 UTC, merged