[MM-43880] Allow one-character playbook names
mattermost/mattermost-plugin-playbooks pull request #1178
Opened 2022-05-11 09:52 UTC by miltalex

#### Summary
Allow one-character playbook names. Channel allows one-character name, and playbook run name which is a channel name should support one-character naming. 

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-server/issues/20108

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2022-05-11 09:53 UTC, mattermod commented
Hello @miltalex,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-05-13 13:38 UTC, lieut-data commented
Sweet, thank you @miltalex! I've asked @gbochora and @agarciamontoro to help review and merge :)

2022-05-15 16:42 UTC, gbochora requested changes
Thank you @miltalex!
I still can't create a playbook run with a one-character name.  The `Run playbook` dialog restricts the name min length to 2 characters, so we need to change it to 1 on this [line](https://github.com/mattermost/mattermost-plugin-playbooks/blob/cb1ff3ae05bbd86da2d7f21ea79d8484b106208f/server/app/playbook_run_service.go#L2311)

2022-05-15 19:56 UTC, miltalex commented
Thank you, @gbochora for the prompt review. Indeed I only tried to catch the error in the model from `mattermost-server`. i have the branch with the change. I have one question for you, the change with the one character channel name is on `master` on `mattermost-server` should I change any files as the `go.mod` to point to that version?

2022-05-16 07:20 UTC, gbochora approved these changes

2022-05-16 17:41 UTC, Phrynobatrachus approved these changes
Local testing :heavy_check_mark: 

Thanks for the PR!

2022-05-16 17:43 UTC, merged