MM-41875 Introducing graphql with playbooks
mattermost/mattermost-plugin-playbooks pull request #1186
Opened 2022-05-16 14:34 UTC by crspeller

This PR adds graphql fetching for a single playbook and updates for a single playbook. This allows the better playbook editor to make incremental updates to playbooks, avoiding conflicts. 

The backend is based on https://github.com/mattermost/mattermost-server/pull/19486 the mattermost-server implementation. Eventually we would be able to reuse that portion when we move over and the multi product architecture allows for combining our schemas. In turn this is based on https://github.com/graph-gophers/graphql-go

I will highlight important parts of the PR in comments. 

On the client side we have no current implementation to copy so I decided to use the simplest to use graphql client Apollo. I debated between Apollo and Relay. They both solve the caching problem for you. Relay is more complex but it allows for fragmented queries to allow sub-components to request exactly what data they need and be forced to only use that. It's a really nice architecture however it very much encompasses your code with Relay code which I didn't want to commit to. It also uses unreleased React features which would force us to upgrade to unstable React versions. (Relay is developed by FB) Apollo is simple and straightforward to understand.

Client types are quite the thing with graphql. I decided to try and generate them using `graphql-codegen`. 
In addition it is able to generate hooks compatible with Apollo. It does this by reading [queries from files. that we write. Then you can easily use that in your own hooks.

2022-05-16 14:34 UTC, crspeller commented on client/client.go
> +func (c *Client) DoGraphql(ctx context.Context, input *GraphQLInput, v interface{}) error {
Very basic for tests.

2022-05-16 14:36 UTC, crspeller commented on server/api/graphql.go
> +var graphiqlPage = []byte(`
This is for the query sandbox. Just visit http://localhost:8065/plugins/playbooks/api/v0/query and this page will be served to you so you can try out queries.

2022-05-16 14:38 UTC, crspeller commented on server/api/graphql_playbook.go
> +func (r *PlaybookResolver) DeleteAt() float64 {
There is some strangeness here as graphql can not support int64 which a lot of our fields are.

2022-05-16 14:39 UTC, crspeller commented on server/api/graphql_root.go
> +	if args.Updates.Public != nil {
Validation is handled separate for each field if it's included.

2022-05-16 14:40 UTC, crspeller commented on server/api/schema.graphqls
> +	checklists: [ChecklistUpdates!]
For now this is here for simplicity, but it should really be a separate mutation with it's own ID.

2022-05-16 14:41 UTC, crspeller commented on server/main.go
> +	if len(os.Args) > 1 {
This allows an easy way to check the graphql schema for validity automatically. Otherwise it would fail at runtime and be really annoying.

2022-05-16 14:44 UTC, crspeller commented on webapp/src/graphql/generated_types.ts
> +import {gql} from '@apollo/client';
This file is generated. Lots of stuff to make using graphql on the client easier.

2022-05-16 14:44 UTC, crspeller commented on webapp/src/graphql/hooks.ts
> +export const usePlaybook = (id: string): [FullPlaybook, PlaybookQueryHookResult] => {
Wrappers for the standard generated hooks to make them easier to use.

2022-05-16 14:44 UTC, crspeller commented on webapp/src/graphql/hooks.ts
> +export type FullPlaybook = PlaybookQuery['playbook']
Ideally we don't use this type and we refactor to use partials and individual queries. But this is quicker. Something for a performance effort to look at.

2022-05-16 14:46 UTC, crspeller commented on webapp/src/graphql/playbook.graphql
> +query Playbook($id: String!) {
Simple query that fetches everything for the editor.

2022-05-16 14:47 UTC, crspeller commented
Attempting to fix circleci at the moment.

2022-05-16 21:57 UTC, calebroseland requested changes
While I haven't gotten through every piece, this is really nice so far. I like the write/update hook usage. Found a couple of bugs, but otherwise first-skim looks pretty good!

2022-05-16 21:57 UTC, calebroseland commented on server/api/graphql_root.go
> +	addToSetmap(setmap, "CreatePublicPlaybookRun", args.Updates.CreatePublicPlaybookRun)
DB: column mapping
```suggestion
	addToSetmap(setmap, "CreatePublicIncident", args.Updates.CreatePublicPlaybookRun)
```

2022-05-16 21:57 UTC, calebroseland commented on server/api/graphql_root.go
> +	addToSetmap(setmap, "CreatePublicPlaybookRun", args.Updates.CreatePublicPlaybookRun)
DB: column mapping
```suggestion
	addToSetmap(setmap, "CreatePublicIncident", args.Updates.CreatePublicPlaybookRun)
```

2022-05-16 21:57 UTC, calebroseland commented on server/api/graphql_root.go
> +	addToSetmap(setmap, "DefaultOwnerEnabled", args.Updates.DefaultOwnerEnabled)
DB: column mapping
```suggestion
	addToSetmap(setmap, "DefaultCommanderEnabled", args.Updates.DefaultOwnerEnabled)
```

2022-05-16 21:57 UTC, calebroseland commented on server/api/graphql_root.go
> +	addToSetmap(setmap, "DefaultOwnerEnabled", args.Updates.DefaultOwnerEnabled)
DB: column mapping
```suggestion
	addToSetmap(setmap, "DefaultCommanderEnabled", args.Updates.DefaultOwnerEnabled)
```

2022-05-16 21:57 UTC, calebroseland commented on server/api/graphql_root.go
> +	Updates struct {
`Metrics` appears to be missing from the update pipeline/infrastructure.

2022-05-16 21:57 UTC, calebroseland commented on webapp/src/graphql/generated_types.ts
> +    metrics {
If `metrics` has a non-zero length, there's an error on read:

```
{
    "errors": [
        {
            "message": "Invalid value metric_integer.\nExpected type MetricType, found metric_integer.",
            "path": [
                "playbook",
                "metrics",
                0,
                "type"
            ]
        }
    ],
    "data": {
        "playbook": null
    }
}
```

2022-05-16 22:34 UTC, crspeller commented on webapp/src/components/backstage/playbook_edit/metrics/shared.ts
> +    if (!target) {
Fixed.

2022-05-18 16:06 UTC, lieut-data commented on server/sqlstore/playbook.go
> +		SetMap(setmap).
I'm not a huge fan of mapping a setmap directly into the SQL query. Commented on this elsewhere, but can we avoid this?

2022-05-18 16:07 UTC, lieut-data commented on server/main.go
> +	if len(os.Args) > 1 {
What's the rationale for building it into the plugin main, vs. a separate binary?

2022-05-18 16:08 UTC, lieut-data commented on server/app/playbook.go
> +			return err
Should we include which url is invalid when this happens?

2022-05-18 16:10 UTC, calebroseland approved these changes

2022-05-18 17:24 UTC, crspeller commented on client/client.go
> +	req, err := c.newRequest(http.MethodPost, url, input)
Yes they are.

2022-05-18 17:25 UTC, crspeller commented on server/api/graphql.go
> +	if !configService.IsConfiguredForDevelopmentAndTesting() {
Yes, these settings are for security and turn off some useful debugging tools.

2022-05-18 17:32 UTC, crspeller commented on server/api/graphql_playbook.go
> +func (r *PlaybookResolver) DeleteAt() float64 {
Yes.

2022-05-18 17:47 UTC, crspeller commented on server/api/graphql_root.go
> +		return nil, err
Only with custom errors see: https://github.com/graph-gophers/graphql-go#custom-errors

2022-05-18 17:49 UTC, crspeller commented on server/api/graphql_root.go
> +		fmt.Println(*args.Updates.BroadcastChannelIDs)
🤦

2022-05-18 17:53 UTC, crspeller commented on server/api/graphql_root.go
> +		if err := c.playbookStore.GraphqlUpdate(args.ID, setmap); err != nil {
I guess it's just a design decision on if you do the validation and modification here or in the store layer. I chose to do it here. Not 100% sure if that is the right decision or if there is a better split.

2022-05-18 18:00 UTC, crspeller commented on server/api_graphql_playbooks_test.go
> +			OperationName: "Playbook",
This is a query not an update. This appears to be idiomatic query naming. You just name the query after the object you get.

2022-05-18 18:06 UTC, crspeller commented on webapp/src/types/playbook.ts
> +    target?: number | null;
Yes, that is still allowed.

2022-05-18 18:09 UTC, crspeller commented on webapp/src/graphql/playbook.graphql
> +query Playbook($id: String!) {
Probably for every query.

2022-05-18 18:10 UTC, crspeller commented on webapp/src/graphql/hooks.ts
> +export const useUpdatePlaybook = (id?: string) => {
It returns a function that you use to update the playbook.

2022-05-18 18:12 UTC, crspeller commented on server/sqlstore/playbook.go
> +		SetMap(setmap).
This is the existing pattern we use just with a more systematic way of constructing it. It's no different then doing this: https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/sqlstore/playbook.go#L608

2022-05-18 18:15 UTC, crspeller commented on server/main.go
> +	if len(os.Args) > 1 {
Separate was my first plan. Ran into issues with the go embed stuff and getting a separate binary to import and read that embedded file. This ended up being simpler.

2022-05-18 19:50 UTC, merged

2022-05-19 15:06 UTC, lieut-data commented on server/sqlstore/playbook.go
> +		SetMap(setmap).
The significant difference is that the `sqlstore` owns the mapping from struct fields to column names, keeping the boundaries of ownership crisp. This approach feels much more like exposing the `p.store.db` and letting the app layer run "arbitrary" queries.