MM-44323: disable duplicate if disallowed
mattermost/mattermost-plugin-playbooks pull request #1192
Opened 2022-05-17 19:38 UTC by lieut-data

#### Summary
If a team disallows public playbook creation, disable the duplicate option for playbooks on that team.

I investigated adding a unit test, but found the effort to customize the system scheme or team scheme out of scope for this small fix.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-44323

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-05-18 08:16 UTC, agarciamontoro requested changes
The logic is good, but I have a doubt about the CSS below.

2022-05-18 08:16 UTC, agarciamontoro commented on webapp/src/components/dot_menu.tsx
> +`;
I'm not sure I understand this, aren't the styles duplicated between `DisabledDropdownMenuItemStyled` and `DropdownMenuItemStyled`? We could simply pass the `props.disabled` to `DropdownMenuItemStyled` and add the different `color` and `cursor` if that prop is true.
We can also just avoid the different return in `DropdownMenuItem` below if we pass `props.disabledAltText` conditionally to `title`, right?

2022-05-19 08:58 UTC, agarciamontoro commented on webapp/src/components/dot_menu.tsx
> +`;
Ah, I didn't catch that. It makes sense to have two returns, then. Thanks for the context :)

2022-05-31 19:26 UTC, lieut-data commented
Thanks again for the help, @calebroseland! Now looks like:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/1023171/171268919-73f446fe-ac34-4741-80ef-99d1d3246dbf.png">

2022-05-31 22:10 UTC, calebroseland approved these changes
Looks good! For expediency, I pushed a brief set of changes:
- Intl
- Added to playbook editor
- (while there) Added a small UX tweak from feedback: default to outline tab as duplicated playbooks will have zero usage on first load

<img width="535" alt="CleanShot 2022-05-31 at 17 01 30@2x" src="https://user-images.githubusercontent.com/11724372/171292103-4ed97f95-e764-4b7b-b814-6f486398c0ed.png">

2022-06-01 00:48 UTC, lieut-data commented on webapp/i18n/en.json
> +  "TD8WrM": "Duplicate is disabled for this team.",
Sigh, I had done this correctly in an earlier cherry-pick, but forgot after cleaning up. Thank you!

2022-06-01 15:17 UTC, agarciamontoro approved these changes
:tada:

2022-06-01 15:19 UTC, merged