Fix adding metric issue
mattermost/mattermost-plugin-playbooks pull request #1204
Opened 2022-05-22 06:46 UTC by gbochora

Update store tests

Add api tests

#### Summary
Metrics fields on the retrospective form are mandatory, so a user must set all values in order to publish the retrospective. Based on this, I assumed that if the Playbook has several metrics, there will be no case when we have values for one of the metrics and don't have for the other. In other words, either all metrics have values in the database, or we don't have data for any of them.
My assumption was wrong because a user can add a metric later, i.e., we have a playbook with a single metric, then we start a run for this Playbook and publish a retrospective. After that, if we add another metric to the Playbook, we have a case when one metric has value in the database and another doesn't. This was causing a `slice bounds out of range` error on the backend.

I have updated store methods, so they will return a `nil` value if no data is available for the specific metric:

- `MetricOverallAverage` gets the Playbook metrics configuration and then maps it with average values. If the average value of the metric is not available, the corresponding element is set to `nil`

- `MetricValueRange` - same as in the `MetricOverallAverage` function.

- `MetricRollingAverageAndChange` - If the first period values of the metric are not available, then the `period average` and `change` are set to `nil`. If the second period values are not available, the `period change` value is set to `nil`.

I replaced metrics tests for the store layer with new ones. Old ones contained data manipulation logic similar to store layer functions, which added complexity. 
Added server `E2E` tests, basically the same as store layer tests, but I think they are still helpful.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43951

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-05-23 10:40 UTC, trilopin commented on server/sqlstore/stats.go
>  		GroupBy("mc.ID").
200% optional

Wow, seeing the groupby clause before the where clause is shocking to me, I guess it doesn't matter to squirrel but it's not very readable in my SQL-brain

2022-05-23 10:40 UTC, trilopin commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, MIN(Value) as Min, MAX(Value) as Max").
why are not we filtering by playbookID here? I guess it works because later we cross data with playbook configs.

2022-05-23 10:40 UTC, trilopin commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, MIN(Value) as Min, MAX(Value) as Max").
I'm a bit confused about two things about the approach:
- why do we query separately avg from min/max?
- why do we need an additional query to metricconfigs and cross data if we already joined the table in the first query?

2022-05-23 11:28 UTC, gbochora commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, FLOOR(AVG(m.Value)) as Value").
There is a check in the API layer(`parsePlaybookStatsFilters` function). If PlaybookID is missing, we return an error. Do you think we still need validation in this function?

2022-05-23 11:51 UTC, gbochora commented on server/sqlstore/stats.go
>  		GroupBy("mc.ID").
Very good point! I'll move it.

2022-05-23 12:45 UTC, gbochora commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, MIN(Value) as Min, MAX(Value) as Max").
1. We have separate sections in the UI for `Range values`(Min, Max) and for `Average` values. Because of that, I've decided to create separate functions. But we never need only average or only range, so It will be better to retrieve them in a single query.
2. The first query will not include information about metrics that don't have any values in the database. We need configurations to get all existing metrics and build a result array, where `valueRange[i]` will be min-max values for the `metricConfigs[i]` or `nil` if there is no data in the database for this specific metric.

2022-05-23 12:55 UTC, trilopin commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, MIN(Value) as Min, MAX(Value) as Max").
1) completely optional 
2) got it

2022-05-23 12:56 UTC, trilopin commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, MIN(Value) as Min, MAX(Value) as Max").
I would add a short comment explaining why we need the second query and recomputation. Is not that intuitive from the code and someone could be tempted to "simplify".

2022-05-23 12:58 UTC, trilopin commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, FLOOR(AVG(m.Value)) as Value").
I would check as soon as func starts to have an early return, even if the API handles it.
It's cheap and we'll become a bit more defensive.

2022-05-24 07:04 UTC, iomodo requested changes
Looks great @gbochora, couple of nits below

2022-05-24 07:04 UTC, iomodo commented on server/sqlstore/stats.go
> +		s.log.Warnf("Error retrieving metrics configs ids for playbook %w", err)
`s.retrieveMetricConfigs` logs the same thing, so this logging is redundant.
Either `s.retrieveMetricConfigs` should not return error at all, or it should not log

2022-05-24 07:42 UTC, gbochora commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, FLOOR(AVG(m.Value)) as Value").
What do you think if we change the argument type from `filters *StatsFilters` to `filters StatsFilters`. In this case, there is no need for `nil` check.

2022-05-24 10:54 UTC, trilopin commented on server/sqlstore/stats.go
> +		Select("mc.ID as ID, FLOOR(AVG(m.Value)) as Value").
it works for me

2022-05-24 16:33 UTC, gbochora commented on client/playbook.go
> +	MetricTypeDuration = "metric_duration"
It would be better, but we will also need to change the `app/playbook` code. So, I would rather not do it in this PR. It already has quite large changes for a bug fix.

2022-05-25 10:50 UTC, trilopin approved these changes
Cool @gbochora , nice job

2022-05-25 11:13 UTC, iomodo approved these changes
LGTM!

2022-05-25 12:02 UTC, merged