Mm 20021
mattermost/mattermost-plugin-playbooks pull request #1221
Opened 2022-05-28 12:31 UTC by lapaz17

#### Summary
Opens a new modal whenever Use button is pressed inside RHS template instead of navigating to playbooks/new url. 

#### Ticket Link

  Fixes: https://github.com/mattermost/mattermost-server/issues/20021

#### Checklist

~~[ ] Telemetry updated~~
~~[ ] Gated by experimental feature flag~~
~~[ ] Unit tests updated~~

2022-05-28 12:31 UTC, mattermod commented
Hello @lapaz17,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-05-31 16:55 UTC, lieut-data approved these changes
This looks great, @lapaz17! Are there any existing e2e tests that we might be able to update as part of this effort?

2022-05-31 16:55 UTC, lieut-data commented on webapp/src/components/templates/template_data.tsx
> +            title: 'Blank',
Thanks for tidying this up!

2022-05-31 16:55 UTC, lieut-data commented on webapp/src/components/templates/template_data.tsx
> -            title: 'Playbooks: Bug Bash',
I like the idea of simplifying this title -- thank you!

2022-05-31 18:55 UTC, lapaz17 commented
> This looks great, @lapaz17! Are there any existing e2e tests that we might be able to update as part of this effort?

No, but just wrote one.

2022-06-11 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-06-13 09:47 UTC, trilopin requested changes
Cool! Thank you for your effort here with the E2E test.

I've added small style suggestions for some e2e comments.

I'm wondering if would make sense to additionally change the behavior in the title click that still navigates to playbook edit. @lieut-data any thought?

2022-06-13 09:47 UTC, trilopin commented on tests-e2e/cypress/integration/channels/rhs/template_spec.js
> +            // Open playbooks RHS.
```suggestion
            // # Open playbooks RHS.
```

2022-06-13 09:47 UTC, trilopin commented on tests-e2e/cypress/integration/channels/rhs/template_spec.js
> +            // Navigate to playbooks creation url.
```suggestion
            // * Assert that we navigated to the playbook creation URL.
```

2022-06-20 17:23 UTC, lieut-data commented
Great suggestion, @trilopin! I've helped make that change.

2022-06-20 17:23 UTC, lieut-data approved these changes

2022-06-20 17:38 UTC, Phrynobatrachus requested changes
Functionality looks correct, just a minor test issue left. Thanks!

2022-06-20 17:38 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/channels/rhs/template_spec.js
> +                cy.get('button > .icon-product-playbooks').click();
```suggestion
                cy.getPlaybooksAppBarIcon().should('be.visible').click();
```

since we're running CI with the app bar enabled now

2022-06-20 17:38 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/channels/rhs/template_spec.js
> +                cy.get('button > .icon-product-playbooks').click();
same as above

2022-06-20 17:39 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/channels/rhs/template_spec.js
> +                cy.get('button > .icon-product-playbooks').click();
```suggestion
                cy.getPlaybooksAppBarIcon().should('be.visible').click();
```

2022-06-21 07:53 UTC, trilopin approved these changes
Cool! Thanks for your work @lapaz17

2022-06-21 13:34 UTC, lieut-data approved these changes
Thanks, @Phrynobatrachus!

2022-06-21 13:53 UTC, Phrynobatrachus approved these changes

2022-06-21 13:53 UTC, merged