Rhs support rundetails
mattermost/mattermost-plugin-playbooks pull request #1239
Opened 2022-06-06 13:25 UTC by trilopin

#### Summary
Naive support for RHS inside playbook run

This will allow us to work on the content of the RHS. It's not completely finished, and some improvements and changes will be necessary to 

I also made "finish run" optional in the checklist, since a new component is needed for the run details page.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44711

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-06-07 14:36 UTC, agarciamontoro requested changes
Looks good! :tada: I left some comments below

2022-06-07 14:36 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    const sidebarRight = React.useRef(null);
Maybe that's just me, but I like to name the ref variables as `whateverRef`. Maybe `sidebarRightRef`? Or `sidebarRef` so it is shorter?

2022-06-07 14:36 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    }
Should the title be provided by the caller? I think that's a bit more flexible.

2022-06-07 14:36 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    z-index: 11;
Isn't there a way to avoid the z-index here? Maybe using a different `position`?

2022-06-07 16:02 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    z-index: 11;
I removed it for this naive iteration. As soon as we need better and deeper integration more hacks will be needed (positioning or z-index or other mechanisms)

2022-06-07 16:55 UTC, agarciamontoro approved these changes
Thanks, Jose! I left a non-blocking comment below.

2022-06-07 16:55 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    color: var(--center-channel-color-rgb);
I think you don't need the `-rgb` here:
```suggestion
    color: var(--center-channel-color);
```

2022-06-08 07:00 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
>      max-width: 780px;
Nit: `max-width` property is duplicated.

2022-06-08 07:08 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    display: ${({isOpen}) => (isOpen ? 'flex' : 'hidden')};
Do we need `isOpen` parameter? It seems its value will always be `true`

2022-06-08 07:09 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    width: 400px;
Nit: `width` property is duplicated.

2022-06-08 07:17 UTC, gbochora approved these changes
Looks great! Thanks @trilopin 🥳  I left a few non-blocking comments.

2022-06-08 07:26 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +    display: ${({isOpen}) => (isOpen ? 'flex' : 'hidden')};
the open state is managed in the parent component, the main idea is to avoid unmounting rhs when closing it. 

```ts
            <RightHandSidebar
                isOpen={isRHSOpen}
                section={RHSContent.RunInfo}
                onClose={() => setIsRHSOpen(false)}
            />
```

2022-06-08 07:57 UTC, merged