Mm 44715 RDP  status update - finish run
mattermost/mattermost-plugin-playbooks pull request #1244
Opened 2022-06-07 16:17 UTC by trilopin

#### Summary
This PR sums efforts in different parts of MAIN and RHS of the new RDP (Run Details Page):
- Status update UI for participant and viewer
- Status updates RHS
- Finish Run UI
- Status updates now are visible as viewers (public and private playbooks)
- LHS integration (experimental features flag needed)

Known limitations:
- finish run action not plugged yet (need https://github.com/mattermost/mattermost-plugin-playbooks/pull/1251 to be merged)
- links to subsections do not automatically scroll when visited
- manage when the viewer has no permission to view run (private playbook and not member)
- posting an update does not automatically load data yet (still needs refresh)
- check flow when looking at status updates without having load the channel (will we have user's info)

The code has still some TODOs to make a 2nd pass.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-44718
- https://mattermost.atlassian.net/browse/MM-44715
- https://mattermost.atlassian.net/browse/MM-44945

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] SOME Unit tests updated

2022-06-14 08:44 UTC, gbochora commented on server/api/playbook_runs.go
> +		return
Should we write an error? It might be useful in some cases.
`h.HandleErrorWithCode(w, http.StatusForbidden, "not authorized to get status updates", err)`

2022-06-14 10:29 UTC, trilopin commented on client/playbook_run.go
> +type StatusUpdatePost struct {
indeed, thanks for the catch

2022-06-14 10:46 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs_status_updates.tsx
> +    </Container>);
Nit: would it look better if we moved `Container` on the next line:
```suggestion
    return (
      <Container>
          {statusUpdates.map((post) => (
              <Wrapper key={post.id}>
                  <StatusUpdateCard post={post}/>
              </Wrapper>
          ))}
      </Container>
    );
```

2022-06-14 16:51 UTC, gbochora approved these changes
Great work @trilopin! Sorry it took me so long to finish the review. I left a few more comments.

2022-06-14 16:51 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
> +};
Why not to reuse `getTimestamp` function from the `rhs_post_update`?

2022-06-15 08:09 UTC, trilopin commented on webapp/src/components/time_spec.tsx
> +    {within: ['second', -45], display: <FormattedMessage defaultMessage='just now'/>},
good catch, I will parametrize it

2022-06-15 08:39 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
> +};
done, I would want to extract that utils to a common place in future PR.

2022-06-15 09:13 UTC, agarciamontoro requested changes
Impressive job, Jose, there is *a lot* of work here! :tada:

I left some comments, but mostly nits. Please, disregard them if you plan to iterate later on them, but I wanted to bring them up just in case.

2022-06-15 09:13 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +                </Scrollbars>
The last update is cut and the scrollbars are partially hidden at the bottom:
![image](https://user-images.githubusercontent.com/3924815/173786212-dd3812c6-3ee8-4538-adad-d165b0cfcacd.png)

2022-06-15 09:13 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
> +    color: ${({type}) => (type === dueType.Overdue ? '#D24B4E' : 'rgba(var(--center-channel-color-rgb), 0.72)')};
Should that color be themable? I guess it's the `var(--dnd-indicator)`. Same comment in the two usages of this hex code below.

2022-06-15 09:13 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +    const [statusUpdates, setStatusUpdates] = useState<StatusPostComplete[]>([]);
`statusUpdates` is only updated on mount and when the currentRun changes, but if you post an update from this page, it doesn't automatically show in the RHS until you reload the page. I guess this is something we can iterate on in a future PR.

2022-06-15 09:16 UTC, trilopin commented on server/app/playbook_run.go
> +	author, _ := post.GetProp("authorUsername").(string)
UserId is the playubooks bot. Unfortunately we can not use it.
My only concern is this prop is filled for all old runs. I guess that I'll include some defensive measure to avoid breaking the statusUpdate card.

2022-06-15 09:21 UTC, agarciamontoro commented on server/app/playbook_run.go
> +	author, _ := post.GetProp("authorUsername").(string)
Oooooooooh, I see, now I understand. Thanks for the context.

2022-06-15 09:23 UTC, trilopin commented on server/app/playbook_run.go
> +	AuthorUserName string `json:"author_user_name"`
it's an option that I thought about. 

This seems repetitive but I thought that it could be better to rely on the type system. 

Anyway, I don't have a very strong opinion on this, and it depends a lot on how the rest of the project usually does this kind of thing. Is it ok to receive an instance in which some fields are set to zero value? I'm not 100% against that but it seemed risky.

2022-06-15 09:28 UTC, trilopin commented on server/app/playbook_run.go
> +	author, _ := post.GetProp("authorUsername").(string)
Info about how it's filled https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/app/playbook_run_service.go#L702

2022-06-15 09:36 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
> +        </Container>
we agreed to show the entire status update without collapse/expand

2022-06-15 09:38 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +import {Role} from '../shared';
I always use absolute paths, but that may be a bit too... absolutist (sorry). Now seriously, I can see the reasoning behind having relative ones for the same directory, but in any case, it's easier for me to think where the file is when you see the whole path.

2022-06-15 09:38 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
> +        </Container>
Oh, ok, perfect then!

2022-06-15 09:40 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
> +];
will show date & time (I took same strategy than old page)
<img width="477" alt="Screenshot 2022-06-15 at 11 39 11" src="https://user-images.githubusercontent.com/4096774/173796617-2f1defc3-540d-4db2-a3a3-cf7fc94cf3f9.png">

2022-06-15 09:45 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
> +];
Oh, cool, that makes sense. Thanks!

2022-06-15 09:47 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +    const [statusUpdates, setStatusUpdates] = useState<StatusPostComplete[]>([]);
yes, I added it to the list of known limitations. I would want to merge this effort before so others can work on top of it.

2022-06-15 10:08 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
> +    }
good catch! I had a temporary icon before

2022-06-15 10:09 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
> +    const user = useSelector<GlobalState, UserProfile>((state) => getUserByUsername(state, userName));
good point, I added this to the next things to check

2022-06-15 10:30 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +    const [statusUpdates, setStatusUpdates] = useState<StatusPostComplete[]>([]);
Ugh, sorry, I had missed that in the list :facepalm:

2022-06-15 10:34 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
> +    const onFinishRun = () => null;
Good point, we can look at that after merging this pr and header pr.

2022-06-15 10:49 UTC, agarciamontoro commented on server/app/playbook_run.go
> +	AuthorUserName string `json:"author_user_name"`
We can try this, if we see it's too repetitive in the long run, we can always remove ti.

2022-06-15 11:01 UTC, merged