[WIP] [MM-37996] create the new modal UI for the playbook run dialog
mattermost/mattermost-plugin-playbooks pull request #1245
Opened 2022-06-07 22:52 UTC by salmanmanekia

### This ticket is a work in progress.

#### Summary

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-06-07 22:52 UTC, mattermod commented
Hello @salmanmanekia,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-06-18 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-06-30 14:50 UTC, calebroseland commented
Hi @salmanmanekia. I took this for a spin real quick and it's looking great so far! Let us know if you need anything, we're happy to help in any way we can. :)

2022-06-30 14:55 UTC, salmanmanekia commented
Hi Caleb, 

Thanks! I am so sorry that this has been stalled. I will continue with this on the weekend.

2022-06-30 15:10 UTC, calebroseland commented
No worries! Just thought I would touch base to say that it will get some good usage and is going to be awesome once this gets in 🚀

2022-07-10 01:34 UTC, salmanmanekia commented
https://user-images.githubusercontent.com/841955/178127901-b1e14fd5-27bc-4c40-8a07-ec5e0197b3f6.mov

Hi @calebroseland, I have made some progress with the ticket. The current implementation works for the basic case i.e. when the user tries to run a playbook either from RHS or from playbook, the modal is shown and on click of the run a channel is created and the user is redirected to it. Somethings that immediately come to my mind that needs to further looked into are

- Playbook tutorial
- Run failure   
and further testing to make sure that the the current implementation does not break.

Let me know how does it look so far and if there are somethings that might be good for me to know as I further code this feature :)

2022-07-12 11:02 UTC, stephenvanhemmen approved these changes
The behaviour shown in the demo looks fantastic. You're absolutely right, in the near future testing run start failure situations will be important and in the further future a playbooks tutorial would be beneficial. Thanks! 🚀

2022-07-21 06:47 UTC, calebroseland requested changes
💯 this is awesome! Great work on this—it's nice to see the dialog without jumping first to Channels.

1)
> Playbook tutorial

We decided these aren't a concern for now, as there are a lot of changes going on which necessitated removing them for now. When/if we decide to re-add them, it can be addressed then.

2)
> Run failure
and further testing to make sure that the the current implementation does not break.

I'd say we're fine with it as it is. We've got a lot of codepaths that don't have graceful error messages, and the testing I did on this flow was all smooth with no issues or failures. It would be great to add them later, but I'd see that more as a feature unto itself throughout Playbooks.



About the PR:

Mostly just some nits around stylistic/translation suggestions, but also 2 UX observations:

1) I realize this wasn't documented in the ticket, but the previous start run dialog would pre-fill `Channel name template` as the run name. It would be good to maintain that functionality if possible.
![CleanShot 2022-07-21 at 00 56 35@2x](https://user-images.githubusercontent.com/11724372/180142248-789b6149-a226-4bd2-9231-0488c7b36e3d.png)
![CleanShot 2022-07-21 at 01 19 25@2x](https://user-images.githubusercontent.com/11724372/180143136-ee94dbcd-c3a4-4861-856e-8df7e90c793d.png)
Maybe something like this?
```tsx
const playbook = usePlaybook(playbookId); //instead of usePlaybookName
useEffect(() => {
    if (playbook) {
        setRunName(playbook.channel_name_template);
    }
}, [playbook?.id]);
```

2) When you click Enter/Return after typing in a run name, it'd be nice to `submit` so that you don't have to mouse-click or tab-enter to start the run. 



But again, thank you for your work on this @salmanmanekia! And my apologies for taking quite a while to get back to you on this.

2022-07-21 06:47 UTC, calebroseland commented on webapp/src/components/modals/run_playbook_modal.tsx
> +	}
```suggestion
    display: flex;
    flex-direction: column;

    & > div, & > input {
        margin-bottom: 12px;
    }
```

2022-07-21 06:47 UTC, calebroseland commented on webapp/src/components/modals/run_playbook_modal.tsx
> +
```suggestion
```

2022-07-21 06:47 UTC, calebroseland commented on webapp/src/components/modals/run_playbook_modal.tsx
> +import {navigateToUrl} from '../../browser_routing';
nit: absolute paths (nothing against, just for consistency)
```suggestion
import {usePlaybookName} from 'src/hooks';
import {BaseInput} from 'src/components/assets/inputs';
import GenericModal, {InlineLabel, Description} from 'src/components/widgets/generic_modal';
import {createPlaybookRun} from 'src/client';
import {navigateToUrl} from 'src/browser_routing';
```

2022-07-23 23:50 UTC, salmanmanekia commented on webapp/src/components/modals/run_playbook_modal.tsx
> +import {navigateToUrl} from '../../browser_routing';
Thank you @calebroseland for the detailed review. I will make the requested changes and update the PR in the next few days.

2022-07-23 23:53 UTC, salmanmanekia commented
Thank you @calebroseland for the detailed review. I will make the requested changes and update the PR in the next few days.

2022-07-28 00:11 UTC, salmanmanekia commented
Hello @calebroseland, The PR is ready for review.

2022-08-03 17:55 UTC, crspeller commented
Created follow up ticket to remove old dialog: https://mattermost.atlassian.net/browse/MM-46194

2022-08-03 17:56 UTC, crspeller approved these changes
Looking good! Thanks @salmanmanekia!

2022-08-04 16:07 UTC, Phrynobatrachus requested changes
I have a few points to address, but overall great work! Thank you.

2022-08-05 08:27 UTC, trilopin submitted a review, later dismissed
Thanks @salmanmanekia, 

I left a couple of comments, the playbook name issue is the most important.

Good job. Can't wait to have this merged!

2022-08-05 08:27 UTC, trilopin commented on webapp/src/components/modals/run_playbook_modal.tsx
> +                            {runName}
```suggestion
                            {playbook.title}
```

Indeed. otherwise, the playbook name change as you change the run name

![CleanShot 2022-08-05 at 09 47 19](https://user-images.githubusercontent.com/4096774/183031520-34b9c98b-df7b-48ff-a896-9ee01a39a05e.gif)

2022-08-05 08:27 UTC, trilopin commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    teamName,
It seems that we are not currently using this prop. Is it possible to remove it?

2022-08-05 08:27 UTC, trilopin commented on webapp/src/components/modals/run_playbook_modal.tsx
> +const playbookRunDescription = 'A channel will be created with this name';
These copies seem unused, it would be great if we clean them.

2022-08-05 08:27 UTC, trilopin commented on webapp/src/components/modals/run_playbook_modal.tsx
> +        });
you could simplify this a bit this piece (must change the import to use navigateToPluginUrl):
```suggestion
        createPlaybookRun(playbookId, currentUser.id, teamId, runName, description)
            .then((newPlaybookRun) => {
                modalProps.onHide?.();
                navigateToPluginUrl(`/runs/${newPlaybookRun.id}`);
            }).catch(() => {
                // show error
            });
```

2022-08-16 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-08-16 17:56 UTC, trilopin commented on webapp/src/components/modals/run_playbook_modal.tsx
> +                        if (e.key === 'Enter' || e.key === 'Escape') {
```suggestion
                        if (e.key === 'Enter') {
```

2022-08-16 18:07 UTC, trilopin commented on webapp/src/components/modals/run_playbook_modal.tsx
> +                            {playbook.title}
```suggestion
                            {playbook?.title}
```

2022-08-16 18:13 UTC, trilopin commented
Hey @salmanmanekia, we are almost there!

I've included a suggestion to fix the playbook name and ESC key. Would you have time to look at the default owner issue that [Cass mentioned](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1245#discussion_r937977068)? 

If you can not spend time, I'd be happy to help on this last little point.

2022-08-17 09:44 UTC, salmanmanekia commented
Hey @trilopin 
Thanks for the suggestions and sorry for the delay. I would look into the default owner issue during the next few days.

2022-08-17 10:27 UTC, trilopin commented
> Thanks for the suggestions and sorry for the delay. I would look into the default owner issue during the next few days.

Nice! 

https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/webapp/src/types/playbook.ts#L39 `default_owner_id` and `default_owner_enabled` properties are relevant for this matter.

2022-08-19 23:30 UTC, salmanmanekia commented
Thanks for the pointer @trilopin. The default owner improvement is now committed and ready for review.

2022-08-22 16:37 UTC, Phrynobatrachus requested changes
You're on the right track with the default owner changes, but they don't quite work. The default owner value doesn't get plumbed through the components correctly, and it also doesn't handle the action setting. It's possible for a default owner to be configured when the toggle is off.

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    defaultUserId,
This does not destructure the value correctly, on line 31 it's passed as `defaultOwnerId`. 

```suggestion
    defaultOwnerId,
```

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    const defaultUser = useSelector<GlobalState, UserProfile>((state) => getUser(state, defaultUserId));
```suggestion
    const defaultOwner = useSelector<GlobalState, UserProfile>((state) => getUser(state, (defaultOwnerId || ''));
```

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    const playbookOwner = defaultUser ? displayUsername(defaultUser, teamnameNameDisplaySetting) : currentUserName;
```suggestion
    const playbookOwner = defaultOwner ? displayUsername(defaultOwner, teamnameNameDisplaySetting) : currentUserName;
```

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    const profileUri = Client4.getProfilePictureUrl(currentUser.id, currentUser.last_picture_update);
```suggestion
    const profileUri = defaultOwner ? Client4.getProfilePictureUrl(defaultOwner.id, defaultOwner.last_picture_update) : Client4.getProfilePictureUrl(currentUser.id, currentUser.last_picture_update)
```

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +        default_owner_id: string,
```suggestion
        default_owner_id: string,
        default_owner_enabled: boolean,
```

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +                    playbook.default_owner_id,
Need to account for the action settting bit.

```suggestion
                    playbook.default_owner_enabled ? playbook.default_owner_id : null,
```

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/modals/run_playbook_modal.tsx
> +export const makeModalDefinition = (playbookId: string, defaultOwnerId: string, description: string, teamId: string, teamName: string) => ({
```suggestion
export const makeModalDefinition = (playbookId: string, defaultOwnerId: string | null, description: string, teamId: string, teamName: string) => ({
```

2022-08-22 16:37 UTC, Phrynobatrachus commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    defaultUserId: string,
```suggestion
    defaultOwnerId: string | null,
```

2022-08-22 16:42 UTC, Phrynobatrachus commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +                    playbook.default_owner_id,
Alternatively you could pass both values through and do the check in the modal component instead of passing `null`. 0/5 though, @trilopin which way do you think is cleaner?

2022-08-23 16:39 UTC, salmanmanekia commented
Thanks for the comment @Phrynobatrachus. I will make the required changes soon.

2022-08-23 19:35 UTC, salmanmanekia commented
@Phrynobatrachus can you please review my recent changes. Thanks already!

2022-08-24 20:25 UTC, Phrynobatrachus approved these changes
I pushed one extra commit so we can get this merged. The lint job in CI caught that particular spot for me, it's definitely worth checking when you have a PR open. Greatly appreciate your patience in sticking with us though, this work should go out in the next minor version release. Thanks again!

2022-08-24 20:54 UTC, merged

2022-08-25 14:03 UTC, salmanmanekia commented
Thank you @Phrynobatrachus. It was pleasure interacting with the team and learning about mattermost app and playbook plugin.

2022-08-25 16:09 UTC, calebroseland commented
🚀