Mm 44717 add retrospective
mattermost/mattermost-plugin-playbooks pull request #1248
Opened 2022-06-13 04:32 UTC by gbochora

#### Summary
This PR adds the `Retrospective` section with existing UI to the run details main form. 
Mainly I've copied the `Retrospective` section code from the `backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx` and made a few modification to fit it in the new run details form:
- Add `Copy link` to the title
- Fix `Upgrade` banner UI
- Remove timeline section
- Refactor `PlaybookRun` update functionality. Use `setPlaybookRun` instead of several small functions to update the run object.

https://user-images.githubusercontent.com/4368372/173279394-0173ea58-de5a-44fe-bfc5-d020cac20d6f.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44717

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-06-13 08:39 UTC, trilopin requested changes
Nice!

My only important point is if fetchPlaybook is really needed, I would do the useeffect-fetch in the parent component to avoid several sub-components doing their own fetch (potentially they fetching the same resource).

several optional comments

2022-06-13 08:39 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +                {...ELAPSED_TIME}
I also did this, at some point we will need to converge.

https://github.com/mattermost/mattermost-plugin-playbooks/pull/1244/files#diff-0fba6ad2fcf358ae67462cb7347844a32561a72755d6d0b5c00c5f1a6c9e4b27R2

2022-06-13 08:39 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +const editDebounceDelayMilliseconds = 2000;
optional: constant style

```suggestion
const DEBOUNCE_2_SECS = 2000;
```

2022-06-13 08:39 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +    const publishButtonText: React.ReactNode = formatMessage({defaultMessage: 'Publish'});
isn't the type implicit?

```suggestion
    const publishButtonText = formatMessage({defaultMessage: 'Publish'});
```

2022-06-13 08:39 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +    let publishComponent = (
optional: I'd separate publishComponent to a local function renderPublishComponent with both cases

2022-06-15 06:43 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +                setPlaybook(fetchedPlaybook ?? null);
We need the playbook to get metrics configuration info: metric name, target value, metric type, and order of metrics. This info is used to build the retrospective form.

2022-06-16 05:32 UTC, gbochora commented
@trilopin I've added viewer mode for the retrospective. `Viewer` user will not be able to edit or publish retrospective.

2022-06-16 05:58 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/shared.tsx
> +    useTime: false,
Since this is not specific code to playbook_runs and already was extracted to time_spec. would make sense to use from there? Your comment regarding useTime was already fixed for the old retrospective.

2022-06-16 06:21 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/shared.tsx
> +    useTime: false,
Yep, that's correct, I missed this part during the merge.

2022-06-16 06:37 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +    const confirmedPublish = () => {
optional, more consistent naming

```suggestion
    const onConfirmPublish = () => {
```

2022-06-16 06:39 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +        const publishButtonText = formatMessage({defaultMessage: 'Publish'});
if only is used once, would make sense that we simply put the formatmessage inside Publishbutton?

2022-06-16 06:51 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +    const persistMetricEditEvent = (metrics_data: RunMetricData[]) => {
100% optional and personal preference

I would love to have different naming here, EditEvent suffix does not say the important message to me. Examples like: saveMetrics storeMetrics persistMetics or onMetricsChange sound better to me. 

Additionally I'd create only one var already wrapped in debounce like 

```ts
const onMetricsChange = debounce((metrics_data: RunMetricData[]) => {
    onChange({...playbookRun, metrics_data});
    updateRetrospective(playbookRun.id, playbookRun.retrospective, metrics_data);
}, DEBOUNCE_2_SECS);
```

2022-06-16 06:56 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +                    {formatMessage({defaultMessage: 'Retrospectives were disabled for this playbook run.'})}
Shouldn't we hide the entire block in this case? https://community.mattermost.com/core/pl/tmd11zyxbjdpxn4r11umpp3nwh

2022-06-16 07:31 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
> +                    {formatMessage({defaultMessage: 'Retrospectives were disabled for this playbook run.'})}
Nice catch! I forgot to remove this part, thanks.

2022-06-16 10:35 UTC, trilopin approved these changes
Thank you @gbochora !

2022-06-17 05:08 UTC, calebroseland approved these changes
I did run into a few issues, but I'm not sure if they would fit in this PR or if they're existing issues. Other than these, LGTM!


1) Metrics added after a retro is published show with a disabled Add Value prompt:
<img width="775" alt="CleanShot 2022-06-16 at 23 56 37@2x" src="https://user-images.githubusercontent.com/11724372/174228480-f9c042d2-dec1-4382-b9a4-3a7abbb364a4.png">

2) When you load a run with a retro, then navigate to another that doesn't have a run, and then you come back to the first, it doesn't show the metric values:
![CleanShot 2022-06-16 at 23 52 25](https://user-images.githubusercontent.com/11724372/174228593-e0648af0-4c98-4061-a37a-d1610086694e.gif)

3) When the Retrospective section UI isn't present, the content goes oddly narrow
<img width="670" alt="CleanShot 2022-06-17 at 00 05 30@2x" src="https://user-images.githubusercontent.com/11724372/174228961-37daaf4d-ea1d-4c16-b3c5-8cd7f0f8cabd.png">
(also shown in prior gif)

2022-06-17 07:22 UTC, trilopin commented
Point 2 is solved in another pr https://github.com/mattermost/mattermost-plugin-playbooks/pull/1256/files#diff-213f2b939a33ffd023fed43b598a2ea37dd385f32971886649f38b8ea67344f2R192

point 3 appeared after LHS integration, some changes must be done at state management.

2022-06-17 08:14 UTC, merged