Mm 44713 add header
mattermost/mattermost-plugin-playbooks pull request #1251
Opened 2022-06-13 16:34 UTC by gbochora

#### Summary
This PR adds header to the new `Run details` form. 
**Header Actions:**
- `Run Actions`
- `Copy link` 
- `Go to channel`
- `View Timeline` - not implemented
- `View info` - not implemented

**Header context menu:**
- `Copy link` 
- `Run Actions`
- `Export channel logs`
- `Finish run`

https://user-images.githubusercontent.com/4368372/173400676-a02cf41e-0e95-4ecf-a0f7-d0b85ea1d7a4.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44713

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-06-13 16:56 UTC, trilopin commented on webapp/src/client.ts
> +        return await doPut(`${apiUrl}/runs/${playbookRunId}/finish`);
oh nice, this will be re-used in my finish-run task 🎉

2022-06-14 09:00 UTC, agarciamontoro requested changes
Really cool! I love seeing how the Run Details Page keeps improving <3

I left some comments below, but mostly nits.

2022-06-14 09:02 UTC, trilopin approved these changes
Thanks @gbochora 

I left some nits that could be fixed here or in next PRs.

2022-06-15 04:51 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +                className={'󰋽 icon-information-outline'}
Nice catch! I've copied the name from the `compass-icons` font demo page and probably also copied the icon.

2022-06-15 05:12 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
> +                    }}
We don't need it, removed.

2022-06-15 06:13 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
> +    margin-top: 50px;
You are right. I changed it to 24px, the distance between the header and progress bar.

2022-06-15 06:19 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +            />
Aha, they are mostly the same, but I think the unified component might be a little complex because both of them have specific features:
- `Header` component has clicked state
- `Copy link` component has url copy functionality

2022-06-15 06:21 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +    line-height: 18px;
Nope, removed.

2022-06-15 12:03 UTC, trilopin commented
To place correctly the header you should add `flex-direction: column;` to MainWrapper and move Header outside Main (but inside MainWrapper). From that only some fine-tune will be needed

2022-06-15 16:41 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
> +    const exportAvailable = useSelector<GlobalState, boolean>((state) => Boolean(state.plugins?.plugins?.['com.mattermost.plugin-channel-export']));
Do you mean just wrap it like this:
```
export const useExportLogAvailable = () => {
    //@ts-ignore plugins state is a thing
    return useSelector<GlobalState, boolean>((state) => Boolean(state.plugins?.plugins?.['com.mattermost.plugin-channel-export']));
};
```

2022-06-16 11:57 UTC, agarciamontoro approved these changes
Cool :tada: Thank you, Giorgi!

2022-06-16 11:57 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
> +        }
Super nit: move the parenthesis and the colon to a new line
```suggestion
            confirmationMessage = formatMessage(
                {defaultMessage: 'There {outstanding, plural, =1 {is # outstanding task} other {are # outstanding tasks}}. Are you sure you want to finish the run?'},
                {outstanding}
            );
        }
```

2022-06-16 11:57 UTC, agarciamontoro commented on webapp/src/hooks/general.ts
> +};
New line?
```suggestion
};

```

2022-06-16 13:08 UTC, merged