MM-44962: Playbooks List and Playbook Editor UI changes to match new LHS experience
mattermost/mattermost-plugin-playbooks pull request #1252
Opened 2022-06-14 05:05 UTC by calebroseland

#### Summary
Changes overall layout to match new designs but without additional functionality; new UX/functionality will come in subsequent PRs.

- Update Playbooks List design
  - Make full-width (constrained to `max-width: 1120px` on old page; unconstrained on LHS-enabled screen)
  - Minor page hierarchy changes
- Update Playbook Editor design
  - Make full-width 
- (https://github.com/mattermost/mattermost-plugin-playbooks/commit/a1c1496f46b81a778af9f6239cc0661bc5ed5d7a) Fix: Global Header menus disappearing on Playbooks List page in Safari
(I couldn't repro this one locally, but could repro on community—the fix applied in devtools fixes it)

New list screen
<img width="700" alt="CleanShot 2022-06-13 at 23 29 31@2x" src="https://user-images.githubusercontent.com/11724372/173493563-58f0964a-0372-4d3b-9a46-5be46d503ea5.png">

Current list screen (`width` constrained if `experimental == false`, all other changes ungated)
<img width="1125" alt="CleanShot 2022-06-13 at 23 48 58@2x" src="https://user-images.githubusercontent.com/11724372/173495511-39ed40f8-af5f-4df4-9ce9-09f221f3e67a.png">

Global Header menus disappearing in Safari (community.mattermost.com)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11724372/173493845-b02d50d8-d5b9-4959-a5c3-021c7adf4560.gif">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11724372/173493856-dff90404-e51d-49be-af02-7b0e1dcd6ea8.gif">

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-44962

#### Checklist

Item | Y / N / NA [^1]
---|---
Telemetry updated? | N
Gated by experimental feature flag? | Y&N)
Unit/E2E tests updated? | N

[^1]: Yes / No / Not Applicable.

2022-06-14 12:37 UTC, lieut-data approved these changes
So awesome to see the cleanup alongside these incremental changes!

2022-06-14 12:37 UTC, lieut-data commented on webapp/src/components/backstage/playbook_list.tsx
> -import LeftDots from 'src/components/assets/left_dots';
❤️

2022-06-14 12:37 UTC, lieut-data commented on webapp/src/components/backstage/playbook_list.tsx
> +    overflow: clip;
nit: Two `overflow` directives?

2022-06-14 21:21 UTC, abhijit-singh requested changes
This is great @calebroseland! A couple of minor things, (not necessary to be done in this PR though):
1. I think it'll make sense to also make the templates list span the full width. Open to feedback though. Something like this - 
<img width="2016" alt="image" src="https://user-images.githubusercontent.com/14369607/173690437-5ef5a0e1-512e-4ca3-aff8-c265b3499647.png">
I removed the max-width and it did the trick. Note that I also reduced the space between the cards to 4rem and it feels better. Also, all cards in a row should ideally be of the same height, even if that'll mean some extra white space in some of them. I added a min-height property to achieve that but not sure if it's the right way.
2. It seems the previous and next buttons are moving horizontally based on the width of the screen. Ideally, they should stay at a fixed distance(~16px) from the left and right edges respectively.

2022-06-15 14:44 UTC, iomodo approved these changes
Looks great Caleb! Thanks ^_^

2022-06-15 22:00 UTC, calebroseland commented
@abhijit-singh I updated for 1 & 2, but the consistent height will have to be a part of a later PR. There are some complexities to that to keep the upper color block to be of the same size while still being responsive.

<img width="1287" alt="CleanShot 2022-06-15 at 16 56 03@2x" src="https://user-images.githubusercontent.com/11724372/173939207-59e816bb-989b-4d6c-a061-17b4cfccd4ef.png">

2022-06-15 22:08 UTC, calebroseland commented
@abhijit-singh, done!

<img width="1321" alt="CleanShot 2022-06-15 at 17 07 23@2x" src="https://user-images.githubusercontent.com/11724372/173940582-278ac301-186c-482c-8764-6329ac40ed57.png">

2022-06-15 22:09 UTC, abhijit-singh commented
Perfect 💯

2022-06-15 22:14 UTC, merged