Add create playbook dropdown
mattermost/mattermost-plugin-playbooks pull request #1257
Opened 2022-06-16 14:41 UTC by iomodo

#### Summary
This PR adds create playbook dropdown to the LHS. 
`Invite people` is out of scope
`Start a run` is not implemented, cause when we create runs we use the interactive dialogue and it will not work without the channel. Either we have to implement our own dialogue or fix the current implementation of the interactive dialogue. 

https://user-images.githubusercontent.com/2340127/174095357-41c3b6c3-784e-4914-8303-9d09b11c1d66.mp4

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-06-17 09:04 UTC, agarciamontoro approved these changes
Neat! :tada: I left some comments below, but none of them blocking.

2022-06-17 09:04 UTC, agarciamontoro commented on webapp/src/components/sidebar/create_playbook_dropdown.tsx
> +                        }
Optional chaining again?
```suggestion
                    onClick={fileInputRef?.current?.click}
```

2022-06-17 09:04 UTC, agarciamontoro commented on webapp/src/components/sidebar/create_playbook_dropdown.tsx
> +                            size={1.25}
Something I learned a couple of weeks ago: It turns out you can pass a string here as `12px`, which is way more  meaningful than this. Could we try it here and in the following mdi icons?

2022-06-17 09:04 UTC, agarciamontoro commented on webapp/src/components/sidebar/create_playbook_dropdown.tsx
> +        background: rgba(255, 255, 255, 0.08);
Should this be themed?

2022-06-17 21:42 UTC, calebroseland requested changes
Just one UI issue (icon alignment):
![CleanShot 2022-06-17 at 16 23 20@2x](https://user-images.githubusercontent.com/11724372/174404465-a800a0d1-8d21-4949-a814-127408b485ab.png)

Otherwise looks great and will be nice to have this in!

2022-06-17 21:42 UTC, calebroseland commented on webapp/src/components/sidebar/create_playbook_dropdown.tsx
> +    const teams = useSelector<GlobalState, Team[]>(getMyTeams);
+1, fewer type imports needed

2022-06-17 21:42 UTC, calebroseland commented on webapp/src/components/sidebar/create_playbook_dropdown.tsx
> +        );
Shouldn't be behind a permissions gate of some sort? The one in `playbook_list` is behind `useCanCreatePlaybooksOnAnyTeam`.  This/that may require refactoring once we rescope to single-team, but I think we should at least match for now.

2022-06-28 22:02 UTC, calebroseland approved these changes

2022-06-28 22:03 UTC, merged