Mm 45108 viewer mode
mattermost/mattermost-plugin-playbooks pull request #1259
Opened 2022-06-17 07:01 UTC by gbochora

#### Summary
This PR adds the `Viewer` mode to the `Header` and `Checklist`. Retrospective `Viewer` mode implemented in this PR: https://github.com/mattermost/mattermost-plugin-playbooks/pull/1248#pullrequestreview-1009998180
Header in `Viewer` mode:
- no `Finish run` menu item.
- no `Go to channel` button. We will need to add `Get Involved` button instead in v2

Checklist in `Viewer` mode is the same as for the finished run.
- no add checklist item
- no add checklist
- no hover menu
- no checklist drag

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45108

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-06-17 08:52 UTC, agarciamontoro approved these changes
Looks good! I'm loving these short, iterative PRs :)

2022-06-17 08:52 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
>  interface Props {
This is a personal preference, but I'd rather have absolute pahts in the imports. Also, new line missing:
```suggestion
import {Role} from '../shared';

interface Props {
```

2022-06-17 11:40 UTC, trilopin commented on webapp/src/components/backstage/playbook_editor/outline/outline.tsx
> +                    viewerMode={false}
1/5 on this comment

Where we are aware of the role, it seems ok to use viewer vs participant and names like isViewer or viewerMode.

Once we are deeper in the component tree and we don't have necessarily the context of what's viewer and participant, I would use names like isReadOnly or isChangeAllowed. it's decoupled of the origin of that decision and explains more about what is going to happen.

2022-06-17 11:41 UTC, trilopin reviewed
Nice job @gbochora 

I noticed that the collapse checklist icon doesn't work when you are a viewer. is that intended?

2022-06-17 15:04 UTC, gbochora commented on webapp/src/components/backstage/playbook_editor/outline/outline.tsx
> +                    viewerMode={false}
Good point, I also had doubts regarding this.

2022-06-17 15:48 UTC, gbochora commented
> I noticed that the collapse checklist icon doesn't work when you are a viewer. is that intended?

@trilopin  No, it's not intended. I tried and can't reproduce it. Do you make some steps before, or it happens every time?

2022-06-27 08:38 UTC, trilopin commented
Big move here @gbochora! 

> * `RD` stores checklist info in the same redux state under the `key=run_details_[runId]`. So the same run will not share `RHS` and `RD` states.

I understand that collapsed state is designed to behave separately between RDP and Channels RHS, but I feel them as connected. Video attached.


https://user-images.githubusercontent.com/4096774/175897039-a2548784-9748-40bf-a4af-52ab2a4d8f29.mp4

2022-06-27 09:34 UTC, agarciamontoro requested changes
Code looks good to me! There's only a naming suggestion.

Also, a more general question: why does the Better Playbook Editor now store the state locally instead of using yet another key for the store? Does that play well with different users viewing the playbook at the same time and one of them checking and unchecking tasks?

2022-06-27 09:34 UTC, agarciamontoro commented on webapp/src/components/checklist/checklist_list.tsx
> +    onEachChecklistCollapsedStateChange: (state: Record<number, boolean>) => void;
This function is called when the collapsed state of every checklist is changed at once, right? If that's correct, I proposeto use `onEveryChecklist` or `onAllChecklsits` instead of `Each`. At least for me the `Each` word threw me off.
```suggestion
    onEveryChecklistCollapsedStateChange: (state: Record<number, boolean>) => void;
```

2022-06-27 10:16 UTC, gbochora commented on webapp/src/components/checklist/checklist_list.tsx
> +    onEachChecklistCollapsedStateChange: (state: Record<number, boolean>) => void;
> Also, a more general question: why does the Better Playbook Editor now store the state locally instead of using yet another key for the store? Does that play well with different users viewing the playbook at the same time and one of them checking and unchecking tasks?

@agarciamontoro  `BPE` never supported caching checklist state in the redux, so I used the local store. If storing the state in the redux makes sense, I can add it, it's just a few lines of code. I don't have a strong opinion regarding this. For `RHS` and `RD`, it's more clear for me because users switch between runs very often and it's important to save the state.

2022-06-27 11:09 UTC, agarciamontoro commented on webapp/src/components/checklist/checklist_list.tsx
> +    onEachChecklistCollapsedStateChange: (state: Record<number, boolean>) => void;
@gbochora Oh, wait, I completely mixed up two things: whether the checklist is collapsed or not and the actual state of the tasks (which is not modified in the playbook editor, sorry :facepalm:). If they didn't add that to redux then let's skip it for now. Thanks for the explanation and sorry for the misunderstanding!

2022-06-27 13:11 UTC, trilopin approved these changes
What a refactor :)

I left some small and optional comments.

2022-06-27 13:11 UTC, trilopin commented on webapp/src/components/backstage/playbook_editor/outline/outline.tsx
> +    const [checklistCollapseState, setChecklistCollapseState] = useState({} as Record<number, boolean>);
nit: use generic instead of type cast
```suggestion
    const [checklistCollapseState, setChecklistCollapseState] = useState<Record<number, boolean>>({});
```

2022-06-27 13:11 UTC, trilopin commented on webapp/src/components/checklist/checklist_list.tsx
> +            if (playbookRun) {
nice move

2022-06-27 13:11 UTC, trilopin commented on webapp/src/components/checklist/generic_checklist.tsx
> +                    {!props.disabled &&
personal preference: use ternary operator over logical and

https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx
not always applies, but it's commonly safer

2022-06-28 08:50 UTC, agarciamontoro approved these changes
:tada:

2022-06-28 08:53 UTC, merged