better state management
mattermost/mattermost-plugin-playbooks pull request #1263
Opened 2022-06-20 12:19 UTC by trilopin

#### Summary
Prevent user from carrying rhs state between different runs.

We were doing a mix of redux check + fetch (useRun which relies on useThing) and parallel promise for extended data. I refactored a bit the code and replaced useRun with a plain selector (to avoid double fetch).

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-45200

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-06-21 11:19 UTC, agarciamontoro requested changes
I'm not sure I understand this change. Wouldn't it be better to still rely on `useRun` and remove the explicit `fetchPlaybookRun` from the parallel `useEffect`?

2022-06-21 11:19 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +    const runFromStore = useSelector<GlobalState, PlaybookRun|undefined|null>(getRun(playbookRunId));
Do we need all the explicit typing here?
```suggestion
    const runFromStore = useSelector(getRun(playbookRunId));
```

2022-06-21 11:19 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +        }
In Channels, switching channels does not close the RHS, should we follow that same pattern here?

2022-06-21 11:45 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +        }
https://community.mattermost.com/core/pl/o693b8n4sj8qxb8he8s4wbtc1h

2022-06-21 13:12 UTC, trilopin commented
> I'm not sure I understand this change. Wouldn't it be better to still rely on `useRun` and remove the explicit `fetchPlaybookRun` from the parallel `useEffect`?

My biggest concern (and it affected negatively) was to have two sources of truth regarding playbookRun (useRun and fetchPlaybookRun). It could be solved by removing fetchPlaybookRun from the parallel promise or by removing useRun. I chose to keep the promise with all fetch but I could recover the useRun if you see more value and clarity.

2022-06-21 13:27 UTC, agarciamontoro commented
I completely agree with the concern, having both is quite error-prone.

Having to choose, I like `useRun` better simply because it encapsulates all the fetch/store logic in a single generic (`useThing`) hook. I feel like that hook is very well tested throughout the codebase because we use it in many places, and that it's easier to miss bugs when repeating that same logic in the individual components. I also find it easier to read, but that's probably secondary (it's easier once you know how the `useThing` hook works, but it's probably a bit more obscure for newcomers).

2022-06-21 14:49 UTC, trilopin commented
Additionally, I added the RHS behavior that @abhijit-singh explained:

- run-info is opened by default
- change run does not close rhs
- if we navigate to a run with rhs-status-udpates open but there aren't (disabled or not posted yet), rhs-run-info will be shown otherwise

2022-06-21 16:24 UTC, agarciamontoro approved these changes
Looks good! Just a minor question: why do we need `useUpdateEffect` and not the regular `useEffect`?

2022-06-22 05:05 UTC, trilopin commented on webapp/src/hooks/general.ts
> +            fetch(id).then(setThing).catch(() => setThing(null));
two tiny changes here that are not minor, state hidden in return value: undefined == loading; null == not found

Ihis pattern is used in other hooks and thought that it was better than returning fetchingState in another value. However, checking everything is not easy and could bring some problems.

@agarciamontoro @gbochora

2022-06-22 06:32 UTC, gbochora reviewed
Nice work @trilopin! Code looks much cleaner now. I've tested retrospective, and everything seems to work perfectly. 
Few issues I've noticed:
- `RHS` doesn't show the title. I think this happened after merging with the master.
- 'RHS' doesn't show the run title.
- Header icons are missing

2022-06-22 06:42 UTC, trilopin commented
> Nice work @trilopin! Code looks much cleaner now. I've tested retrospective, and everything seems to work perfectly. 
> Few issues I've noticed:
> - `RHS` doesn't show the title. I think this happened after merging with the master.
> - 'RHS' doesn't show the run title.
> - Header icons are missing
> 

Oh that must be the last master merge. Let me check those points.

2022-06-22 07:49 UTC, agarciamontoro commented on webapp/src/hooks/general.ts
> +            fetch(id).then(setThing).catch(() => setThing(null));
What if we have a global `FetchingState` type that we can rely everywhere? It's something common to all fetches, so it may be useful.

2022-06-22 07:57 UTC, trilopin commented on webapp/src/hooks/general.ts
> +            fetch(id).then(setThing).catch(() => setThing(null));
I would love to have a simple API with the data and the state of the fetch with idle/pending/done/error and maybe error code.

But to do that we need to:
- make another different useThing for useRun and test extensively all useRun
- change useThing directly and test extensively all hooks that use useThing

Both points are a bit out of this scope. I would want to do it outside this PR.

2022-06-22 11:35 UTC, agarciamontoro requested changes
Love the `useFetch` proposal, thank you! :tada: I left mostly nits, the only blocking comment is the one about fetch.

2022-06-22 11:35 UTC, agarciamontoro commented on webapp/src/hooks/general.ts
> +    useEffect(() => {
Super nit: new line before useEffect:

```suggestion
    const [data, setData] = useState<T | null>(null);

    useEffect(() => {
```

2022-06-22 11:35 UTC, agarciamontoro commented on webapp/src/hooks/general.ts
> +    fetch: (id: string) => Promise<T>,
Could we rename this so we don't shadow the global `fetch` function? The suggested name is just a proposal, any other thing is good for me:
```suggestion
    fetchFunction: (id: string) => Promise<T>,
```

2022-06-22 11:35 UTC, agarciamontoro commented on webapp/src/hooks/general.ts
> +                setData(null);
Really cool :pray:

2022-06-22 12:08 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +    const [metadata, metadataRes] = useRunMetadata(playbookRunId);
😂

2022-06-22 12:11 UTC, trilopin commented on webapp/src/hooks/general.ts
> +    fetch: (id: string) => Promise<T>,
good catch

2022-06-22 12:46 UTC, agarciamontoro approved these changes
:tada:

2022-06-22 12:57 UTC, merged