Add endpoints for categories
mattermost/mattermost-plugin-playbooks pull request #1266
Opened 2022-06-21 14:19 UTC by iomodo

#### Summary
This PR adds endpoint for categories
It also performs a migration and adds `Favorite` category for every user in every team.

No UI changes

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-07-05 16:29 UTC, calebroseland commented
/update-branch

2022-07-05 16:49 UTC, crspeller requested changes

2022-07-05 16:49 UTC, crspeller commented on server/api/categories.go
> +	if category.TeamID != teamID {
Why not just use the category team ID?

2022-07-05 16:49 UTC, crspeller commented on server/app/category_service.go
> +	if existingCategory.UserID != userID {
The permissions validations here seem to be spread over api and app layer. Can we move them all to one or the other? Generally the API layer does permissions.

2022-07-05 18:39 UTC, crspeller approved these changes

2022-07-05 20:34 UTC, calebroseland approved these changes
LGTM, just one question/concern about newly-created users after the migration.

2022-07-05 20:34 UTC, calebroseland commented on server/sqlstore/migrations.go
> +			// Create `Favorite` category for every user in every team
What about users that are created after this migration? How will they get a static `'Favorite'` category?

2022-07-06 08:36 UTC, iomodo commented on server/sqlstore/migrations.go
> +			// Create `Favorite` category for every user in every team
@calebroseland good catch!
I removed the migration entirely, since we anyway have to check/create for new users.
We will create `Favorite` category when user first favorites an item.

Alternative approach would be creating category in `UserHasBeenCreated` hook, but it will increase complexity.

2022-07-06 09:24 UTC, merged