Mm 45156 rdp cypress e2e
mattermost/mattermost-plugin-playbooks pull request #1267
Opened 2022-06-22 11:59 UTC by trilopin

#### Summary
E2E tests for run details page

#### Ticket Link
Related https://mattermost.atlassian.net/browse/MM-45156

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-06-29 08:46 UTC, gbochora approved these changes
Great job @trilopin! 🥳  I left some questions and optional suggestions.

2022-06-29 08:46 UTC, gbochora commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                        // should be disabled
Do you mean that header `Run Actions` button should be disabled/hidden?

2022-06-29 08:46 UTC, gbochora commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                it('can be confirmed', () => {
Do we plan here to check if the `Finish run` item is missing?

2022-06-29 08:46 UTC, gbochora commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    // do sth
I think(2/5) `Viewer` should be able to open the `Run actions` modal to view configured actions.

2022-06-29 08:46 UTC, gbochora commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +    describe.skip('viewer', () => {
Some of the tests are the same for viewers and participants. Would it be better to reuse code?

2022-06-29 08:46 UTC, gbochora commented on webapp/src/selectors.ts
> +// @deprecated: now we should check playbookRun.participants ang ignore channel members
type:
```suggestion
// @deprecated: now we should check playbookRun.participants and ignore channel members
```

2022-06-29 09:05 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    // do sth
Not sure about it, as a viewer you are interested more in "what's the progress of the run" than in "How is internally configured?". Could we end up informing about broadcasts on lots of channels we don't have access to (more likely in a viewer than a participant)?

But also 2/5 on that thought.

2022-06-30 16:19 UTC, agarciamontoro approved these changes
This is great! Thank you for all the work here, Jose :)

2022-06-30 16:19 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +    describe('participant', () => {
Nit: I think it's easier to read
```suggestion
    describe('as participant', () => {
```

2022-06-30 16:19 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
> +    describe('participant', () => {
Same nit:
```suggestion
    describe('as participant', () => {
```

2022-06-30 16:19 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
> +    describe('viewer', () => {
Same nit:
```suggestion
    describe('as viewer', () => {
```

2022-06-30 16:19 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +    describe.skip('viewer', () => {
+1

2022-06-30 16:19 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                        // should be disabled
This was meant to simply check whether the modal shows / hides when clicking on the button / closing it.

2022-06-30 16:19 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    // do sth
Channel actions can be viewed by channel members that are not channel admins. I think this should be the same: viewers should be able to see what's configured, but not change it.

2022-06-30 16:19 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
> +    it.skip('redirects to not found error if the playbook run is unknown', () => {
Should we create tickets for these? Or at least mark them with TODOs? I don't know what changes this refer to, either.

2022-06-30 19:53 UTC, trilopin commented on tests-e2e/cypress/integration/runs/actions_spec.js
> +
I created https://mattermost.atlassian.net/browse/MM-45451 for the cleanup, maybe we should make a list of what to clean inside

2022-06-30 19:58 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
> +    it.skip('redirects to not found error if the playbook run is unknown', () => {
is already done, now it's merged I have to revisit all skipped tests

2022-07-05 17:14 UTC, agarciamontoro requested changes
This is great, Jose, thank you very much for all this work. I left some comments, but I think once we solve these, we'll be able to merge.

2022-07-05 17:14 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
> +    });
This test threw me off. It does not belong here, right?

2022-07-05 17:14 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
> +        cy.findByTestId('run-summary-section').should('not.contain', 'Last edited');
Typos
```suggestion
            // * Assert that data has not changed
            cy.findByTestId('rendered-text').contains('Add a run summary');
        });

        // * Assert last edition date is not visible
        cy.findByTestId('run-summary-section').should('not.contain', 'Last edited');
```

2022-07-05 17:14 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +            });
This `stubClipboard` thing is cool!

2022-07-05 17:14 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +            commonHeaderTests();
Very nice modularization!

2022-07-05 17:14 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    getDropdownItemByText('Finish run').should('not.exist');
Nit: I think everywhere we use `getDropdownItemByText`, it is preceded by first opening the dropdown. What if we add the `cy.findByTestId('run-header-section').find('h1').click();` to `getDropdownItemByText` directly?

2022-07-05 17:14 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    cy.findByTestId('run-header-section').findByTestId('badge').contains('In Progress');
Same comment here about swapping these two steps
```suggestion
                    // * Check that status badge is in-progress
                    cy.findByTestId('run-header-section').findByTestId('badge').contains('In Progress');

                    // # Click on finish run
                    getDropdownItemByText('Finish run').click();
```

2022-07-05 17:14 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                        getDropdownItemByText('Run actions').click();
Typo
```suggestion
                        // # Click on run actions
                        getDropdownItemByText('Run actions').click();
```

2022-07-05 17:18 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
> +                    ) : null}
you need it if you want to use a ternary which I usually prefer to &&

2022-07-05 17:23 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
> +    });
you're right, I created a new generic file with only that test

2022-07-06 07:06 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                            openRunActionsModal();
you are right, I make link from title to use the experimental features toggle to navigate to the right url

2022-07-06 07:35 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
> +                    ) : null}
Ugh, yes, I meant `&&`. I'm ok with the ternary, but I'm just curious: why do you prefer it over `&&`?

2022-07-06 07:37 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    it.only('honours the settings from the playbook', () => {
Just one more only! :joy:

2022-07-06 07:52 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    it.only('honours the settings from the playbook', () => {
omg... sorry

2022-07-06 08:54 UTC, merged