Mm 44766 participants
mattermost/mattermost-plugin-playbooks pull request #1276
Opened 2022-06-29 07:31 UTC by gbochora

#### Summary
This PR adds `RHS > Participants` view:
- Participants list
- `RHS` back navigation
- `Send message` button on hover 

NOTE: Search is not implemented yet. We decided to do it in v2.

https://user-images.githubusercontent.com/4368372/176377807-fddbdfe7-9cb6-442b-97eb-87493094bbe5.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44766

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-06-29 07:50 UTC, trilopin requested changes
Thank you @gbochora 

I left some details and doubts

2022-06-29 07:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +                onClick={() => onViewTimeline()}
```suggestion
                onClick={onViewTimeline}
```

2022-06-29 07:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +                onClick={() => onViewInfo()}
```suggestion
                onClick={onViewInfo}
```

2022-06-29 07:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
> +                    onBack ? <BackIcon>
this is a personal preference, but you could use a better indentation when doing ternary operator.

Example.

```ts 
            {props.parent === 'retro' ? (
                <TimeContainer parent={props.parent}>
                    {timeSincePrevEvent}
                </TimeContainer>
            ) : null}
```

2022-06-29 12:08 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/send_message_button.tsx
> +            dispatch(fetchUser(props.userId));
Good point. I moved fetching inside the `onClick` function.

2022-06-29 14:08 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/send_message_button.tsx
> +        actionFunc.then((data) => {
I tested this and works fine. But as far as I know, waiting for a dispatched action does not guarantee that the reducer has been executed. 

what happens if you navigate without doing the fetch first?

2022-06-29 14:12 UTC, trilopin reviewed
I left a comment about promises and actions. Additionally, I'm wondering if we should avoid navigating to our own user.

2022-06-29 15:45 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/send_message_button.tsx
> +        actionFunc.then((data) => {
not the selector but the action.

I think with redux, the fact that the promise of the action has been solved doesn't mean that the reducer has been executed. 

I'm still not sure if we expected that or if we simply do a best-effort strategy (that would be enough most of the cases).

2022-06-29 18:10 UTC, agarciamontoro requested changes
Impressive work! The only blocking comment is the one about the plural, because if there's one participant, it still reads "1 participants". All the other comments are nits. Thanks! :tada:

2022-06-30 08:08 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
> +                    {formatMessage({defaultMessage: '{num} Participants'}, {num: participantsIds.length})}
Nice catch!

2022-06-30 10:56 UTC, trilopin approved these changes
🎉

2022-07-02 07:45 UTC, merged