MM-45446: Auto scroll infrastructure
mattermost/mattermost-plugin-playbooks pull request #1281
Opened 2022-06-30 18:14 UTC by agarciamontoro

#### Summary
This simply sets up the infrastructure needed to automatically scroll to every element in the main section of the page when using an anchor link. Try, for example, to visit `/playbooks/run_details/<run_id>#playbook-run-retrospective` to see it.

I'll add the actual navigation links in other PR.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45446

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-06-30 22:05 UTC, trilopin requested changes
I try to navigate to a URL with retrospective hashtag but it doesn't seem to automatically scroll. Am I doing sth wrong?

2022-06-30 22:05 UTC, trilopin commented on webapp/src/components/backstage/backstage.tsx
> +        scroll-padding-top: 64px;
TIL

2022-07-01 08:13 UTC, agarciamontoro commented on webapp/src/components/backstage/backstage.tsx
> +    const isRunDetailsPage = pathname.startsWith('/playbooks/run_details');
Oh, that's a good solution, thanks!

2022-07-01 08:17 UTC, agarciamontoro commented on webapp/src/components/backstage/backstage.tsx
> +        scroll-padding-top: 64px;
Same :joy:

2022-07-01 10:07 UTC, agarciamontoro commented on webapp/src/components/backstage/backstage.tsx
> +    const isRunDetailsPage = pathname.startsWith('/playbooks/run_details');
Now that I think of it, I'm not sure I understand the benefit: we'll still need to remove the `useExperimentalFeatures` when we move this to production, right? Because we'll want the `/playbooks/runs` URL regardless of whether the experimental features are enabled or not.
And I want the `isRunDetailsPage` to be true only when we are in the new run details page, not in the old one.

2022-07-01 10:10 UTC, agarciamontoro commented
@trilopin, thanks for checking, the problem was that I was not testing completely reloading the page! On Firefox, if you add a `#id` manually to the url, it does not reload, it simply scrolls to the required position. And the bug you saw happened only on first load, because the component is not mounted and the browser does not know where to scroll, so it just does nothing. https://github.com/mattermost/mattermost-plugin-playbooks/pull/1281/commits/754971f0ca2880dd2736c0927f6352002bcdee11 fixes it.

2022-07-02 14:50 UTC, gbochora approved these changes
Great! 🥳

2022-07-05 07:31 UTC, trilopin approved these changes
Thanks @agarciamontoro

2022-07-05 07:33 UTC, merged