Mm 44852 request an update
mattermost/mattermost-plugin-playbooks pull request #1285
Opened 2022-07-02 09:57 UTC by gbochora

#### Summary
This PR adds `Request update` functionality.
Change-log:
- Add `request update` API endpoint
- Add `Request update` button implementation
- Add toast message on success/failure
- Fix the `success` toast text color. It was the same as the background color, and the text was invisible.

https://user-images.githubusercontent.com/4368372/176995678-bd51637b-e82b-4332-934a-52ae9c58bdba.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44852

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-07-04 08:27 UTC, agarciamontoro approved these changes
Looks great, @gbochora! :tada: There's just a non-blocking comment on the `client` package. Thanks!

2022-07-04 08:27 UTC, agarciamontoro commented on client/playbook_runs.go
> +func (s *PlaybookRunService) RequestUpdate(ctx context.Context, playbookRunID, userID string) error {
The userID is not needed here, right?
```suggestion
func (s *PlaybookRunService) RequestUpdate(ctx context.Context, playbookRunID) error {
```

2022-07-04 08:27 UTC, agarciamontoro commented on webapp/src/components/backstage/toast_banner.tsx
> +    color: var(--center-channel-bg);
Whoops, this was my mistake, sorry!

2022-07-04 08:29 UTC, agarciamontoro commented on client/playbook_runs.go
> +func (s *PlaybookRunService) RequestUpdate(ctx context.Context, playbookRunID, userID string) error {
I thought this would have been caught by the linter :thinking:

2022-07-04 15:53 UTC, agarciamontoro commented
This fixes https://mattermost.atlassian.net/browse/MM-45418 too.

2022-07-05 08:18 UTC, trilopin requested changes
Check [message in community](https://community-daily.mattermost.com/core/pl/qoowkqw1utb65cpw73rt1mzyhc) . This "request update" should be linked to professional license, having upgrade banner otherwise.

2022-07-05 09:38 UTC, trilopin approved these changes
Code is fine, missing license check will be added in a future PR.

2022-07-05 09:40 UTC, merged