[MM-44757] Restrict runs and playbooks in LHS
mattermost/mattermost-plugin-playbooks pull request #1293
Opened 2022-07-06 10:32 UTC by iomodo

#### Summary
This PR Restricts runs and playbooks

#### Ticket Link
  Fixes: 
https://mattermost.atlassian.net/browse/MM-44757
https://mattermost.atlassian.net/browse/MM-44758

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-07-06 16:44 UTC, crspeller commented on server/api/categories.go
> +	filteredRuns := filterItemsInCategory(runsCategory, categories)
What is this about? This seems quite inefficient and isn't it already done by the DB?

2022-07-06 16:45 UTC, crspeller commented on webapp/src/components/sidebar/playbooks_sidebar.tsx
> +    useEffect(() => {
Could we use a custom hook here to make it more clear?

2022-07-06 17:38 UTC, iomodo commented on server/app/category.go
> +		if catItem.ItemID == item.ItemID && catItem.Type == item.Type {
Theoretically yes. ItemID is either playbookID or runID and they can be the same(low probability but still)

2022-07-06 17:39 UTC, iomodo commented on server/api/categories.go
> +const maxItemsInRunsAndPlaybooksCategory = 100
Should we have no limit here? I'm 0/5

2022-07-07 17:57 UTC, crspeller commented on server/api/categories.go
> +	filteredRuns := filterItemsInCategory(runsCategory, categories)
I think the function and variable names here are a bit confusing as to what is happening. 
`filterItemsInCategory` -> `filterDuplicatesFromCategories`? 
`categories` -> `userCategories` or `customCategories`

2022-07-07 17:58 UTC, crspeller requested changes
Existing comments.

2022-07-07 19:54 UTC, crspeller approved these changes
Unblocking for after the limit change.

2022-07-11 17:20 UTC, calebroseland approved these changes

2022-07-11 17:20 UTC, merged