Mm44851 get involved
mattermost/mattermost-plugin-playbooks pull request #1295
Opened 2022-07-06 14:17 UTC by trilopin

#### Summary
Get involved flow.

If a viewer user wants to get involved in a run, can click the get involved button and:
- if channel is accessible will join it directly
- a message will be sent to the channel otherwise

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-44851

#### Checklist
- [ ] ~~Telemetry updated~~
- [X] Gated by experimental feature flag
- [ ] Unit tests updated

2022-07-06 16:44 UTC, agarciamontoro reviewed
I think the approach makes total sense. I may add a comment to the `channel === null` explaining we assume that that means the channel is private. But apart from that, I think everything looks good!

2022-07-07 11:17 UTC, trilopin commented
cc @justinegeffen , here we have the efforts for the get involved feature. Feel free to suggest awesome copies right here.

2022-07-11 08:04 UTC, agarciamontoro requested changes
This looks great! I left a bunch of comments, but mostly nits and typos. I have a general UX comment, though: Should we also show a confirmation modal when the user will directly join the channel? Something like "Do you want to be added to this run's channel, ~channelname?" People may not be aware that "Get involved" means joining a channel.

Also, future improvements for v2: Wen someone requests to get involved to a private channel and a message is sent to the channel, we may render a custom post with an `Invite` button that automatically invites the member to the channel.

2022-07-11 08:10 UTC, trilopin commented on server/app/playbook_run_service.go
> +	}
do you mean to check in addition to the frontend check? because the webapp button won't be shown if the user is already a participant

2022-07-11 08:27 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +	}
Yes, I think we should check it here, too, because a user could still do it through the API. It's probably an edge case, but I think it's an easy enough check, so I'd say it's worth doing it.

2022-07-11 08:32 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                        cy.get('#postListContent').should('not.contain', 'wants to get involved in this run.');
didn't know, it's a useful helper

2022-07-11 09:18 UTC, trilopin commented
> This looks great! I left a bunch of comments, but mostly nits and typos. I have a general UX comment, though: Should we also show a confirmation modal when the user will directly join the channel? Something like "Do you want to be added to this run's channel, ~channelname?" People may not be aware that "Get involved" means joining a channel.

I've mixed feelings about that. Modals are educative but also stop the flow. Since the user could leave the channel I would start like this unless we hear about tons of accidental channel join. Additionally, the modal to confirm the request also has a motivation to avoid flooding the channel (also could be done through a debounce tho). 

 
> Also, future improvements for v2: Wen someone requests to get involved to a private channel and a message is sent to the channel, we may render a custom post with an `Invite` button that automatically invites the member to the channel.

Couldn't agree more. Nice topic to revisit after checking usage metrics.

2022-07-11 09:23 UTC, agarciamontoro approved these changes
Thanks for addressing all my comments! :)

> I would start like this unless we hear about tons of accidental channel join

Ok, let's go with that!

2022-07-11 15:20 UTC, trilopin commented on server/app/playbook_run_service.go
> +	if _, err = s.poster.PostMessage(playbookRun.ChannelID, T("app.user.run.request_get_involved", data)); err != nil {
is your concern related to this server code or the overall behavior?

I mean, by using the feature as a user, message and sender are fixed (copy and playbooks bot) and could not be arbitrary. So I guess it's more about this code at server side.

What kind of bad use are you worried about?

2022-07-11 15:27 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    cy.wait(500);
I could force an artificial rendered item to wait for it naturally. But it seemed even hackier than the wait 😂

2022-07-11 16:21 UTC, crspeller commented on server/app/playbook_run_service.go
> +	if _, err = s.poster.PostMessage(playbookRun.ChannelID, T("app.user.run.request_get_involved", data)); err != nil {
It's more of the behavior of being able to message a channel you are not a member of. Not sure if there is a precedent for that anywhere in the system. 

Technically you could change your username into the message you want sent. 

I don't think its too much of an issue since the offending user is easily identified.

2022-07-11 16:28 UTC, trilopin commented on server/app/playbook_run_service.go
> +	if _, err = s.poster.PostMessage(playbookRun.ChannelID, T("app.user.run.request_get_involved", data)); err != nil {
now I get it, thanks for the explanation. I will raise this topic in order to see if we can avoid that scenario.

2022-07-12 06:53 UTC, abhijit-singh requested changes
Thanks, @trilopin! The flows look great! I just found 1 functional issue:
1. When I start a run, and then navigate to the run detail page, I still see the `Get involved` button. This should not be the case because I'm already a member and owner of that run. 
![2022-07-12 12 10 36](https://user-images.githubusercontent.com/14369607/178426375-bd9137a7-3b4f-45bc-a68c-5ce79dafc068.gif)


Also a couple of minor visual issues. These are non-blocking and can also be fixed with other smaller UX fixes...
1. Add 8px space between the get involved button and the info icon. 
2. For the `get involved` button, font-size should be 12 px.

2022-07-12 08:06 UTC, trilopin commented
@agarciamontoro I fixed the flow problem that @abhijit-singh noticed in https://github.com/mattermost/mattermost-plugin-playbooks/pull/1295/commits/c796033f890c8d9f9fb259314e58b5ab2d8cb8f1 . However, please take a look because it seems a bit hacky to me.

**details**
the useChannel hook is built with useThing hook, which tries to get data from redux before doing a new fetch. If the data lacked some fields, we don't ask again for the full data.

The run we sent from server to webapp after Run creation was not the same as the Run we extracted from DB. 

My change: I forced the participantIds in run-creation to respect all Role-checks in the webapp side.  

I'm wondering if it's not better to force a complete run retrieval from DB, instead of hacking tons of things.

2022-07-12 08:21 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +	playbookRun.ParticipantIDs = append(playbookRun.ParticipantIDs, playbookRun.OwnerUserID)
Also, we should probably check if we do a similar append in the webapp side.

2022-07-12 08:22 UTC, trilopin commented on server/app/playbook_run_service.go
> +	playbookRun.ParticipantIDs = append(playbookRun.ParticipantIDs, playbookRun.OwnerUserID)
ok, I'll be more defensive here

2022-07-12 08:35 UTC, trilopin commented
> Thanks, @trilopin! The flows look great! I just found 1 functional issue:
> 
> 1. When I start a run, and then navigate to the run detail page, I still see the `Get involved` button. This should not be the case because I'm already a member and owner of that run.
>    ![2022-07-12 12 10 36](https://user-images.githubusercontent.com/14369607/178426375-bd9137a7-3b4f-45bc-a68c-5ce79dafc068.gif)
>          
>            [
>              
>                ![2022-07-12 12 10 36](https://user-images.githubusercontent.com/14369607/178426375-bd9137a7-3b4f-45bc-a68c-5ce79dafc068.gif)
>              
>            ](https://user-images.githubusercontent.com/14369607/178426375-bd9137a7-3b4f-45bc-a68c-5ce79dafc068.gif)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://user-images.githubusercontent.com/14369607/178426375-bd9137a7-3b4f-45bc-a68c-5ce79dafc068.gif)

wow, very good catch

> 
> Also a couple of minor visual issues. These are non-blocking and can also be fixed with other smaller UX fixes...
> 
> 1. Add 8px space between the get involved button and the info icon.
> 2. For the `get involved` button, font-size should be 12 px.

Thanks a ton @abhijit-singh, I pushed some changes that should have fixed the style and flow issues.

2022-07-12 11:14 UTC, agarciamontoro approved these changes

2022-07-12 11:14 UTC, agarciamontoro commented on server/api/playbook_runs.go
> +	return h.playbookRunService.GetPlaybookRun(playbookRunReturned.ID)
Much better, thanks!

2022-07-12 13:17 UTC, abhijit-singh approved these changes
Looks good!

2022-07-12 13:18 UTC, merged