[MM-44755] Favoriting Playbooks
mattermost/mattermost-plugin-playbooks pull request #1312
Opened 2022-07-11 18:38 UTC by iomodo

#### Summary
This PR adds means to favorite Playbook.
Feature is implemented with GraphQL.
There are REST API endpoints `favorite`, `unfavorite` and `isfavorite` they are not being used in this PR, but we will need them for favoriting runs.

Currently list of runs is not being updated, so after favoriting the playbook you have to refresh to see it in the LHS.

https://user-images.githubusercontent.com/2340127/178334235-66ff4734-0298-4ed5-a9c4-a7681a318c5c.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-44755

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-07-12 16:57 UTC, crspeller requested changes
Nice! Love the GraphQL usage!
Not sure why there is also a REST way to do this? Seems like we should be able to use GraphQL all the way here.

2022-07-12 16:57 UTC, crspeller commented on server/sqlstore/category.go
> +		if err := c.Create(category); err != nil {
Why bother actually writing it back? Shouldn't it be created on write not read? It seems like as written if I where to try and add a favorite before reading (using API directly) it would fail.

2022-07-12 16:57 UTC, crspeller commented on server/api/categories.go
> +	categoriesRouter.HandleFunc("/favorites", handler.addFavorite).Methods(http.MethodPost)
I thought we where going to do this through GraphQL?

2022-07-12 16:57 UTC, crspeller commented on webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
> +        isFavoriteItem(teamId, playbookId, CategoryItemType.PlaybookItemType)
We already have the playbook and it should include the isFavourite you added right?

2022-07-13 08:06 UTC, iomodo commented on server/sqlstore/category.go
> +		if err := c.Create(category); err != nil {
GetFavoriteCategory is called on write actually so no fail would occur, but you are right, readability is bad here, will refactor

2022-07-13 14:52 UTC, crspeller requested changes

2022-07-13 15:32 UTC, crspeller approved these changes

2022-07-14 06:12 UTC, calebroseland approved these changes
This is great! ⭐️

2022-07-14 07:37 UTC, iomodo commented
Removing @abhijit-singh's review, will address his suggestions in the next PR.

2022-07-14 07:38 UTC, calebroseland commented
UX review deferred cc @abhijit-singh

2022-07-14 07:38 UTC, merged