MM-45933: Playbook List Columns: Last used, Active runs, Runs in 30 days
mattermost/mattermost-plugin-playbooks pull request #1360
Opened 2022-07-22 21:07 UTC by calebroseland

![image](https://user-images.githubusercontent.com/11724372/180568602-d7126008-7ec9-4553-8f2a-83dace8ff078.png)

#### Summary

- [x] New column: `Last used` (Needs tests)
- [ ] New column: `Active runs` (TODO)
- [ ] New column: `Runs in 30 days` (TODO)

Note: might be good to keep `num_runs` as a sum metric (instead of repurposing), and add something named `num_runs_active`?

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-07-26 14:12 UTC, iomodo commented
Added the active runs column.
regarding the Runs in 30 days not quite sure what that means. Runs that ended 30 days ago or less + active runs? cc @stephenvanhemmen. Or runs that started 30 days ago?

2022-07-26 14:48 UTC, stephenvanhemmen commented
> Added the active runs column. regarding the Runs in 30 days not quite sure what that means. Runs that ended 30 days ago or less + active runs? cc @stephenvanhemmen. Or runs that started 30 days ago?

I'm not sure, I'd want to leave this question to @abhijit-singh. For this release these changes aren't critical, the only thing that is absolutely necessary is the join/run buttons. Can the categories (checklists, tasks, runs) be kept the same for this release? I think we should focus on a list upgrade (giving dashboard functionality) as a different feature.

2022-07-26 16:12 UTC, lieut-data requested changes

2022-07-26 16:12 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	case "", app.SortByActiveRuns:
This doesn't seem right -- should we be setting `sort` to something else when we match on `app.SortByActiveRuns`?

2022-07-26 16:12 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	if opts.Sort == app.SortByActiveRuns {
If I'm understanding this correctly, this won't work past page 1 of the results since the server will always return the same set for the first page?

2022-07-29 13:56 UTC, lieut-data approved these changes
Sweet!

2022-08-03 17:57 UTC, crspeller commented
Need rebasing after https://github.com/mattermost/mattermost-plugin-playbooks/pull/1357

2022-08-29 16:38 UTC, calebroseland commented
@crspeller this is ready now

2022-08-29 17:40 UTC, crspeller approved these changes

2022-08-29 17:40 UTC, merged