[MM-45116] Feature: playbooks insights
mattermost/mattermost-plugin-playbooks pull request #1366
Opened 2022-07-26 10:44 UTC by plant99

#### Summary

Add two new endpoints used by Insights page in mm-webapp.
```
/playbooks/api/v0/playbooks/insights/teams/4f3rbqs5qibn5erzfazxgmssmh?time_range=28_day&page=0&per_page=200
/playbooks/api/v0/playbooks/insights/user/me?time_range=28_day&page=0&per_page=200&team_id=4f3rbqs5qibn5erzfazxgmssmh
```
Following is a sample response
```
{
  "has_next": false,
  "items": [
    {
      "playbook_id": "6nrnwj5hfty8787mos9h6dtx6y",
      "num_runs": 3,
      "title": "sth",
      "last_run_at": 1658827931570
    },
    {
      "playbook_id": "3ii9fwq47pdtupqdd6ajo3axuc",
      "num_runs": 1,
      "title": "Test playbook",
      "last_run_at": 1658493052384
    }
  ]
}
```
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45116
#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-08-15 15:02 UTC, crspeller requested changes

2022-08-15 15:02 UTC, crspeller commented on server/api/playbooks.go
> +	if teamID != "" && !h.PermissionsCheck(w, h.permissions.PlaybookList(userID, teamID)) {
What if `teamID == ""`? What is the expected behavior? Should we return an error?

2022-08-16 10:04 UTC, plant99 commented on server/sqlstore/playbook.go
> +		boards = boards[:len(boards)-1]
Thanks for pointing this out, [here](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1366/files#diff-54c87c177e0c1f4e0ab4c2c0c903e13fcdabf27aa1e12afae9801c66ae1b95f5R1135) we query for an extra row so we can determine if `Page.HasNext` is true or false.

2022-08-16 10:07 UTC, plant99 commented on server/sqlstore/playbook.go
> +				sq.Eq{"p.ID": accessiblePlaybooks},
Please let me know if the query seems wrong to you with the latest commit.

2022-08-16 10:07 UTC, plant99 commented on server/api/playbooks.go
> +	if teamID != "" && !h.PermissionsCheck(w, h.permissions.PlaybookList(userID, teamID)) {
Added checks for teamID = ""

2022-08-16 10:09 UTC, plant99 commented
Thanks so much @crspeller for the review! I've updated the code as per your suggestions.

2022-08-16 20:07 UTC, mkraft approved these changes

2022-08-17 21:07 UTC, crspeller requested changes

2022-08-17 21:07 UTC, crspeller commented on server/sqlstore/playbook.go
> +		OR NOT EXISTS(SELECT 1
This `OR NOT EXISTS` part is unnecessary. No members used to mean public but that is no longer the case.

2022-08-17 21:07 UTC, crspeller commented on server/sqlstore/playbook.go
> +		OR NOT EXISTS(SELECT 1
Same here.

2022-08-17 21:07 UTC, crspeller commented on server/sqlstore/playbook.go
> +				sq.Eq{"p.Public": true},
This query and the one in GetTopPlaybooksForUser are identical except for this one includes all public playbooks. Could we construct a common query and just modify the one where clause?

2022-08-18 07:56 UTC, plant99 commented on server/sqlstore/playbook.go
> +				sq.Eq{"p.Public": true},
Nice suggestion, thank you! For now, I've generalised just the query builder. But I see scope of them being a common function with params changing in app layer. Not sure if it's a good pattern. I'd love to know your thoughts on that.

2022-08-18 15:04 UTC, BenCookie95 approved these changes

2022-08-18 17:34 UTC, crspeller approved these changes

2022-08-18 17:54 UTC, lieut-data commented
@Phrynobatrachus, can you help take a look at this PR for the Insights feature?

2022-08-19 17:10 UTC, Phrynobatrachus commented
Is the feature supposed to be fully working alongside https://github.com/mattermost/mattermost-webapp/pull/10919/files or is there still additional plumbing left to do?

2022-08-19 17:31 UTC, Phrynobatrachus approved these changes
Endpoints themselves seem fine so approving this, if my question above is an actual issue I expect it's on the webapp side.

2022-08-19 18:38 UTC, BenCookie95 commented
> Is the feature supposed to be fully working alongside https://github.com/mattermost/mattermost-webapp/pull/10919/files or is there still additional plumbing left to do? As it is right now, the table only shows the loading state, and no actual data.
> 
> ![Screenshot from 2022-08-19 13-13-09](https://user-images.githubusercontent.com/3723666/185672255-35b6037b-c816-497e-a8a8-67cf613801ed.png)

I'll take a look and see what's up!

2022-08-19 19:01 UTC, BenCookie95 commented
Oh I see what happened, we merged the client stuff into upstream and not Shivashis' branch.

@plant99 Can you merge upstream/MM-45116_top_playbooks into this branch?

2022-08-22 06:29 UTC, plant99 commented
Hi @BenCookie95 , @Phrynobatrachus  I've merged changes from that branch into this one. Should work now.

2022-08-22 14:44 UTC, merged