Add retrospective broadcast
mattermost/mattermost-plugin-playbooks pull request #1369
Opened 2022-07-27 12:34 UTC by gbochora

#### Summary
This PR adds retrospective broadcast to the channels. When the run's actions are configured to broadcast status updates to channels, we broadcast retrospective to the same thread.

Updated the `Run actions` dialog copies, needs review.
<img width="595" alt="Screenshot 2022-07-27 at 16 31 02" src="https://user-images.githubusercontent.com/4368372/181247442-7aa2663b-8d89-412d-b0b6-36e46cf76db7.png">

https://user-images.githubusercontent.com/4368372/181244657-d7148c57-fdee-40de-baf7-5985abf9cd16.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45175

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-07-28 10:50 UTC, trilopin requested changes
I left some comments, suggestions and questions.

The only blocker is the URL thing that I feel we must fix.

2022-07-28 10:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +			"URL":  retrospectiveURL + "#playbook-run-retrospective",
Let's replace `getRunRetrospectiveURL`method since it's still linking the old retrospective tab. That could be an excellent place to include the hashtag.

What do you think?

2022-07-28 10:50 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                            cy.findByText(CHANNEL_BROADCAST_TEXT).parent().within(() => {
Optional suggestions: personal preferences

```ts
const getBroadcastSection = () => cy.FindByText('Broadcast to selected channels');
...
getBroadcastSection().click();
getBroadcastSection().parent().get('input').should('be.checked');
```
1. You can define and reuse the command locally instead of using a constant
2. I usually chain commands directly when within only has one call


thoughts?

2022-07-28 10:50 UTC, trilopin commented on tests-e2e/cypress/support/plugin/api_commands.js
> +});
Thanks, very useful

2022-07-28 10:50 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                            cy.get(post).contains(retrospective);
[question/nofeedback]: what is injected into that promise? 

Is this function which is called?

```ts
Cypress.Commands.add('getLastPost', () => {
    waitUntilPermanentPost();

    cy.findAllByTestId('postView').last();
});
```

2022-07-28 11:45 UTC, gbochora commented on server/app/playbook_run_service.go
> +			"URL":  retrospectiveURL + "#playbook-run-retrospective",
I agree 💯.

2022-07-28 11:48 UTC, gbochora commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                            cy.findByText(CHANNEL_BROADCAST_TEXT).parent().within(() => {
Again, an excellent suggestion 👍

2022-07-31 06:45 UTC, gbochora commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                            cy.get(post).contains(retrospective);
It's unclear to me too. We use `getLastPost` in many places, and I did the same.

2022-08-01 13:46 UTC, trilopin approved these changes
Cool, thanks @gbochora !

2022-08-01 19:05 UTC, justinegeffen approved these changes

2022-08-01 19:05 UTC, justinegeffen commented
Thanks, @gbochora, this looks good to me! :)

2022-08-02 14:20 UTC, crspeller approved these changes

2022-08-02 14:20 UTC, merged

2022-08-02 16:29 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                            cy.get(post).contains(retrospective);
This is something I've wondered about before as well, the official docs don't explain the semantics very well IMO. This post by Gleb (one of the maintainers) notes:

https://glebbahmutov.com/blog/writing-custom-cypress-command/#simple-custom-command

`Notice that we did not have to return the command chain from the custom command, this is done automatically for every command.`