[MM-45741] Add following button to runs list
mattermost/mattermost-plugin-playbooks pull request #1370
Opened 2022-07-27 14:51 UTC by iomodo

#### Summary
This PR adds following button to runs list. It uses already existed `useRunMetadata` hook. To avoid creating additional api endpoint or hook. It will change when we move to GraphQL for runs.

https://user-images.githubusercontent.com/2340127/181278512-722add60-f9ba-4bf1-9a3a-66437db99686.mp4

#### Ticket Link

  Fixes: https://mattermost.atlassian.net/browse/MM-45741

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-07-28 11:17 UTC, trilopin requested changes
Thanks @iomodo 👍🏽 

I left some questions and comments

2022-07-28 11:17 UTC, trilopin commented on webapp/src/components/backstage/runs_list/row.tsx
> +    color: var(--center-channel-color-64);
buttons are completely different here and on the run details page (run info overview). is that intended?

2022-07-28 11:17 UTC, trilopin commented on webapp/src/components/backstage/runs_list/row.tsx
> +    const [isFollowing, setIsFollowing] = useState(followers.includes(currentUser.id));
```suggestion
    const isFollowing = followers.includes(currentUser.id);
```

I may be wrong, but this seems to be a derived property that don't need to be state

2022-07-28 11:17 UTC, trilopin commented on webapp/src/components/backstage/runs_list/row.tsx
> +    useEffect(() => {
we could use useUpdateEffect from react-use to make more clear that we only need it for future changes (not the initial one)

2022-08-25 14:16 UTC, iomodo commented on webapp/src/components/backstage/runs_list/row.tsx
> -                />
These are no longer in the design

2022-08-25 14:31 UTC, trilopin approved these changes
Thanks @iomodo

2022-08-25 15:09 UTC, iomodo commented
/update branch

2022-08-25 22:52 UTC, crspeller approved these changes

2022-08-25 22:52 UTC, merged