Mm 46070 lhs not updated
mattermost/mattermost-plugin-playbooks pull request #1376
Opened 2022-08-01 10:01 UTC by gbochora

#### Summary
This PR adds LHS refresh for some actions:
- Finish run
- Become a participant
- Leave a run
- Archive playbook
- Restore playbook
- Create playbook

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46070

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-08-01 13:57 UTC, trilopin requested changes
I'm unsure about the GraphQL client thing.  I'll let @crspeller spread his wisdom on that 🧙🏽‍♂️.

Regarding e2e within calls, I personally chain calls when there's only one call inside the within. From my point of view, in that case, it's better to have a longer line than nesting contexts.

2022-08-01 13:57 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/creation_button_spec.js
> +        });
optional: would make sense to make this a one-liner?
```suggestion
        cy.findByTestId('lhs-navigation').findByText(playbookName).should('exist');
```

2022-08-01 13:57 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +                    getHeader().findByText('Participate').should('exist');
would you want to additionally check that is visible in the screen?
```suggestion
                    getHeader().findByText('Participate').should('be.visible');
```

2022-08-01 13:57 UTC, trilopin commented on webapp/src/components/backstage/lhs_navigation.tsx
> +import {getPlaybooksGraphQLClient} from 'src/graphql_client';
we have the following disclaimer at this singleton
```ts
// Global for use in gloablly mounted modals that won't work with react context.
// Don't use this. If you need the client itself use `useApolloClient`.
```

should we use it for this goal? can't we call useApolloClient? 0/5 on this (on both approaches)

2022-08-03 14:46 UTC, crspeller requested changes

2022-08-03 14:46 UTC, crspeller commented on webapp/src/components/backstage/lhs_navigation.tsx
> +import {getPlaybooksGraphQLClient} from 'src/graphql_client';
@trilopin is right here we should use `useApolloClient` for this. This get was just a hack for global modals that don't have the context wrapped. 

Overall this is a pattern to be avoided but it's the best one I have found for interfacing between non-graphql and graphql for updates (until we can get push updates from server side)

2022-08-04 11:09 UTC, trilopin commented on webapp/src/components/backstage/lhs_navigation.tsx
> +    return refreshLists;
if you only expose the refresh op, should the hook be called `useLHSRefresh` ?

2022-08-04 11:10 UTC, trilopin approved these changes

2022-08-04 16:35 UTC, crspeller approved these changes

2022-08-05 06:42 UTC, merged