Add sort by name
mattermost/mattermost-plugin-playbooks pull request #1384
Opened 2022-08-02 18:44 UTC by gbochora

#### Summary
This PR adds sorting LHS run list by name. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46116

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-08-03 18:19 UTC, crspeller requested changes

2022-08-03 18:19 UTC, crspeller commented on server/api/schema.graphqls
> +		sort: String = "name",
I don't think we want to set this as the default in the schema. We probably just want to modify the LHS query in https://github.com/mattermost/mattermost-plugin-playbooks/blob/f529e4a00faf188b4d6628e22fc9643bb215e2c1/webapp/src/graphql/playbook.graphql#L69

2022-08-04 16:39 UTC, crspeller approved these changes

2022-08-04 16:44 UTC, trilopin approved these changes
Thanks @gbochora !

2022-08-04 16:44 UTC, trilopin commented on tests-e2e/cypress/integration/runs/list_spec.js
> +            cy.apiRunPlaybook({
optional nit:

I've never tried in cypress but what if you do a Promise.all to avoid 4 level nesting.

2022-08-05 14:08 UTC, merged