MM-45989 Fix overview navigation spacing.
mattermost/mattermost-plugin-playbooks pull request #1390
Opened 2022-08-03 21:51 UTC by crspeller

#### Summary
Update the playbook navigation spacing to have some more spacing at low screen sizes. 

#### Screenshot
![image](https://user-images.githubusercontent.com/3191642/182718793-6f819589-c2ee-44e5-9239-0f92e5271cf7.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45989

2022-08-04 13:48 UTC, lieut-data approved these changes

2022-08-04 15:01 UTC, gbochora approved these changes

2022-08-05 15:54 UTC, abhijit-singh requested changes
Thanks, @crspeller! A few requests:
1. Can we double the space between the navigation and the white box containing the content? (Adding a margin-right: 1.5rem on the `playbook-preview-navbar` did it for me)
2. Can we ensure the text in the navigation never has to wrap like in the screenshot below? (I couldn't figure out why that was happening but setting a min-width of anything more than 140px solved the issue, but that's probably not the correct way)
<img width="200" alt="image" src="https://user-images.githubusercontent.com/14369607/183114890-a7400ee5-f698-4ca3-8dc5-00ff5d59c62f.png">

2022-08-09 23:06 UTC, abhijit-singh approved these changes
Pefect 💯 

Thanks, @crspeller!

2022-08-09 23:07 UTC, merged