Morph adoption
mattermost/mattermost-plugin-playbooks pull request #1397
Opened 2022-08-10 03:23 UTC by gbochora

#### Summary
Adds morph migrations from `v0.1.0` to `v0.3.0`. We have separate files for MySQL and PostgreSQL, located in
`server/sqlstore/migrations/mysql` and `server/sqlstore/migrations/postgres`.
Files with prefix `00001 - 00004` correspond to the migration `v0.1.0` -> `v0.2.0`
Files with prefix `00005` correspond to the migration `v0.2.0` -> `v0.3.0`
The migration filenames attempt to describe changes to the database.

Changes in the `migrate.go`:
- Commented morph migration temporary until properly tested. 
- Split `runMigrationsWithMorph` into several functions to make them reusable

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44243
https://mattermost.atlassian.net/browse/MM-44244
https://mattermost.atlassian.net/browse/MM-44245

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-08-10 13:20 UTC, lieut-data requested changes
Nice! Awesome to see us moving towards the multi-product architecture :)

A few comments below.

2022-08-10 13:20 UTC, lieut-data commented on server/sqlstore/migrations/mysql/000005_add_active_stage_title_to_ir_incident.down.sql
> +    ) > 0,
Is `> 0` necessary here?

2022-08-10 13:20 UTC, lieut-data commented on server/sqlstore/migrations/mysql/000005_add_active_stage_title_to_ir_incident.up.sql
> +UPDATE IR_Incident
Ooh, this goes back to early days! 0/5 for this PR, but I'm wondering if we should consider deprecating this more aggressively, since I believe we don't use this field at all anymore, and it would be a shame to permanently keep that complexity. Thoughts?

2022-08-10 13:20 UTC, lieut-data commented on server/sqlstore/migrations/postgres/000003_create_ir_playbook.up.sql
> +DO $$
Since we require PostgreSQL 10.0+ now, can we just rely on `CREATE INDEX IF NOT EXISTS`?

2022-08-10 13:20 UTC, lieut-data commented on server/sqlstore/migrations/postgres/000005_add_active_stage_title_to_ir_incident.up.sql
> +CREATE OR REPLACE function json_array_length_safe(p_json text)
Should we drop this function afterwards?

2022-08-11 10:09 UTC, gbochora commented on server/sqlstore/migrations/postgres/000003_create_ir_playbook.up.sql
> +DO $$
Excellent point!

2022-08-11 11:23 UTC, gbochora commented on server/sqlstore/migrations/mysql/000005_add_active_stage_title_to_ir_incident.up.sql
> +UPDATE IR_Incident
I agree, it would be better if we removed this unnecessary complexity. I'll do it in a different PR, this one already has a lot of changes.

2022-08-11 14:02 UTC, lieut-data approved these changes

2022-08-12 16:11 UTC, crspeller approved these changes

2022-08-12 16:11 UTC, crspeller commented on server/sqlstore/migrations/mysql/000003_create_ir_playbook.down.sql
> +DROP TABLE IF EXISTS IR_Playbook;
I feel like these down migrations are like a bomb waiting to go off and delete all our data.

2022-08-13 09:54 UTC, merged