WIP: [MM-45116] Adding playbooks client stuff for insights
mattermost/mattermost-plugin-playbooks pull request #1398
Opened 2022-08-10 20:30 UTC by BenCookie95

#### Summary
I had to upgrade the webapp commit hash so we can use the new insights handler, this also meant having to add in the client package from webapp.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42744

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-08-16 11:19 UTC, plant99 approved these changes

2022-08-17 21:29 UTC, crspeller requested changes

2022-08-17 21:29 UTC, crspeller commented on webapp/webpack.config.js
>              '@mattermost/types': path.resolve(__dirname, './node_modules/mattermost-webapp/packages/types/src/'),
I don't think webpack needs these anymore right? Since we are using the ones from the package.json? Same with the lines in the `tsconfig.json`

2022-08-18 17:13 UTC, BenCookie95 commented on webapp/webpack.config.js
>              '@mattermost/types': path.resolve(__dirname, './node_modules/mattermost-webapp/packages/types/src/'),
Removed from here but I needed to keep it in `tsconfig.json`, there was a bunch of lint errors when it's removed

2022-08-18 17:31 UTC, crspeller approved these changes

2022-08-18 17:32 UTC, merged