Update run participants table and related queries.
mattermost/mattermost-plugin-playbooks pull request #1412
Opened 2022-08-16 16:46 UTC by crspeller

#### Summary
Adding participants to the `IR_Run_Participants` table. Modifying the queries to pull from the updated list.
Note that there is currently no way to actually become a participant. 

Tests are currently broken because of previous assumptions that participants will be added automatically. Will be fixed with #1401 

#### Ticket Link
Fixes #1399

2022-08-18 17:23 UTC, trilopin requested changes
Cool move!

I left some comments about naming and multiple-users support

2022-08-18 17:23 UTC, trilopin commented on server/app/playbook_run.go
> +	Participate(playbookRunID, userID string) error
I'd use the same naming as mutations and store `AddParticipants`, `RemoveParticipants`. Otherwise, it could be misleading when we use leave on other users' behalf.

2022-08-18 17:23 UTC, trilopin commented on server/app/playbook_run.go
> +	AddParticipant(playbookRunID, userID string) error
If it is not hard, I'd add support to pass multiple userID in one shot to avoid multiple queries. Also for RemoveParticipant.

2022-08-18 17:23 UTC, trilopin commented on server/app/playbook_run.go
> +	Participate(playbookRunID, userID string) error
additionally, I'd add support to multiple userIDs in both funcions

2022-08-18 17:23 UTC, trilopin commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) addChannelJoinTimelineEvent(user *model.User, channel *model.Channel, actorID string, playbookRunID string, userID string) error {
nice refactor 👍🏽

2022-08-18 17:23 UTC, trilopin commented on server/app/playbook_run_service.go
> +	member, _ := s.pluginAPI.Channel.GetMember(playbookRun.ChannelID, userID)
nice! almost done waiting for just a couple of flags :)

2022-08-18 17:23 UTC, trilopin commented on server/sqlstore/playbook_run.go
> +	// Guests must be participants
why do we need an special block for guests?

2022-08-18 18:05 UTC, crspeller commented on server/sqlstore/playbook_run.go
> +	// Guests must be participants
Because they don't have permissions to view all the playbooks on a team.

2022-08-19 05:35 UTC, trilopin approved these changes
Thanks @crspeller: looks good to merge

I left a style comment about error returned+logged in the timeline functions

2022-08-19 05:35 UTC, trilopin commented on server/app/playbook_run_service.go
> +			return err
we are currently both loogging the error and returning it. After that, we ignore it in the upper level. 

I see two options here:
- return err in this scope and log it in the upper level (remove logging here)
- log err in this level and don't return it to the upper level (remove return type)

Personally, I don't have any special preference for any of those.

Thoughts?

2022-08-19 05:35 UTC, trilopin commented on server/app/playbook_run_service.go
> +	// Automaticly leave if you leave the channel
```suggestion
	// Automatically leave run if you leave the channel
```

2022-08-19 05:35 UTC, trilopin commented on server/app/playbook_run_service.go
> +	return nil
same comment than the one for joinTimelineEvent

2022-08-19 05:36 UTC, trilopin commented on server/sqlstore/playbook_run.go
> +	// Guests must be participants
yeah, makes sense when I look at the whole piece of code 👍🏽

2022-08-19 15:15 UTC, crspeller commented on server/app/playbook_run_service.go
> +	if err := s.AddParticipants(playbookRunID, []string{user.Id}); err != nil {
Good question! They where allowed to be participants before, but that might change now. I suspect we don't.

2022-08-19 15:25 UTC, crspeller commented on server/app/playbook_run_service.go
> +	if err := s.AddParticipants(playbookRunID, []string{user.Id}); err != nil {
Decision was to allow it: https://community.mattermost.com/core/pl/jus93dbx1bn5urbxqz4qe4s35a

2022-08-19 15:34 UTC, gbochora approved these changes
Great stuff! 🎉

2022-08-19 15:44 UTC, merged