Separate run participants graphql participants move
mattermost/mattermost-plugin-playbooks pull request #1424
Opened 2022-08-19 13:44 UTC by trilopin

#### Summary
This PR introduces the new graphql run mutations but internally relies on channel members. It has the latest unmerged code from https://github.com/mattermost/mattermost-plugin-playbooks/pull/1412.

RootResolver split on Run & Playbook embebbed objects. 1/5 on this move, I'm 100% open to discussion or to revert it if doesn't feel ok.

RunResolver completed with missing fields. Not really necessary for this PR.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1402

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-08-22 22:03 UTC, crspeller requested changes
Awesome! Just one question about the refactor.

2022-08-23 07:05 UTC, gbochora reviewed
Great work @trilopin! I've left some questions and comments.

2022-08-23 07:39 UTC, trilopin commented on server/api/graphql_run.go
> +	}
Currently, becoming a participant implies following, and removing from participants implies unfollowing. We feel this behavior won't be like that forever, that's the main reason to keep them separated at service/store and just call both cases from handler/resolver.

2022-08-23 07:40 UTC, trilopin commented on server/api/graphql_run.go
> +	}
[same case](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1424#discussion_r952257865)

2022-08-23 07:41 UTC, trilopin commented on server/app/playbook_run_service.go
> +	}
At this point, leaving the channel implies leaving the run. Additionally, leaving the run implies unfollowing.

That will change after introducing actions, and here we will have a boolean flag that enable/disable this behavior.

2022-08-23 07:43 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +            .catch(() => addToast(formatMessage({defaultMessage: 'It wasn\'t possible to join the run'}), ToastType.Failure));
Not sure if I understand you. This is about joining a run, not a channel.

2022-08-23 08:21 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +            .catch(() => addToast(formatMessage({defaultMessage: 'It wasn\'t possible to join the run'}), ToastType.Failure));
Yep, I can see it's pretty unclear : ))
If we have a public run with a private channel, adding a user to run members also means adding to the channel. 

https://github.com/mattermost/mattermost-plugin-playbooks/blob/10b892f5c771a9d7a1f0cbfc6f621b09012d31ca/server/app/playbook_run_service.go#L2817

So by clicking on the `Participate` button user will become a member of the private channel.

2022-08-23 08:26 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +            .catch(() => addToast(formatMessage({defaultMessage: 'It wasn\'t possible to join the run'}), ToastType.Failure));
Oh, I got it. You are right

From webapp, we don't add to channel anymore. However, we are temporarily adding the user to channel when it's added to run. That shouldn't happen if the is participate-flow with private channel.

Good catch!

2022-08-23 12:35 UTC, trilopin commented on server/api/graphql_run.go
> +	if err := c.permissions.RunView(userID, args.RunID); err != nil {
Thanks @gbochora, two points here:
- any user with access to a run can add other user (and this internally relies on channel members)
- since it relies on channel members... it needs to be migrated to rely on run members

https://github.com/mattermost/mattermost-plugin-playbooks/issues/1432

2022-08-23 12:38 UTC, trilopin commented
@gbochora @crspeller Thank you for your comments

Several changes:
- refactor refactored :) Naming improved and rootresolvers separated from resolvers. Still 2/5, open to more changes if you have ideas.
- e2e tests for graphql run root resolvers 
- handled edge case (+test) when participating in a public run with private channel


Created new issue to handle permissions https://github.com/mattermost/mattermost-plugin-playbooks/issues/1432

2022-08-23 14:56 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +            .catch(() => addToast(formatMessage({defaultMessage: 'It wasn\'t possible to join the run'}), ToastType.Failure));
I thought we had decided this case was OK? Since the user has access to the run and the action is configured to automatically add them to the channel. 
I am fine with keeping it this way until a explicit action is configurable though.

2022-08-23 14:59 UTC, crspeller approved these changes

2022-08-24 08:03 UTC, gbochora approved these changes
Looks good! Thanks, @trilopin 🥳

2022-08-24 08:03 UTC, gbochora commented on server/app/playbook_run_service.go
> +	channel, err := s.pluginAPI.Channel.Get(playbookRun.ChannelID)
Optional: Would it be better to move this call outside the `participateActions` function and pass information as an argument? We will avoid multiple calls for each user.

2022-08-24 09:10 UTC, trilopin commented on server/app/playbook_run_service.go
> +	channel, err := s.pluginAPI.Channel.Get(playbookRun.ChannelID)
> Optional: Would it be better to move this call outside the `participateActions` function and pass information as an argument? We will avoid multiple calls for each user.

but the channel is not queried before, is it?

2022-08-24 10:30 UTC, trilopin commented on server/app/playbook_run_service.go
> +	channel, err := s.pluginAPI.Channel.Get(playbookRun.ChannelID)
nice catch @gbochora, same find inside a loop for every user... 🗡️

2022-08-24 17:08 UTC, merged