Duplicate task as next task instead of end of list
mattermost/mattermost-plugin-playbooks pull request #1430
Opened 2022-08-23 05:39 UTC by varundey

#### Summary

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-08-23 05:39 UTC, mattermod commented
Hello @varundey,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-08-23 20:22 UTC, mickmister requested changes
Great work on this @varundey :+1:

Looks mostly good, though I think the ordering logic has one issue where the new item is being put before the old item instead of after. Please let me know your thoughts on this.

Also do we need to update this function? https://github.com/mattermost/mattermost-plugin-playbooks/blob/5dfbc8189a8999a2ee0d03f573cace729401bff5/webapp/src/components/checklist/generic_checklist.tsx#L56-L63

2022-08-23 20:22 UTC, mickmister commented on server/app/playbook_run_service.go
> +	playbookRunToModify.Checklists[checklistNumber].Items[itemNumber] = checklistItem
Trying this out in the Go playground, this seems to put the new element before the item to be duplicated, instead of after. It probably doesn't matter due to the items being the same, but something may change about this logic later that could cause issues.

This worked for me:

```suggestion
	playbookRunToModify.Checklists[checklistNumber].Items = append(
		playbookRunToModify.Checklists[checklistNumber].Items[:itemNumber+1],
		playbookRunToModify.Checklists[checklistNumber].Items[itemNumber:]...)
	playbookRunToModify.Checklists[checklistNumber].Items[itemNumber+1] = checklistItem
```

2022-08-23 20:40 UTC, varundey commented
> Looks mostly good, though I think the ordering logic has one issue where the new item is being put before the old item instead of after. Please let me know your thoughts on this.

Sure we can put the new item after the original one instead of before.

> Also do we need to update this function?

I looked at this but I could not find an instance where `playbookRunId` is not present [here](https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/webapp/src/components/checklist_item/hover_menu.tsx#L94). If you could help me figure out when and how this function gets called, I can try testing this as well.

2022-08-23 20:49 UTC, varundey commented on server/app/playbook_run_service.go
> +	playbookRunToModify.Checklists[checklistNumber].Items[itemNumber] = checklistItem
Updated this.

2022-08-25 14:09 UTC, mickmister commented
> I looked at this but I could not find an instance where `playbookRunId` is not present [here](https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/webapp/src/components/checklist_item/hover_menu.tsx#L94). If you could help me figure out when and how this function gets called, I can try testing this as well.

I'm not too familiar with the project, so I'm not sure what conditions would cause this. You could force the condition and make it so the duplicate function is always called, for the purpose of testing your feature.

2022-08-25 14:12 UTC, mickmister reviewed
I'm thinking the client-side function still needs to be updated, so I'll defer approval until the discussion is resolved

2022-08-25 15:17 UTC, varundey commented
> I'm thinking the client-side function still needs to be updated, so I'll defer approval until the discussion is resolved

Fixed this too

2022-08-25 15:17 UTC, varundey commented
> I'm thinking the client-side function still needs to be updated, so I'll defer approval until the discussion is resolved

Fixed this too

2022-08-25 15:28 UTC, mickmister commented on webapp/src/components/checklist/generic_checklist.tsx
> +        newChecklistItems.splice(index, 0, duplicate);
This is putting the new item before the pre-existing item rather than afterwards

2022-08-25 15:34 UTC, varundey commented on webapp/src/components/checklist/generic_checklist.tsx
> +        newChecklistItems.splice(index, 0, duplicate);
Ahh sorry you are right. I tested with the correct index on a random array. Didn't realise the difference on checklist array cos the item is the same. Updating this.

2022-08-25 15:39 UTC, varundey commented
Whoops. Clicking on re-review removes other reviewers. 😬

2022-08-26 09:03 UTC, gbochora approved these changes
Looks great, thanks @varundey  🥳

2022-08-26 13:35 UTC, Phrynobatrachus approved these changes
LGTM, thank you!

2022-08-26 13:35 UTC, merged