[GH-20818] - Add restore run feature for playbook
mattermost/mattermost-plugin-playbooks pull request #1448
Opened 2022-08-28 18:38 UTC by rolwin100

#### Summary

* This feature restores a run that is finished.
* There was a /restore feat already present in the repo
* created a api request in client.ts
* added a hook in restore_run.tsx
* Added menu in button in context_menu.tsx and called the hook on button click.

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/20818

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-08-28 18:38 UTC, mattermod commented
Hello @rolwin100,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-08-29 17:50 UTC, nickmisasi requested changes
Overall LGTM! Couple changes required.

My question here is whether this is _restoring_ or _restarting_ the run. Will the run pick up where it was left off (ie, any already completed steps will still be completed) or will this act more like it's a fresh new run?

Depending on which this is, I think it's important to ensure that all verbiage (things displayed to user, as well as file names/function names/etc) is consistently either `restore` _or_ `restart` to avoid confusion.

2022-08-29 17:50 UTC, nickmisasi commented on webapp/i18n/en.json
> +  "ELjMDy": "Are you sure you want to restart the run ?",
```suggestion
  "ELjMDy": "Are you sure you want to restart the run?",
```

2022-08-29 17:50 UTC, nickmisasi commented on webapp/src/components/backstage/playbook_runs/playbook_run/restore_run.tsx
> +        const confirmationMessage = formatMessage({defaultMessage: 'Are you sure you want to restart the run ?'});
```suggestion
        const confirmationMessage = formatMessage({defaultMessage: 'Are you sure you want to restart the run?'});
```

2022-08-29 18:09 UTC, itao commented
👋 Hi @rolwin100, thanks for taking on this PR! I noticed that the [original issue](https://github.com/mattermost/mattermost-server/issues/20818) mentioned

> Restarting a run should add an event to the timeline, as well as post a message to the associated channel:

Could you confirmed if that was something already implemented or if it's expected as part of this PR, please?

2022-08-30 04:39 UTC, rolwin100 commented
Its'a part of this PR.

2022-08-30 04:42 UTC, rolwin100 commented on webapp/i18n/en.json
> +  "ELjMDy": "Are you sure you want to restart the run ?",
@nickmisasi this feature will restore as well as restart the run as per what I can understand.

2022-08-30 04:44 UTC, rolwin100 commented on webapp/i18n/en.json
> +  "ELjMDy": "Are you sure you want to restart the run ?",
Made a commit and removed the extra space.

2022-08-30 04:44 UTC, rolwin100 commented on webapp/src/components/backstage/playbook_runs/playbook_run/restore_run.tsx
> +        const confirmationMessage = formatMessage({defaultMessage: 'Are you sure you want to restart the run ?'});
Made a commit and removed the extra space.

2022-08-30 14:35 UTC, itao commented
@nickmisasi regarding your question whether this is restoring or restarting the run.

Yes, the run will pick up where it was left off. However I prefer the copy `restart` over `restore` since the latter is more often associated with archiving or deletion, whereas the action we're undoing in this case is finishing. There is still a difference between:
- `restart the run`: pick up where it left off when marked as finished
- `rerun the playbook`: start a fresh new run

2022-08-30 17:02 UTC, rolwin100 commented
> @nickmisasi regarding your question whether this is restoring or restarting the run.
> 
> Yes, the run will pick up where it was left off. However I prefer the copy `restart` over `restore` since the latter is more often associated with archiving or deletion, whereas the action we're undoing in this case is finishing. There is still a difference between:
> 
> * `restart the run`: pick up where it left off when marked as finished
> * `rerun the playbook`: start a fresh new run

@itao @nickmisasi  can we proceed with the existing change because the api which was present was named as restore and I don't see much problem with this.

2022-08-31 07:53 UTC, gbochora approved these changes
Great work, @rolwin100! Thanks! I left two optional suggestions.

2022-08-31 07:53 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/restore_run.tsx
> +};
New line at the end of the file.
```suggestion
};

```

2022-08-31 07:53 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/restore_run.tsx
> +            onCancel: () => {},
```suggestion
            onCancel: () => null,
```

2022-08-31 15:22 UTC, rolwin100 commented on webapp/src/components/backstage/playbook_runs/playbook_run/restore_run.tsx
> +            onCancel: () => {},
Yo @gbochora thanks for the suggestion :). Yes, this was a must.

2022-09-01 08:23 UTC, gbochora commented
@rolwin100, great work on tests; thanks again! We will be able to merge this PR after the second reviewer approves it.

2022-09-01 14:11 UTC, nickmisasi reviewed
Code LGTM. Will need tests to pass before approval. Thanks @rolwin100 🎉!

2022-09-01 14:11 UTC, nickmisasi commented on tests-e2e/cypress/integration/runs/rdp_main_restore_spec.js
> +        it('can be confirmed', () => {
This test seems to be failing: 
![image](https://user-images.githubusercontent.com/12176405/187935277-be7819a7-d3ba-45c6-b8ee-f20ff75e4335.png)

2022-09-01 14:44 UTC, rolwin100 commented on tests-e2e/cypress/integration/runs/rdp_main_restore_spec.js
> +        it('can be confirmed', () => {
let me check it again it's working for me let me cross check and verify it

2022-09-01 15:05 UTC, rolwin100 commented on tests-e2e/cypress/integration/runs/rdp_main_restore_spec.js
> +        it('can be confirmed', () => {
I'm not facing this issue. I'm running  `CYPRESS_developerMode=true npm run cypress:open` inside playbook tests-e2e folder as mentioned by @trilopin

2022-09-01 15:32 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/runs/rdp_main_restore_spec.js
> +        it('can be confirmed', () => {
Fails about 20% of the time locally for me. In the test, the run is finished and _then_  you check for the `In Progress` badge, this ordering makes the assertion dependent on how quickly the API resolves. If it takes a bit longer, the text will still be `In Progress` and the assertion works, if it completes quickly the badge will have already changed to `Finished` and the assertion fails.   

Move the `In Progress` assertion above the finish run modal interactions and it should be fine. :+1:

2022-09-01 16:10 UTC, rolwin100 commented on tests-e2e/cypress/integration/runs/rdp_main_restore_spec.js
> +        it('can be confirmed', () => {
Oops Got it my bad :) thanks @Phrynobatrachus

2022-09-01 16:10 UTC, rolwin100 commented on tests-e2e/cypress/integration/runs/rdp_main_restore_spec.js
> +        it('can be confirmed', () => {
@nickmisasi this is resolved

2022-09-01 18:06 UTC, nickmisasi approved these changes
Thanks @rolwin100!

2022-09-01 20:34 UTC, Phrynobatrachus approved these changes

2022-09-01 20:34 UTC, merged