Mm 44752 add dot menu to lhs
mattermost/mattermost-plugin-playbooks pull request #1458
Opened 2022-08-30 09:36 UTC by gbochora

#### Summary
This PR adds a dot menu to the LHS. 
Playbook menu items:
- Favorite / Unfavorite
- Copy link
- Leave

Run menu items:
- Favorite / Unfavorite
- Copy link
- Follow / Unfollow
- Leave (Only if participants)

Changelog highlights:
- DotMenu had issues with z-index and content overflow, thanks to @calebroseland switched to using `dropdown` instead.
- Moved menu items from `contex_menu` to `controls` to reuse them in the LHS 
- Moved shared components to `shared.tsx`

https://user-images.githubusercontent.com/4368372/187399285-3803723d-10e4-421f-a7fe-b9e021a38a0b.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44752

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-08-31 07:51 UTC, trilopin commented on webapp/src/components/backstage/lhs_run_dot_menu.tsx
> +    const {leaveRunConfirmModal, showLeaveRunConfirm} = useLeaveRun(playbookRunId, isFollowing);
This is getting from fetch every run and metadata individually. 

I'd rather add to LHSQuery the data you need to handle dotmenu and pass to this component as a prop instead of fetching.

2022-08-31 07:56 UTC, trilopin commented on webapp/src/components/backstage/lhs_run_dot_menu.tsx
> +    const {leaveRunConfirmModal, showLeaveRunConfirm} = useLeaveRun(playbookRunId, isFollowing);
I guess you need participantIDs and isFollower. 

Would that be enough to remove the useRunMetadata, useRun and useFavoriteRun?

2022-08-31 09:11 UTC, trilopin requested changes
Huge effort in this PR, thanks @gbochora 

I'm concerned on the data flow approach. The right approach to me would be to get the data from LHSQuery and avoid all the additional fetch.

We could delay it a bit for useRun and rely on useThing getting that from redux for the following useRun calls. Unfortunately, we still have useRunMetadata with relies on useFetch and it's not stored in redux.

Run resolver is a bit more finished on [this branch](https://github.com/mattermost/mattermost-plugin-playbooks/tree/graphql-run-resolver). We may want to pick some of that code to solve this problem.

2022-08-31 14:50 UTC, Phrynobatrachus commented
Something I noticed - for runs, favorite/unfavorite using the dot menu updates the LHS as expected, however the star icon in the run details does not change until a refresh.

2022-09-02 09:50 UTC, trilopin requested changes
great work on graphql move


I still see tons of run requests, probably because uiseRun inside useLeaveRun. Could you please add owneruserid to gql so we can avoid that one?

the comments on moving logic to controls is optional and I'd do it in future prs.

2022-09-02 09:50 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +        return cy.findByTestId('dropdownmenu').findByText(text);
why did you change this func? it was designed to find dropdownmenu inside run-header-section, not globally.

If it failed, I would have tried to change the chaining to a within statement

2022-09-02 09:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +    const {formatMessage} = useIntl();
Once you made a separated component for this, would make sense to import and use the useUpdateRun here instead of passing from parent? It may hide some complexity. You already did that for leave op.

2022-09-02 09:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
> +                    onExportClick={onExportClick}
would make sense to hide complexity and move that flow onExportClick to the controls file?

2022-09-02 09:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
> +import {useAllowChannelExport, useExportLogAvailable, useRun} from 'src/hooks';
you can avoid calling useRun if you retrieve owneruserid from GQL

2022-09-02 09:50 UTC, trilopin commented on webapp/src/components/dot_menu.tsx
> +    min-width: 16rem;
why this change? just curiosity

2022-09-02 14:20 UTC, gbochora commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +        return cy.findByTestId('dropdownmenu').findByText(text);
DotMenu now works differently; The drop-down is not added inside the header element. Because of that, we can't find it inside the header.

2022-09-02 14:28 UTC, gbochora commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +    const {formatMessage} = useIntl();
Good point; this way, we will encapsulate logic inside menu item.

2022-09-02 14:35 UTC, gbochora commented on webapp/src/components/dot_menu.tsx
> +    min-width: 16rem;
It's Caleb's change. I guess now the dropdown is more flexible; if someone zooms, the page dropdown will increase proportionally to font size.

2022-09-02 15:56 UTC, Phrynobatrachus commented
Favorite/unfavorite is working better in that the run details star now updates when clicking away and back to the run without a full page refresh, but I still would like that to happen immediately in the same view if possible.

2022-09-02 18:39 UTC, gbochora commented
> Favorite/unfavorite is working better in that the run details star now updates when clicking away and back to the run without a full page refresh, but I still would like that to happen immediately in the same view if possible.

Unfortunately, there is no easy way to make the live update work for Follow/Unfollow and Favorite/Unfavorite until we move entirely run API to GraphQL. I'll add Jira bugs and will fix them after API is migrated.

2022-09-02 19:01 UTC, Phrynobatrachus approved these changes
LGTM, thanks!

2022-09-02 19:13 UTC, trilopin commented on webapp/src/graphql/runs.graphql
> +query Run($id: String!) {
this is not really needed, but is not harmful too

2022-09-02 19:20 UTC, trilopin requested changes
Just a detail, you must force a refreshLHS when setting a new owner to force LHS to know about the change, and allow you to leave the run.

2022-09-05 06:20 UTC, gbochora commented
> Just a detail, you must force a refreshLHS when setting a new owner to force LHS to know about the change, and allow you to leave the run.

Nice catch! thanks.

2022-09-06 14:37 UTC, calebroseland approved these changes
Everything LGTM! Thank you for all the work on this. Really great stuff.

2022-09-06 14:37 UTC, merged