set a 5MB limit for all incoming requests
mattermost/mattermost-plugin-playbooks pull request #1463
Opened 2022-09-01 16:54 UTC by trilopin

#### Summary
Limit incoming requests to be 5MB large. Requests larger than that will fail.

mattermost-server limit request with more size than max_file_size, playbooks plugin 5MB.
We'll see if some endpoints need lower limits.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-46829

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~
- [X] Manually tested

2022-09-01 17:43 UTC, crspeller approved these changes

2022-09-02 06:43 UTC, gbochora approved these changes

2022-09-02 07:14 UTC, srkgupta requested changes
Thanks @trilopin. The issue is partially fixed now. I still see the client-side JS issue as shown in this screenshot. Can you please fix this as well.

2022-09-05 14:14 UTC, trilopin commented on server/sqlstore/migrations_utils.go
> +				RAISE NOTICE 'Ignoring ALTER TABLE statement. Column "%s" can not be changed to type %s in table "%s".';
@gbochora @lieut-data I followed the same pattern but I couldn't make this notice appear when I forced the failure (manually I could, programmatically I couldn't). 

should it be an error instead?

2022-09-06 18:27 UTC, lieut-data approved these changes
A handful of comments, but nothing strictly blocking. Nice work :)

2022-09-06 18:27 UTC, lieut-data commented on server/e2etest.config.json.sample
> +// Rename this file (and remove comments) to e2etest.config.json to force some server settings to e2e engine
0/5, but wondering if we should just force these on all the time? The way I /think/ I did it in my PR, the logs only get spit out if the test fails, and it's likely you want these in that case all the time.

2022-09-06 18:27 UTC, lieut-data commented on server/sqlstore/migrations_utils.go
> +				RAISE NOTICE 'Ignoring ALTER TABLE statement. Column "%s" can not be changed to type %s in table "%s".';
If an error, playbooks as a product can't be upgraded: is it worth leaving things as-is in such a case instead?

2022-09-06 18:27 UTC, lieut-data commented on server/sqlstore/store.go
> +const MaxJSONLength = 65535
Do we need to export this, or could it be internal only? (Also, propose we raise to something like 256kb to avoid artificially low limits.)

2022-09-07 05:27 UTC, trilopin commented on server/sqlstore/migrations/future/postgres/0.57.up.sql
> +ALTER TABLE ir_incident ALTER COLUMN id TYPE varchar(26);
good idea 👍🏽

2022-09-07 08:05 UTC, gbochora reviewed
Great work @trilopin! I left a few comments. Also, the table `IR_ViewedChannel` is missing in migration; was it intentional?

2022-09-07 09:06 UTC, trilopin commented on server/sqlstore/migrations.go
> +				},
yep, it's a typo. channelid was already a varchar(26)

2022-09-07 09:53 UTC, trilopin commented
> the table `IR_ViewedChannel` is missing in migration; was it intentional?
not intentional, I added it and will be pushed soon. Nice catch @gbochora

2022-09-07 12:39 UTC, trilopin commented on server/sqlstore/migrations_utils.go
> +				RAISE NOTICE 'Ignoring ALTER TABLE statement. Column "%s" can not be changed to type %s in table "%s".';
> If an error, playbooks as a product can't be upgraded: is it worth leaving things as-is in such a case instead?

unless we print and return nil as error inside the migration

2022-09-07 12:44 UTC, trilopin commented
Feedback addressed:

@gbochora 
- added missing field migration to ir_incident
- added missing table migration
- fixed typo at ir_channelaction

@lieut-data 
- created placeholder MySQL migrations to be more explicit (future morph)
- increased JSON limit to 256KB and graphql request size to 300KB (It was at 100KB) 

@srkgupta 
- added test & error handling for playbook update

2022-09-07 13:46 UTC, gbochora commented
Looks great! 🎉 thanks @trilopin

2022-09-07 14:17 UTC, srkgupta approved these changes
Thanks @trilopin. Changes LGTM

2022-09-08 07:48 UTC, merged