[MM-45662] Fix context dropdown closing when clicked
mattermost/mattermost-plugin-playbooks pull request #1467
Opened 2022-09-06 16:23 UTC by MusabShakeel576

#### Summary
Resolved task filter context dropdown closing when checked and unchecked.

Now context dropdown is closed only when clicking on parent element, clicking outside the menu, or if dropdown parent appears on hover then hovering outside of the element.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/20821

#### Checklist
- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-09-06 16:23 UTC, mattermod commented
Hello @MusabShakeel576,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-09-06 16:33 UTC, MusabShakeel576 commented
/check-cla

2022-09-06 20:18 UTC, Phrynobatrachus requested changes
Copying my comment from Dev: Playbooks:

I think your solution is too general. The failures are from usages of the Dot Menu that your PR affects, but should not. The plainest way I see is to add a new prop to `Dot_Menu` that you pass to its usage in `Multi_Checkbox`, and then make your original change conditional on that.

2022-09-06 20:18 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +            cy.findByTestId('run-header-section').findByTestId('dropdownmenu').should('be.visible');
This should not be necessary, for example.

2022-09-07 16:55 UTC, MusabShakeel576 commented on tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
> +            cy.findByTestId('run-header-section').findByTestId('dropdownmenu').should('be.visible');
alright, removed [056946c](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1467/commits/056946c2e9d193da79f560ada6f07ae14e01e8fa#diff-60962e12ef06c5823b22865dfa586ffbf548aeb7e12548efd361c0b48a8c9678)

2022-09-07 17:10 UTC, calebroseland requested changes
I think the prop approach is great solution, but maybe it could be named according to the behavior?

2022-09-07 17:10 UTC, calebroseland commented on webapp/src/components/dot_menu.tsx
> +                    return isMultiCheckbox ? null : setOpen(false);
This return ternary feels a little odd to me. Could we just do an if block?

```suggestion
                   if (closeOnClick) {
                       setOpen(false);
                   }
```

2022-09-07 18:24 UTC, MusabShakeel576 commented on webapp/src/components/dot_menu.tsx
> +                    return isMultiCheckbox ? null : setOpen(false);
resolved [f5bf468](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1467/commits/f5bf468b7f99baa539993767d8dc49f7436ab0a5#diff-cd9f22e13bba5ded76a48757c8918b7ca3e7dd1dc01cd055ba7543d9a64b522bR134-R136)

2022-09-07 18:25 UTC, MusabShakeel576 commented on webapp/src/components/dot_menu.tsx
> +    isMultiCheckbox,
resolved [f5bf468](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1467/commits/f5bf468b7f99baa539993767d8dc49f7436ab0a5#diff-cd9f22e13bba5ded76a48757c8918b7ca3e7dd1dc01cd055ba7543d9a64b522bR81)

2022-09-07 18:34 UTC, Phrynobatrachus approved these changes
Nice. The failing E2E is unrelated, it's something I need to look at separately. Thank you for the contribution!

2022-09-07 18:53 UTC, calebroseland approved these changes
Awesome, thanks @MusabShakeel576!

2022-09-07 18:55 UTC, merged