play with logger http
mattermost/mattermost-plugin-playbooks pull request #1483
Opened 2022-09-13 15:00 UTC by trilopin

## Summary

Example output
```
➜  mattermost-server git:(master) tail -f mattermost.log | jq -c 'select(.msg=="Handled HTTP request") | {ts: .timestamp, method: .method, url: .url, status: .status, time: .time, gql: .gql_operation}'
{"ts":"2022-09-13 16:57:34.559 +02:00","method":"GET","url":"/api/v0/runs/an9ifn1fsf8upyf7ixgq8ym3po/status-updates","status":"200","time":"100","gql":null}
{"ts":"2022-09-13 16:57:34.561 +02:00","method":"POST","url":"/api/v0/query","status":"200","time":"361","gql":"PlaybookLHS"}
{"ts":"2022-09-13 16:57:34.561 +02:00","method":"GET","url":"/api/v0/runs/an9ifn1fsf8upyf7ixgq8ym3po/metadata","status":"200","time":"100","gql":null}
{"ts":"2022-09-13 16:57:34.835 +02:00","method":"POST","url":"/api/v0/query","status":"200","time":"251","gql":"PlaybookLHS"}
{"ts":"2022-09-13 16:58:27.221 +02:00","method":"POST","url":"/api/v0/query","status":"200","time":"250","gql":"PlaybookLHS"}
{"ts":"2022-09-13 16:58:34.495 +02:00","method":"POST","url":"/api/v0/query","status":"200","time":"276","gql":"PlaybookLHS"}
{"ts":"2022-09-13 16:59:04.712 +02:00","method":"GET","url":"/api/v0/runs/zry53s7b578bmm3ktryjzo88cw","status":"200","time":"76","gql":null}
{"ts":"2022-09-13 16:59:04.769 +02:00","method":"GET","url":"/api/v0/my_categories/favorites?item_id=zry53s7b578bmm3ktryjzo88cw&team_id=mgxhrprsjbrx9yqsoacrqqkgro&type=r","status":"200","time":"30","gql":null}
{"ts":"2022-09-13 16:59:04.786 +02:00","method":"GET","url":"/api/v0/playbooks/fcoemjoja7dk8gddsabqgjn6re","status":"200","time":"47","gql":null}
{"ts":"2022-09-13 16:59:04.800 +02:00","method":"POST","url":"/api/v0/telemetry/run/zry53s7b578bmm3ktryjzo88cw","status":"204","time":"59","gql":null}
{"ts":"2022-09-13 16:59:04.806 +02:00","method":"GET","url":"/api/v0/runs/zry53s7b578bmm3ktryjzo88cw/status-updates","status":"200","time":"66","gql":null}
{"ts":"2022-09-13 16:59:04.830 +02:00","method":"GET","url":"/api/v0/runs/zry53s7b578bmm3ktryjzo88cw/metadata","status":"200","time":"91","gql":null}
{"ts":"2022-09-13 16:59:05.671 +02:00","method":"GET","url":"/api/v0/runs/n3tdab7uxpbdbf8jdrd75gj3do","status":"200","time":"50","gql":null}
{"ts":"2022-09-13 16:59:05.719 +02:00","method":"GET","url":"/api/v0/my_categories/favorites?item_id=n3tdab7uxpbdbf8jdrd75gj3do&team_id=mgxhrprsjbrx9yqsoacrqqkgro&type=r","status":"200","time":"32","gql":null}
{"ts":"2022-09-13 16:59:05.750 +02:00","method":"POST","url":"/api/v0/telemetry/run/n3tdab7uxpbdbf8jdrd75gj3do","status":"204","time":"62","gql":null}
{"ts":"2022-09-13 16:59:05.750 +02:00","method":"GET","url":"/api/v0/runs/n3tdab7uxpbdbf8jdrd75gj3do/status-updates","status":"200","time":"61","gql":null}
{"ts":"2022-09-13 16:59:05.756 +02:00","method":"GET","url":"/api/v0/runs/n3tdab7uxpbdbf8jdrd75gj3do/metadata","status":"200","time":"67","gql":null}
{"ts":"2022-09-13 16:59:07.204 +02:00","method":"POST","url":"/api/v0/query","status":"200","time":"74","gql":"Playbook"}
{"ts":"2022-09-13 16:59:07.228 +02:00","method":"GET","url":"/api/v0/stats/playbook?playbook_id=ktf6b7wx1tnz8nnzgj7q3kwqmh","status":"200","time":"98","gql":null}
{"ts":"2022-09-13 16:59:07.288 +02:00","method":"GET","url":"/api/v0/runs/owners?team_id=","status":"200","time":"8","gql":null}
{"ts":"2022-09-13 16:59:07.309 +02:00","method":"GET","url":"/api/v0/playbooks/ktf6b7wx1tnz8nnzgj7q3kwqmh/autofollows","status":"200","time":"29","gql":null}
{"ts":"2022-09-13 16:59:07.325 +02:00","method":"POST","url":"/api/v0/telemetry/playbook/ktf6b7wx1tnz8nnzgj7q3kwqmh","status":"204","time":"45","gql":null}
```
## Ticket Link
Nope

#### Checklist
- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-09-15 14:00 UTC, lieut-data requested changes
Love the incremental improvements! Just one comment below for discussion.

2022-09-25 14:19 UTC, trilopin commented on server/api/graphql.go
> +	w.Header().Add("X-GQL-Operation", params.OperationName)
to avoid the header, we'd have to read the body, parse the json and recreate again the body in order to keep it ready for the actual handler. 

Something like 
```go
if r.URL.Path == "/api/v0/query" {
	body, err := ioutil.ReadAll(r.Body)
	if err != nil {
		logger.WithError(err).Error("Unable to read body")
		return
	}
	r.Body.Close()
	r.Body = ioutil.NopCloser(bytes.NewBuffer(body))
	params := struct {
		OperationName string `json:"operationName"`
	}{}
	if err := json.Unmarshal(body, &params); err == nil && params.OperationName != "" {
		logger = logger.WithField("gql_operation", params.OperationName)
	}
}

logger.Debug("Received HTTP request")
```

The previous code seems dirtier than the header trick, but you may have a cleaner idea about the double body read

2022-10-03 19:54 UTC, lieut-data approved these changes

2022-10-03 19:54 UTC, lieut-data commented on server/api/graphql.go
> +	w.Header().Add("X-GQL-Operation", params.OperationName)
Oh, I understand better now -- the problem you're solving is to escalate the operation name /up/ to where we log the final event for the handler. I had only been thinking about passing that metadata to loggers downstream from this code.

I better appreciate your original approach, and my only remaining thought would be, should we "write" the headers to the `http.Request` instead, to avoid sending that back to the client unnecessarily?

2022-10-04 07:15 UTC, trilopin commented on server/api/graphql.go
> +	w.Header().Add("X-GQL-Operation", params.OperationName)
very good point, I started removing the response header but makes more sense to use the request to communicate the different middlewares.

2022-10-04 07:25 UTC, trilopin commented on server/api/logger.go
> +			logger = logger.WithField("gql_operation", gqlOp)
@srkgupta can we dismiss this alert?

2022-10-04 18:33 UTC, trilopin commented
/update-branch

2022-10-06 16:48 UTC, srkgupta approved these changes
@trilopin dismissed the CodeQL alert as False Positive. The changes LGTM.

2022-10-07 07:18 UTC, merged