GH-20841 - Enable/Disable run status updates
mattermost/mattermost-plugin-playbooks pull request #1494
Opened 2022-09-23 18:30 UTC by rolwin100

## Summary

- added apis to enable/disable status run
- added button for enabling and disabling in the ui

## Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/20841

## Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-09-23 18:30 UTC, mattermod commented
Hello @rolwin100,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-24 10:34 UTC, rolwin100 commented
@gbochora Pla have a look at the PR and suggest few improvements if necessary

2022-09-28 16:50 UTC, trilopin requested changes
Hey @rolwin100 ,

Thanks a lot for all the energy you put in this PR.

There are some points that need revision to be ready but it's basically remove code and make a couple of points simpler.

2022-09-28 16:50 UTC, trilopin commented on webapp/src/types/playbook_run.ts
> +    return playbookRun.status_update_enabled;
is this function really needed? Why not using directly the field?

2022-09-28 16:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
> +        summaryTitle = formatMessage({defaultMessage: 'Run status update enabled by {name}'}, {name: props.event.subject_display_name});
```suggestion
        summaryTitle = formatMessage({defaultMessage: 'Run status updates enabled by {name}'}, {name: props.event.subject_display_name});
```

2022-09-28 16:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
> +        summaryTitle = formatMessage({defaultMessage: 'Run status update disabled by {name}'}, {name: props.event.subject_display_name});
```suggestion
        summaryTitle = formatMessage({defaultMessage: 'Run status updates disabled by {name}'}, {name: props.event.subject_display_name});
```

2022-09-28 16:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/enable_disable_run_status_update.tsx
> +            refreshLHS();
Why do we need to refreshLHS? enable/disable status updates should not change at all LHS, so I don't think we have to refresh it.

2022-09-28 16:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/enable_disable_run_status_update.tsx
> +        const confirmationMessage = formatMessage({defaultMessage: 'Are you sure you want to {status} status update for this run?'}, {status});
This approach is correct for English but could be problematic for other languages. I think you should do two separate strings for enabling and disabling (with no variables interpolated) and then use the right one using a ternary operator.

2022-09-28 16:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/controls.tsx
> +export const DisableRunStatusUpdateMenuItem = (props: {playbookRun: PlaybookRun, role: Role}) => {
These two components are almost the same. what if you merge them and make handle some strings with a ternary operator?

2022-09-28 16:50 UTC, trilopin commented on server/api/playbook_runs.go
> +	_, _ = w.Write([]byte(`{"status":"OK"}`))
I think that there's no need of this write operation. When needed it's better to use ReturnJSON to force setting the right headers.

2022-09-28 16:50 UTC, trilopin commented on server/api/playbook_runs.go
> +	_, _ = w.Write([]byte(`{"status":"OK"}`))
same, line not needed

2022-09-28 16:50 UTC, trilopin commented on server/api/playbook_runs.go
> +	playbookRunRouterAuthorized.HandleFunc("/status-update/disable", handler.disableStatusUpdate).Methods(http.MethodPut)
what if we have only add one endpoint with the desired value?

2022-09-28 16:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +	if enable == false {
```suggestion
	if !enable {
```

2022-09-28 16:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +	statusUpdateDisabled       messageType = "status update disabled"
these values are unused

2022-09-28 16:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +	s.RemoveReminder(playbookRunID)
nice! 👍🏽

2022-09-28 16:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +	message := fmt.Sprintf("@%s %s the status update for this run", user.Username, statusUpdate)
Not sure if we want to send this message, but if we want it must be a translatable string.

[example of how to use translations at server](https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/app/playbook_run_service.go#L2933)

2022-09-28 16:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +		if playbookRunToModify.RetrospectiveEnabled && playbookRunToModify.RetrospectivePublishedAt == 0 {
I imagine that this piece comes from the finish-run code, but we shouldn't invoke any code related to retrospectives here. Enabling/Disabling status updates is independent of retrospectives.

![Screenshot 2022-09-28 at 18 42 08](https://user-images.githubusercontent.com/4096774/192839988-2d1784e7-e8ae-4a10-bc99-dd872e52662b.png)

2022-09-28 16:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +	message := fmt.Sprintf("@%s %s the status update for this run", user.Username, statusUpdate)
```suggestion
	message := fmt.Sprintf("@%s %s the status updates for this run", user.Username, statusUpdate)
```

2022-09-28 16:50 UTC, trilopin commented on server/api/playbook_runs.go
> +	playbookRunRouterAuthorized.HandleFunc("/status-update/disable", handler.disableStatusUpdate).Methods(http.MethodPut)
you will need the withContext wrapper to add context as the first parameter of the endpoint (latest changes in log management).
The you'll have to get from there the logger to inject it into the handleError func (second parameter)

```suggestion
	playbookRunRouterAuthorized.HandleFunc("/status-update/disable", withContext(handler.disableStatusUpdate)).Methods(http.MethodPut)
```

2022-10-03 23:46 UTC, rolwin100 commented on server/api/playbook_runs.go
> +	playbookRunRouterAuthorized.HandleFunc("/status-update/disable", handler.disableStatusUpdate).Methods(http.MethodPut)
@trilopin I had thought about this but again we need to add validation to take only enable and disable and then do conditional check which will increase slight complexity and not much line of code difference.

2022-10-03 23:59 UTC, rolwin100 commented on webapp/src/types/playbook_run.ts
> +    return playbookRun.status_update_enabled;
not sure! The reason I did this because I noticed other place people have done this so it motivated me to write this function.

2022-10-04 00:00 UTC, rolwin100 commented on webapp/src/types/playbook_run.ts
> +    return playbookRun.status_update_enabled;
Should I remove it

2022-10-04 11:23 UTC, gbochora reviewed
Thanks a lot, @rolwin100, for the huge amount of work. I've left a few comments.

2022-10-04 11:23 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
> +    console.log(props.event.event_type);
I'm assuming this was for debugging purposes, do we still need it?

2022-10-04 11:57 UTC, trilopin commented on webapp/src/types/playbook_run.ts
> +    return playbookRun.status_update_enabled;
IMHO if it is a function, I'd expect to have more complex behavior (and that's not the case). 

I would use directly the property.

2022-10-04 17:11 UTC, rolwin100 commented on server/app/playbook_run_service.go
> +	if err = s.store.UpdatePlaybookStatusUpdateEnable(playbookRunID, enable); err != nil {
It's needed right since we are updating a single field I didn't find a function doing this also other functionality also it takes care. Please let me know your thoughts.

2022-10-04 17:13 UTC, rolwin100 commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
> +    console.log(props.event.event_type);
sorry

2022-10-04 17:14 UTC, rolwin100 commented on server/app/playbook_run_service.go
> +	}
can you add more detail on this what needs to be done

2022-10-04 17:24 UTC, rolwin100 commented on webapp/src/types/playbook_run.ts
> +    return playbookRun.status_update_enabled;
okay will change it then

2022-10-05 05:04 UTC, rolwin100 commented on server/app/playbook_run_service.go
> +	if err = s.store.UpdatePlaybookStatusUpdateEnable(playbookRunID, enable); err != nil {
if you see `UpdatePlaybookRun` making a complete update of all the values and currently that function is not having a `StatusUpdateEnabled` field for an update I may need to modify that function as well so I didn't use it. Let me know your thoughts. I feel we can proceed because this function will be a bit faster than the `UpdatePlaybookRun`. @gbochora

2022-10-05 05:22 UTC, rolwin100 commented on server/app/playbook_run_service.go
> +	if err = s.store.UpdatePlaybookStatusUpdateEnable(playbookRunID, enable); err != nil {
if you notice `FinishPlaybookRun` even this function is the same I referred this and made the change

2022-10-05 14:23 UTC, gbochora commented on server/app/playbook_run_service.go
> +	}
When we want to disable status updates:
- we need to remove the scheduled reminder. 
- we don't need to reset the reminder timer because it only sets the `run.PreviousReminder's` value to zero.  `run.PreviousReminder's` value is never used when status updates are disabled, so no need to set it to zero.

We don't need to do anything when we want to enable status updates. 

So my suggestion is:
```suggestion
	if !enable {
		s.RemoveReminder(playbookRunID)
	}
```

2022-10-07 08:41 UTC, trilopin commented on server/api/playbook_runs.go
> +	playbookRunRouterAuthorized.HandleFunc("/status-update/disable", handler.disableStatusUpdate).Methods(http.MethodPut)
There's no need for additional checks. You could create one endpoint that accepts a JSON with a bool parameter which is passed to the service function `UpdatePlaybookRunStatusUpdate`.

I see a lot of value in having less API surface with deeper endpoints.

2022-10-07 09:17 UTC, rolwin100 commented on server/api/playbook_runs.go
> +	playbookRunRouterAuthorized.HandleFunc("/status-update/disable", handler.disableStatusUpdate).Methods(http.MethodPut)
okay you mean I need to create an endpoint `/status-update` and then pass ` {statusEnabled: boolean}` in the body right?

2022-10-07 11:52 UTC, gbochora commented on assets/i18n/en.json
> +    "translation": "@{{.Username}} %{{.statusUpdate}} the status update for this run"
This text also could be problematic to translate into other languages. I think it would be better to have two strings:
1. "@{{.Username}} enabled the status update for this run"
2. "@{{.Username}} disabled the status update for this run"

2022-10-07 12:07 UTC, gbochora commented on server/app/playbook_run_service.go
>  	if s.licenseChecker.RetrospectiveAllowed() {
I think you removed the license check code from the `FinishPlaybookRun` function instead of the `UpdatePlaybookRunStatusUpdate`

2022-10-07 12:13 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
> +                />
We can have a single menu item here that handles both enable and disable based on the current state. You can see `FollowRunMenuItem` as an example.

2022-10-07 12:18 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/controls.tsx
> +export const EnableDisableRunStatusUpdateMenuItem = (props: {playbookRun: PlaybookRun, role: Role, status: 'enable' | 'disable'}) => {
You don't need the `status` parameter here; you can rely on the `playbookRun.status_update_enabled`

2022-10-08 02:58 UTC, rolwin100 commented
@trilopin @gbochora I have made all the changes suggested I guess we can call it a day guys.

2022-10-11 08:29 UTC, trilopin requested changes

2022-10-11 08:29 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
> +        iconClass = 'icon icon-flag-outline';
maybe ClockOutlineIcon / icon-clock-outline?

2022-10-11 08:29 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/enable_disable_run_status_update.tsx
> +        const confirmTitle = status ? formatMessage({defaultMessage: 'Confirm enable status update'}) : formatMessage({defaultMessage: 'Confirm disable status update'});
```suggestion
        const confirmTitle = status ? formatMessage({defaultMessage: 'Confirm enable status updates'}) : formatMessage({defaultMessage: 'Confirm disable status updates'});
```

2022-10-11 08:29 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/enable_disable_run_status_update.tsx
> +        const confirmationMessage = status ? formatMessage({defaultMessage: 'Are you sure you want to enable status update for this run?'}) : formatMessage({defaultMessage: 'Are you sure you want to
```suggestion
        const confirmationMessage = status ? formatMessage({defaultMessage: 'Are you sure you want to enable status updates for this run?'}) : formatMessage({defaultMessage: 'Are you sure you want to disable status updates for this run?'});
```

2022-10-11 08:29 UTC, trilopin commented on webapp/src/client.ts
> +export async function runStatusUpdate(playbookRunId: string, status_enabled: boolean) {
naming nit, what do you think of `toggleRunStatusUpdates` ?

2022-10-11 08:29 UTC, trilopin commented on server/sqlstore/playbook_run.go
> +func (s *playbookRunStore) UpdatePlaybookStatusUpdateEnable(playbookRunID string, enable bool) error {
we could extend `UpdatePlaybookRun` instead of creating a new method

2022-10-12 14:03 UTC, gbochora requested changes
I think you have missed one of my comments from the previous review. In the `playboook_run_service.go` file, you have removed the license check(`s.licenseChecker.RetrospectiveAllowed()`) from the the`FinishPlaybookRun` function and copied it into the `ToggleStatusUpdates` function. 
We should revert this particular change, the `ToggleStatusUpdates` function should not make any license check.

2022-10-13 06:48 UTC, gbochora approved these changes
Looks great! Thanks a lot for your effort @rolwin100

2022-10-13 07:04 UTC, rolwin100 commented
> Looks great! Thanks a lot for your effort @rolwin100

thank you so much

2022-10-13 08:48 UTC, rolwin100 commented
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1494#discussion_r991928052

@trilopin regarding this. I don't want to play around with this, the reason is simple. In the database, we are storing this field as StatusUpdateEnabled. changing it will introduce confusion for sure. Also this was already present and is being used by many other api's we may not be able to change this at this point of time.

2022-10-17 07:40 UTC, trilopin approved these changes
THanks a lot for all your time @rolwin100 , this is a really valuable addition to the Run Details Page.

2022-10-17 07:54 UTC, rolwin100 commented
@amyblais this PR is safe to be merged can we close this

2022-10-17 08:31 UTC, trilopin commented
> @amyblais this PR is safe to be merged can we close this

@rolwin100 I labeled it for UX review, please wait a bit more for that. I'll merge it when it's ready.

2022-10-20 08:58 UTC, abhijit-singh requested changes
Thanks @trilopin for looping me in and thank you @rolwin100 for the awesome work on this! I have a couple of change requests:
- For the confirmation modal, can we change the CTA of the button to `Enable updates` and `Disable updates` for the respective case instead of `Ok`? 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/14369607/196904188-8aaeed0c-e9d1-4a01-a03d-7b75674734c0.png">

- In the dropdown, the icon for the enable/disable status update menu item needs to be changed to [`icon-update`](https://mattermost.github.io/compass-icons/) instead of the current clock icon. 
<img width="139" alt="image" src="https://user-images.githubusercontent.com/14369607/196904076-7d71ed9a-fd43-4f1d-9323-89478b8c778c.png">

2022-10-25 07:29 UTC, rolwin100 commented
@abhijit-singh I have made the changes.

2022-10-25 10:33 UTC, abhijit-singh approved these changes
Perfect! 💯 

Thank you @rolwin100!

2022-10-25 11:41 UTC, merged