Add error checking in insights API
mattermost/mattermost-plugin-playbooks pull request #1496
Opened 2022-09-26 16:34 UTC by cyrilzhang-mm

## Summary

Change some function calls in accordance with the changes in https://github.com/mattermost/mattermost-server/pull/21048

## Ticket Link

[Jira ticket](https://mattermost.atlassian.net/browse/MM-45052?focusedCommentId=134358)

## Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-09-29 15:58 UTC, BenCookie95 commented on server/api/playbooks.go
> +		h.HandleError(w, c.logger, err)
Why is this one `HandleError` and the other one `HandleErrorWithCode`? I think `HandleErrorWithCode` is the correct function to use

2022-09-29 15:58 UTC, BenCookie95 requested changes
Just one small comment!

2022-09-29 16:24 UTC, BenCookie95 commented on server/api/playbooks.go
> +		h.HandleError(w, c.logger, err)
I think we can leave 672 alone because `handleError` throws a `StatusInternalServerError` which is correct

2022-09-30 04:19 UTC, plant99 requested changes

2022-09-30 04:19 UTC, plant99 commented on server/api/playbooks.go
> +	startTime, err := model.StartOfDayForTimeRange(timeRange, timezone)
[This line](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1496/files#diff-b55bb9e04426298a406a87bf3b9e243d8f0903ae4a24af04f89a6cd37fd66293R719) looks great now, can we use the same function arguments here too?

Or does `HandleErrorWithCode` default to 400 status code?

2022-09-30 15:34 UTC, cyrilzhang-mm commented on server/api/playbooks.go
> +	startTime, err := model.StartOfDayForTimeRange(timeRange, timezone)
Yes, you're right.

2022-10-03 03:05 UTC, plant99 approved these changes
Looks good!

2022-10-03 14:14 UTC, BenCookie95 approved these changes

2022-10-03 15:32 UTC, BenCookie95 commented
@crspeller Any idea why the pipeline isn't picking up mm-server changes from it's corresponding branch? https://github.com/mattermost/mattermost-server/pull/21048. Focalboard pipeline is passing, https://github.com/mattermost/focalboard/pull/3876

2022-10-03 15:34 UTC, crspeller commented
@Phrynobatrachus Is our CI setup to do pick up a server branch?

2022-10-03 15:39 UTC, Phrynobatrachus commented
It's not. I'll try to get something setup this afternoon.

2022-10-03 18:44 UTC, Phrynobatrachus commented
Some DB tests failed with:

```
server/api/playbooks.go:660:26: undefined: model.GetStartOfDayForTimeRange
server/api/playbooks.go:717:26: undefined: model.GetStartOfDayForTimeRange
```

Does the plugin's server dependency need to be bumped once the server PR is merged?

2022-10-12 17:23 UTC, BenCookie95 approved these changes

2022-10-17 05:57 UTC, plant99 commented
> Does the plugin's server dependency need to be bumped once the server PR is merged?

Yes please note @cyrilzhang-mm .

2022-10-17 05:58 UTC, plant99 approved these changes

2022-10-25 14:26 UTC, cyrilzhang-mm commented
/update-branch

2022-10-27 14:16 UTC, Phrynobatrachus approved these changes

2022-10-27 14:16 UTC, merged