[MM-21265] Checkbox to show/hide skipped tasks
mattermost/mattermost-plugin-playbooks pull request #1513
Opened 2022-10-12 15:20 UTC by akhil-ghatiki

## Summary

Introduce a Show skipped tasks, defaulting on, that allows the user to optionally hide those tasks when filtering the checklists. It has same persistence semantics as Show checked tasks, meaning not remembered after a page reload. New option is shown just below the existing Show checked tasks option below.

## Ticket Link

  Fixes: https://github.com/mattermost/mattermost-server/issues/21265

## Checklist
- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-10-12 15:20 UTC, mattermod commented
Hello @akhil-ghatiki,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-10-12 16:39 UTC, lieut-data commented
@akhil-ghatiki, to expedite design review, could I trouble you for a screenshot of this in play?

2022-10-12 17:11 UTC, akhil-ghatiki commented
> @akhil-ghatiki, to expedite design review, could I trouble you for a screenshot of this in play?

@lieut-data I had trouble running the application on my machine (mac). So, I made this PR based on the code understanding

2022-10-12 17:34 UTC, lieut-data commented
Oh, no, @akhil-ghatiki! That's unfortunate -- can we help you sort those deployment issues? It /should/ be as simple as running `make deploy` from this repository, assuming you have already have a server and webapp running and have enabled plugin uploads. If not, I'd love to fix whatever is complicating things for you :)

2022-10-12 17:50 UTC, akhil-ghatiki commented
> Oh, no, @akhil-ghatiki! That's unfortunate -- can we help you sort those deployment issues? It /should/ be as simple as running `make deploy` from this repository, assuming you have already have a server and webapp running and have enabled plugin uploads. If not, I'd love to fix whatever is complicating things for you :)

ah ! Let me retry that. I was not using `make deploy`

2022-10-20 08:40 UTC, gbochora requested changes
Thanks, @akhil-ghatiki; looks good! Just one thing to fix, the filter option value should be `skipped`.

2022-10-20 08:40 UTC, gbochora commented on webapp/src/components/rhs/rhs_checklist_list.tsx
> +            value: 'checked',
```suggestion
            value: 'skipped',
```

2022-10-20 09:06 UTC, abhijit-singh requested changes
Thanks @akhil-ghatiki!

I'm afraid it's not working as expected. I'm unable to toggle the `show skipped tasks` filter. 
![2022-10-20 14 35 07](https://user-images.githubusercontent.com/14369607/196906260-04bef858-0530-41f5-9349-e3ffc4c7fb77.gif)

2022-10-26 13:08 UTC, gbochora approved these changes

2022-10-26 13:09 UTC, gbochora commented
@abhijit-singh Fixed the` show skipped tasks` toggle issue.

2022-10-26 16:23 UTC, iomodo approved these changes
LGTM!

2022-10-27 08:27 UTC, abhijit-singh approved these changes
💯

2022-10-27 10:48 UTC, merged