[MM-46382] Make convert to private playbook more prominent
mattermost/mattermost-plugin-playbooks pull request #1517
Opened 2022-10-17 15:20 UTC by cannalee90

## Summary

- Add convert to playbook private menu in the dropdown
- Create custom hook for converting playbook private 
- Apply custom hook for playbook access modal for converting private

## Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/21184
JIRA: https://mattermost.atlassian.net/browse/MM-46382

## Checklist
- [x] Telemetry updated
- [x] Unit tests updated(everything except formatted_duration.test.tsx because of i18n issue)

2022-10-17 15:20 UTC, mattermod commented
Hello @cannalee90,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-18 10:28 UTC, cannalee90 commented
gonna fix it asap

2022-10-20 18:09 UTC, crspeller requested changes
Thanks for the contribution!

2022-10-20 18:09 UTC, crspeller commented on webapp/src/components/backstage/convert_private_playbook_modal.tsx
> +const useConfirmPlaybookConvertPrivateModal = ({playbookId, refetch}: Props): ConfirmPlaybookConvertPrivateReturn => {
I like that you pulled this out from the access modal. Could we update the usage there?

2022-10-20 18:09 UTC, crspeller commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +                            telemetryEventForPlaybook(playbook.id, 'playbook_makeprivate');
I think we forgot to actually open the modal.

2022-10-20 18:09 UTC, crspeller commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +                        <FormattedMessage defaultMessage='Convert to private playbook'/>
We probably want an icon here. @abhijit-singh Can you provide an icon recommendation?

2022-10-21 10:55 UTC, cannalee90 commented on webapp/src/components/backstage/convert_private_playbook_modal.tsx
> +const useConfirmPlaybookConvertPrivateModal = ({playbookId, refetch}: Props): ConfirmPlaybookConvertPrivateReturn => {
So are you suggesting to make change to use this hook  for access modal?

2022-10-21 15:29 UTC, cannalee90 commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +                            telemetryEventForPlaybook(playbook.id, 'playbook_makeprivate');
I just fix it

2022-10-21 15:42 UTC, crspeller commented on webapp/src/components/backstage/convert_private_playbook_modal.tsx
> +const useConfirmPlaybookConvertPrivateModal = ({playbookId, refetch}: Props): ConfirmPlaybookConvertPrivateReturn => {
Exactly, so we are using the same code in both places.

2022-10-25 10:36 UTC, abhijit-singh commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +                        <FormattedMessage defaultMessage='Convert to private playbook'/>
The lock-outline icon should work here 
<img width="157" alt="image" src="https://user-images.githubusercontent.com/14369607/197751969-0074e326-bd79-44d7-aa81-bff877427d2b.png">

2022-10-25 16:16 UTC, cannalee90 commented on webapp/src/components/backstage/playbook_editor/controls.tsx
> +                        <FormattedMessage defaultMessage='Convert to private playbook'/>
I added icon-lock-outline icon!

2022-10-25 16:22 UTC, cannalee90 commented
@crspeller Hi. As you suggested I just apply my custom hook for playbook access modal but there is a problem. If I convert it to private access modal, the private link I just clicked not disappeared even though lock-icon appeared in background.

The reason why it happed it that the playbook object that used in access-modal is not same as the one that I used in the custom hook. so I just passed the updater function to solve this problem. If you have any other idea please give me a hint for that

Thank you!

2022-10-25 20:07 UTC, crspeller approved these changes
@cannalee90 That's fine for now. Thanks!

2022-10-26 18:33 UTC, lieut-data approved these changes
Super slick! Thanks, @cannalee90 :)

2022-10-27 08:34 UTC, abhijit-singh approved these changes
Looks good, thanks @cannalee90!

2022-10-28 17:08 UTC, merged

2023-01-05 18:51 UTC, jordanafung commented
Hi @cannalee90 
You were selected as one of our Top Contributors for Hacktoberfest!
Please fill out [this form](https://docs.google.com/forms/d/11pLB3pF1CmOslYqHr7c7bxFWU6QAEAJuiaKgHD1vJtg) to select your swag as thanks!
Thank you for all you do and for making Mattermost even better!