Gh 1507 pb run actions joinleave
mattermost/mattermost-plugin-playbooks pull request #1518
Opened 2022-10-17 15:33 UTC by trilopin

## Summary
Add actions to playbook and run to:
- create a channel member when a new participant joins the run
- remove a channel member when a existent participant leaves the run

Remove run participant creation/removal on channel join/leave events. This is a major change since we relied a lot on visiting public channels to join public runs (e2e).

Note that:
- runs `options.ParticipantOrFollowerID` sqlstore function has been updated to get the participant from the ir_run_participants table instead of the channel members.
- there was a problem that didn't redirect the user to the error page when trying to access a non-existent/forbidden Run (blank page instead of redir to error page).

### migrations
Two new fields have been created in playbooks and run table.
- Default values are the same as the current behavior (true=create/remove channel members)
- Migrations in morph style added to `future` folder

### UI
![CleanShot 2022-10-21 at 12 43 24](https://user-images.githubusercontent.com/4096774/197178624-9e9463d2-175f-4076-b8bf-f2d87ad772ff.gif)

At playbook editor side:
- added two new triggers
- moved channel triggers to a modal

At run detail page side:
- added two new triggers

### E2E
Many tests relied on adding users to the channel to let them join the run. Now that's changed.

New command `cy.apiAddUsersToRun(runID, userIDs)` to replace `cy.apiAddUserToChannel`.

### graphql
Updated playbook and run graphql schemas to handle the two new fields 

This task involves the migration of updateRunActions to existent graphql updateRun mutation.
Key points:
- old endpoint, service and test functions removed
- managed permissions RunMageProperties in updateRun endpoint unless the user changes only isFavorite (isFavorite should be a different mutation IMHO)
- same strategy as playbook with setmap to do the update, except that a step through the service has been forced to handle side tasks (like real time through WS). Even if it's just wrapper I would keep it and avoid resolver<->store direct calls. 
- tests done in graphql server e2e

### telemetry
- update run action event moved from server to frontend

## Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1507

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [X] Unit tests updated

2022-10-18 10:41 UTC, trilopin commented on server/main_test.go
> -		sapp.SetLogger(testLogger),
don't know why, but no-logger was back in the code

if you want to disable the e2e logging you should do `config.LogSettings.EnableConsole = model.NewBool(false)`in the code above instead of setting a no-logger

2022-10-20 15:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +	}
this code was done before by joining channel and being subscribed to userJoinedChannel hook. Since we removed the hook, we have to manually add the owner to the list of followers and participants

2022-10-20 18:58 UTC, crspeller requested changes
Nice work! I think we should get a @Phrynobatrachus pass on this. What do you think?

2022-10-20 18:58 UTC, crspeller commented on server/api/graphql_root_run.go
> +	// scalar updates
Nice! 😄

2022-10-20 18:58 UTC, crspeller commented on tests-e2e/cypress/support/plugin/api_commands.js
> +const doGraphqlQuery = (query, operationName, variables) => {
Helpful!

2022-10-20 18:58 UTC, crspeller commented on webapp/src/components/actions_modal_action.tsx
> +                {props.children ?? null}
Does it barf on undefined? Why do we need the `?? null`?

2022-10-20 18:58 UTC, crspeller commented on webapp/src/components/playbook_actions_modal.tsx
> +            messageOnJoinEnabled: welcomeMessageEnabled,
Do these values update immediately? I think you need to have local updated copies of these.

2022-10-20 18:58 UTC, crspeller commented on server/plugin.go
> -	p.playbookRunService.UserHasJoinedChannel(channelMember.UserId, channelMember.ChannelId, actorID)
We should remove these functions from the service as well.

2022-10-20 18:58 UTC, crspeller commented on server/app/playbook_run_service.go
> +	err = s.AddParticipants(playbookRun.ID, []string{playbookRun.OwnerUserID}, playbookRun.OwnerUserID)
These actually get added above in `addPlaybookRunUsers` I updated the name of that function to make a bit more sense in my PR: https://github.com/mattermost/mattermost-plugin-playbooks/pull/1521

2022-10-21 07:30 UTC, trilopin commented on webapp/src/components/playbook_actions_modal.tsx
> +            messageOnJoinEnabled: welcomeMessageEnabled,
> Nice work! I think we should get a @Phrynobatrachus pass on this. What do you think?

Agreed, I wanted to do a pure code review first but I do want @Phrynobatrachus to help here. 💯

2022-10-21 07:55 UTC, trilopin commented on server/app/playbook_run_service.go
> +	err = s.AddParticipants(playbookRun.ID, []string{playbookRun.OwnerUserID}, playbookRun.OwnerUserID)
the code you mention adds botUserID and RunOwner to the channel, but not the run. Since we broke that promotion channel->run we have to explicitly add them.

Should I move the new code I did inside the function to hold the member-creation for bot&owner in all needed places?

2022-10-21 07:56 UTC, trilopin commented
> I think we should get a @Phrynobatrachus pass on this. What do you think?


Agreed, I wanted to do a pure code review first but I do want @Phrynobatrachus to help here. 💯

2022-10-21 08:03 UTC, trilopin commented on webapp/src/components/actions_modal_action.tsx
> +                {props.children ?? null}
simplified, it wasn't needed

2022-10-21 08:05 UTC, trilopin commented on webapp/src/components/playbook_actions_modal.tsx
> +            messageOnJoinEnabled: welcomeMessageEnabled,
they update when modal is confirmed, onSave() internal handler

Local copies are saved in internal state

2022-10-21 18:51 UTC, gbochora approved these changes
Great work @trilopin! Looks good, I just left a few non-blocking comments.

2022-10-21 18:51 UTC, gbochora commented on webapp/src/components/playbook_actions_modal.tsx
> +    };
Should we add here setting `categoryName` and `categorizeChannelEnabled` states?

2022-10-21 18:51 UTC, gbochora commented on webapp/src/components/run_actions_modal.tsx
>      const onHide = () => {
The same is here. It would be better to reset `createChannelMemberEnabled` and `removeChannelMemberEnabled` states on hide.

2022-10-21 18:51 UTC, gbochora commented on webapp/src/components/playbook_actions_modal.tsx
> +        }
I think these state changes will not be applied immediately, and `updatePlaybook` will be called with old values.

2022-10-24 07:49 UTC, trilopin commented on webapp/src/components/playbook_actions_modal.tsx
> +        }
kept local state conditions + handled in var assignment

2022-10-24 07:52 UTC, trilopin commented on server/sqlstore/playbook.go
> +	// TOOD add new actions to numactions
nope, good catch

2022-10-24 08:14 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                it.skip('persists the category even if the toggle is off', () => {
oops, I forgot to remove the skip and fix this one. Thanks for noticing it.

2022-10-24 15:17 UTC, trilopin commented
merge blocked until https://github.com/mattermost/mattermost-plugin-playbooks/pull/1521 is merged (owner&invite-action management)

2022-10-25 13:51 UTC, crspeller commented on server/app/playbook_run_service.go
> +	err = s.AddParticipants(playbookRun.ID, []string{playbookRun.OwnerUserID}, playbookRun.OwnerUserID)
Of course! 😵‍💫
0/5 but that section is a bit confusing.

2022-10-25 17:26 UTC, Phrynobatrachus approved these changes
Awesome work, thanks for all of the test updates!

2022-10-26 13:36 UTC, gbochora approved these changes
Looks good! 🥳

2022-10-26 13:44 UTC, trilopin commented on server/app/playbook_run_service.go
> +	err = s.AddParticipants(playbookRun.ID, []string{playbookRun.OwnerUserID}, playbookRun.OwnerUserID)
I've renamed the method (again, sorry) and added the code for the Run membership.

2022-10-27 08:18 UTC, abhijit-singh approved these changes
Looks awesome @trilopin! One small request — The icon in the `Setup channel actions` button in the playbook outline seems too large. It should be 16px x 16 px and the button height should be 40 px as per the designs.

2022-10-27 12:42 UTC, merged