1413 add participants
mattermost/mattermost-plugin-playbooks pull request #1522
Opened 2022-10-20 08:06 UTC by gbochora

## Summary
This PR adds the `Add participants modal` that allows us to add multiple participants to the run.
Ignore the checkbox and text at the button of the modal. After merging [1518](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1518) modal will show the correct message.

https://user-images.githubusercontent.com/4368372/196892179-09074131-f64a-4641-aa7f-ceadffe53d77.mp4

## Ticket Link
https://github.com/mattermost/mattermost-plugin-playbooks/issues/1413

## Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-10-20 18:24 UTC, crspeller requested changes

2022-10-20 18:24 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
> +    useUpdateEffect(() => {
Could we maybe intercept the hide modal code instead of having an extra use effect here? `onExited`?

2022-10-20 18:24 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
> +                    checked={addToChannel}
I think we want to have a clean master. (especially when we move to being a product) Maybe we should comment out the unused parts?

2022-10-20 18:24 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/participants_selector.tsx
> +const ParticipantsSelector = (props: Props) => {
Why do we need our own ParticipantsSelector? Why can't we use the profile autocomplete directly? There is a bit of duplication here.

2022-10-21 06:18 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
> +    useUpdateEffect(() => {
Good point.

2022-10-21 09:44 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
> +export const useAddParticipants = (playbookRun: PlaybookRun) => {
I've done many times this pattern but recently it started to feel bad returning components inside hook. Shouldn't we better create a component with a hook inside?

2022-10-21 14:49 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run/participants_selector.tsx
> +const ParticipantsSelector = (props: Props) => {
I've reused profile autocomplete. The `ProfileAutocomplete` component seems a little more complex; maybe it's better to have a separate component. What do you think @crspeller @trilopin?

2022-10-21 19:23 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/participants_selector.tsx
> +const ParticipantsSelector = (props: Props) => {
I like the reuse.

2022-10-21 19:25 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
> +export const useAddParticipants = (playbookRun: PlaybookRun) => {
But then how do you open it?

2022-10-21 19:25 UTC, crspeller approved these changes

2022-10-25 08:40 UTC, trilopin approved these changes
Cool!

2022-10-25 08:42 UTC, merged