remove channel coupling
mattermost/mattermost-plugin-playbooks pull request #1538
Opened 2022-11-03 12:27 UTC by trilopin

## Summary
Evolve ProfileSelector / AssignTo to become decoupled from channel.

Literals are now: run participants / not participating when groups are shown.
However it wasn't just a literals thing, we took as run members only those members that were also in the channel. The significant change is to take the participant_ids list to decide if they are members or not (and force `ensureProfiles` for them).
Some variables have been renamed in the ProfileSelector to run away from channel/run coupling.

Run list has a profile selector that is not linked to a run (but many). It still works fine.

## Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1526

## Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-11-03 17:06 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +    useEnsureProfiles(playbookRun?.participant_ids ?? []);
I don't understand why this line makes follow/unfollow button in RDP-RHS fail (it doesn't even trigger onclick handler).

2022-11-03 17:53 UTC, trilopin commented on webapp/src/components/backstage/runs_list/filters.tsx
> +        const owners = await fetchOwnersInTeam(currentTeamId);
we were asking for all owners always because fetchParams.team_id was always empty

2022-11-04 21:17 UTC, abhijit-singh requested changes
Thanks @trilopin, awesome work!
A couple of requests:
1. If I change the owner from the Channels RHS to someone who is not in the run, there's a modal saying that they will be added to the channel — that modal no longer makes sense and can be removed. I don't think we need a confirmation modal for adding people to the run but I can be convinced otherwise if anyone feels we need it. cc @itao 
![2022-11-05 02 44 37](https://user-images.githubusercontent.com/14369607/200076108-84852317-3fb9-42b1-98ca-b13b7dafc4a9.gif)

2. (Non-blocking) Since we're touching this dropdown, can we make the `font-weight: 600` for the `Run participants` and `Not participating` headings in the dropdown. It seems to be incorrectly set to 500 right now.

2022-11-06 17:54 UTC, trilopin commented
> 1. If I change the owner from the Channels RHS to someone who is not in the run, there's a modal saying that they will be added to the channel — that modal no longer makes sense and can be removed. I don't think we need a confirmation modal for adding people to the run but I can be convinced otherwise if anyone feels we need it. cc @itao
       
Good point. If we currently do the change-owner from RDP, we already add it to the run but not to the channel if we action toggle is off. I'd do the same in both places.         

> 2. (Non-blocking) Since we're touching this dropdown, can we make the `font-weight: 600` for the `Run participants` and `Not participating` headings in the dropdown. It seems to be incorrectly set to 500 right now.

👍🏽

2022-11-07 19:25 UTC, crspeller requested changes

2022-11-07 19:25 UTC, crspeller commented on webapp/src/components/profile/profile_selector.tsx
> +    memberUserIds: string[];
Should this be `participantUserIds`?

2022-11-07 19:25 UTC, crspeller commented on webapp/src/components/profile/profile_selector.tsx
>  export default function ProfileSelector(props: Props) {
Could we do the `useEnsureUsers` in here instead? (maybe it would fix that strange problem above)

2022-11-08 09:58 UTC, gbochora approved these changes
Looks great! Thanks, @trilopin!

2022-11-08 10:54 UTC, trilopin commented on webapp/src/components/profile/profile_selector.tsx
>  export default function ProfileSelector(props: Props) {
The problem does not happen anymore. 

I didn't do ensureProfiles here to avoid having to create an additional lock to prevent concurrent fetch (like we have for team/channels) at hooks/general. The thing is that even if we could do the lock lockProfilesInRunFetch, would we have to store duplicated prodilesByRun in redux?

Given all that complexity, it seemed easier to do it at the top level just once.

2022-11-08 10:58 UTC, trilopin commented on webapp/src/components/profile/profile_selector.tsx
> +    memberUserIds: string[];
Could be. 

But I'm also wondering if we could do this component also run-agnostic. The only things that seem run-related are the literals for the group names. 

What if this component has the following props:
- handler for one master group of users 
- a subset of user ids (optional)
- group names (optional) with the literals

Would this make sense to you?

2022-11-08 15:48 UTC, crspeller commented on webapp/src/components/profile/profile_selector.tsx
> +    memberUserIds: string[];
Yes please. That is way better. We shouldn't have run/playbook specific terms in such a generic component.

2022-11-08 15:54 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
> +    useEnsureProfiles(playbookRun?.participant_ids ?? []);
it seems to be solved 🎉

2022-11-08 17:40 UTC, trilopin commented on webapp/src/components/profile/profile_selector.tsx
>  export default function ProfileSelector(props: Props) {
it felt like that, but I'll double-check it.

2022-11-09 16:22 UTC, trilopin commented on webapp/src/components/datetime_selector.tsx
> +                classNamePrefix='playbook-react-select'
generic classname name since it was used/applied to any react-select use

2022-11-09 16:28 UTC, trilopin commented on tests-e2e/cypress/support/plugin/ui_commands.js
> +        cy.get('#channel_view').should('be.visible');
@Phrynobatrachus thoughts about this? 

appbar was inside channel_view before, but now is outside. Without this line, when we click on appbar playbooks icon before Channelview render what triggers is the user menu

2022-11-09 17:47 UTC, Phrynobatrachus commented on tests-e2e/cypress/support/plugin/ui_commands.js
> +        cy.get('#channel_view').should('be.visible');
Yep I think this should help, I included it in #1557

2022-11-10 07:45 UTC, abhijit-singh approved these changes
Looks good to me! 

Just one thing I'm wondering is if we should add users to a run if a task is assigned to them. But it seems like we don't do that today so I'm not sure. We can discuss and pick it up later if needed.

2022-11-10 15:31 UTC, trilopin commented
> Just one thing I'm wondering is if we should add users to a run if a task is assigned to them. But it seems like we don't do that today so I'm not sure. We can discuss and pick it up later if needed.

True, I missed that point.

How do you imagine that? Just adding them to the run as participants or is an informative modal necessary if the assignee is not a participant yet?

2022-11-11 17:33 UTC, crspeller approved these changes
Nice!

2022-11-11 17:33 UTC, crspeller commented on webapp/src/components/profile/profile_selector.tsx
> +    // isMembersModeEnabled: boolean;
Remove?

2022-11-14 19:21 UTC, merged