1415 join run when you become participant
mattermost/mattermost-plugin-playbooks pull request #1540
Opened 2022-11-04 11:04 UTC by gbochora

## Summary
This PR updates become a participant flow. When a not participant tries to join the run:
- If the `join action` is enabled, the user will also become the linked channel member, whether the channel is public or private.
- If the `join action` is disabled and the linked channel is public, the user can decide whether to join the channel and select the checkbox.
- If the `join action` is disabled and the linked channel is private, the user can't join the channel, but he/she can send the join request.

https://user-images.githubusercontent.com/4368372/199952382-286e3795-afe4-40dd-b966-63b51d0eb9bc.mp4

## Ticket Link
https://github.com/mattermost/mattermost-plugin-playbooks/issues/1415

## Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-11-10 09:43 UTC, trilopin requested changes
This modal of becoming participant can be triggered from channels RHS and, in that case, side-actions related to channel would make no sense in the modal. isn't it?

![Screenshot 2022-11-10 at 10 41 46](https://user-images.githubusercontent.com/4096774/201056197-bf85752a-c6ed-4813-a35e-93d7b6585ee3.png)

2022-11-10 09:43 UTC, trilopin commented on server/app/playbook_run_service.go
> -	}
oh nice, this makes no sense anymore. I think we should manually remove those literals. shouldn't we?

2022-11-10 09:43 UTC, trilopin commented on webapp/src/components/rhs/rhs_run_details.tsx
> +    const {ParticipateConfirmModal, showParticipateConfirm} = useParticipateInRun(playbookRun || {} as PlaybookRun, 'channel_rhs');
wouldn't you accept undefined playbookRun in the hook instead of `{}  as PlaybookRun`?

2022-11-10 17:19 UTC, gbochora commented
> This modal of becoming participant can be triggered from channels RHS and, in that case, side-actions related to channel would make no sense in the modal. isn't it?
> 
Good catch! I've fixed the logic; if a user is already a channel member, it will not show an extra message.

2022-11-11 15:00 UTC, trilopin approved these changes
Cool 🎉

2022-11-11 17:30 UTC, crspeller approved these changes
Awesome!

2022-11-15 14:23 UTC, merged