Gh 1541 pbe link to existing channel
mattermost/mattermost-plugin-playbooks pull request #1549
Opened 2022-11-07 15:35 UTC by trilopin

## Summary

Everything runs around two new fields in the playbook: ChannelID and ChannelMode.

### API & GQL
Playbook query carries the new fields and UpdatePlaybook mutation accepts them.

### Service & Store
The new fields have been created in the playbook, create-new-channel is the default behavior.
Removed the unique constraint for the channelID index in the ir_incident table.

### Playbook UI
The user can choose whether create a new channel per run or link an existing one. Available channels are those you have permission to.

Channel Selector has been modified to allow single channel selection (it was hardcoded top multi before)

It is considered valid to save without selecting a channel but telling that you'll link the run to an existing channel. It will be mandatory in the run-start.

https://user-images.githubusercontent.com/4096774/200348951-daf36d56-c9eb-409c-b3f4-f14a387eb256.mp4

Pending:
- [ ] Playbook names are still created with channel name
- [ ] E2E tests
- [ ] double check migrations and update future versions (morph)
- [ ] toggle?

## Ticket Link

## Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-11-11 17:26 UTC, crspeller requested changes
Looking good!

2022-11-11 17:26 UTC, crspeller commented on server/api/graphql_root_playbook.go
> +		ChannelID                               *string
Just `ChannelID` confused me on first pass. Maybe call it `RunLinkChannelID`? Or something else more descriptive?

2022-11-11 17:26 UTC, crspeller commented on server/app/playbook_run_service.go
> +		/*	PRE MULTIPLERUNS IN A CHANNEL
We can just remove this.

2022-11-11 17:26 UTC, crspeller commented on server/sqlstore/playbook_run.go
> +		Select("i.ID", "i.Name AS Name", "i.Description AS Summary", "i.CommanderUserID AS OwnerUserID", "i.TeamID", "i.ChannelID",
We can remove the join on the channels table right?

2022-11-14 14:15 UTC, gbochora approved these changes
Great work, @trilopin 🥳

2022-11-14 15:36 UTC, trilopin commented on server/sqlstore/playbook_run.go
> +		Select("i.ID", "i.Name AS Name", "i.Description AS Summary", "i.CommanderUserID AS OwnerUserID", "i.TeamID", "i.ChannelID",
I also created a ticket for the refactor of the digest queries  https://github.com/mattermost/mattermost-plugin-playbooks/issues/1571

2022-11-14 15:45 UTC, trilopin commented on server/api/graphql_root_playbook.go
> +		ChannelID                               *string
2/5 if the playbook acts as a run template, wouldn't the same naming (for the fields that are copied) be the less surprising choice?

2022-11-14 16:32 UTC, crspeller commented on server/api/graphql_root_playbook.go
> +		ChannelID                               *string
That's a good point. I can see it both ways. I will leave it to your discretion.

2022-11-15 08:32 UTC, trilopin commented on server/app/playbook_run_service.go
> +		playbookRun.Name = pb.ChannelNameTemplate
not really

2022-11-15 11:08 UTC, trilopin commented on server/sqlstore/migrations/future/postgres/0.61.down.sql
> +ALTER TABLE IR_Incident  ADD CONSTRAINT ir_incident_channelid_key UNIQUE(ChannelID);
I tried IF NOT EXISTS but apparently does not work here. thoughts @gbochora ?

2022-11-15 13:47 UTC, abhijit-singh approved these changes
Looks good!

2022-11-18 11:22 UTC, gbochora reviewed
I've left a few comments regarding morph migrations.

2022-11-18 11:22 UTC, gbochora commented on server/sqlstore/migrations/future/postgres/0.61.down.sql
> +ALTER TABLE IR_Incident  ADD CONSTRAINT ir_incident_channelid_key UNIQUE(ChannelID);
```suggestion
DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT INDEXNAME FROM PG_INDEXES
        WHERE TABLENAME = 'ir_incident'
        AND INDEXNAME = 'ir_incident_channelid_key'
    ) THEN
        ALTER TABLE IR_Incident ADD CONSTRAINT ir_incident_channelid_key UNIQUE(ChannelID);
	END IF;
END
$$;

```

2022-11-18 11:30 UTC, trilopin commented on server/sqlstore/migrations/future/mysql/0.61.down.sql
> +    EXISTS(
oops

2022-11-18 23:10 UTC, crspeller approved these changes

2022-11-18 23:10 UTC, merged