Add missing telemetry for adding and removing participants.
mattermost/mattermost-plugin-playbooks pull request #1550
Opened 2022-11-07 23:02 UTC by crspeller

## Summary
Adding add and remove participants telemetry for tracking the separation of runs and participants. 

## Ticket Link
#1433

2022-11-07 23:04 UTC, crspeller commented on webapp/src/graphql/hooks.ts
> -export const useRunMembership = (runID?: string, userIDs?: string[]) => {
This was basically a duplicate of the other one so I just removed it.

2022-11-07 23:04 UTC, crspeller commented on webapp/src/components/rhs/rhs_participants.tsx
> -const AddParticipants = () => {
Appears to be unused. Confused me when I was looking around for participants code.

2022-11-08 11:23 UTC, trilopin requested changes
Nice work @crspeller 

I left some comments to reduce the number of event types.

2022-11-08 11:23 UTC, trilopin commented on webapp/src/types/telemetry.ts
> +    AddParticipant = 'playbookrun_add_participant',
I'd rename it to make more clear that accept multiple
```suggestion
    AddParticipant = 'playbookrun_add_participants',
```

2022-11-08 11:23 UTC, trilopin commented on webapp/src/types/telemetry.ts
> +    RemoveParticipant = 'playbookrun_remove_participant',
Same
```suggestion
    RemoveParticipant = 'playbookrun_remove_participants',
```

2022-11-08 11:23 UTC, trilopin commented on webapp/src/types/telemetry.ts
> +    AddParticipant = 'playbookrun_add_participant',
and same for server-side names

2022-11-08 11:23 UTC, trilopin commented on server/app/telemetry.go
> +	telemetryRunAddedByPlaybook:   "playbookrun_addedbyplaybook",
I would transform this type (and telemetryRunParticipate) into a property of telemetryRunAddParticipants rather than creating more event types for the same action.

something like: `trigger` with values 'participate' | 'add_participant' | 'invite_on_create'

2022-11-08 11:23 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
> +        telemetryEvent(PlaybookRunEventTarget.AddParticipant, {playbookrun_id: playbookRun.id, from: 'run_details'});
I would add also the playbook_id to answer questions like: "What are the average participants added per playbook" or "what the ratio initial invited users vs later added users per playbook?"

is there another value for from? Could we cover that with the trigger property suggestion?

2022-11-08 11:23 UTC, trilopin commented on webapp/src/graphql/hooks.ts
> -
nice dupe code removal!

2022-11-08 11:23 UTC, trilopin commented on webapp/src/components/rhs/rhs_participants.tsx
> -const AddParticipants = () => {
🎉

2022-11-08 19:31 UTC, crspeller commented on server/app/telemetry.go
> +	telemetryRunAddedByPlaybook:   "playbookrun_addedbyplaybook",
Done!

2022-11-10 07:51 UTC, gbochora approved these changes
Nice! 🥳

2022-11-10 11:43 UTC, trilopin commented on server/app/playbook_run_service.go
> +				"trigger": "invite_on_create",
I miss playbookRunID here

2022-11-10 11:50 UTC, trilopin requested changes
I'd expect to have the same properties in all events of the same eventType (even if for some specific cases are a bit forced like count=1).

2022-11-10 11:50 UTC, trilopin commented on server/app/playbook_run_service.go
> +				"trigger": "invite_on_create",
I miss playboorun_id field here

2022-11-10 11:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
> +        telemetryEvent(PlaybookRunEventTarget.Participate, {playbookrun_id: playbookRun.id, from: 'run_details', trigger: 'add_participant'});
I miss count field here (with the number items in ids array)

2022-11-10 11:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
> +                telemetryEvent(PlaybookRunEventTarget.Leave, {playbookrun_id: playbookRunId, from, trigger: 'leave'});
I'd force a count=1 field for consistency in event fields

2022-11-10 11:50 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
> +        telemetryEvent(PlaybookRunEventTarget.Leave, {playbookrun_id: playbookRun.id, from: 'run_details', trigger: 'remove_participant'});
I miss count field here (with the number items in ids array)

2022-11-11 15:13 UTC, trilopin approved these changes
Cool! 🎉

2022-11-11 15:13 UTC, trilopin commented on tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
> +                    expect(interception.request.body.properties.from).to.eq('run_details');
optional
```suggestion
                    expect(interception.request.body.properties.from).to.eq('run_details');
expect(interception.request.body.properties.trigger).to.eq('add_participant');
expect(interception.request.body.properties.count).to.eq('2');
```

2022-11-11 17:30 UTC, merged