[MM 44807] Adjust outline hover effects
mattermost/mattermost-plugin-playbooks pull request #1570
Opened 2022-11-14 12:54 UTC by m-ripper

## Summary
The hover effects in the playbook outline are now more consistent.
Only section headers with a right header element are highlighted on hovering.

![msedge_ZvIexJGS9g](https://user-images.githubusercontent.com/8669935/201663153-29223761-cac6-49d3-b52e-e308548342f2.png)

## Ticket Link
[MM-44807](https://mattermost.atlassian.net/browse/MM-44807)

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-11-14 15:13 UTC, abhijit-singh requested changes
Thanks @m-ripper! A couple of requests:
1. Clicking on the copy link icon on the left should not toggle the section on and off. Ideally, it should just copy the link and not trigger the toggle. Also, once you copy link, the hover state gets stuck.
2. Can we reduce the space between the header and the subtitle? The header section seems to have a margin-bottom of 10px currently which can be reduced to 2px.

2022-11-14 15:49 UTC, m-ripper commented
> Thanks @m-ripper! A couple of requests:
> 
> 1. Clicking on the copy link icon on the left should not toggle the section on and off. Ideally, it should just copy the link and not trigger the toggle. Also, once you copy link, the hover state gets stuck.
> 2. Can we reduce the space between the header and the subtitle? The header section seems to have a margin-bottom of 10px currently which can be reduced to 2px.

Thanks @abhijit-singh for the feedback.

Regarding 2.: Should this affect all headers or only those with a subtitle?

2022-11-14 15:51 UTC, abhijit-singh commented
> Regarding 2.: Should this affect all headers or only those with a subtitle?

Just the ones with a subtitle, which will be `Status updates` and `Retrospective` today.

2022-11-16 11:41 UTC, iomodo commented on webapp/src/components/backstage/playbook_editor/outline/section_retrospective.tsx
> +                    onChange={(option: { label: string; value: number; }) => {
extra spaces

2022-11-16 11:54 UTC, iomodo commented on webapp/src/components/backstage/playbook_editor/outline/outline.tsx
> +                onHeaderClick={() => {
Could we create a single function to make sure that  toggle `onChange` and `onHeaderClick` does the same thing

2022-11-16 11:54 UTC, iomodo commented on webapp/src/components/backstage/playbook_editor/outline/outline.tsx
> +                onHeaderClick={() => {
same here

2022-11-18 10:19 UTC, trilopin approved these changes
🎉 LGTM

2022-11-28 14:00 UTC, iomodo approved these changes
Looks great @m-ripper, thanks <3

2022-11-29 13:47 UTC, abhijit-singh approved these changes

2022-11-29 14:10 UTC, merged