MM-47235: Fix styling of hr in status updates
mattermost/mattermost-plugin-playbooks pull request #1572
Opened 2022-11-14 15:33 UTC by lieut-data

## Summary
An upstream change to CSS broke the styling for status updates:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/1023171/201700419-ea715bd4-0695-42a1-a6b3-70ba9b2a354f.png">

Restore to the expected design:
<img width="496" alt="CleanShot 2022-11-14 at 11 31 20@2x" src="https://user-images.githubusercontent.com/1023171/201700371-63f13d2b-1a91-4b5f-9b87-59d75d96fc74.png">

## Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-47235

2022-11-14 15:34 UTC, lieut-data commented on webapp/src/components/update_post.tsx
> +    &&& {
More specificity to overcome: 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/1023171/201700654-96643cae-e322-4385-9ade-c3819ff9d822.png">

2022-11-14 15:34 UTC, lieut-data commented on webapp/src/components/update_post.tsx
> +        margin: 0;
Override new Bootstrap scaffolding:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/1023171/201700752-710f927d-5a88-4c2f-99e5-fab529ccf272.png">

2022-11-14 15:58 UTC, calebroseland approved these changes
LGTM! Though it would be nice to fix the bg color while we're here.

2022-11-14 15:58 UTC, calebroseland commented on webapp/src/components/update_post.tsx
>          background: rgba(var(--center-channel-color-rgb), 0.61);
Seemed a little bolder than the usual divider, probably typo during feature—should be 0.16 per [designs](https://www.figma.com/file/OJeUZDfESLlXgblbn7Beac/Better-Status-Updates?node-id=1027%3A333472&t=2OvhTlqVtl7MFdOs-4).

```suggestion
        background: rgba(var(--center-channel-color-rgb), 0.16);
```

2022-11-14 16:02 UTC, calebroseland commented on webapp/src/components/update_post.tsx
> +        margin: 0;
Though maybe this, too:

```suggestion
        margin: 12px 0;
```

<img width="107" alt="CleanShot 2022-11-14 at 10 00 27@2x" src="https://user-images.githubusercontent.com/11724372/201707072-d89678bc-cb9e-479d-8bbb-aff2ebfda2fb.png">
<img width="156" alt="CleanShot 2022-11-14 at 10 00 22@2x" src="https://user-images.githubusercontent.com/11724372/201707202-5c628c11-70fe-4988-bf20-a29508414df6.png">

2022-11-15 14:10 UTC, abhijit-singh requested changes
There seems to be a 20% opacity applied on top of the `background: rgba(var(--center-channel-color-rgb), 0.16);`, which is making the line very light. 

I think we can either add an opacity:1 attribute to this instance or change the color to  `background: rgba(var(--center-channel-color-rgb), 0.8);`.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/14369607/201940101-f05a7e5c-cb7e-480a-a830-7304959afbff.png">

2022-11-15 20:39 UTC, lieut-data commented
Wow, good eye, @abhijit-singh! Now looks like:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/1023171/202020770-c3cbe82e-e5fb-4479-9d0f-c2913953c349.png">

2022-11-15 20:40 UTC, abhijit-singh approved these changes
💯

2022-11-15 20:55 UTC, merged