migrate digest related methods to avoid using channel names
mattermost/mattermost-plugin-playbooks pull request #1574
Opened 2022-11-15 13:56 UTC by trilopin

## Summary
Change approach at the digest messages sent by playbooks bot. After this change, they will show run name instead of the channel displayname, and additionally link to the RDP instead of the channel

## Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1571

## Checklist
- [ ] Telemetry updated
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-11-21 15:33 UTC, m-ripper approved these changes
Looks good to me!

2022-11-22 13:42 UTC, m-ripper requested changes
Looks good overall, ~~only the skipped test-case needs to be discussed.~~

2022-11-25 11:13 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +            it.skip('can fill a channel and is persisted', () => {
yes, until it is reliable

2022-11-25 11:16 UTC, trilopin commented
I added a couple of helpers to cypress to handle telemetry, let me know if they feel useful. If so, I'll create tickets to migrate other telemetry assertions in e2e.

2022-11-25 12:58 UTC, m-ripper approved these changes

2022-11-25 16:19 UTC, crspeller approved these changes

2022-11-25 16:19 UTC, merged