Show fullname owners
mattermost/mattermost-plugin-playbooks pull request #1576
Opened 2022-11-16 12:42 UTC by trilopin

## Summary
Honour PrivacySettings.ShowFullName value at getOwners endpoint.

Added client function and tests.

It's a bit surprising to get a nil value when is false from GetConfig() server calls, but it will be investigated separately.

## Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-48008

## Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [X] Unit tests updated

2022-11-16 15:35 UTC, crspeller requested changes

2022-11-16 15:35 UTC, crspeller commented on server/app/playbook_run_service.go
> +	// TODO: further investigation
I like to have these with actual tickets otherwise when I read this I have no idea what the status on this TODO is.

2022-11-16 15:35 UTC, crspeller commented on server/app/playbook_run.go
> +	if len(options) != 0 && !options["fullname"] {
Is there a reason to make this complicated? Why not just leave should we or should we not sanitize for the caller to decide?

2022-11-16 15:38 UTC, trilopin commented on server/app/playbook_run.go
> +	if len(options) != 0 && !options["fullname"] {
I followed the same pattern that is used at mattermost-server with Users where more fields can be sanitized based on config. If we don't plan to add more info here, we can just clean it in the getowners service call.

2022-11-16 15:47 UTC, trilopin commented on server/app/playbook_run.go
> +	if len(options) != 0 && !options["fullname"] {
I've simplified it since we have only one field and GetSanitizeOptions is not usable until we figure out what's happening with nil return.

2022-11-16 15:48 UTC, crspeller approved these changes

2022-11-16 20:29 UTC, lieut-data approved these changes

2022-11-17 12:45 UTC, oh6hay approved these changes
LGTM :+1:

2022-11-17 13:23 UTC, merged