[MM-42882] Allow playbook import for first-time users
mattermost/mattermost-plugin-playbooks pull request #1577
Opened 2022-11-16 13:54 UTC by m-ripper

## Summary
Added a link button on the Get Started page to import a playbook.

![msedge_aEyk5MxKXv](https://user-images.githubusercontent.com/8669935/202198911-5808e505-b37e-44a9-b0c5-37721a47c506.gif)

## Ticket Link
[MM-42882](https://mattermost.atlassian.net/browse/MM-42882)

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-11-16 17:41 UTC, calebroseland requested changes
It would be best to have the translated message as part of the same entry. When a message is broken up between multiple fragments, it becomes hard for translators to match those up.

Otherwise looks good!

2022-11-16 17:41 UTC, calebroseland commented on webapp/src/components/backstage/playbook_list.tsx
> +};
The `#` href isn't necessary IMO; it allows open-in-new-tab flows which doesn't really make sense for this. (And the `children` to unify the message.)

```suggestion
const ImportLinkButton = (props: {children: React.ReactNode | React.ReactNode[]; onClick?: () => void}) => {
    return (
        <ImportLink onClick={props.onClick}>
            {props.children}
        </ImportLink>
    );
};
```

2022-11-17 16:18 UTC, m-ripper commented on webapp/src/components/backstage/playbook_list.tsx
> +                                    />
Thanks for pointing that out! I initially implemented it that way but thought there's no advantage and switched to the current approach due to simplicity but it makes sense to keep the message together.

2022-11-21 15:00 UTC, calebroseland approved these changes

2022-11-21 15:02 UTC, merged