1543 start a run modal upgrade
mattermost/mattermost-plugin-playbooks pull request #1584
Opened 2022-11-17 14:55 UTC by gbochora

## Summary
This PR updates the `Run a Playbook` modal UI. When the `linkRunToExistingChannelEnabled` feature flag is enabled, the modal shows channel configuration, and the user can modify it.
When a user runs a playbook from the command line or action menu, the modal doesn't show channel configs but starts a run based on the playbook configuration.

https://user-images.githubusercontent.com/4368372/202961712-76901f29-ea09-4772-9282-72ba11b0a42c.mp4

## Ticket Link
Fixes #1543 

## Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-11-17 18:13 UTC, crspeller approved these changes

2022-11-18 11:08 UTC, trilopin requested changes
Shouldn't the context of the choices not be shown at the same time? From the designs, we just see the channel selector or the public/private selector depending on which choice we selected.

![Screenshot 2022-11-18 at 12 06 49](https://user-images.githubusercontent.com/4096774/202691589-1ef4c0ed-0f9b-4456-be8a-b1d1e1ce791b.png)

![Screenshot 2022-11-18 at 12 06 45](https://user-images.githubusercontent.com/4096774/202691591-6bb714ea-112d-4537-af17-988eaecf9a13.png)

2022-11-18 11:08 UTC, trilopin commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    const channelConfigSection = (
Given that this code is temporary, it might not be worth refactoring it.

For the next step of doing the final modal, I would look for ways to share this piece of code between pbe and modal.

2022-11-18 12:59 UTC, gbochora commented on webapp/src/components/modals/run_playbook_modal.tsx
> +    const channelConfigSection = (
Good point!

2022-11-18 13:19 UTC, gbochora commented on server/app/playbook_run_service.go
> -		playbookRun.ChannelID = pb.ChannelID
Slash and post both use the same endpoint(`createPlaybookRunFromDialog`), and when the run object is created, I set the `ChannelID:   playbook.GetRunChannelID(),`. I assumed that if `ChannelID` is empty, we must create a new channel. Otherwise, we need to run in the existing channel. This is not entirely correct; the `ChannelID` might be not-empty, but at the same time, `ChannelMode` can be set to `Create a new channel`.
So, you are right; I need to add the `ChannelMode` check. Thanks, great catch!

2022-11-18 13:32 UTC, gbochora commented on server/app/playbook_run_service.go
> -		playbookRun.ChannelID = pb.ChannelID
It turned out that I already did the `ChannelMode` check in the `playbook.GetRunChannelID()` function, so there is no need t modify anything.

2022-11-24 19:01 UTC, trilopin commented on server/api/playbook_runs.go
> +			ChannelID:   playbook.GetRunChannelID(),
shouldn't we use the channelid the user configured? 

I tried to do the following:
- configure playbook p1 to link to c1
- start a run modal, but configure to channel c2

run is still created linked to c1

2022-11-24 19:02 UTC, trilopin requested changes
check the comment about changing existing channel during run creation

a couple of server e2e test on this matter would be super useful given how core is this behavior

2022-11-24 19:29 UTC, abhijit-singh requested changes
Great work @gbochora! Haven't been able to test this locally (issues with my local dev environment that I haven't been able to solve yet) so just going by the screen recording. I had a couple of requests:
1. Let's remove the text below the run name input box that says `A channel will be created with this name`. I would suggest removing it irrespective of the choice made in the radio options below it. 
2. The spacing between the help text below run name and the radio options seems a little tight right now. With the help text gone, can we ensure that there's at least 24px space between the run name input box and the radio option to `Link run to existing channel`.

2022-11-25 16:45 UTC, gbochora commented on server/api/playbook_runs.go
> +			ChannelID:   playbook.GetRunChannelID(),
This endpoint is for the run dialog, and at this stage, users can't configure the channel in the UI. Because of that, I set the channel from the playbook configs. 
The bug you described was happening because of this code in the `PlaybookRunServiceImpl > CreatePlaybookRun`:
```
	if pb != nil && pb.ChannelMode == PlaybookRunLinkExistingChannel {
		playbookRun.ChannelID = pb.ChannelID
```

2022-11-25 16:46 UTC, gbochora commented
@trilopin Fixed changing existing channel issue, added server e2e tests.

@abhijit-singh resolved you requests, this is how modal looks like now:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/4368372/204019968-3164022f-32f8-435c-a02a-c329ae16809f.png">

2022-11-25 17:44 UTC, trilopin approved these changes
Thanks @gbochora for addressing all feedback


I've noticed that the modal is still submitted if I click Enter when I'm at the template input and there no channel filled. it would be great to cover that edge case

2022-11-28 12:22 UTC, abhijit-singh approved these changes
Looks good! Thanks @gbochora!

2022-11-28 12:23 UTC, merged