Gh 1586 rename run graphql
mattermost/mattermost-plugin-playbooks pull request #1587
Opened 2022-11-18 16:55 UTC by trilopin

## Summary
Implement Run rename feature:
- inline edit via TextEdit component
- hides context menu and closest icons when edit mode is enabled
- implemented in graphql

I also migrated the summary update from rest to graphql because why not.

![CleanShot 2022-11-18 at 17 51 50](https://user-images.githubusercontent.com/4096774/202758991-b475dee9-7d48-4261-a9d3-68cdfca1c909.gif)

## Ticket Link

## Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] Unit tests updated

2022-11-22 10:57 UTC, gbochora requested changes
Great work @trilopin! The only blocker is the permission check; it breaks the favorite/unfavorite functionality when a user is not a participant.

2022-11-22 10:58 UTC, trilopin commented on server/api/graphql_root_run.go
> +	if err := c.permissions.RunManageProperties(userID, args.ID); err != nil {
Sorry, I've just reverted to RunView before seeing your comment.

Agree on confusing permission, fav/unfav should be a different mutation than UpdateRun since we are not updating a run but a run-user relationship (plus the permission confussion)

2022-11-22 12:20 UTC, gbochora approved these changes
🎉

2022-11-24 18:40 UTC, crspeller requested changes
Just a couple things.

2022-11-24 18:40 UTC, crspeller commented on server/app/playbook_run_service.go
> +// func (s *PlaybookRunServiceImpl) UpdateDescription(playbookRunID, description string) error {
Remove.

2022-11-24 18:40 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +                disabled={playbookRun.current_status !== PlaybookRunStatus.InProgress}
Should this also be disabled if we are not a participant?

2022-11-24 18:53 UTC, trilopin commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +                disabled={playbookRun.current_status !== PlaybookRunStatus.InProgress}
I can add that to the condition if you want, but it's already unreachable because as viewer the context menu doesn't have the rename option.

2022-11-24 19:31 UTC, abhijit-singh approved these changes
Looks good! Thanks @trilopin!

2022-11-24 20:46 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
> +                disabled={playbookRun.current_status !== PlaybookRunStatus.InProgress}
Ah right. It thought there was a direct way to access it.

2022-11-24 20:46 UTC, crspeller approved these changes

2022-11-24 20:47 UTC, merged