more accurate text when leaving run
mattermost/mattermost-plugin-playbooks pull request #1595
Opened 2022-11-23 15:51 UTC by trilopin

## Summary

More accurate message in confirm modal when leaving run and while not being a follower.
![CleanShot 2022-11-23 at 16 48 05](https://user-images.githubusercontent.com/4096774/203589989-aedbdc4b-d6eb-4df2-ac9c-d51980bc330a.gif)

Merge timeline events for invite-users on run creation into one only add-to-run event.

## Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-48594
Fixes  https://mattermost.atlassian.net/browse/MM-48601

## Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-11-23 21:09 UTC, trilopin commented
here we have another case of add-means-follow additional complexity coming from LHS @lieut-data

2022-11-24 08:09 UTC, gbochora approved these changes
Looks good! Just a few optional comments.

2022-11-24 09:03 UTC, trilopin commented on server/app/playbook_run_service.go
> +	usersFailedToInvite, err := s.AddParticipants(playbookRun, invitedUserIDs, s.configService.GetConfiguration().BotUserID, false)
I wanted the team check to be there for different cases of addParticipants than start-run.

2022-11-25 14:05 UTC, lieut-data requested changes
Thanks, @trilopin! A few thoughts on how we might organize differently: let me know if I understood the changes correctly :)

2022-11-25 14:05 UTC, lieut-data commented on server/api/graphql_root_run.go
> +	failed, err := c.playbookRunService.AddParticipants(run, args.UserIDs, userID, args.ForceAddToChannel)
I'd love to see the service log a warning per user vs. having to give back `failed` to a client who "probably doesn't care".

2022-11-25 14:05 UTC, lieut-data commented on server/app/playbook_run_service.go
>  	}
nit: I feel like this would read more clearly as `return nil, nil` and located at the top of the method.

2022-11-25 14:59 UTC, trilopin commented on server/app/playbook_run_service.go
> +	}
I don't think so: if you couldn't invite anyone, the run has the same state as before the action, and therefore, there's no need to send the websocket.

2022-11-25 15:24 UTC, trilopin commented on server/api/graphql_root_run.go
> +	failed, err := c.playbookRunService.AddParticipants(run, args.UserIDs, userID, args.ForceAddToChannel)
I could agree on the log at service level, but we still have to return the failed (or the succeeded) items to do proper follow (don't make followers the users who failed to participate).

One more time the underlying question appears: should we keep the point "participate implies following"? Most of the weird data pass/return is because of having different actions that are linked.

Another point is, if we do believe that "participate implies following", we may have to do that in the service participation code (addparticipants or participateActions). This would be a bit more self-contained.

2022-11-25 15:26 UTC, trilopin commented on server/api/graphql_root_run.go
>  		}
oh, you are saying sth similar to what I answered. Agreed.

 Let's decide to stop "following on participate" or "following as part of participate code".

2022-11-25 15:37 UTC, lieut-data commented on server/api/graphql_root_run.go
> +	failed, err := c.playbookRunService.AddParticipants(run, args.UserIDs, userID, args.ForceAddToChannel)
I'm inclined to preserve the existing semantics that participate == follow, at least until we revisit this holistically. Does that simplify the immediate approach, @trilopin?

2022-11-25 16:04 UTC, trilopin commented on server/api/graphql_root_run.go
> +	failed, err := c.playbookRunService.AddParticipants(run, args.UserIDs, userID, args.ForceAddToChannel)
agreed, at least until we rethink LHS is the best choice.

in this scenario, I'm going to move the follow side-effect when participating to the service, cleaning the interface/data.

2022-11-28 14:04 UTC, lieut-data approved these changes
Nice cleanup, @trilopin! Just one proposed change below around slice semantics.

2022-11-28 14:04 UTC, lieut-data commented on server/app/playbook_run_service.go
> +		s.sendPlaybookRunUpdatedWS(playbookRun.ID, withAdditionalUserIDs(usersToNotify))
As an alternate to my comment above, would it make sense to just pass another `withAdditionalUserIDs` for the `requesterID`? (Does the abstraction here handle that itself?)

2022-11-28 14:04 UTC, lieut-data commented on server/app/playbook_run_service.go
> +			return errors.Wrap(err, "failed to make participant to unfollow run")
```suggestion
			return errors.Wrap(err, "failed to make participant to follow run")
```

2022-11-28 14:34 UTC, trilopin commented on server/app/playbook_run_service.go
> +		s.sendPlaybookRunUpdatedWS(playbookRun.ID, withAdditionalUserIDs(usersToNotify))
nice point, the abstraction wasn't prepared to be called twice but it was really easy to handle it

2022-11-28 14:44 UTC, lieut-data approved these changes

2022-11-28 14:44 UTC, lieut-data commented on server/app/playbook_run_service.go
> +		}
I think this is redundant, right? `append(nil, additionalUserIDs...)` should work fine.

2022-11-28 14:53 UTC, trilopin commented on server/app/playbook_run_service.go
> +		}
true, I'm a bit defensive with uninitialized slices/maps, sometimes unnecessarily :)

2022-11-29 06:42 UTC, gbochora approved these changes
Nice improvements!

2022-11-29 08:31 UTC, merged