Multiple runs in a channel: Channel RHS runs list
mattermost/mattermost-plugin-playbooks pull request #1598
Opened 2022-11-24 00:14 UTC by crspeller

## Summary

Runs list in the channels RHS supporting multiple runs in a single channel.

#### Selecting filtering and sorting for multiple runs:
![selecting_filtering](https://user-images.githubusercontent.com/3191642/203666902-a0a793ee-49e4-490d-80a3-404f60e5a5a1.gif)

#### Pagination:
![pagination](https://user-images.githubusercontent.com/3191642/203666905-c84fa7dd-9bde-4815-a41a-653951401eef.gif)

#### Only finished runs:
![onlyfinished](https://user-images.githubusercontent.com/3191642/203666909-4c7e05c1-f82f-4e4d-b160-c623cc0b2b9f.gif)

#### Rules for auto display:
No Runs Ever -> RHS Home
Only Finished Runs -> Runs list blank state
Single active run (ignoring finished) -> Details page for that run (back button goes to runs list)
Multiple active runs -> Runs list

## Review notes

### Graphql Pagination
GraphQL pagination has been implemented for runs list. The pattern comes from https://graphql.org/learn/pagination/ which is often referred to as Relay style as it's the preferred style for the Relay GraphQL client. It's probably over complicated for our use case at the moment, but it's the closest thing to a standard pagination style GraphQL has and it made it really easy to make Apollo work with it.

### RHS Title remote render
I didn't like the way we where handling the awkwardness of having to render the title of the RHS separate from the body. In this new style we use a portal to wave the problem away with a simple wrapper, this way each RHS page can render its title itself. We also avoid abusing redux for this. Have a look in rhs_title_remote_render.tsx to see how it's done.

## Follow up tickets
- [ ] Give feedback button in RHS runs list
- [ ] Dot menus on RHS runs list items
- [ ] Start run buttons for RHS runs list
- [ ] Fancy title for RHS runs list
- [ ] Switch sort icon for RHS runs list
- [ ] Progress bar on items in RHS runs list
- [ ] GraphQL migration product runs list to paginated API

## Ticket Link
Fixes #1544

2022-11-24 00:26 UTC, crspeller commented on server/api/graphql.go
> +			graphql.MaxDepth(8),
Queries are deeper now so had to bump this limit.

2022-11-24 00:26 UTC, crspeller commented on webapp/package.json
> +    "@apollo/client": "3.7.1",
Ran into what I thought was an Apollo bug, turns out it was not but I kept the update.

2022-11-24 00:26 UTC, crspeller commented on webapp/src/graphql/runs.graphql
> +fragment RHSRunFields on Run {
Finally a use for fragments!

2022-11-24 00:26 UTC, crspeller commented on webapp/src/index.tsx
> +                            runs: relayStylePagination(['teamID', 'sort', 'direction', 'statuses', 'participantOrFollowerID', 'channelID']),
This I don't like. You have to list here all the fields that should make two queries unique. Otherwise the default relay implementation for Apollo combines them. 

You can also do the paging yourself, but this makes it so much easier on the component side.

2022-11-24 00:26 UTC, crspeller commented on webapp/src/rhs_title_remote_render.tsx
> +    return ReactDOM.createPortal(props.children, container);
Here is the magic. Just create a portal you can render too. That's it.

2022-11-24 11:54 UTC, trilopin requested changes
What an effort here, love the cursor pattern and the portalling for the titles.

I left some questions or comments about nits.

From manual QA I've noticed the following details: 

1. I miss the blue check in the sort dropdown to indicate the active choice.

![Screenshot 2022-11-24 at 12 39 04](https://user-images.githubusercontent.com/4096774/203775902-c7b81a1d-9259-4d75-a1e7-949975c6c5db.png)

![CleanShot 2022-11-24 at 12 39 29](https://user-images.githubusercontent.com/4096774/203775772-ef0c7f94-81b9-4d6c-86d9-361ff2678087.gif)

2. last update in card only reflect timeline changes but some changes don't have any event (update summary for example)

3. could we have missing zero case for empty lists (finished)

or maybe that option should be disabled.
 
![Screenshot 2022-11-24 at 12 48 10](https://user-images.githubusercontent.com/4096774/203777245-972854e5-a363-42b0-9ff7-b201eea88bf6.png)


4. finish run from rhs

https://user-images.githubusercontent.com/4096774/203777925-7c869414-fce3-4da5-8805-0b5216112966.mp4

2022-11-24 11:54 UTC, trilopin commented on webapp/src/components/checklist_item/assign_to.tsx
> +        props.onSelectedChange?.();
why is this change neccesary?

2022-11-24 11:54 UTC, trilopin commented on webapp/src/components/rhs/rhs_main.tsx
> +    };
this is where all prev effort pays off 🎉

2022-11-24 11:54 UTC, trilopin commented on webapp/src/components/rhs/rhs_run_list.tsx
> +import {SecondaryButton, TertiaryButton} from '../assets/buttons';
optional nit: 

I'd want all imports to be absolute. They are more resilient to refactors or code re-use. They also. are more dense in blocks and some blank lines are not needed.

2022-11-24 11:54 UTC, trilopin commented on webapp/src/components/rhs/rhs_run_list.tsx
> +interface PlaybookToDisplay {
optional nit:

I'd like to put styled components after the actual component.

2022-11-24 11:54 UTC, trilopin commented on webapp/src/components/rhs/rhs_run_list.tsx
> +            </RHSTitleRemoteRender>
I like the trick with the portalling, the previous title was very complex and now it's cleaner with even more functionality covered. ❤️

2022-11-24 11:54 UTC, trilopin commented on webapp/src/slash_command.ts
> -                store.dispatch(setRHSViewingPlaybookRun());
why is this removed?

2022-11-24 16:20 UTC, crspeller commented on webapp/src/index.tsx
> +                            runs: relayStylePagination(['teamID', 'sort', 'direction', 'statuses', 'participantOrFollowerID', 'channelID']),
Agreed.

2022-11-24 16:31 UTC, crspeller commented on server/api/graphql_run.go
> +	return float64(r.PlaybookRun.TimelineEvents[len(r.PlaybookRun.TimelineEvents)-1].EventAt)
Unfortunately Run.UpdateAt isn't a thing. This goes with your observation above that the summary updating doesn't reflect on this value. 

There is actually one for just the summary so we could fix that, but it wouldn't fix it for stuff like editing a checklist item which doesn't have an event. 

We should probably think though what events we want to count here so I will make a follow up ticket for this.

2022-11-24 16:33 UTC, crspeller commented on server/api/schema.graphqls
> +	cursor: String!
Its stored as an integer because it is just the page number. It's always the page number for us. It's returned as a string by GraphQL because it's supposed to be opaque to the client. (actually there was a recommendation to base64 encode it). That way you can change paging patterns and the client is none the wiser.

2022-11-24 16:41 UTC, crspeller commented on webapp/src/components/checklist_item/assign_to.tsx
> +        props.onSelectedChange?.();
I don't remember 🤷

2022-11-24 16:41 UTC, crspeller commented on webapp/src/components/rhs/rhs_main.tsx
> +    };
Yup!

2022-11-24 17:08 UTC, crspeller commented on webapp/src/components/rhs/rhs_run_list.tsx
> +import {SecondaryButton, TertiaryButton} from '../assets/buttons';
Agreed. Wish there was an eslint rule that would cover this. When these get auto imported it does relative for some reason.

2022-11-24 17:10 UTC, crspeller commented on webapp/src/slash_command.ts
> -                store.dispatch(setRHSViewingPlaybookRun());
No need to set the state in redux anymore. Handled internally.

2022-11-24 17:16 UTC, trilopin commented
> 1. I miss the blue check in the sort dropdown to indicate the active choice.
> 
> ![Screenshot 2022-11-24 at 12 39 04](https://user-images.githubusercontent.com/4096774/203775902-c7b81a1d-9259-4d75-a1e7-949975c6c5db.png)

I've just noticed that the title "SORT RUNS BY" is also missing there.

2022-11-24 17:17 UTC, crspeller commented
@trilopin 

1. Will add a separate ticket for that. 
2. See inline comment.
3. Separate ticket.
4. Can't reproduce this. Is there something specific to your environment causing that? I can finish runs no problem admins and non-admins. The one thing I did notice doing this is that if the action to remove you from a channel you are in is enabled for a run in a channel with multiple runs, it will remove you from the channel despite being in other runs! This is bad.

2022-11-24 17:25 UTC, trilopin commented
> @trilopin
> 
> 1. Will add a separate ticket for that.

ok

> 2. See inline comment.

oh true, there's a bigger pending conversation here. I queued item for next sync

> 3. Separate ticket.

ok

> 4. Can't reproduce this. Is there something specific to your environment causing that? I can finish runs no problem admins and non-admins. The one thing I did notice doing this is that if the action to remove you from a channel you are in is enabled for a run in a channel with multiple runs, it will remove you from the channel despite being in other runs! This is bad.

I'll try again later today

🎉

2022-11-25 11:45 UTC, trilopin commented
More feedback:

1. finished runs do nothing when clicked
![CleanShot 2022-11-25 at 12 41 49](https://user-images.githubusercontent.com/4096774/203978616-01d2dba3-4cdb-4019-9ed0-a1da1278a65a.gif)

2. slash commands interaction is erratic

- messages in the channel are not accurate (mentions to "this run" while we have 9)
- don't give context about which run is affected
- finish through slash command while seeing the list works for one run (don't know which one)

should we block commands while the list is being showed and keep them just for when the run details is what we see in RHS?

![CleanShot 2022-11-25 at 12 39 40](https://user-images.githubusercontent.com/4096774/203978724-64076065-264b-4150-bcf1-a0a873e486ba.gif)

2022-11-25 16:04 UTC, crspeller commented
1. Fixed. 

2. Made a draft ticket in the project. (this one needs more discussion)

2022-11-25 18:15 UTC, trilopin commented on tests-e2e/cypress/integration/channels/rhs/list_spec.js
> +        cy.wait(1000);
optional: I'd try to replace time based waits with element based waits.

in other places we have:
```js
                // # Wait until the channel loads enough to show the post textbox.
                cy.get('#post-create').should('exist');
```

2022-11-25 18:18 UTC, trilopin commented on webapp/src/components/rhs/rhs_main.tsx
> +
would make sense to add here the algorithm for display in a comment?

Rules for auto display (from your pr desc):
- No Runs Ever -> RHS Home
- Only Finished Runs -> Runs list blank state
- Single active run (ignoring finished) -> Details page for that run (back button goes to runs list)
- Multiple active runs -> Runs list

2022-11-25 18:19 UTC, trilopin approved these changes
great job 🎉

2022-11-28 13:40 UTC, gbochora approved these changes
Massive amount of work and lots of great stuff! I've left a few questions and optional suggestions.

1. After a run is started in the channel, there is no longer way to navigate to RHS > Your Playbooks list page. Are we ok with that? It doesn't seem like a huge loss, but I still wanted to ensure it.
2. If a channel has a single run and it's finished, should we, by default, show the run details in the RHS?
3. Should we make the alphabetic sort ascending? Now it sorts descending.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/4368372/204291853-32c9a727-9cdc-420d-8f2d-d82bd408bfd5.png">

2022-11-28 19:10 UTC, crspeller commented on server/api/graphql_root_run.go
> +	After                   *string
It's the spec: https://graphql.org/learn/pagination/
The idea is to make it opaque to the client. So you can use any pagination pattern.

2022-11-28 19:13 UTC, crspeller commented on webapp/src/components/rhs/rhs_main.tsx
> +    const fetchFinished = () => (true);
Oh. That's a remnant from some performance optimization I was going to do. Removed.

2022-11-28 19:21 UTC, crspeller commented
1. I believe so. @abhijit-singh can confirm. 
2. I don't think so. It does make it a bit more awkward to get to, but I guess we are assuming you would rather show a new run. Thoughts @abhijit-singh ?
3. Certainly. Fixed.

2022-11-29 16:00 UTC, abhijit-singh commented
Amazing work! Appreciate all the details and interactions, and thank you for making follow up tickets for pending items. 

To answer a few questions from the comments: 
1. > there is no longer way to navigate to RHS > Your Playbooks list page.

Yep that's not a problem. We'll be able to get rid of it completely with the upcoming `Checklists` effort.

2. > If a channel has a single run and it's finished, should we, by default, show the run details in the RHS?

The first thing we'd want you to do is `Start a new run` in this case. We could possibly make it easier to get to the finished run but let's do that as an iteration if we feel the need.

2022-11-29 16:45 UTC, abhijit-singh approved these changes
Looks good to go ahead! Just one non-blocking request apart from the follow-up items already listed — the font of the title `Runs in progress`/`Finished runs` seems incorrect. It should be 
```
/* Heading 200 */
font-family: 'Metropolis';
font-style: normal;
font-weight: 600;
```

2022-11-29 16:52 UTC, crspeller commented
@abhijit-singh Ahh I didn't notice the font changed. Will fix in follow up PR: https://github.com/mattermost/mattermost-plugin-playbooks/pull/1609

2022-11-29 16:52 UTC, merged

2022-11-30 10:56 UTC, trilopin commented on webapp/src/components/rhs/rhs_run_list.tsx
> +import {SecondaryButton, TertiaryButton} from '../assets/buttons';
![Screenshot 2022-11-30 at 11 54 12](https://user-images.githubusercontent.com/4096774/204778130-1935fc57-d312-4c64-8079-607e76e0dea3.png)

if you use vscode, you can tell that auto-imported files are absolute from the source configured in tsconfig.

2022-11-30 11:15 UTC, trilopin commented on webapp/src/components/rhs/rhs_run_list.tsx
> +import {SecondaryButton, TertiaryButton} from '../assets/buttons';
Also, proposal for eslint rule https://github.com/mattermost/mattermost-plugin-playbooks/pull/1624