MM-47749: Task Actions
mattermost/mattermost-plugin-playbooks pull request #1611
Opened 2022-11-25 18:22 UTC by ashishbhate

## Summary

- Task Actions, https://www.figma.com/file/tnkgFLUnEijcjF8Tq1v4Bu/%F0%9F%A6%8A-Playbooks-%3C%3E-Gitlab?node-id=96%3A77967&t=pxjdUUoumCWbTNXN-0
  This PR adds the Task Actions feature. For more details about the feature see the linked figma designs and Jira ticket. For more details about the implementation see the next comment.

## Ticket Link

- https://mattermost.atlassian.net/browse/MM-47749

## Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-11-26 04:54 UTC, ashishbhate commented
### Notes about Task Actions:

1. A `TaskAction` is made up of a `Trigger` and `Actions`.  When a `Trigger` is triggered, `Actions` are executed". The backend supports having more than one action executed by a trigger, but currently we only have one type of action implemented and the UI only supports a single action (more on this later)

```Go
type TaskAction struct {
	Trigger Trigger  `json:"trigger"`
	Actions []Action `json:"actions"`
}
```

2. A checklist item (aka task) can have multiple `TaskActions`. Currently the UI only shows one `TaskAction`. All the supporting code already exists. This was done to speed up the implementation/delivery of this feature.

3. A checklist item (aka task) can have multiple `TaskActions`, and each `TaskAction` can have multiple `Actions`. This makes `TaskActions` fully composable, and flexible enough to execute complex, and conditional logic. 

6. One type of trigger has been implemented: `keywords_by_users` - This `Trigger` is triggered when a message containing any of the specified "keywords" is posted by the any of the specified "users". 

7. One type of action has been implemented: `mark_item_as_done` - This `Action` marks a checklist item as done. 

8. `Triggers` and `Actions` share a simple structure (implemented with stronger more specific types on the backend for safety)

```Go
struct {
	Type string `json:"type"`
	Payload string `json:"payload"`
}
```

The `Type` identifies the type of the action or trigger.
The `Payload` contains action/trigger specific configuration/data


### Notes about this PR/Implementation

1. The frontend definitely needs polish. I've tried to reuse some components from "Channel Actions". The structure and implementation of these components are a close match, but don't fit "Task Actions" exactly, so you will notice some oddities in the way the components are laid out. Some of these existing components need tweaking to make them more reusable and stylistically configurable. I've only made small changes where absolutely required. Other places require larger changes that can come in follow-up PRs (e.g. the sizes of the selected user labels in the Profile Autocomplete input)

2. The GraphQL types could possibly be implemented better in terms of Nullability. I struggled to get the three type systems (Typescript, GraphQL, and Go) to play well together. 

3. Tests! There are none unfortunately. I'm working on tests for the backend. I will push these as the PR is being reviewed. I would love some assistance with tests on the frontend.

4. Frontend coding style - My VSCode isn't linting or re-formatting frontend code correctly. I'm not sure why. `make check-style` passes, but feel free to leave comments on the code style that I may have missed.

### Things left to do

- [ ] Support for Message Attachments - WIP
- [ ] Tests - WIP coming soon
- [ ] Telemetry - @lieut-data I still haven't figured out telemetry (or metrics). Is this a blocker for this PR?
- [ ] Feature Flag - @lieut-data Does this feature need to go behind a feature flag?

2022-11-28 14:39 UTC, lieut-data requested changes
Nice work, @ashishbhate! I've focused on the server-side changes with my review. A few comments for discussion.

2022-11-28 14:39 UTC, lieut-data commented on server/api/graphql.go
> +			graphql.MaxDepth(6),
cc @crspeller, what are the wider ramifications of allowing this?

2022-11-28 14:39 UTC, lieut-data commented on server/api/graphql_playbook.go
> +	TaskActions      *[]app.TaskAction `json:"task_actions"`
Is `TaskActions` as a pointer to a slice necessary?

2022-11-28 14:39 UTC, lieut-data commented on server/api/graphql_root_playbook.go
> +			return "", errors.Wrapf(err, "failed to marshal checklist in graphql json for playbook id: '%s'", args.ID)
Should we update the error message here to indicate the failure to validate vs. marshal?

2022-11-28 14:39 UTC, lieut-data commented on server/api/graphql_root_playbook.go
> +	for listIndex := range checklists {
Do we need to iterate using the indices, or would it be clearer to just use the values directly?

2022-11-28 14:39 UTC, lieut-data commented on server/api/playbooks.go
> +// NOTE: Any changes to this function must be made to function 'validateUpdateTaskActions' for the GraphQL endpoint.
cc @crspeller / @trilopin, it looks like Ashish had to make changes to both our GraphQL and REST endpoints, adding complexity. Thoughts on creating tasks to migrate more of our REST code to GraphQL to avoid this?

2022-11-28 14:39 UTC, lieut-data commented on server/app/playbook.go
> +	TaskActions []TaskAction `json:"task_actions" export:"-"`
Is `export` omitted here on purpose? I guess there may be explicit `UserIDs` that won't match? cc @crspeller, thoughts?

2022-11-28 14:39 UTC, lieut-data commented on server/app/playbook_run_service.go
> +		}).Error("unable retrieve run ID from post")
I'm hesitant about logging anything on `MessageHasBeenPosted`: this could easily overwhelm the server logs if the issue is somehow Playbooks specific. Thoughts? Would it make sense to only `Debug` this instead?

2022-11-28 14:39 UTC, lieut-data commented on server/app/playbook_run_service.go
> +						logrus.WithError(err).Error("unable to decode trigger")
Can we include some metadata with this log that identifies the task action in question?

2022-11-28 14:39 UTC, lieut-data commented on server/app/playbook_run_service.go
> +					if t.IsTriggered((post)) {
Is `((post))` intentional?

2022-11-28 14:39 UTC, lieut-data commented on server/app/playbook_run_service.go
> +							logrus.WithError(err).Error("can't process task actions")
As above, can we include some metadata in the log?

2022-11-28 14:39 UTC, lieut-data commented on server/app/playbook_run_service.go
> +						return errors.Wrapf(err, "can't mark iteam as done")
```suggestion
						return errors.Wrapf(err, "can't mark item as done")
```

2022-11-28 14:39 UTC, lieut-data commented on server/app/task_actions.go
> +// Triggers
nit: This comment seems incomplete?

2022-11-28 16:13 UTC, ashishbhate commented on server/api/graphql.go
> +			graphql.MaxDepth(6),
Specifying a lower MaxDepth is a good idea to prevent abuse and keep the application resource usage under control (deeper queries mean more work for the app). 

UUIC the graphQL AST is parsed and parts of the queries requesting data deeper than the max depth are like a no-op.

Without this bump we can't get TaskActions when requesting Playbook Runs from the GraphQL query.

2022-11-28 16:16 UTC, ashishbhate commented on server/app/playbook.go
> +	TaskActions []TaskAction `json:"task_actions" export:"-"`
Yep, there is comment at the top of this struct

```
// The tag export supports the export/import feature. If the field makes sense for export, the value should be
// the JSON name of the item in the export format. If the field should not be exported the value should be "-".
// Fields should be exported if they are not server specific like InvitedUserIDs or are tracking metadata like CreateAt.
```

UserIds are server specific, and could be present in task actions so I opted not to export the field.

2022-11-28 16:19 UTC, ashishbhate commented on server/app/task_actions.go
> +// Triggers
Nope, just indicates that this section of the file contains triggers. There's a similar comment on line 105 for actions and 128 for validators. 
0/5 if they're helpful or not

2022-11-28 16:27 UTC, ashishbhate commented on server/api/graphql_playbook.go
> +	TaskActions      *[]app.TaskAction `json:"task_actions"`
This is a consequence of the GraphQL nullability issue I've spoken about. This needs to be a pointer for the null GraphQL type for the updator.
I think I might know how to make all these types work better together, but I really haven't had the time to try things out. Would you be open to this coming as a later improvement?

2022-11-28 16:40 UTC, ashishbhate commented on server/app/playbook_run_service.go
> +					if t.IsTriggered((post)) {
Nope, bad code clean-up on refactor on my part :)

2022-11-28 18:16 UTC, lieut-data commented on server/api/graphql_playbook.go
> +	TaskActions      *[]app.TaskAction `json:"task_actions"`
I'm fine with that, as I believe the change is all internal to the server.

2022-11-28 18:18 UTC, lieut-data commented on server/app/playbook_run_service.go
> +		}).Error("unable retrieve run ID from post")
Thanks for deep diving there: indeed it looks like my fears are unfounded given an existing pattern already exists. Let's leave it as you have it :)

2022-11-28 19:24 UTC, crspeller commented on server/api/graphql.go
> +			graphql.MaxDepth(6),
What he said + I already bumped the value higher in my PR: https://github.com/mattermost/mattermost-plugin-playbooks/pull/1598/files#diff-2db6c89c7fc8f9ca00844febd6f949939b62019f64b13251eff2af8bbb33822fL65

2022-11-28 19:24 UTC, crspeller commented on server/api/playbooks.go
> +// NOTE: Any changes to this function must be made to function 'validateUpdateTaskActions' for the GraphQL endpoint.
Yes we should. I want to deprecate the REST and use GraphQL api for most things.

2022-11-28 19:30 UTC, crspeller commented on server/app/playbook.go
> +	TaskActions []TaskAction `json:"task_actions" export:"-"`
Agree the userID are server specific and won't export. It would be nice if we defined specific export behavior for this field so cross server applicable stuff would transfer. Not sure if that is possible, not familiar enough with this feature.

2022-11-28 23:29 UTC, calebroseland requested changes
Overall looks pretty good to me! Just a few nits, but nothing major.


Long-term, it would be nice to see the TS typing for `TaskAction` mature. Perhaps generics could be added down the line to increase clarity and `trigger`-`action[]` relationships.

2022-11-28 23:29 UTC, calebroseland commented on webapp/src/components/checklist_item/task_actions_modal.tsx
> +        }];
To reduce type casting, improve readability IMHO (2/5)

```suggestion
        const newTaskAction: TaskAction = {
            trigger: {
                type: KeywordsByUsersTriggerType,
                payload: JSON.stringify({keywords: newKeywords, user_ids: newUserIDs}),
            },
            actions: [
                {
                    type: MarkItemAsDoneActionType,
                    payload: JSON.stringify({enabled: newIsEnabled}),
                },
            ],
        };
```

2022-11-28 23:29 UTC, calebroseland commented on webapp/src/components/checklist_item/task_actions_modal.tsx
> +    const actionPayload = (taskAction.actions?.length > 0 && taskAction.actions[0]?.payload) ? JSON.parse(taskAction.actions[0].payload) : markAsDoneEmptyPayload;
IMHO, it would be nice to see this pre-parsed/decoded at a higher level—but that may not be realistic for this MVP.

So for containment, could we wrap this parsing logic in a func or custom hook? (0/5 on the de-structuring)

```suggestion
    const {keywords, user_ids: userIds} = keywordsTriggerPayloadFromTaskAction(taskAction);
    const {enabled} = markAsDonePayloadFromTaskAction(taskAction);
```

```tsx
type KeywordsTriggerPayload = {keywords: string[]; user_ids: string[];}
export const keywordsTriggerEmptyPayload: KeywordsTriggerPayload = {keywords: [], user_ids: []};

type MarkAsDonePayload = {enabled: boolean;};
export const markAsDoneEmptyPayload: MarkAsDonePayload = {enabled: false};

const keywordsTriggerPayloadFromTaskAction = (taskAction: TaskAction): KeywordsTriggerPayload => {
    // we only have one kind of trigger
    const triggerType = taskAction.trigger?.type ? taskAction.trigger.type : KeywordsByUsersTriggerType;
    const triggerPayload: KeywordsTriggerPayload = taskAction.trigger?.payload ? JSON.parse(taskAction.trigger.payload) : keywordsTriggerEmptyPayload;

    return triggerPayload;
};

const markAsDonePayloadFromTaskAction = (taskAction: TaskAction): MarkAsDonePayload => {
    // we currently only support one action per trigger
    const actionType = (taskAction.actions?.length > 0 && taskAction.actions[0]?.type) ? taskAction.actions[0].type : MarkItemAsDoneActionType;
    const actionPayload: MarkAsDonePayload = (taskAction.actions?.length > 0 && taskAction.actions[0]?.payload) ? JSON.parse(taskAction.actions[0].payload) : markAsDoneEmptyPayload;
    return actionPayload;
};

// const TaskActionsModal(...) => { ...
```

2022-11-29 05:15 UTC, calebroseland commented
Pushed a small polish/fix, please feel free to rewind/revert/revise if necessary.

1). Task Actions disabled when task is skipped, run is finished, or if marked readonly (Copy-pasted from the other controls)
2). Added hover state
<img width="543" alt="CleanShot 2022-11-28 at 23 14 41@2x" src="https://user-images.githubusercontent.com/11724372/204444719-85d7b545-a4c0-4331-9a08-5ae463c862a9.png">

2022-11-29 05:19 UTC, calebroseland commented
Not crucial, could be done later, but nice a UI nicety would be to have pre-filled options for the `Posted by` option. 

Example from Assignee dropdown shown.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/11724372/204445163-46b9014d-3471-4307-9426-987431b8aed5.png">

2022-11-29 11:42 UTC, ashishbhate commented on webapp/src/components/backstage/profile_autocomplete.tsx
> +            autoFocus={!props.disableAutoFocus && true}
TIL about `??` the "nullish coalescing operator"

2022-11-29 11:59 UTC, ashishbhate commented on webapp/src/components/checklist_item/task_actions_modal.tsx
> +import {TaskAction as TaskActionType} from 'src/types/playbook';
We don't necessarily need it, but there is a variable called `taskAction` and I wanted make it easier to differentiate between the two. 
I'm 0/5. Let me know which way you prefer it.

2022-11-29 12:19 UTC, ashishbhate commented
@lieut-data I've pushed the server review suggestions

@calebroseland Thanks so much for the quick review and also for pushing your improvements.
I'm keeping track of all the UI polish issues. The feature team has a sync meeting tomorrow (Wednesday). Based on the discussions tomorrow, I'll have a better understanding of how much of the UI polish is doable now vs punting them for later.

2022-11-29 13:42 UTC, lieut-data commented on server/app/playbook.go
> +	TaskActions []TaskAction `json:"task_actions" export:"-"`
Yeah, I think it would have to be an all or nothing here, since a trigger that "loses" its user id filter might be annoying, as would a partially exported set of task actions for triggers without user ids.

2022-11-29 13:43 UTC, lieut-data approved these changes
Looks awesome, @ashishbhate! I'm aiming to help contribute E2E tests starting this afternoon my time, but this PR is good to go from my perspective.

2022-11-29 17:00 UTC, crspeller requested changes

2022-11-29 17:00 UTC, crspeller commented on server/api/graphql_playbook.go
> +	TaskActions      *[]app.TaskAction `json:"task_actions"`
If we modified the types we wouldn't have to have it like this. You can see it working on the struct above.

2022-11-29 17:12 UTC, ashishbhate commented on server/api/schema.graphqls
> +	taskActions: [TaskActionUpdates!]
IIRC, I did this way to prevent empty task actions json arrays being stored in the DB for every checklist for every checklist item update.

2022-11-29 17:22 UTC, ashishbhate commented on webapp/src/client.ts
> +    const data = await doPut(`${apiUrl}/runs/${playbookRunID}/checklists/${checklistNum}/item/${itemNum}/taskactions`,
Because that is the existing pattern in the code - webapp/src/components/checklist_item/checklist_item.tsx

It appears Playbooks and runs are fetched through GraphQL, but are sometimes updated with GraphQL, and some other parts are updated through REST. To keep it consistent with the rest of the code where this function is used (see file above), where the due date, command, etc. are all updated through the REST API, I implemented the REST API as well.

Also, I have no idea about the usage of the Playbooks API. Since there were REST endpoints to update other parts of a checklist item, it made sense to write it for task actions as well for the sake of completeness.  

I didn't want to break any existing patterns or set new GraphQL patterns for an unfamiliar code base that it going through a piecemeal migration from REST to GraphQL.

2022-11-29 22:04 UTC, crspeller commented on server/api/schema.graphqls
> +	taskActions: [TaskActionUpdates!]
Yes the way checklist items are stored is a bit awkward. I see why it's like this.

2022-11-29 22:05 UTC, crspeller commented on webapp/src/client.ts
> +    const data = await doPut(`${apiUrl}/runs/${playbookRunID}/checklists/${checklistNum}/item/${itemNum}/taskactions`,
I understand following existing patterns. Could we have your help removing the REST API you added and just use the GraphQL one you added instead? GraphQL is the way forward for us now.

2022-11-29 22:05 UTC, crspeller commented on server/api/graphql_playbook.go
> +	TaskActions      *[]app.TaskAction `json:"task_actions"`
Never mind I see the difference here now.

2022-11-30 10:19 UTC, ashishbhate commented on webapp/src/client.ts
> +    const data = await doPut(`${apiUrl}/runs/${playbookRunID}/checklists/${checklistNum}/item/${itemNum}/taskactions`,
Yep, I will update to use the GraphQL updator, and remove the new REST endpoint for task actions.

This PR also includes an addition to a validator in the the `createPlaybook` REST endpoint. Let me know if this should be removed too.

2022-11-30 16:28 UTC, ashishbhate commented
@crspeller I've removed the REST endpoint. TaskActions is fully GraphQL now (both on Playbooks and Run).

2022-11-30 21:10 UTC, crspeller approved these changes
Thanks!

2022-11-30 22:12 UTC, calebroseland commented
Fixed: 

| before | after |
|---|---|
|  ![CleanShot 2022-11-30 at 16 02 07](https://user-images.githubusercontent.com/11724372/204919062-0f888bcb-1275-4e02-8323-af83b936edeb.gif) | ![CleanShot 2022-11-30 at 16 07 29](https://user-images.githubusercontent.com/11724372/204919116-ef283ad0-be51-4058-bb6a-b6166751c97d.gif) |

2022-11-30 22:31 UTC, calebroseland approved these changes

2022-12-02 12:16 UTC, ashishbhate commented on webapp/src/types/telemetry.ts
> +    TaskInbox = 'task_inbox',
fixed a small typo along the way

2022-12-02 12:36 UTC, abhijit-singh approved these changes
Looks awesome! Thanks @ashishbhate!

2022-12-02 13:56 UTC, lieut-data commented
Wow, nice work everyone! This is a huge effort coming together :D

2022-12-03 01:07 UTC, DHaussermann commented
**Test Summary** 
- General 
  - Task actions can be added to a playbooks
  - Tasks actions can be added to individual runs 
  - Mark as done must be true for the task to be completed 

- Keywords Testing
  - Single word
  - Multiple words
  - Case sensitive 

- Respect user scope
  - Team member not in channel cannot be selected as users on the task action
  - Only current channel members can be assigned to an action task
  - All current channel members can be assigned even if they are not yet "participants" of the playbook run

-- issue --
1. Post action is still not getting saved on first save attempt - Must save twice.
2. String evaluation is not formatting agnostic "Published release `v1.5.0`"
3. Affected by autolink re-writting your posts  "Close Jira ticket MM-1234 " the "MM-1234" actually get's re-written as "[MM-1234](https://mattermost.atlassian.net/browse/MM-"  0/5 Can this ignore `[]` to avoid m,ost common cases of Autolink 
4. Task actions can add assignees at the playbook level. 0/5 Do we want this? You can assign users on the team who may not be in the channel when a run is created   
-- UX --
5. It would be ideal if there were some kind of feedback that I have just marked a task as done in the thread. "Release cut v1.5.0"  ""Release cut v1.5.0 has failed" could result in someone marking a task done by mistake. There no way to know if the RHS is closed.   
6. To add multiple strings at once I need to move the focus out and back in or hit return. (unless there's a more obvious way I've missed) Otherwise it adds a multiword string. Is this how this type of control normally works?  

**Notes**:
- Case insensitive opt-in would be a nice touch as future enhancement. 
- Why does this ignore `-` character? For strings like `followup` Vs `follow-up`  will match. Are there excempted characters? If so see 3.

2022-12-05 13:16 UTC, merged