Add loader to favorites
mattermost/mattermost-plugin-playbooks pull request #1632
Opened 2022-12-01 16:02 UTC by jecepeda

## Summary

After doing [this PR](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1615) I noticed that playbooks don't use any dataloader. If this plugin doesn't use dataloaders, we are basically doing N+1 queries.

This PR covers `isFavorite`, as it is the last piece of code where I worked.

Added:
* Add favorite dataloader to the main graphql function
* Create GraphQl loader for isFavorite on runs
* Create new category service function

## Ticket Link

No ticket link

## Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-12-01 16:02 UTC, mattermod commented
Hello @jecepeda,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-12-07 17:24 UTC, jecepeda commented on server/app/playbook_run_service.go
> +					return errors.Wrapf(err, "can't mark item as done")
Running golangci on master gave me this error: `nilness: tautological condition: non-nil != nil`

Basically we're already checking on 3542 `if err != nil`

2022-12-18 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-01-10 10:58 UTC, trilopin requested changes
Really good job @jecepeda, it's amazing to have your help here.

I've added some comments, requests and doubts.

💯

2023-01-10 10:58 UTC, trilopin commented on server/api/resolver.go
> +func getFavoritesLoader(ctx context.Context) (*dataloader.Loader, error) {
would make sense to rename this file as server/api/grahql_dataloader.go?

2023-01-10 10:58 UTC, trilopin commented on server/api/resolver_favorite.go
> +func graphQLRunFavoritesLoader(ctx context.Context, keys dataloader.Keys) []*dataloader.Result {
this loader seems to work for both playbook favorites and run favorites since favoriteInfo includes app.CategoryItemType. could we rename this func to remove the Run keyword from it?

2023-01-10 10:58 UTC, trilopin commented on server/api/resolver_favorite.go
> +
woudl make sense to rename this file as server/api/graphql_loader_favorite.go?

2023-01-10 10:58 UTC, trilopin commented on server/api/graphql_run.go
> +	loader, err := getFavoritesLoader(ctx)
could you please do the same for graphql_playbook.go IsFavorite function?

2023-01-10 11:34 UTC, jecepeda commented on server/api/graphql_run.go
> +	loader, err := getFavoritesLoader(ctx)
Sure!

2023-01-11 22:29 UTC, crspeller requested changes

2023-01-11 22:29 UTC, crspeller commented on go.mod
> +	github.com/graph-gophers/dataloader/v6 v6.0.0
Could we use v7 instead of v6? I have a in progress work and I am using v7. It supports generic so the interface is more type safe.

2023-01-11 22:29 UTC, crspeller commented on server/api/graphql.go
> +	favoritesLoader := dataloader.NewBatchedLoader(graphQLRunFavoritesLoader, dataloader.WithBatchCapacity(loaderBatchCapacity))
Can we add these to the existing graphQLContext rather than individual items on the context? 

Like this:
```go
	postsLoader := dataloader.NewBatchedLoader(postsBatchLoader, dataloader.WithBatchCapacity[string, *model.Post](batchCapacity))

	graphQLContext := &GraphQLContext{
		r:                  r,
		playbookService:    h.playbookService,
		playbookRunService: h.playbookRunService,
		categoryService:    h.categoryService,
		pluginAPI:          h.pluginAPI,
		logger:             c.logger,
		config:             h.config,
		permissions:        h.permissions,
		playbookStore:      h.playbookStore,
		licenceChecker:     h.licenceChecker,
		postsLoader:        postsLoader,
	}

```

2023-01-11 22:29 UTC, crspeller commented on server/api/resolver.go
> +func getPlaybookLoader(ctx context.Context) (*dataloader.Loader, error) {
These become redundant given the suggestion above.

2023-01-21 11:42 UTC, jecepeda commented
Hey @crspeller @trilopin I just finished your requested changes. I'll take a look now in case there're any errors and/or linting errors, but I generally think this is ready for another round of reviews.

2023-01-24 19:28 UTC, trilopin commented on server/api/graphql_loader_playbook.go
> +				Error: fmt.Errorf("playbook %q not found", playbookInfo.ID),
This error can be triggered when we try to execute a nested query with runs and their playbooks but we lack permissions for that graph navigation. 

There's a valid scenario where a user can have access to runs, but not the playbooks. related to those runs. That's what happens in the current e2e failures at command_spec.js.

For those cases, I wonder if we can just nest an empty PlaybookResolver instead of failing (and handle at the webapp side the different actions as we already do).

cc @crspeller on funny scenarios nesting resources with different permission levels 🎉

2023-01-24 23:04 UTC, crspeller requested changes
Other than the permissions thing it looks good.

2023-01-24 23:04 UTC, crspeller commented on server/api/graphql_loader_playbook.go
> +				Error: fmt.Errorf("playbook %q not found", playbookInfo.ID),
We need the equivalent of:
```go
if !errors.Is(err, app.ErrNoPermissions) {
    c.logger.WithError(err).Error("error retrieving playbook of run")
}
return nil, nil
```
from the previous code. Just ignore it if it's a permissions error and return nil.

2023-01-26 09:41 UTC, trilopin approved these changes
Huge job @jecepeda 

I left a couple of non-blocking comments

2023-01-26 09:41 UTC, trilopin commented on server/api/graphql_loader_playbook.go
> +}
Are Raw / String functions still needed ?

2023-01-26 09:43 UTC, trilopin commented on server/api/graphql_loader_playbook.go
> +				Error: fmt.Errorf("playbook %q not found", playbookInfo.ID),
Those permissions are handled not by permission service but with buildPermissionExpr at the store layer, so I guess we just have to ignore non-returned playbooks

2023-01-26 22:30 UTC, crspeller approved these changes

2023-02-08 11:48 UTC, trilopin commented
/update-branch

2023-02-08 12:18 UTC, merged