1667  Make run configuration labels clickable
mattermost/mattermost-plugin-playbooks pull request #1668
Opened 2022-12-09 13:52 UTC by m-ripper

## Summary
Makes configuration labels clickable by changing `AutomationTitle` from `div` to `label`. This way, the inner `input` will automatically be clicked when the `AutomationTitle` is clicked.  
Also adjusted components that use `AutomationTitle` to have no `div` inside the `label` for clean HTML.

[Screencast from 09.12.2022 14:43:49.webm](https://user-images.githubusercontent.com/8669935/206717166-3632b1d6-daf8-4581-a9d4-a5fcad84af8b.webm)

## Ticket Link

fixes #1667 

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-12-09 13:55 UTC, lieut-data approved these changes
Ah, the beautify of  `label` -- nice, clear solution @m-ripper :)

2022-12-09 21:58 UTC, calebroseland requested changes
Definitely the right direction! Though, I think it would be good to unify the labels into one (via `children`). This would avoidhaving to add a bunch of IDs and is a bit more straightforward IMO.

2022-12-09 21:58 UTC, calebroseland commented on webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
> +    inputId?: string;
```suggestion
    inputId?: string;
    children: React.ReactNode;
```

(with `children` right after `RoundSwitch`)

2022-12-09 21:58 UTC, calebroseland commented on webapp/src/components/backstage/playbook_edit/automation/webhook_setting.tsx
>                  />
e.g.
```suggestion
                <Toggle
                    isChecked={props.enabled}
                    onChange={props.onToggle}
                    disabled={props.disabled}
                >
                    {props.textOnToggle}
                </Toggle>
```

2022-12-09 21:58 UTC, calebroseland commented on webapp/src/components/backstage/playbook_edit/automation/webhook_setting.tsx
> +                </AutomationLabel>
```suggestion
```

2022-12-09 21:58 UTC, calebroseland commented on webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
> +    inputId?: string;
`Label` would also need additional styling something akin to: 

```css
display: flex;
align-items: center;
column-gap: 12px;
font-weight: inherit;
```

2022-12-14 21:38 UTC, calebroseland approved these changes
Thanks, @m-ripper!

2022-12-14 21:38 UTC, merged