Use proxy state item
mattermost/mattermost-plugin-playbooks pull request #1669
Opened 2022-12-09 15:39 UTC by trilopin

## Summary
Follow up https://github.com/mattermost/mattermost-plugin-playbooks/pull/1563 and https://github.com/mattermost/mattermost-plugin-playbooks/pull/1556

**This is a POC to experiment/learn with state management** 

As scenario we usually play with a complex state: 
- level state and server state
- there're different interactions: live local save + cta to remote save, local&server save at the same time, double-save with control + modal.
- updates sometimes rely on receiving websockets

Some of the problems we use to deal with:
- you can cancel and changes are saved anyway
- if WS fail UI loses ability to update, if endpoint is slow, UI takes time too to update

I followed @calebroseland suggestions and played a bit with useProxyState. This code assumes that useProxyState can be used without onChange param.

Handle local state which triggers also a remote side effect to effectively persist in the server.

Several doubts and next steps are added inline as comments.

## Ticket Link
Related https://mattermost.atlassian.net/browse/MM-48857

## Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2022-12-09 15:41 UTC, trilopin commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                console.error(response.error); // eslint-disable-line no-console
Would make sense to revert the local change when the remote has errored?

2022-12-09 15:44 UTC, trilopin commented on webapp/src/components/checklist_item/checklist_item.tsx
> +                            saveTaskActions(taskActions);
This works perfectly but it's a bit ugly, 3 requests to make updates even if only 1 param has changed.

I'd be inclined to create the updateChecklistItem as a GQL mutation (as updateRun or updatePlaybook) and accept optionally all fields in one only mutation.

2022-12-09 16:14 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/edit/task_actions_spec.js
> +            editTask();
For the task actions modal, the experience is still weird because we have to click two Save CTA to make it really persist (before it saved in first no matter what you clicked in the second 😂 ).

I fixed the e2e just because I wanted them in green, but we need to think better about this one.

2022-12-09 17:07 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/edit/task_actions_spec.js
> +            editTask();
oh, run task actions e2e are still red :(

2022-12-09 23:39 UTC, calebroseland requested changes
This is great, @trilopin! I pushed 1 change, fixed the e2e for that other spec, and there's just 2 questions, otherwise I think this is looking pretty good on the technical side. (I agree some things could be better on the UX flows)

2022-12-09 23:39 UTC, calebroseland commented on webapp/src/components/checklist_item/checklist_item.tsx
> +    }, [props.checklistItem.task_actions]);
Is this needed with `useProxyState(props.checklistItem.task_actions ...` below?

2022-12-09 23:39 UTC, calebroseland commented on webapp/src/components/checklist_item/checklist_item.tsx
>          }
Same here with this above

```tsx
        if (props.newItem || isEditing) {
            return;
        }
        
```

2022-12-09 23:39 UTC, calebroseland commented on tests-e2e/cypress/integration/playbooks/edit/task_actions_spec.js
> +            editTask();
> For the task actions modal, the experience is still weird because we have to click two Save CTA to make it really persist (before it saved in first no matter what you clicked in the second 😂 ).

+1

2023-02-14 21:35 UTC, lieut-data commented
Closing this out for now as we revisit the feature set for Playbooks.

2023-02-14 21:35 UTC, closed without merging