PR Template: add optional details section
mattermost/mattermost-plugin-playbooks pull request #1684
Opened 2022-12-15 22:15 UTC by calebroseland

## Summary
Amends the PR template to include an optional Details section with copiable examples.

## Ticket Link
None

## Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2022-12-16 08:16 UTC, trilopin approved these changes

2022-12-16 16:03 UTC, lieut-data requested changes
I'm supportive of the general direction, but worried about making things too complicated. I already spend time deleting all of this when pushing up my PRs and reformatting manually, but of course see the value in helping first-time committers. Some thoughts inline.

2022-12-16 16:03 UTC, lieut-data commented on .github/PULL_REQUEST_TEMPLATE.md
> +- d77ea0dd3491882e8ba3d25bea6017232a87385b: changes this other thing
nit: each commit should already be self-described in the commits tab, right?

2022-12-16 16:03 UTC, lieut-data commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Details
Is the title then already functioning as the summary? I've almost always jumped into the description section from the first paragraph, but just aimed to "keep it short".

2023-02-14 21:35 UTC, lieut-data commented
Closing this out for now.

2023-02-14 21:35 UTC, closed without merging