MM-48599 Improve toast for participating in a run
mattermost/mattermost-plugin-playbooks pull request #1708
Opened 2023-01-04 16:59 UTC by m-ripper

## Summary

Increased the duration the toast for participating in a run is shown from 3 to 4.5 seconds. 

Additionally, toasts with a `buttonCallback` will not be hidden while hovered. 
This behavior can be disabled by setting `interactive` to `false` for the toast.

[Screencast from 04.01.2023 17:54:43.webm](https://user-images.githubusercontent.com/8669935/210608030-39b7800e-5c77-49de-91b0-652c250313be.webm)

## Ticket Link

[MM-48599](https://mattermost.atlassian.net/browse/MM-48599)

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2023-01-04 22:32 UTC, calebroseland approved these changes
LGTM! Just a super tiny whitespace nit

2023-01-04 22:32 UTC, calebroseland commented on webapp/src/components/backstage/toast_banner.tsx
> +const toastTimeoutMap :Record<number, number> = {};
```suggestion
const toastTimeoutMap: Record<number, number> = {};
```

2023-01-05 19:22 UTC, crspeller requested changes
In addition I am wondering what happens if you spam the join button a bunch of times. Does this cause any strangeness? Was having an issue with that.

2023-01-05 19:22 UTC, crspeller commented on webapp/src/components/backstage/toast.tsx
> +    interactive?: boolean;
Why the interactive flag? Seems fine to hold the toast open for non-interactive toasts if the mouse is on it. We can remove the `?` in this case. We also don't seem to set the flag anywhere?

2023-01-06 14:28 UTC, abhijit-singh approved these changes
Looks good to me, thanks @m-ripper!

2023-01-06 14:38 UTC, m-ripper commented
> In addition I am wondering what happens if you spam the join button a bunch of times. Does this cause any strangeness? Was having an issue with that.

@crspeller I figured out the strangeness was caused because `lodash.debounce` was used which resets the timer with every call, therefore a second toast could only be added if the user waited 2 seconds before triggering the toast again.
I've changed this to use `lodash.throttle` instead which makes sure that the user can trigger the toast every 4.5 seconds which means that there should only be a single toast at all times if the user doesn't hover over them.

2023-01-09 16:03 UTC, crspeller approved these changes

2023-01-10 15:21 UTC, merged