MM-48582 Playbook import via drag and drop
mattermost/mattermost-plugin-playbooks pull request #1712
Opened 2023-01-09 17:43 UTC by m-ripper

## Summary

Playbooks can be imported by dropping a file onto the import buttons.

Additionally, the LHS is now refreshed when a playbook is imported.

So far there is no indicator that this feature exists but this will be implemented in a different PR.

[Screencast from 09.01.2023 18:38:35.webm](https://user-images.githubusercontent.com/8669935/211372120-c9d8c8ca-da4c-453f-9fa3-51e4230e48bd.webm)

[Screencast from 09.01.2023 18:38:48.webm](https://user-images.githubusercontent.com/8669935/211372129-c2fae8e7-78d8-47e3-b603-f1433c86626e.webm)

## Ticket Link

[MM-48582](https://mattermost.atlassian.net/browse/MM-48582)

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2023-01-10 11:43 UTC, trilopin requested changes
Good job Max,

How hard would be to do the style change to visually tell the user that the import button is the drop area when drag start?

Please check the tiny details I wrote.

2023-01-10 11:43 UTC, trilopin commented on tests-e2e/cypress/integration/playbooks/list_spec.js
> +                    action: 'drag-drop'
TIL 🎉

2023-01-10 11:43 UTC, trilopin commented on webapp/src/components/backstage/import_playbook.tsx
> +        readFile(e.target.files[0])
would make sense to limit the file size before reading the file and handle it as a user-readable error?

2023-01-10 11:43 UTC, trilopin commented on webapp/src/components/backstage/import_playbook.tsx
> +        if (!e.target.files?.[0]) {
what happens if the user drop more than one file?

2023-01-10 11:43 UTC, trilopin commented on webapp/src/components/backstage/import_playbook.tsx
> +        if (!e.target.files?.[0]) {
I tested, the first is imported, rest are ignored. Could we fail with an explicit error when more than 1 file is uploaded?

2023-01-10 12:41 UTC, m-ripper commented on webapp/src/components/backstage/import_playbook.tsx
> +        readFile(e.target.files[0])
That's probably a good idea. What file size were you thinking about if you had any in mind so far?

2023-01-12 15:57 UTC, m-ripper commented
I've added a visual indicator for the dropzone and updated the video above. I'm 2/5 in regards of the UX that the dropzone gets shown when the user drags a file to any part of the page. In Channels, it is only shown when dragged into the dropzone.

2023-01-12 16:24 UTC, m-ripper commented on webapp/src/components/assets/files_overlay_image.tsx
> +const source = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAABrCAMAAAAW2X0YAAAC9FBMVEUAAAAAAAAAAAD////Ozs4AAAABAQHPz8/GxsYAAADMzMwAAADv7+/6+vri4uIAAAAAAAD7+/v////+/v78/Pz29vbNzc0AAAAAAAAAAAD9/
I don't like this solution, but didn't find a better one at the moment. I want to use [this image](https://github.com/mattermost/mattermost-webapp/blob/master/images/filesOverlay.png) that is already included in the webapp but due to hashes I cannot use the already existing one. 

The Plugin API doesn't seem to support adding static files from a plugin, that's why I am using a base64 version of the the image, but maybe I am missing something. If there's a SVG version of the image, I will use it instead.

2023-01-12 23:05 UTC, calebroseland commented on webapp/src/components/assets/files_overlay_image.tsx
> +const source = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAABrCAMAAAAW2X0YAAAC9FBMVEUAAAAAAAAAAAD////Ozs4AAAABAQHPz8/GxsYAAADMzMwAAADv7+/6+vri4uIAAAAAAAD7+/v////+/v78/Pz29vbNzc0AAAAAAAAAAAD9/
I pushed a small fix to the webpack config that should support PNGs now—same outcome as what you have, just avoids having to do it manually. I think they have to be inlined because I think the current mattermost-server plugin build/flow that playbooks is in doesn't support URL resources (or other webpack chunks).

2023-01-12 23:10 UTC, calebroseland approved these changes
Awesome work @m-ripper! Thanks for the expanded indicators.

One thought on a helpful error message if you try to upload an unsupported file type, but not essential so feel free to proceed without.

2023-01-12 23:10 UTC, calebroseland commented on webapp/src/components/assets/files_overlay_image.tsx
> +const source = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAABrCAMAAAAW2X0YAAAC9FBMVEUAAAAAAAAAAAD////Ozs4AAAABAQHPz8/GxsYAAADMzMwAAADv7+/6+vri4uIAAAAAAAD7+/v////+/v78/Pz29vbNzc0AAAAAAAAAAAD9/
e.g. 
```suggestion
import source from './files_overlay.png';
```

2023-01-12 23:10 UTC, calebroseland commented on webapp/src/components/backstage/import_playbook.tsx
> +        }
```suggestion
        }
        if (file.type !== 'application/json') {
            addToast({
                content: formatMessage({defaultMessage: 'The file must be a valid JSON playbook template.'}),
                toastStyle: ToastStyle.Failure,
            });
            reject(new Error('File must be a JSON file'));
            return;
        }
```

2023-01-13 10:31 UTC, abhijit-singh approved these changes
Love it @m-ripper!

2023-01-13 11:16 UTC, trilopin approved these changes
Good job @m-ripper 

Non blocking suggestion regarding messages accuracy

2023-01-16 11:36 UTC, merged