feat(ci): Migrate CircleCI to Github Actions
mattermost/mattermost-plugin-playbooks pull request #1713
Opened 2023-01-10 12:36 UTC by toninis

## Summary

Migrate CircleCI to Github Actions 
- Use services for DB integration tests
- Use reusable composite actions for repeated steps

## Ticket Link

https://mattermost.atlassian.net/browse/CLD-4810

2023-01-10 12:41 UTC, spirosoik reviewed
good job first PR ;), few minor comments

2023-01-10 12:41 UTC, spirosoik commented on .github/actions/test-with-db/action.yaml
> +name: "test-with-db"
wondering if we should make this a dependency of the main CI flow

2023-01-10 12:42 UTC, phoinixgrr reviewed
Awesome work 🚀 🎖️ 🏅 🥇 
Left some minor comments

2023-01-10 12:42 UTC, phoinixgrr commented on .github/actions/test-with-db/action.yaml
> +      uses: actions/setup-go@v3
Are we going to SHA pin external actions?

2023-01-10 12:42 UTC, phoinixgrr commented on .github/workflows/ci.yaml
> +            git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)..HEAD >> dist/release-notes.md
Could we use this bad boy: https://github.com/marketplace/actions/generate-release-changelog  , to streamline this and remove this clutter?

2023-01-10 14:25 UTC, toninis commented on .github/actions/test-with-db/action.yaml
> +name: "test-with-db"
what do you mean ? add it on the https://github.com/mattermost/actions repo ?

2023-01-10 14:25 UTC, toninis commented on .github/actions/test-with-db/action.yaml
> +      uses: actions/setup-go@v3
Will do

2023-01-10 14:33 UTC, phoinixgrr commented
/check-cla

2023-01-10 14:34 UTC, toninis commented
/check-cla

2023-01-11 08:37 UTC, toninis commented on .github/workflows/ci.yaml
> +            git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)..HEAD >> dist/release-notes.md
Community is widely using [this](https://github.com/softprops/action-gh-release) since the official from Github was archived for some reason .

I suggest we migrate as is right now and re evaluate with proper Release notes across all repos

2023-01-11 08:37 UTC, toninis commented
/check-cla

2023-01-11 08:50 UTC, phoinixgrr commented on .github/workflows/ci.yaml
> +            git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)..HEAD >> dist/release-notes.md
Makes sense

2023-01-12 19:46 UTC, lieut-data commented
@toninis, heads up that I've just merged a fix that addresses some e2e flakiness. Feel free to merge `master` if that helps with your efforts here :)

2023-01-13 07:29 UTC, toninis commented
/update-branch

2023-01-13 08:47 UTC, toninis commented
@lieut-data Thanks mate this was great . I also see a lot of 
```
CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `gqlPlaybookLHS`. No request ever occurred.
```
Is this normal ?

2023-01-13 13:50 UTC, lieut-data commented
> @lieut-data Thanks mate this was great . I also see a lot of
> 
> ```
> CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `gqlPlaybookLHS`. No request ever occurred.
> ```
> 
> Is this normal ?

Hmm, no, that doesn't sound normal @toninis. I took a look at recent, successful CircleCI runs to confirm.

2023-01-13 14:30 UTC, toninis commented
> > @lieut-data Thanks mate this was great . I also see a lot of
> > ```
> > CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `gqlPlaybookLHS`. No request ever occurred.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this normal ?
> 
> Hmm, no, that doesn't sound normal @toninis. I took a look at recent, successful CircleCI runs to confirm.

Cool . I am trying to figure out if this is a resources issue since from 8 cores on CircleCI we stepped down to 2 .

2023-01-16 10:29 UTC, spirosoik commented on .github/actions/test-with-db/action.yaml
> +name: "test-with-db"
forget my comment, I just realised that it's composite. nice!!!

2023-01-16 13:07 UTC, phoinixgrr approved these changes

2023-01-16 16:26 UTC, lieut-data commented
@toninis, small nit: can you help [avoid force pushes](https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing) to PRs up for review? I find reviewers have an easier time consuming the incremental diffs, and since we squash on merge, it all gets nicely cleaned up anyway.

2023-01-16 16:28 UTC, lieut-data commented
> The /e2e-test is not applied yet . We would like to introduce this functionality since e2e tests take too long and require too many resources . By controlling when we are going to execute the e2e tests we will reduce costs.

@toninis / @spirosoik, would the idea be to switch to manual invocation but still require them for each PR before merging? I'm wondering what guidance we'll offer developers who want to know the results of their push but before a PR is officially opened. (I often rely on CI to run my suite faster than I can feasibly run it locally.)

2023-01-16 17:15 UTC, lieut-data requested changes
Thanks so much, @toninis! A handful of code review comments. Also a few high-level questions:

1. I don't actually see any of the artifacts being saved, i.e. the videos or such. Am I looking in the wrong place?
<img width="681" alt="CleanShot 2023-01-16 at 13 11 13@2x" src="https://user-images.githubusercontent.com/1023171/212734044-fc38499f-4c05-421a-b788-f0c848a6bb8a.png">

2. Is it possible to rename the split test invocation to something like `#1`, `#2`, if only to be able to refer to them more readily?
<img width="872" alt="CleanShot 2023-01-16 at 13 09 59@2x" src="https://user-images.githubusercontent.com/1023171/212734103-fb7afe13-3de1-4dca-bd45-a62462e95cfb.png">

3. At least one of the tests is actually failing, but doesn't seem to be getting caught by the CI, incorrectly marking is as successful:
<img width="1233" alt="CleanShot 2023-01-16 at 13 12 13@2x" src="https://user-images.githubusercontent.com/1023171/212734168-e78d2fcd-d07f-4595-81cf-e842e134b7eb.png">

4. Lastly, where can we view the summary of tests run and their pass / fail status?

2023-01-16 17:15 UTC, lieut-data commented on .github/actions/generate-specs/split-tests.go
> +		}
`err` hasn't changed here -- were you wanting to check the result of `regexp.Compile`? I'd suggest pulling this out into a top-level `var` and just use `MustCompile` instead.

2023-01-16 17:15 UTC, lieut-data commented on .github/workflows/cd.yaml
> +    if: ${{ github.ref_name  == 'master' }}
```suggestion
    if: ${{ github.ref_name == 'master' }}
```

2023-01-16 17:30 UTC, spirosoik commented
@toninis we started recently adopt slow architecture decision records, check [here](https://github.com/joelparkerhenderson/architecture-decision-record). I think it will be good to include the decisions/compromised we collective took here. We have some examples already, ping me or @phoinixgrr to share.

cc @lieut-data

2023-01-17 07:59 UTC, toninis commented
> @toninis, small nit: can you help [avoid force pushes](https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing) to PRs up for review? I find reviewers have an easier time consuming the incremental diffs, and since we squash on merge, it all gets nicely cleaned up anyway.

Sorry for this mate . Bad habit . Thanks for noticing 😄

2023-01-17 09:13 UTC, phoinixgrr commented
> @toninis, small nit: can you help [avoid force pushes](https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing) to PRs up for review? I find reviewers have an easier time consuming the incremental diffs, and since we squash on merge, it all gets nicely cleaned up anyway.

I would consider this more as a personal preference, than best practise. Indeed if we are squashing on merge, it makes no difference. But rebasing on merge, makes world of a difference, merging a clear git commit history. 

By the way, There is always the "Compare" button functionality provided by GitHub, that can help in these situations. I find that it can quickly present any changes force pushed, comparing with before. 


<img width="879" alt="Screenshot 2023-01-17 at 11 08 02" src="https://user-images.githubusercontent.com/36594156/212856470-2056fb6d-a57a-49ab-b5f0-ec95fb8c61cb.png">

2023-01-17 09:14 UTC, toninis commented
> > @toninis, small nit: can you help [avoid force pushes](https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing) to PRs up for review? I find reviewers have an easier time consuming the incremental diffs, and since we squash on merge, it all gets nicely cleaned up anyway.
> 
> I would consider this more as a personal preference, than best practise. Indeed if we are squashing on merge, it makes no difference. But rebasing on merge, makes world of a difference, merging a clear git commit history.
> 
> By the way, There is always the "Compare" button functionality provided by GitHub, that can help in these situations. I find that it can quickly present any changes force pushed, comparing with before.
> 
> <img alt="Screenshot 2023-01-17 at 11 08 02" width="879" src="https://user-images.githubusercontent.com/36594156/212856470-2056fb6d-a57a-49ab-b5f0-ec95fb8c61cb.png">

Yeah you are right . The one thing that force push does is the removal of the progress on the PR review and this is bad . I do not like this either 😄

2023-01-17 13:10 UTC, toninis commented
@lieut-data Thanks for the thorough review 😄 

1. All test results are bundled under `cypress-test-results` zipped file at the end of the run . [This](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1713/files#diff-d496110c4b13634034d0bf0df877eb43154becd7200135066d2b09afdc7c9ff6R94) step does the job . You can download this to check all the contents (mp4,junit)
2. I can yes . I need to change the logic and create a dictionary rather than a list . I left it as is so that you can see the specs tested on the current run . 
3. I intentionally configured it with continue-on-error [here](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1713/files#diff-d496110c4b13634034d0bf0df877eb43154becd7200135066d2b09afdc7c9ff6R92)  because if the tests fail the results are not uploaded  . I will fix this though for proper visibility , I will fail the task afterwards .
4. Unfortunately this is not supported by Github as it is on CircleCI . My idea was after the first iteration (migrate as is the pipeline to GHA) to create a custom message commenting the failed tests by parsing them from cypress output .

Any other thoughts are welcome . 
cc: @mattermost/core-build-engineers

2023-01-17 13:12 UTC, toninis commented on .github/actions/e2e-test/action.yaml
> +        cache: true
It automatically gets the version from go.mod file . Check [here](https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file)

2023-01-17 13:14 UTC, toninis commented on .github/actions/e2e-test/action.yaml
> +        sudo apt-get install libxss1 postgresql-client -y
Yep my thought also . I tried but it's a bit sketchy to run a script on an image without an entrypoint . I will try to make this work

2023-01-17 13:15 UTC, toninis commented on .github/actions/e2e-test/action.yaml
> +        sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
Yep . Creating a base action with all the necessary dependencies should be better . We need to find a way from this to be easily configurable though

2023-01-17 13:15 UTC, toninis commented on .github/actions/e2e-test/action.yaml
> +        retention-days: 5 ## No need to keep CI builds more than 5 days
Yep . Can do for sure

2023-01-17 14:12 UTC, toninis commented on .github/actions/e2e-test/action.yaml
> +
I would suggest to just create a small golang script to perform this API call for better control also . I saw some erroneous failures from the API calls . WDYT ? 
cc: @mattermost/core-build-engineers

2023-01-17 14:12 UTC, toninis commented on .github/actions/generate-specs/split-tests.go
> +		}
Missed that . Nice one 👍🏼

2023-01-17 16:34 UTC, lieut-data commented on .github/actions/e2e-test/action.yaml
> +        cache: true
Ah, even better! Nice :)

2023-01-17 16:36 UTC, lieut-data commented on .github/actions/e2e-test/action.yaml
> +
Indeed, we've found the `trial-license` endpoint often fails upstream, and it's something on the growth team's radar. 0/5 on whether a Go script would be better for how we organize the code for CI.

2023-01-17 19:44 UTC, lieut-data commented
>     1. All test results are bundled under `cypress-test-results` zipped file at the end of the run . [This](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1713/files#diff-d496110c4b13634034d0bf0df877eb43154becd7200135066d2b09afdc7c9ff6R94) step does the job . You can download this to check all the contents (mp4,junit)

Aha, that makes sense. Is it huge inconvenience if we keep them as separate artifacts for easier browsing? We often dig into these when a failure occurs, linking directly to the videos or such.

>     2. I can yes . I need to change the logic and create a dictionary rather than a list . I left it as is so that you can see the specs tested on the current run .

If I /could/ see all the specs in the current run, that might make sense, but it seems like all I really get is the first spec, with everything else being ellipsized anyway.

>     3. I intentionally configured it with continue-on-error [here](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1713/files#diff-d496110c4b13634034d0bf0df877eb43154becd7200135066d2b09afdc7c9ff6R92)  because if the tests fail the results are not uploaded  . I will fix this though for proper visibility , I will fail the task afterwards .

Oh, I see! Yeah, it would be awesome to fail and upload the test results if possible.

>     4. Unfortunately this is not supported by Github as it is on CircleCI . My idea was after the first iteration (migrate as is the pipeline to GHA) to create a custom message commenting the failed tests by parsing them from cypress output .

Understood. This will be a relatively big pain to lose the detailed visibility, but perhaps I can work something out to just subscribe to CypressIO or engage @saturninoabril's team to figure out a way to use their tooling.

Thanks for the focused effort, @toninis!

2023-01-18 10:57 UTC, toninis commented
/update-branch

2023-01-19 06:12 UTC, saturninoabril commented
> subscribe to CypressIO or engage @saturninoabril's team to figure out a way to use their tooling

Yup, we can help with it. Our tool right now (automation dashboard) is good for orchestrating specs for parallel jobs. The downside, it's not currently saving video artifacts but we'll add soon.

2023-01-19 08:06 UTC, toninis commented
> > subscribe to CypressIO or engage @saturninoabril's team to figure out a way to use their tooling
> 
> Yup, we can help with it. Our tool right now (automation dashboard) is good for orchestrating specs for parallel jobs. The downside, it's not currently saving video artifacts but we'll add soon.

Do we have a Cypress Cloud account ? We can easily integrate the pipelines with it . That would be great and more efficient for you !!

2023-01-19 08:37 UTC, saturninoabril commented
We don’t have in Platform but not sure if Playbooks or other teams have or are using it. Last time we evaluated the product, it lacked the feature we’d specifically require for parallel testing. They do have a parallel test feature but it didn’t fit with our requirements since for us, each runner (Cypress agent) has its own test server for isolation (with each spec potentially changing server’s config setting, admin user preference, plugins, services, etc). I do agree about the benefits of its Dashboard but it could be very expensive as well, especially as we go with the idea of monorepo. Test results of 10K can easily be exhausted just by running a handful of PRs (~ <10), currently.

2023-01-19 15:15 UTC, toninis commented
@mattermost/core-build-engineers @lieut-data  In order to finalize this PR we need to provide more resources to the pipelines . In my tests I saw that the e2e tests need at least 6 cores and 6GB of memory to run smoothly . 

We will continue internally and revert back .

2023-01-19 15:56 UTC, lieut-data commented
> We don’t have in Platform but not sure if Playbooks or other teams have or are using it. Last time we evaluated the product, it lacked the feature we’d specifically require for parallel testing. They do have a parallel test feature but it didn’t fit with our requirements since for us, each runner (Cypress agent) has its own test server for isolation (with each spec potentially changing server’s config setting, admin user preference, plugins, services, etc). 

We aren't currently using CypressIO -- Cass having found a way to do the "smart" parallelization entirely within CircleCI -- but I've eyed it as an option before, simply because it seems so well integrated.

FWIW, Playbooks also has a test server for isolation, but we aren't doing anything "special" to parallelize here. I'd love to better understand the CypressIO limitations in case we go for that in the short term.

>  I do agree about the benefits of its Dashboard but it could be very expensive as well, especially as we go with the idea of monorepo. Test results of 10K can easily be exhausted just by running a handful of PRs (~ <10), currently.

Agreed, the costs could be prohibitive here. I'm wondering if https://sorry-cypress.dev/ would be a drop-in, self-hosted replacement we might pursue (perhaps even starting with /their/ hosted offering at much lower prices).

Anyway, I'll find time for you and I to sync, @saturninoabril, so we can discuss next steps :)

2023-01-19 16:24 UTC, toninis commented
> 

The https://sorry-cypress.dev/ thingy seems really promising . We can give it a try if you feel like it in a next iteration . Nice 👍🏼

2023-01-20 18:02 UTC, lieut-data requested changes
Thanks @toninis, some discussion on the `/e2e-test` document, but only blocking on the large commented block in `.github/worksflows/ci.yaml` before we aim to merge.

2023-01-20 18:02 UTC, lieut-data commented on docs/adr/0001-use-command-for-e2e-tests.md
> +![e2e](assets/e2e-test-ci-workflow.jpeg)
I can't comment directly on the picture, but the proposed flow is counter to how we do pull requests: with developers preferring to wait until tests pass before spending time reviewing the PR.

I realize this is potentially complicated for community PRs where we'd like a degree of protection against malicious or wasteful tests. I fully support `/e2e-test` for forked branches as such, but would propose we keep doing things automatically for staff contributions.

2023-01-23 06:39 UTC, toninis commented on .github/workflows/ci.yaml
> +  # lint:
No I was just testing . The pipeline is ready 😄 . I will uncomment everything once we end our discussion

2023-01-23 16:00 UTC, toninis commented on docs/adr/0001-use-command-for-e2e-tests.md
> +Analyzing our pipelines we figured out that integration tests take too much time and are resource hungry. We want to introduce a new process to mitigate the cost and provide a more user friendly deve
Yep . We are discussing internally for this

2023-01-23 16:00 UTC, toninis commented on docs/adr/0001-use-command-for-e2e-tests.md
> +We want to introduce a custom PR command `/e2e-test` in order to manually trigger integration tests. The idea is similar to mattermod command introduced [here](https://github.com/mattermost/mattermos
We are trying to tackle all considerations and be security compliant at the same time . We will get back to you

2023-01-23 17:51 UTC, lieut-data commented on docs/adr/0001-use-command-for-e2e-tests.md
> +Analyzing our pipelines we figured out that integration tests take too much time and are resource hungry. We want to introduce a new process to mitigate the cost and provide a more user friendly deve
Thanks, @toninis! Would you be able to point link to the relevant conversation -- I assuming it's in Mattermost?

2023-02-15 10:41 UTC, toninis commented
/update-branch

2023-02-15 13:12 UTC, toninis commented
@lieut-data We implemented something like this above in order to match Cypress features . I think this is more than ok . 

> Ignore all those failures these are just on purpose failures in order to demonstrate the functionality . 

You can browse the annotation for the failed tests .

2023-02-15 13:34 UTC, lieut-data commented
This looks great, @toninis! Let's get this merged as soon as it passes and we can iterate from there.

2023-02-15 13:34 UTC, lieut-data approved these changes

2023-02-16 14:21 UTC, toninis commented
@lieut-data We are good to go . We only share the test results if we have failures . If you want this behaviour to change we can just do it . 
I fixed the issue with the files by installing the correct version of mocha-junit-reporter [here](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1713/files#diff-fa756e83d949189c1d35202753e07aa84e79d48d30f9350ddc5e601b3016c401R34) . 

We are good to go . I will disable CircleCI builds and merge this when you are ready

2023-02-16 14:29 UTC, merged

2023-02-16 14:31 UTC, lieut-data commented
Awesome, thanks again @toninis!