MM-49791: Disable edit summary after run finished
mattermost/mattermost-plugin-playbooks pull request #1762
Opened 2023-01-25 18:46 UTC by lieut-data

## Summary
This is a client-side only change to disable the functionality for editing a run summary after a run has finished. The GraphQL endpoint currently seems to allow edits regardless, and I didn't want to tackle locking that down here.

## Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-49791

2023-01-25 18:59 UTC, trilopin requested changes
Shouldn't we also disable summary editing in the channels RHS when the run is finished?

2023-01-25 20:28 UTC, lieut-data commented
You're right, @trilopin! Updated :)

2023-01-26 09:05 UTC, gbochora commented on tests-e2e/cypress/integration/channels/rhs/header_spec.js
> +            // # verify textarea does not appear
Nit:
```suggestion
            // * Verify textarea does not appear
```

2023-01-26 09:29 UTC, gbochora approved these changes
Nice!

2023-01-26 09:29 UTC, gbochora commented on tests-e2e/cypress/integration/channels/rhs/header_spec.js
> +            // # verify textarea does not appear
Nit:
```suggestion
            // * Verify textarea does not appear
```

2023-01-26 09:29 UTC, gbochora commented on tests-e2e/cypress/integration/channels/rhs/header_spec.js
> +            // # Verify no prompt to join appears (timeout ensures it fails right away before toast disappears)
```suggestion
            // * Verify no prompt to join appears (timeout ensures it fails right away before toast disappears)
```

2023-01-26 09:29 UTC, gbochora commented on tests-e2e/cypress/integration/channels/rhs/header_spec.js
> +            // # verify the menu items
```suggestion
            // * Verify the menu items
```

2023-01-26 09:29 UTC, gbochora commented on tests-e2e/cypress/integration/channels/rhs/header_spec.js
> +            // # Verify no prompt to join appears (timeout ensures it fails right away before toast disappears)
```suggestion
            // * Verify no prompt to join appears (timeout ensures it fails right away before toast disappears)
```

2023-01-26 09:58 UTC, trilopin approved these changes

2023-01-26 12:36 UTC, merged