GH-1723 New RHS landing page and blank state
mattermost/mattermost-plugin-playbooks pull request #1782
Opened 2023-01-27 15:24 UTC by m-ripper

## Summary

Updates the RHS landing page in preparation for channel checklists. 

Added new blank state

![Screenshot from 2023-01-27 16-21-50](https://user-images.githubusercontent.com/8669935/215122464-310d75a8-7c44-4c28-afbd-2754e9788c9b.png)

Updated empty state

![Screenshot from 2023-01-27 16-22-15](https://user-images.githubusercontent.com/8669935/215122438-c8670987-5cb0-4366-96a5-46741b984d36.png)

Updated default state

![Screenshot from 2023-01-27 16-22-07](https://user-images.githubusercontent.com/8669935/215122447-08f9490b-4617-4556-bc10-84de7f9d46cc.png)

## Ticket Link

Fixes #1722 
Fixes #1723 

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2023-01-31 14:47 UTC, calebroseland requested changes
🚀 Great work! I don't see any UI issues, and just one UX/flow inconsistency when `currentChannelId` is blank.

2023-01-31 14:47 UTC, calebroseland commented on webapp/src/components/rhs/rhs_main.tsx
> -    }
When in Insights or Threads, Checklists RHS shows all runs from all teams and channels. Presumably this is because `currentChannelId` is `''` in that case, so it might not be filtering correctly. We should probably handle that to contain things properly in respective channels/teams.

2023-02-11 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-02-15 15:08 UTC, lieut-data commented
We're shifting priorities on Playbooks features, and have decided not to ship Channel Checklists at this time. Thanks again, @m-ripper!

2023-02-15 15:08 UTC, closed without merging