GH-1726 Update run details view style
mattermost/mattermost-plugin-playbooks pull request #1786
Opened 2023-01-30 17:44 UTC by m-ripper

## Summary

Update style of run details view: Remove hard-coded height and implement smaller tweaks.

## Ticket Link

Fixes #1726 

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2023-02-05 13:42 UTC, iomodo requested changes
Looks good @m-ripper 
We should change the header to show the title right?

2023-02-05 13:42 UTC, iomodo commented on webapp/src/components/assets/icons/external_link.tsx
> -            fillOpacity='0.48'
why remove this?

2023-02-06 12:40 UTC, m-ripper commented on webapp/src/components/assets/icons/external_link.tsx
> -            fillOpacity='0.48'
I've talked about the header with @abhijit-singh and we came to the conclusion that the title in the header is not really useful because the title can be quite long and the header space is quite narrow.  Also, we didn't have a nice solution for renaming. 

About the removed fillOpacity: This caused the icon to always seem lighter than it actually is. This way it's easier to replicate the color that is used in the designs.

2023-02-15 15:13 UTC, lieut-data commented
Skipping this in line with the shifting priorities on Playbooks features.

2023-02-15 15:13 UTC, closed without merging