MM-50738 Remove keyword prompt post instead of editing it.
mattermost/mattermost-plugin-playbooks pull request #1821
Opened 2023-02-24 17:48 UTC by crspeller

## Summary
Removes the editing of the keyword prompt action post and instead deletes it, leaving the notifications of run creation to the regular channels. 

## Ticket Link
https://mattermost.atlassian.net/browse/MM-50738

2023-02-27 19:59 UTC, trilopin requested changes
Thanks @crspeller, I left a couple of comments and questions.

I've tested manually and it works perfectly 🎉.

A server test api_signal_test to check that the post is correctly deleted would be highly appreciated.

2023-02-27 19:59 UTC, trilopin commented on server/api/signal.go
> +	if err := h.api.Post.DeletePost(req.PostId); err != nil {
you call `returnJSON` before DeletePost, is that intended?

2023-02-27 19:59 UTC, trilopin commented on server/api/playbook_runs.go
> -	post.Message = fmt.Sprintf("@%s started the run [%s](%s) using the [%s](%s) playbook.",
1/5 wouldn't be useful to insert the content of the post not as edit but as a new post to still communicate the trigger-result in the channel?

2023-02-27 19:59 UTC, trilopin commented on server/api/signal.go
> +	if err := h.api.Post.DeletePost(req.PostId); err != nil {
silly question, do DeletePost handle permissions, what if this method is called with an arbitrary req.postId, would it be deleted? should we check that the author is playbooksBot?

2023-02-27 22:19 UTC, crspeller commented on server/api/signal.go
> +	if err := h.api.Post.DeletePost(req.PostId); err != nil {
Just following the form of the `ignoreKeywords` handler that does this. I don't think it matters. 

No that's a good question. You can't call this endpoint without a valid triggerid it will fail before it gets to the deletion portion.

2023-02-27 22:20 UTC, crspeller commented on server/api/playbook_runs.go
> -	post.Message = fmt.Sprintf("@%s started the run [%s](%s) using the [%s](%s) playbook.",
I think there are already plenty of notification mechanisms for run start. (it does post an ephemeral message)

2023-02-28 10:34 UTC, trilopin approved these changes
unblocking here

server test still desired ❤️

2023-03-02 00:10 UTC, calebroseland approved these changes

2023-03-07 13:15 UTC, jupenur approved these changes

2023-03-07 20:15 UTC, merged