Fix team run team interaction.
mattermost/mattermost-plugin-playbooks pull request #1878
Opened 2023-10-27 22:59 UTC by crspeller

2023-10-30 19:18 UTC, lieut-data approved these changes

2023-11-01 17:52 UTC, esarafianou requested changes

2023-11-01 17:52 UTC, esarafianou commented on server/api_runs_test.go
> +		err = e.PlaybooksClient.PlaybookRuns.UpdateStatus(context.Background(), e.BasicRun.ID, "update", 600)
UpdateStatus doesn't call the `POST /plugins/playbooks/api/v0/runs/<RUN_ID>/update-status-dialog` endpoint. It calls the `runs/<RUN_ID>/status` endpoint which is not what we'd like to test: https://github.com/mattermost/mattermost-plugin-playbooks/blob/a10bb42418667c0f5337f44b39e582f7a8fc81cf/client/playbook_runs.go#L141C27-L141C43.

2023-11-01 17:52 UTC, esarafianou commented on server/app/permissions_service.go
>  func (p *PermissionsService) runManagePropertiesWithPlaybookRun(userID string, run *PlaybookRun) error {
The `POST /plugins/playbooks/api/v0/runs/<RUN_ID>/update-status-dialog` doesn't seem to ever call the `runManagePropertiesWithPlaybookRun` function so this fix won't get applied in that endpoint: https://github.com/mattermost/mattermost-plugin-playbooks/blob/a10bb42418667c0f5337f44b39e582f7a8fc81cf/server/api/playbook_runs.go#L922-L971

2023-11-01 21:02 UTC, crspeller commented on server/app/permissions_service.go
>  func (p *PermissionsService) runManagePropertiesWithPlaybookRun(userID string, run *PlaybookRun) error {
It is a little confusing if you don't know what is going on. There is actually some registered middleware that is taking care of it. You can see it here: https://github.com/mattermost/mattermost-plugin-playbooks/blob/d03dfd8d4e200e8db5c5f64ae05a7ba4b68032fc/server/api/playbook_runs.go#L79

2023-11-01 21:18 UTC, crspeller commented on server/api_runs_test.go
> +		err = e.PlaybooksClient.PlaybookRuns.UpdateStatus(context.Background(), e.BasicRun.ID, "update", 600)
The code paths for checking permissions are identical. The only difference is the input.
However I added a test for it just to be safe.

2023-11-01 21:30 UTC, sbishel approved these changes

2023-11-02 09:51 UTC, esarafianou approved these changes
LGTM!

2023-11-02 09:51 UTC, esarafianou commented on server/app/permissions_service.go
>  func (p *PermissionsService) runManagePropertiesWithPlaybookRun(userID string, run *PlaybookRun) error {
Aah, that makes sense. Thanks for pointing to that! I missed it.

2023-11-02 17:07 UTC, merged