Support the MS Teams Tab App
mattermost/mattermost-plugin-playbooks pull request #1942
Opened 2024-09-13 17:08 UTC by lieut-data

## Summary
This is the "backend" for https://github.com/mattermost/mattermost-teams-tab, allowing colleagues in Teams to connect to a Mattermost server, proving their membership in a configured tenant via the [Microsoft ID token](https://learn.microsoft.com/en-us/entra/identity-platform/id-tokens), and getting read-only access to playbook runs that have explicitly invited the `@msteams` bot.

## Ticket Link

## Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2024-09-13 17:15 UTC, lieut-data commented on client/actions.go
> +	req, err := s.client.newAPIRequest(http.MethodPost, actionURL, opts)
This is the first in a series of `s/newRequest/newAPIRequest/` to allow the `client` package to be used with non-`/api` endpoints.

2024-09-13 17:15 UTC, lieut-data commented on client/tabapp.go
> +	url := fmt.Sprintf("plugins/%s/tabapp/runs", manifestID)
We don't use the `/api` endpoint directly here.

2024-09-13 17:15 UTC, lieut-data commented on go.mod
> +go 1.21
This came for free -- trusting to e2e tests for coverage here.

2024-09-13 17:15 UTC, lieut-data commented on plugin.json
> +  "id": "playbooks",
Noisy because of some whitespace cleanup.

2024-09-13 17:15 UTC, lieut-data commented on server/api/api.go
> +	root.Use(LogRequest)
Moving this to the root to log all requests, not just those on `api/`.

2024-09-13 17:15 UTC, lieut-data commented on server/api/permutation_test.go
> +package api
Copied verbatim from the MS Teams plugin to help with testing permutations -- will lift this to a common place soonish.

2024-09-13 17:15 UTC, lieut-data commented on server/api/tabapp.go
> +	ExpectedAudience        = "api://playbooks.integrations.mattermost.com/8f7d5beb-ed24-4d95-aa31-c26298d5a982"
Both hard-coded to match our production deploy.

2024-09-13 17:15 UTC, lieut-data commented on server/api/tabapp_test.go
> +func TestValidateToken(t *testing.T) {
These unit tests focus on the validation of the token -- I've added top-level tests that focus on the tabapp results themselves.

2024-09-13 17:15 UTC, lieut-data commented on server/api/tabapp_test.go
> +		t.Run("hmac key pretending to be rsa", func(t *testing.T) {
cc @esarafianou

2024-09-13 17:15 UTC, lieut-data commented on server/api_tabapp_test.go
> +		setDeveloperMode(t, true)
We basically only test with developer mode, as we can't spoof a token for the production configuration.

2024-09-13 23:46 UTC, lieut-data commented
Swapping @sbishel for @crspeller given the dual overlap of Playbook and the "Fast Futures" nature of this initiative.

2024-09-16 09:51 UTC, esarafianou reviewed
Thank you Jesse! One comment around Full name and two optional comments

2024-09-16 09:51 UTC, esarafianou commented on .github/workflows/ci.yaml
> +  GO_VERSION: 1.21.13
Since we're updating it here, can we have it match the `mattermost` golang version: https://github.com/mattermost/mattermost/blob/master/server/go.mod#L3-L5 ?

2024-09-16 09:51 UTC, esarafianou commented on go.mod
> +go 1.21
Same comment as above, but only if no additional changes are needed. otherwise bumping to 1.22 can happen independently.

2024-09-16 09:51 UTC, esarafianou requested changes
Marking this as requested changes for the Full name one

2024-09-16 12:57 UTC, lieut-data commented on server/api/tabapp.go
> +			LastName:  user.LastName,
Gah, thank you @esarafianou -- this was the last change I addressed and I should have given this a bit more "brain soak" time. Will address!

2024-09-16 15:22 UTC, esarafianou approved these changes

2024-09-19 16:28 UTC, JulienTant commented on client/tabapp.go
> +	resp.Body.Close()
nit because unsure: errcheck?

2024-09-19 16:28 UTC, JulienTant commented on server/tabapp.go
> +		}
If the MSTeams plugin is not installed, and as a consequence we don't have the MSTeams bot, what's the advantage of creating a MSTeams bot here instead of using the Playbooks one?

I'm just thinking if the name of the MSTeams bot has to be changed for some reason or we want to update the avatar for the bot, we'll have to remember to do it everywhere 😅

2024-09-19 16:31 UTC, JulienTant approved these changes
Sorry it took me a minute to review. Swapping my review into "Approved" as I don't have anything that is a blocker to move forward.

2024-11-07 07:21 UTC, crspeller requested changes
I don't see any current security problems, however it seems unlikely that we found them all in this unconventional flow. 
I suspect there are some flows around adding users to public channels that would cause some issues here. Adding users to public channels doesn't usually get that much scrutiny since from as security perspective it doesn't change data access. However adding this magic msteams user is now a dangerous action since in a large company msteams access and MM access might be wildly different.

The feature is also really unintuitive. Why would adding some random MS teams user suddenly publish my run publicly to the whole company?

2024-11-07 14:49 UTC, lieut-data commented
> I don't see any current security problems, however it seems unlikely that we found them all in this unconventional flow. 

Thanks, @crspeller! @esarafianou, I know you took a look at the security surface originally: is there anything else we should prioritize given some of this additional context?

> I suspect there are some flows around adding users to public channels that would cause some issues here. Adding users to public channels doesn't usually get that much scrutiny since from as security perspective it doesn't change data access. However adding this magic msteams user is now a dangerous action since in a large company msteams access and MM access might be wildly different.

At the moment the user has to be added as a run participant, and not just a channel member. We do have automation to make run participants into channel members, but I don't believe it happens in the reverse anymore. Can you confirm?

> The feature is also really unintuitive. Why would adding some random MS teams user suddenly publish my run publicly to the whole company?

I agree re: unintuitive. That said, this is much more of a "fast futures" experiment. Given it's behind an explicit plugin configuration as such, can do we anything else to build confidence towards shipping this experiment? I absolutely see us firming up the sharing flow if there's adoption.

2024-11-08 18:36 UTC, crspeller approved these changes
> At the moment the user has to be added as a run participant, and not just a channel member.

Right! That makes sense.

Alright let's consider this to be a FF style experiment and see if we get any signal.

2024-11-09 00:33 UTC, merged