MM-36347 - Fix for spamming users endpoint
mattermost/mattermost-plugin-playbooks pull request #629
Opened 2021-07-10 16:21 UTC by cpoile

#### Summary
- can review by commit
- change how we use `useProfilesInCurrentChannel` so that only the parent calls it; the children just need to use the selector
- fixed the infinite loop just in case
- Note: I tried to have `useProfilesInCurrentChannel` just `useCurrentChannel` and then delegate to the `useProfilesInChannel` hook, but that interacts in a weird way with how we're using react-beautiful-dnd: because we're hiding the drag handle in the hovermenu of our checklist items, react-beautiful-dnd complains it is `unable to find drag handle`. This spits out about 100 console errors normally. When changing `useProfilesInCurrentChannel` to delegate to the `useProfilesInChannel` hook, you get ~1000 console errors. Filed a new bug for the main issue: https://mattermost.atlassian.net/browse/MM-36948 .  When that's fixed, I will simplify these hooks.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-36347

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-07-12 16:15 UTC, lieut-data approved these changes
This looks pretty clean (especially reviewing by commit). @crspeller, any risks that we should consider before merging for v1.14?

2021-07-12 16:33 UTC, agarciamontoro approved these changes
Elegant solution!

2021-07-12 17:33 UTC, crspeller requested changes

2021-07-12 17:33 UTC, crspeller commented on webapp/src/hooks.ts
> +        if (!fetched) {
Won't this not fetch for new channels now?

2021-07-13 13:33 UTC, lieut-data commented on webapp/src/hooks.ts
> +        if (!fetched) {
I ended up resolving this in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/632 by just `profilesInChannel` from the dependency list for `useEffect`. The main underlying problem is that `getProfileSetForChannel` returns a new object every time it's called.

2021-07-13 13:35 UTC, cpoile commented on webapp/src/hooks.ts
> +        if (!fetched) {
@crspeller Ahh, maybe you're right. Need to add `if (channelId !== lastChannelId) { setFetched(false) }` above. Does that make sense? Sorry but do you think you can add that? (I'm not on my work machine)

2021-07-13 13:38 UTC, cpoile commented on webapp/src/hooks.ts
> +        if (!fetched) {
@lieut-data Would the above problem still be there? (when no remounting, and changing to a new channel unseen channel, `fetched` might be set to true)

2021-07-13 13:46 UTC, lieut-data commented on webapp/src/hooks.ts
> +        if (!fetched) {
See linked PR, but by just having `channelId` as a dependency to `useEffect`, it only runs when that channel changes, fetching profiles at most once for a given channel id per component.

2021-09-07 15:35 UTC, closed without merging