MM-36266 - Fix: Incident commander can be changed to the incident bot
mattermost/mattermost-plugin-playbooks pull request #630
Opened 2021-07-10 17:22 UTC by cpoile

#### Summary
- Remove bot from drop down menus, and disallow from command
- Chose to make changing owner or assignee through API be a no-op, to follow how we handle self-assignment

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-36266

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-07-12 16:11 UTC, lieut-data commented
I'm not actually sure we want to disallow this. In fact, I could totally see assigning a run to a bot as a signal for that bot to drive interactions. It could even be an interesting way to build a "plugin" for playbooks.

2021-07-13 10:39 UTC, iomodo approved these changes
Looks great! Thanks @cpoile

2021-07-14 14:59 UTC, lieut-data requested changes
Let's discuss if we actually want to do this. It might be "useless" right now, but it doesn't seem like something we should explicitly disallow.

2021-08-03 13:54 UTC, cpoile commented
@lieut-data So, optional and not going to merge? Or merge because at least it's done? :)

2021-08-03 14:42 UTC, lieut-data commented
Propose we err on the side of "less functionality" and leave things as-is until we have a compelling reason to do otherwise.

2021-08-03 14:44 UTC, closed without merging