[MM-35264] Workspace wide scope - playbooks
mattermost/mattermost-plugin-playbooks pull request #641
Opened 2021-07-19 15:15 UTC by iomodo

#### Summary
This PR adds playbooks to the workspace-wide context.

https://user-images.githubusercontent.com/2340127/126183656-bf7e6a20-9006-4e49-b02e-61913c52c119.mp4

https://user-images.githubusercontent.com/2340127/126183707-d974eab8-b97d-4b6d-8d0e-f10a88179e58.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-35264

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-07-19 23:28 UTC, crspeller requested changes
Excited for these changes! I think that's good for now. Will do a more thorough review after the first set of changes.

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +    label: JSX.Element | string;
```suggestion
    label: React.ElementType;
```

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +    const [teamOptions, setTeamOptions] = useState<Option[]>([]);
I am confused. Why is this state? It seems to be derived directly from props?

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +        updateTeamOptions();
Why?

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +        return props.teams.filter((team) => team.id === teamId)[0];
Are you looking for `find`?  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +    const [isOpen, setOpen] = useState(false);
This open and coordinate state might look nicer as a one-off custom hook.

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +    }, [rect, teamOptions.length]);
rect won't change except on mount, and teamOptions appears to be derived from props so I think this can be cleaned up when teamOptions is fixed.

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +            <PrimaryButton
Maybe leave the styling to the children? Then we don't have to so the `withButton` thing and we just watch for clicks on the container div like below.

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +    children: JSX.Element;
I think the correct type for children is `React.ReactNode`

2021-07-19 23:28 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +const Dropdown = ({children, isOpen, showOnRight, moveUp, target, onClose, dependsOnMousePosition, position}: DropdownProps) => {
Why is this copy pasted?

2021-07-20 13:02 UTC, abhijit-singh reviewed
Awesome work on the team selector popup for templates opening up wherever the user clicks! 🎉

A few small points:
1. The search in the team selector popup seems to have an`arrow icon`, like in a dropdown. It doesn't really do anything, right? It isn't there in other places and I don't think it was there in the last PR. Can we remove it?
2. Related to the above point, there's also a `x` cross icon that appears if there's a selected team, but clicking on it doesn't do anything. It is also there in the `Owner` filter. Ideally, we should remove that too, but doesn't have to be a part of this effort. 
3. The key icon should be in the same color as the `status - online indicator`(#06D6A0). 
4. Wherever a button is triggering a dropdown, it'll be ideal if the dropdown is placed just below the button instead of overlapped on it. Screenshot attached - 
![image](https://user-images.githubusercontent.com/14369607/126328550-11a1a95d-b53e-4d27-a318-020139b25bba.png)

2021-07-20 21:02 UTC, iomodo commented
Thanks for the wonderful suggestion @crspeller ! I think I addressed all of them.
Will address @abhijit-singh 's suggestions tomorrow.

2021-07-21 16:25 UTC, iomodo commented
Addressed @abhijit-singh 's suggestions.

2021-07-21 18:31 UTC, iomodo commented
Some screenshots for @abhijit-singh 
<img width="1439" alt="Screen Shot 2021-07-21 at 22 30 02" src="https://user-images.githubusercontent.com/2340127/126541075-ad074d10-f78d-4485-9d37-a66f0756ef0c.png">
<img width="1453" alt="Screen Shot 2021-07-21 at 22 30 19" src="https://user-images.githubusercontent.com/2340127/126541086-73360471-ff31-46cb-ae0c-34985825110d.png">

2021-07-21 18:53 UTC, abhijit-singh commented
> Some screenshots for @abhijit-singh
> <img alt="Screen Shot 2021-07-21 at 22 30 19" width="1453" src="https://user-images.githubusercontent.com/2340127/126541086-73360471-ff31-46cb-ae0c-34985825110d.png">

@iomodo Awesome, the styling changes look good! 

One more thing from the screenshot above - if all teams have a playbook each, can we show the key icon on the `Create playbook` button like we do today? That was the behaviour suggested in [this conversation](https://community-daily.mattermost.com/core/pl/buwj7zmajbyc78wq8tyxy13phh): 

> 3. Two playbooks created, one in each team: There is a key icon on the Create playbook button and clicking on it triggers a modal.


`

2021-07-23 16:13 UTC, crspeller requested changes

2021-07-23 16:13 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +    const [dropdownPosition, setDropdownPosition] = useState({x: 0, y: 0, isOpen: false});
Better! If you made this into a custom hook it would look really nice.

2021-07-23 16:13 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +                onChange={(option) => onSelectedChange(option as Option)}
So we need this extra arrow function just to do the type conversion? Or can we just change the type the function accepts to match and do it within there.

2021-07-23 16:13 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +        const team = getTeam(value?.teamId || '');
Could we not just attach the team object to the option list to avoid this?

2021-07-23 16:13 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +    useEffect(() => {
Why have this useEffect and state to calculate this? It's not a lot of calculation.

2021-07-23 16:13 UTC, crspeller commented on webapp/src/components/team/team_with_icon.tsx
> +    allowed: boolean;
It's more like not licensed right?

2021-07-23 16:13 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +const Dropdown = ({children, showOnRight, moveUp, target, onClose, dependsOnMousePosition, position}: DropdownProps) => {
Why is this copy pasted form profile selector? Could we not share some code here?

2021-07-25 19:52 UTC, iomodo commented on webapp/src/components/backstage/new_playbook.tsx
> +    const teams = useSelector<GlobalState, Team[]>(getMyTeams);
Missed that. Do you mean using `getMyTeams` without the `useSelector`? Won't we need a global state object for that? It seems an overkill to introduce `store` object in `new_playbook`. Am I missing something?

2021-07-25 21:32 UTC, iomodo commented on webapp/src/components/team/team_with_icon.tsx
> +    allowed: boolean;
Depends on the context actually. It is used in `Team` filter as well which has nothing to do with licensing. Maybe `showIcon` is a better name here.

2021-07-25 21:35 UTC, iomodo commented on webapp/src/components/team/team_with_icon.tsx
> +    allowed: boolean;
Or maybe `showNotLicensedIcon`?

2021-07-25 21:38 UTC, iomodo commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +const Dropdown = ({children, showOnRight, moveUp, target, onClose, dependsOnMousePosition, position}: DropdownProps) => {
`Dropdown` is in 4 different places copy/pasted (with slight changes). I'd suggest to address this in a different PR for the whole repo.

2021-07-26 09:18 UTC, agarciamontoro approved these changes
Great job here, @iomodo, I guess these PRs are being tricky! I left a couple of non-blocking comments, approving right away :)

2021-07-26 09:18 UTC, agarciamontoro commented on webapp/src/components/backstage/template_selector.tsx
> +                        {!allowPlaybookCreation && <NotAllowedIcon className='icon icon-key-variant-circle'/>}
Same comment for reusing (the refactored version of) UpgradeBadge, just not to duplicate the icon definition.

2021-07-26 09:18 UTC, agarciamontoro commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +        const hoverColor = 'rgba(20, 93, 191, 0.08)';
Is this theme-independent?

2021-07-26 09:18 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_list.tsx
> +                        onNewPlaybook={(team: Team) => newPlaybook(team)}
Does Typescript complain here? It should not, right?

2021-07-26 18:29 UTC, crspeller approved these changes
Awesome! The rest is non-blocking.

2021-07-26 18:29 UTC, crspeller commented on webapp/src/components/backstage/new_playbook.tsx
> +    const teams = useSelector<GlobalState, Team[]>(getMyTeams);
No I mean why are we selecting a bunch of teams, then picking the one we want? Why not just use the get team selector directly?

2021-07-26 18:29 UTC, crspeller commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +const Dropdown = ({children, showOnRight, moveUp, target, onClose, dependsOnMousePosition, position}: DropdownProps) => {
Alright. Could you make a ticket for it?

2021-07-27 09:13 UTC, iomodo commented on webapp/src/components/team/create_playbook_team_selector.tsx
> +        const hoverColor = 'rgba(20, 93, 191, 0.08)';
Yes. Same behaviour as in profile select.

2021-07-27 09:14 UTC, iomodo commented on webapp/src/components/team/team_with_icon.tsx
> +            {props.showNotLicensedIcon ? <NotAllowedIcon className='icon icon-key-variant-circle'/> : ''}
I created separate ticket for refactoring `UpgradeBadge` and `NotAllowedIcon`

2021-07-29 12:52 UTC, iomodo commented
Screenshots for @abhijit-singh 

https://user-images.githubusercontent.com/2340127/127495330-1725b0f5-c646-41a3-99c9-b98e9f73a592.mp4


https://user-images.githubusercontent.com/2340127/127495345-54631875-b0f3-4be9-bd5f-19cd705e332d.mp4

2021-07-29 14:07 UTC, abhijit-singh approved these changes
Thanks @iomodo!

A couple of non-blocking things so adding them here and approving:
1. Ideally the key icon should have a white background, like @agarciamontoro had in his implementation that can be seen here https://github.com/mattermost/mattermost-plugin-playbooks/pull/592
2. We should try and explain to the user why creating playbooks for certain teams is locked while for others it isn't. The idea is to change the upgrade modal text to explain that the limit for that particular team has been hit. 
Suggestion: `This team already has a playbook. Upgrade to create multiple playbooks to prescribe different workflows for each team.`

^ This will mean we'll need to show different text when the user clicks on a team and sees the modal vs when the user clicks on `+ Create playbook` and sees the modal. 
In an attempt to unify those, maybe we can use: `In your current plan, each team can have just 1 playbook. Upgrade to create multiple playbooks to prescribe different workflows for each team.`

Looking to @justinegeffen for feedback & review .

2021-07-29 19:17 UTC, justinegeffen commented
Thanks, @abhijit-singh! I really like your suggestion of a generic option and your wording makes sense. I've reworded it a little, LMK if it works for you: 

"Your subscription allows one playbook per team. Upgrade your subscription and create multiple playbooks with unique workflows for each team."

2021-07-30 15:04 UTC, merged