Updated playbook templates
mattermost/mattermost-plugin-playbooks pull request #652
Opened 2021-07-27 21:40 UTC by lieut-data

#### Summary
As per @itao's
[proposal](https://docs.google.com/document/d/1pJscJCqiL3CDemsBN-V_3NRvOeapB3nbjE7eEKTwmGY/edit),
replace the existing templates:
* Blank (unchanged)
* Product Release
* Customer Onboarding
* Service Reliability Incident (refreshed)
* Feature Swimlane (basically empty)

The existing template selector scrolls on demand, but to give a slightly better experience on a typical MacBook Pro, I reduced the required margin to avoid scrolling in this case:

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/1023171/127220165-17babf6b-11ed-4510-8d01-ccfd971e79c0.png">

On smaller screens, scrolling still works:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1023171/127220224-53fe843d-85d2-4089-9b38-3398c9160edf.png">

And @calebroseland's updated RHS works beautifully with the new templates (though it seems like `num_actions` is hard-coded at the moment to `0`).

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1023171/127220267-6cad88d1-007b-43f3-9d2f-3943c3625547.png">

Telemetry is updated to track clicks on the template icons in the backstage, as well as the `Use template` option in the new RHS experience.

#### Ticket Link
None.

#### Checklist
- [x] Telemetry updated
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-07-27 22:21 UTC, calebroseland commented on webapp/src/components/backstage/template_selector.tsx
> +            num_stages: 4,
@lieut-data I think `num_actions` may need to be set manually alongside `num_stages`

2021-07-27 22:23 UTC, lieut-data commented on webapp/src/components/backstage/template_selector.tsx
> +            num_stages: 4,
Ah, of course! Thank you :)

2021-07-28 13:47 UTC, crspeller approved these changes

2021-07-28 17:30 UTC, lieut-data commented
@calebroseland, `num_actions` calculations updated (including to count a recently added action). I feel like there's some duplication in the backstage around this property that we could iterate on in the future -- maybe, for example, we just always send down all the data for playbooks all the time, vs. trying to compute fields like `num_stages`, `num_actions`, etc.

2021-07-28 17:33 UTC, calebroseland commented
> @calebroseland, `num_actions` calculations updated (including to count a recently added action). I feel like there's some duplication in the backstage around this property that we could iterate on in the future -- maybe, for example, we just always send down all the data for playbooks all the time, vs. trying to compute fields like `num_stages`, `num_actions`, etc.

100% agree with that—and thanks for adding updating those calculations.

2021-07-28 17:40 UTC, calebroseland requested changes
I think the action `ExportChannelOnArchiveEnabled` that was also recently added, otherwise LGTM!

2021-07-28 17:40 UTC, calebroseland commented on server/sqlstore/playbook.go
> +			) AS NumActions`,
`ExportChannelOnArchiveEnabled`
```suggestion
			`(
				CASE WHEN InviteUsersEnabled THEN 1 ELSE 0 END +
				CASE WHEN DefaultCommanderEnabled THEN 1 ELSE 0 END +
				CASE WHEN AnnouncementChannelEnabled THEN 1 ELSE 0 END +
				CASE WHEN WebhookOnCreationEnabled THEN 1 ELSE 0 END +
				CASE WHEN MessageOnJoinEnabled THEN 1 ELSE 0 END +
				CASE WHEN WebhookOnStatusUpdateEnabled THEN 1 ELSE 0 END +
				CASE WHEN SignalAnyKeywordsEnabled THEN 1 ELSE 0 END +
				CASE WHEN CategorizeChannelEnabled THEN 1 ELSE 0 END + 
				CASE WHEN ExportChannelOnArchiveEnabled THEN 1 ELSE 0 END
			) AS NumActions`,
```

2021-07-28 17:40 UTC, calebroseland commented on server/sqlstore/playbook.go
> +				CASE WHEN p.CategorizeChannelEnabled THEN 1 ELSE 0 END
`ExportChannelOnArchiveEnabled`
```suggestion
				CASE WHEN p.CategorizeChannelEnabled THEN 1 ELSE 0 END + 
				CASE WHEN p.ExportChannelOnArchiveEnabled THEN 1 ELSE 0 END
```

2021-07-28 17:40 UTC, calebroseland commented on server/sqlstore/playbook.go
> +				CASE WHEN p.CategorizeChannelEnabled THEN 1 ELSE 0 END
`ExportChannelOnArchiveEnabled`
```suggestion
				CASE WHEN p.CategorizeChannelEnabled THEN 1 ELSE 0 END + 
				CASE WHEN ExportChannelOnArchiveEnabled THEN 1 ELSE 0 END
```

2021-07-28 18:05 UTC, lieut-data commented
Excellent! Thank you, @calebroseland :)

2021-07-28 18:06 UTC, calebroseland approved these changes

2021-07-28 18:24 UTC, merged