[MM-37314] Remove channel from prev category
mattermost/mattermost-plugin-playbooks pull request #657
Opened 2021-07-29 10:46 UTC by iomodo

#### Summary
Remove channel from previous category and fix the concurrency bug

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-37314

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2021-07-29 10:48 UTC, iomodo commented on server/app/playbook_run_service.go
> +	m, err := cluster.NewMutex(s.api, "playbook_run_categories")
wouldn't it be better to have `s.pluginAPI.Cluster.NewMutex("key")` instead of this?

2021-07-29 11:57 UTC, agarciamontoro approved these changes
Looks good! Great investigation work :)

2021-07-29 11:57 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +			if !sliceContains(category.Channels, channelID) {
Good safeguard here!

2021-07-29 11:58 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +	m, err := cluster.NewMutex(s.api, "playbook_run_categories")
+1

2021-07-29 14:28 UTC, lieut-data requested changes

2021-07-29 14:28 UTC, lieut-data commented on server/app/playbook_run_service.go
> +	m, err := cluster.NewMutex(s.api, "playbook_run_categories")
I think a `Cluster.*` could increase discoverability, but on the flip side it encourages baking in "complex" logic into the plugin API, and I personally found it elegant to isolate the `cluster` package away from the rest of the API.

2021-07-29 14:28 UTC, lieut-data commented on server/app/playbook_run_service.go
> +	m.Lock()
@iomodo and I discussed offline, and I don't think we have conclusive evidence of a race condition here to justify use of the mutex yet.

2021-07-29 14:28 UTC, lieut-data commented on server/app/playbook_run_service.go
> +	// remove channel from previous category
This /feels/ like a complication that we might want to consider solving for users in the pluginapi at some point. @hmhealey, can you also confirm the intended use of the category APIs in this case?

2021-07-30 12:16 UTC, lieut-data approved these changes

2021-07-30 12:16 UTC, merged

2021-07-30 16:54 UTC, hmhealey commented on server/app/playbook_run_service.go
> +	// remove channel from previous category
I thought we did that in the DB layer, but maybe that was never tested thoroughly. I'm pretty sure the web app makes a request to update both categories at once.