[MM-35248] Make backstage current team agnostic
mattermost/mattermost-plugin-playbooks pull request #668
Opened 2021-08-02 14:39 UTC by iomodo

#### Summary
This PR makes backstage "current team" agnostic.
Since there is a lot of places where we use `currentTeam` I might have missed couple. This PR should be tested thoroughly before merging. 

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-35248

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2021-08-03 19:51 UTC, iomodo commented
Just an FYI, already tested thoroughly, I think I did not miss anything. When/if you'll be testing pay attention that after refresh all the `NeedsTeam` context is removed from the redux. So there are couple of places where it gets tricky. It's ready to be reviewed. 
cc @lieut-data @cpoile 
P.S. sorry for the long PR :)

2021-08-04 21:21 UTC, cpoile requested changes
Wow, lots of changes, nice work @iomodo!

I mostly have questions, some may prompt a revision (or not). :)

To help test this, is there a list of all the affected things we should check? Or is it almost everything?

2021-08-04 21:21 UTC, cpoile commented on webapp/src/components/backstage/backstage.tsx
> +                            to={`/${teams[0].name}/messages/@surveybot`}
Would it make sense to send the user to the current team? This might avoid a surprising switch when they might not expect it.

2021-08-04 21:21 UTC, cpoile commented on webapp/src/components/backstage/css_utils.tsx
> +export function applyTheme(theme: any) {
I wonder if there's a better way to do this? No worries if there isn't. I just imagine this will break as soon as we change how themes are done.

2021-08-04 21:21 UTC, cpoile commented on webapp/src/components/backstage/playbook_edit_wrapper.tsx
> +const PlaybookEditWrapper = () => {
I'm not sure why we need this wrapper?

2021-08-04 21:21 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
> +        dispatch(startPlaybookRun(teams[0].id)); //TODO add team selector ?
Or take a team parameter? So that `newPlaybookRun(teamId)` can use the current team (wherever the user currently is).

2021-08-04 21:21 UTC, cpoile commented on webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
> +        const owners = await fetchOwnersInTeam(props.playbook?.team_id || ''); //TODO verify
Verify?

2021-08-05 06:12 UTC, iomodo commented on server/app/playbook_run_service_test.go
> +				"http://example.com/plug/com.mattermost.plugin-incident-management/runs/"+createdPlaybookRun.ID,
Yes, it is the new route

2021-08-05 07:44 UTC, iomodo commented on webapp/src/actions.ts
> +    type: TeamTypes.SELECT_TEAM,
Good catch. It's redundant. Forgot to remove after the refactoring. 
`<TextBox> needs a `currentTeamId` for the slash command autocomplete and there is none in the store, so I'm setting the `id` manually. I found the `selectTeam` action in the redux repo that does the same and am using that here https://github.com/mattermost/mattermost-plugin-playbooks/blob/9115852d90a329e7e317beb5850af0e12a16d2b9/webapp/src/components/backstage/playbook_edit.tsx#L190

2021-08-05 07:45 UTC, iomodo commented on webapp/src/components/backstage/backstage.tsx
> +                            to={`/${teams[0].name}/messages/@surveybot`}
But which is the current team? There is no such thing in the backstage anymore.

2021-08-05 07:47 UTC, iomodo commented on webapp/src/components/backstage/css_utils.tsx
> +export function applyTheme(theme: any) {
I've talked about this with @crspeller and this solution is fine for now. We will refactor it after merging the global header if needed.

2021-08-05 07:48 UTC, iomodo commented on webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
> +        dispatch(startPlaybookRun(teams[0].id)); //TODO add team selector ?
Again the thing is that we do not have the current team in this context

2021-08-05 07:49 UTC, iomodo commented on webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
> +        const owners = await fetchOwnersInTeam(props.playbook?.team_id || ''); //TODO verify
Forgot to remove after testing.

2021-08-05 07:56 UTC, iomodo commented
>> To help test this, is there a list of all the affected things we should check? Or is it almost everything?
Unfortunately there is no concrete list. Almost everything has changed. We'll probably need a bug bash to test this in more detail. I've tested everything what I could think of, but I may have missed something

2021-08-05 12:48 UTC, lieut-data commented on webapp/src/components/backstage/backstage.tsx
> +                            to={`/${teams[0].name}/messages/@surveybot`}
There is the concept of the "previous team" in webapp -- it's used to send the user to the last team they viewed when loading the webapp afresh without an explicitly team in the URL.

However it's awkwardly in local storage and not Redux, and it's something that's shared across all tabs. Could we model this ourselves to remember the last team, keying off the existing `TeamTypes.SELECT_TEAM` (and `UserTypes.LOGOUT_SUCCESS`) actions?

2021-08-05 15:05 UTC, iomodo commented on webapp/src/components/backstage/backstage.tsx
> +                            to={`/${teams[0].name}/messages/@surveybot`}
I'm guessing it's in the local storage because of the refresh consistency. I don't think we should be storing this in memory, the `currentTeam` is already there if do not refresh it will stay there.

How about getting the `currentTeam` and if it's undefined then use to the `team[0]`?

I'd suggest deferring the `previous team` (if we will use that) to the next PR.

2021-08-05 16:20 UTC, lieut-data commented on webapp/src/components/backstage/backstage.tsx
> +                            to={`/${teams[0].name}/messages/@surveybot`}
:+1: for subsequent PR :)

2021-08-10 13:26 UTC, lieut-data requested changes
Thanks, @iomodo! A handful of comments below, but a high-level summary:
* I'm worried about having to pass `team_id` in the query string to inform the client of something I feel like it should be able to look up on its own.
* The proliferation of `team` into components /feels/ like it could be optimized, if only to just pass around `team_id` in many cases. (Various comments below.)
* The need to resolve our own set of team channels in various cases "smells wrong", and wondering if we can leverage the webapp's existing functionality here more closely?

2021-08-10 13:26 UTC, lieut-data commented on server/app/playbook_run_service.go
> +		"",
Why empty string?

2021-08-10 13:26 UTC, lieut-data commented on server/app/playbook_run_service.go
> +		url := getPlaybooksNewURL(siteURL, s.configService.GetManifest().Id)
Nice!

2021-08-10 13:26 UTC, lieut-data commented on server/app/playbook_service.go
> +		url := fmt.Sprintf("%s/%s/edit/automation?teamId=%s", playbooksURL, playbooks[0].ID, playbooks[0].TeamID) // automation tab
Is it possible for the client to resolve the team on demand? What happens, for example, if this URL is crafted "maliciously", specifying the "wrong" team id?

2021-08-10 13:26 UTC, lieut-data commented on server/app/urls.go
> +	)
nit: Might we consider formatting as:
```suggestion
	return fmt.Sprintf(
              "%s/%s/%s/runs",
		siteURL,
		pluginRoute,
		manifestID,
	)
```

2021-08-10 13:26 UTC, lieut-data commented on server/command/command.go
> +		url := fmt.Sprintf("/%s/%s/playbooks/%s", "plug", r.configService.GetManifest().Id, playbookID)
Can we inline `"plug"` into the format string here (like `playbooks`)?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/types/actions.ts
> +import Teams from 'mattermost-redux/action_types/teams';
Is this used?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/index.tsx
>              r.registerNeedsTeamRoute('/error', ErrorPage);
Do we still use the team routes?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/rhs/rhs_post_update.tsx
> +                onClick={() => dispatch(updateStatus(team.id))}
Can we just use `props.playbookRun.team_id` directly here?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/rhs/rhs_footer.tsx
> +                onClick={() => dispatch(updateStatus(team.id))}
Can we just use `props.playbookRun.team_id || playbookRun?.team_id || ''` here directly?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/rhs/rhs_footer.tsx
> +    const team = useSelector<GlobalState, Team>((state) => getTeam(state, props.playbookRun.team_id || playbookRun?.team_id || ''));
Is there a reason we can't just use `playbookRun?` or `props.playbookRun` exclusively? Wondering why this component has to be "aware" of two entry points.

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/rhs/rhs_checklists.tsx
> +                <FinishButton onClick={() => dispatch(updateStatus(team.id, 'Resolved'))}>
Can we use `props.playbookRun.team_id` directly?Can we use `props.playbookRun.team_id` directly?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/rhs/rhs_checklists.tsx
> +                    teamId={team.id}
Can we use `props.playbookRun.team_id` directly?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/rhs/post_card.tsx
> +                {'No recent updates. '}<a onClick={() => dispatch(updateStatus(props.team.id))}>{'Click here'}</a>{' to update status.'}
If we only need the id here, should we consider only passing that vs. the whole `team`?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/rhs/collapsible_checklist.tsx
> +                            dispatch(addNewTask(teamId, index));
It seems weird to pass `teamId` to `addNewTask`, but we don't have to pass `playbookRunId` and such. I'm guessing `addNewTask` is a thunk? Should we just have it look up the current team where it needs it?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/post_menu.tsx
> +            dispatch(addToTimeline(channel.team_id, props.postId));
See below, but thinking we can make `addToTimeline` do the work of resolving the `team_id` instead.

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
> +            team_id: props.playbook?.team_id,
Can we find a way to omit `team_id` altogether here? Presumably the server can resolve it itself?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline.tsx
> +    const team = useSelector<GlobalState, Team>((state) => getTeam(state, props.playbookRun.team_id));
Can we check that `RHSTimelineEventItem` needs the whole team and not just the `team_id`?

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/backstage/playbook_edit.tsx
> +                const fetchedChannels = await fetchMyChannels(props.teamId);
It would be awesome to be able to dispatch a plain `FETCH_TEAM_CHANNELS` Redux action and have the webapp "handle" this for us instead of having to maintain our own (duplicate state) and without having to import an action from the webapp. This is a place where a side effects library could really help.

2021-08-10 13:26 UTC, lieut-data commented on webapp/src/components/backstage/playbook_edit.tsx
> +    const [channels, setChannels] = useState<Channel[]>([]);
Wondering if we can find a way to use what's in the webapp Redux store instead? (Kicking it as needed?)

2021-08-10 13:26 UTC, cpoile commented on webapp/src/actions.ts
> +    type: TeamTypes.SELECT_TEAM,
I guess the `getCurrentTeamId` selector might not work, if we didn't first come from the channels side?

2021-08-10 13:27 UTC, cpoile commented on webapp/src/components/backstage/backstage.tsx
> +                            to={`/${teams[0].name}/messages/@surveybot`}
👍

2021-08-10 13:29 UTC, cpoile commented on webapp/src/components/backstage/playbook_edit_wrapper.tsx
> +const PlaybookEditWrapper = () => {
Still wondering about this, @iomodo?

2021-08-10 13:33 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
> +        dispatch(startPlaybookRun(teams[0].id)); //TODO add team selector ?
I have a feeling this is going to be bad UX. Maybe we should have a "default" team to start runs in, set by the admin in the plugin settings? Otherwise new runs will start popping up in random teams and once you've started a run we don't let you move them. @itao , @abhijit-singh ?  
(Adding this setting would be for another PR of course, not this one)

2021-08-10 13:34 UTC, cpoile commented
I didn't mean to re-request a review from Jesse -- don't know why it did that.

2021-08-10 13:36 UTC, cpoile approved these changes
Approving to unblock, but I'm still interested in the answers to the remaining questions above. Nice work again @iomodo, thanks!

2021-08-10 13:39 UTC, iomodo commented on webapp/src/actions.ts
> +    type: TeamTypes.SELECT_TEAM,
Correct. Or if we refresh.

2021-08-10 13:42 UTC, lieut-data requested changes
Re-requesting review (without additional comment).

2021-08-10 17:02 UTC, iomodo commented on server/app/playbook_run_service.go
> +		"",
It's was a relative path, I left a relative path

2021-08-10 17:12 UTC, iomodo commented on webapp/src/index.tsx
>              r.registerNeedsTeamRoute('/error', ErrorPage);
We don't but is still works. Not sure if we want to delete, maybe customers have some links that will get broken? I'm 0/5

2021-08-10 17:25 UTC, iomodo commented on webapp/src/components/rhs/rhs_footer.tsx
> +    const team = useSelector<GlobalState, Team>((state) => getTeam(state, props.playbookRun.team_id || playbookRun?.team_id || ''));
I don't think we are using this component at all. Changing to rely on props

2021-08-10 17:28 UTC, iomodo commented on webapp/src/components/rhs/post_card.tsx
> +                {'No recent updates. '}<a onClick={() => dispatch(updateStatus(props.team.id))}>{'Click here'}</a>{' to update status.'}
We need whole `team` for the `PostText` below in this component

2021-08-10 17:32 UTC, iomodo commented on webapp/src/components/rhs/collapsible_checklist.tsx
> +                            dispatch(addNewTask(teamId, index));
`addNewTask` runs a slash command. And we need a `team_id` to do that. Getting the `currentTeam` might not work after refresh. So everywhere where client needs to execute a slash command we are passing the `team_id` directly.

2021-08-10 17:47 UTC, lieut-data commented on server/app/playbook_service.go
> +		url := fmt.Sprintf("%s/%s/edit/automation?teamId=%s", playbooksURL, playbooks[0].ID, playbooks[0].TeamID) // automation tab
@iomodo, this was one of the cases where I think I was confused about the use of `teamId`. It seems like we're using this here not for "new playbook with no team picked", but an existing playbook for which we should already know the team?

2021-08-10 17:47 UTC, lieut-data commented on webapp/src/index.tsx
>              r.registerNeedsTeamRoute('/error', ErrorPage);
Let's add a TODO (in the code?) to deprecate in v2.0.

2021-08-10 17:48 UTC, lieut-data commented on webapp/src/components/rhs/collapsible_checklist.tsx
> +                            dispatch(addNewTask(teamId, index));
Once we eliminate the use of interactive dialogs for things like this, I imagine it will get a lot simpler.

2021-08-10 17:50 UTC, iomodo commented on server/app/playbook_service.go
> +		url := fmt.Sprintf("%s/%s/edit/automation?teamId=%s", playbooksURL, playbooks[0].ID, playbooks[0].TeamID) // automation tab
Yes, yes I'm changing this.

2021-08-10 18:18 UTC, iomodo commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline.tsx
> +    const team = useSelector<GlobalState, Team>((state) => getTeam(state, props.playbookRun.team_id));
It needs whole `team` for markdown options to format text.

2021-08-11 10:59 UTC, iomodo commented on webapp/src/components/backstage/playbook_edit_wrapper.tsx
> +const PlaybookEditWrapper = () => {
Removed it

2021-08-11 13:39 UTC, lieut-data approved these changes
Super nice cleanup! Just a handful of non-blocking thoughts.

2021-08-11 13:39 UTC, lieut-data commented on webapp/src/components/backstage/channel_selector.tsx
> +    type GetChannelType = (channelID: string) => Channel
Should we define this outside the closure? (i.e. at the file level)

2021-08-11 13:39 UTC, lieut-data commented on webapp/src/components/backstage/playbook_edit.tsx
> +interface URLParams {
nit:
```suggestion
}

interface URLParams {
```

2021-08-11 13:39 UTC, lieut-data commented on webapp/src/components/backstage/playbook_edit.tsx
> +                        team_id: props.teamId || '',
It feels weird to have a playbook sometimes fall back to an empty `teamId`. I'm guessing this is TypeScript complaining about `teamId` potentially being `undefined`? What would it take to make `teamId` a non-optional property here (with error checking higher up for the cases where we can't know?)

2021-08-11 13:39 UTC, lieut-data commented on webapp/src/components/backstage/playbook_edit.tsx
> +        return dispatch(getProfilesInTeam(props.teamId || playbook.team_id, 0, PROFILE_CHUNK_SIZE, '', {active: true}));
Would it make sense to use `playbook.team_id` unconditionally for clarity?

2021-08-11 15:10 UTC, iomodo commented on webapp/src/components/backstage/playbook_edit.tsx
> +                        team_id: props.teamId || '',
It could be `undefined` when we create playbook we pass the `teamId`, but when we edit playbook we pass `playbookId` and get `teamId` from there.
In this case since it's a new playbook there will be a `teamId` and the ` || ''` is just for TypeScript.

2021-08-11 19:46 UTC, iomodo commented
PR has a known issue. When go to the backstage websocket connection is closed. When return to the channels websocket connection may not be open before we dispatch `executeSlashCommand` actions. 
Steps to reproduce the issue:
1. go to the backstage
2. refresh
3. go to any playbook
4. click run
dialogue is not shown, when it should be.

Notice that if you do not refresh everything is working fine since it takes smaller time to load the page.

Discussed with @cpoile  and @crspeller offline(huge thanks to them in helping detecting the issue), we suggest to merge with this known problem.

2021-08-11 19:58 UTC, lieut-data approved these changes

2021-08-11 19:58 UTC, lieut-data commented on webapp/src/client.ts
> +    if (!currentChannel || currentChannel.team_id !== teamId || isBackstage) {
It's not super obvious what `isBackstage` does here: given the known issue with the websockets, does this bit actually help us?

2021-08-11 20:29 UTC, crspeller commented
@lieut-data We did discuss that. The decision that was made was that was not necessary given the solution coming that will fix the websockets.

2021-08-11 20:36 UTC, crspeller commented
@lieut-data I think the idea there was @iomodo noted it worked under certain conditions of what team the playbook was on. I think this makes it even and adds a delay everywhere that wins the race in certain situations. 
I don't think it's necessary given the eventual fix.

2021-08-12 03:18 UTC, merged