Mm 37532 split name and team
mattermost/mattermost-plugin-playbooks pull request #673
Opened 2021-08-04 15:40 UTC by iomodo

#### Summary
This PR will split playbook name and team name
#### Ticket Link

  Fixes: https://mattermost.atlassian.net/browse/MM-37532

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2021-08-04 16:18 UTC, agarciamontoro approved these changes
Oh, much much better! :tada:

2021-08-04 16:18 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
> +export const TeamNameWithPadding = styled(TeamName)`
If we're only using this in backstage/playbook_list.tsx`, would it make sense to move this styled component there?

2021-08-04 18:52 UTC, lieut-data requested changes
So much better! Just two comments for clarity.

2021-08-04 18:52 UTC, lieut-data commented on webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
> +                            <TeamName>{teams.length > 1 ? getTeamName(teams, playbookRun.team_id) : ''}</TeamName>
Should we omit `TeamName` altogether instead of rendering an empty string?

2021-08-04 18:52 UTC, lieut-data commented on webapp/src/components/backstage/playbook_list.tsx
> +                    <TeamNameWithPadding>{teams.length > 1 ? ' (' + getTeamName(teams, p.team_id) + ')' : ''}</TeamNameWithPadding>
Should we do the same multi-line approach here?

2021-08-05 08:12 UTC, iomodo commented
This would be the result of the playbook name and team name split
<img width="1285" alt="Screen Shot 2021-08-05 at 12 10 31" src="https://user-images.githubusercontent.com/2340127/128315718-00c7ca21-c8d8-4673-ad98-fe01ce826396.png">

2021-08-05 12:00 UTC, lieut-data approved these changes
Nice, thanks @iomodo! Two suggestions below for being idiomatic, but looks good :)

2021-08-05 12:00 UTC, lieut-data commented on webapp/src/components/backstage/playbook_list.tsx
> +                    {teams.length > 1 ? <TeamName>{getTeamName(teams, p.team_id)}</TeamName> : '' }
For this case, I would suggest the following pattern:
```suggestion
                    {teams.length > 1 && <TeamName>{getTeamName(teams, p.team_id)}</TeamName>}
```

effectively rendering `null` vs. the empty string altogether.

2021-08-05 12:00 UTC, lieut-data commented on webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
> +                            {teams.length > 1 ? <TeamName>{getTeamName(teams, playbookRun.team_id)}</TeamName> : ''}
Same as above -- suggest:
```suggestion
                            {teams.length > 1 && <TeamName>{getTeamName(teams, playbookRun.team_id)}</TeamName>}
```

2021-08-05 13:23 UTC, iomodo commented on webapp/src/components/backstage/playbook_list.tsx
> +                    {teams.length > 1 ? <TeamName>{getTeamName(teams, p.team_id)}</TeamName> : '' }
nice!

2021-08-05 13:50 UTC, abhijit-singh approved these changes
Looks good!

2021-08-05 13:55 UTC, merged