MM-37678: Disallow title editing if user has no permissions to change channel name
mattermost/mattermost-plugin-playbooks pull request #682
Opened 2021-08-09 16:37 UTC by agarciamontoro

#### Summary
While we decide how to handle run titles decoupled from channel names, this PR completely disables the ability to edit the title from the RHS when the user has no permissions to change the channel name.

This mimics the feature to change the channel name from the channel header: the menu entry `Rename Channel` is only shown to users that have permissions to actually change it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37678

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-08-09 16:37 UTC, agarciamontoro commented
@abhijit-singh, I think this makes sense from a UX standpoint, but assigning you here to double-check.

2021-08-09 16:38 UTC, lieut-data approved these changes
Classy!

2021-08-10 08:35 UTC, abhijit-singh approved these changes

2021-08-10 13:41 UTC, cpoile requested changes
Just a quick question, otherwise nice!

2021-08-10 13:41 UTC, cpoile commented on webapp/src/components/rhs/rhs_about_title.tsx
> +};
I'm wondering... Have you viewed the react profiler after this change? Will this cause the whole component to re-render on any store change?

2021-08-10 14:21 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_about_title.tsx
> +};
I have not. Taking a look, thanks!

2021-08-10 14:48 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_about_title.tsx
> +};
@cpoile, I'm checking with the paint flashing tool and making changes in the store does not make the component re-render. Maybe I'm not testing it as expected, would you have done something different to check your concern?

2021-08-10 17:09 UTC, cpoile commented on webapp/src/components/rhs/rhs_about_title.tsx
> +};
Nope, that's perfect, thanks @agarciamontoro !

2021-08-10 17:09 UTC, cpoile approved these changes
Nice!

2021-08-10 17:10 UTC, merged