Mm 37645 customizable auto categorization
mattermost/mattermost-plugin-playbooks pull request #683
Opened 2021-08-11 13:20 UTC by Duaard

#### Summary

See [issue](https://github.com/mattermost/mattermost-server/issues/18062) description for details

#### Ticket Link

Fixed: mattermost/mattermost-server/issues/18062
JIRA: https://mattermost.atlassian.net/browse/MM-37645

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Modify backstage setting to add input box
- [x] Add a database migration to add new column CategoryName
- [x] Modify data model and queries, copy value when playbook is run
- [x] Modify createOrUpdatePlaybookRunSidebarCategory function to use category name
- [x] Add input validation for category name 
- [x] Unit tests updated
- [ ] E2E tests

2021-08-11 13:20 UTC, mattermod commented
Hello @Duaard,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-08-11 14:16 UTC, agarciamontoro commented
Thank you for this, @Duaard! We'll review it as soon as possible :)

2021-08-11 17:08 UTC, lieut-data commented
Due to our licensing situation, pkg.go.dev won't expose this documentation in a useful way: but wondering if we can do something in the `client/` package which we explicitly license (and module) separately so that it's visible on https://pkg.go.dev/github.com/mattermost/mattermost-plugin-playbooks/client?

2021-08-11 18:52 UTC, lieut-data requested changes
Really tremendous work, @Duaard! Just a handful of comments below :)

2021-08-11 18:52 UTC, lieut-data commented on server/app/playbook_run.go
> +	CategoryName                         string          `json:"category_name"`
Nice! I was going to ask why we didn't add `CategoryName` to `CategorizeChannelEnabled`, but I see now the pattern here to omit the `*Enabled` fields from the `playbook` when unnecessary.

2021-08-11 18:52 UTC, lieut-data commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, playbookRunsCategoryName string) error {
nit: let's simplify the variable name to just `categoryName` here -- we don't write `playbookRunChannelID`, etc., when the context is unambiguous.

2021-08-11 18:52 UTC, lieut-data commented on server/app/playbook_run_service_test.go
> +		playbookRun := &app.PlaybookRun{CategoryName: "Playbook Run"}
For additional coverage, can we try with a "new" `CategoryName`, ala "Playbook Runs 2"`?

2021-08-11 18:52 UTC, lieut-data commented on server/app/playbook_run_service_test.go
> +		playbookRun := &app.PlaybookRun{CategoryName: "Playbook Run"}
nit: since this is a category name, we should probably keep the pluralization: `Playbook Runs`, just to make the test more realistic.

2021-08-11 18:52 UTC, lieut-data commented on server/sqlstore/migrations.go
> +			return nil
Can you add a data migration here that updates this field (when enabled) to be "Playbook Runs", preserving backwards compatibility for any existing configurations?

2021-08-11 18:52 UTC, lieut-data commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
@agarciamontoro, thoughts on what to do with the now unused `CategorizeChannelEnabled` on `IR_Incident`?

2021-08-11 18:52 UTC, lieut-data commented on server/api/playbooks.go
> +		categoryNameLength := len(playbook.CategoryName)
Can we pull this out into a `validateCategoryName` helper?

2021-08-11 18:52 UTC, lieut-data commented on webapp/src/components/backstage/automation/settings.tsx
> +    categoryNameChange: (url: string) => void;
nit: can we fix the type here to call the parameter `categoryName`, not `url`?

2021-08-11 18:52 UTC, lieut-data commented on webapp/src/components/backstage/playbook_edit.tsx
> +        if (playbook.category_name !== name) {
Nice check!

2021-08-12 11:17 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
Good question. I guess we can simply "deprecate" it. We don't have a strict process for that; the only similar thing we've done in the codebase is to mark it as deprecated here https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/sqlstore/playbook_run.go#L388-L392. Thoughts?

2021-08-12 16:25 UTC, Duaard commented on server/app/playbook_run_service_test.go
>  }
Let me know if this is fine. I just yoinked the existing test and changed the name, but it should work. 😆

2021-08-12 16:35 UTC, agarciamontoro requested changes
This is amazing, @Duaard, thank you!

I left a couple of minor comments below that we can discuss.

2021-08-12 16:35 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +					return errors.Wrapf(err, "failed setting default value in column CategoryName of table IR_Playbook")
Typo here
```suggestion
					return errors.Wrapf(err, "failed setting default value in column CategoryName of table IR_Incident")
```

2021-08-12 16:35 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if categoryNameLength == 0 || categoryNameLength > 22 {
Here we should simply check the maximum length. The code already uses the category name only if it's not empty, so we can skip the minimum length check.

2021-08-12 16:35 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
I think we should make sure to lowercase the `categoryName` string inside this function before using it, as `Custom Category` and `custom category` will actually create two different categories in the sidebar, while they render as the same.
![image](https://user-images.githubusercontent.com/3924815/129232965-46f2a715-6544-4871-a426-3f9f3701d239.png)

The problem with this is that we'll break the `Playbook Runs` category whenever old playbooks that had not changed the category name are saved again (as new runs will change from `Playbook Runs` to `playbook runs`). @lieut-data, thoughts on that migration? I'm not too concerned about this, as people can still move the channels beteween categories and renaming and deleting the categories, but it will be slightly annoying.

2021-08-12 16:55 UTC, Duaard commented on server/api/playbooks.go
> +	if categoryNameLength == 0 || categoryNameLength > 22 {
It will actually still push through for the update and creation of **Playbook**, the check that will only use the Category Name is for **Playbook Runs**. Similar to how the **Webhook** input is being handled, it will just not push through with the update/create as the API will fail at the URL parsing.

I followed the logic of the webhooks while coding this and also observed their behavior. I can change this for the Category Name input but keep in mind to do the same for the webhook. (if it's not intended to let empty inputs be submitted)

2021-08-12 16:57 UTC, Duaard commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
Good catch, yeah that makes sense. I'll wait on @lieut-data for the decision on `Playbook Runs` before working on this.

2021-08-12 17:06 UTC, Duaard commented on webapp/src/components/backstage/automation/settings.tsx
> +                        pattern={'^[\\s\\S]{1,22}$'}
Yeah I agree on this. I think the error feedback from the `PatternedInput` isn't too helpful in this case. Let me work on modifying the `PatternedInput` component.

2021-08-17 13:59 UTC, lieut-data commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
Oops, apologies for missing this notification, @Duaard & @agarciamontoro. On the case issue, I definitely agree that we want to avoid creating duplicate categories with the same name. Is there a way to check all the category names for the user in question and do the lowercase comparison on our side and reusing the one we find if it matches?

2021-08-17 14:02 UTC, lieut-data commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
(Not sure if that addresses the `Playbook Runs` question or if there is another comment I might be missing? I'll finish my overall review on this today either way :))

2021-08-17 14:25 UTC, lieut-data commented on server/app/playbook_run_service_test.go
>  }
Looks good!

2021-08-17 14:26 UTC, lieut-data approved these changes
Nice work on this, @Duaard -- appreciate your patience with my delay in responding, as well as your determination to get this done well :)

2021-08-17 14:30 UTC, Duaard commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
We can definitely do that in the `createOrUpdatePlaybookRunSidebarCategory` function, with a slight edge case where there already exists duplicate categories (created manually). It will then be added to the first one to match the lower case check.

2021-08-17 14:35 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
> check all the category names for the user in question and do the lowercase comparison on our side and reusing the one we find if it matches?

Yeah, that also solves the issue with the `Playbook Runs` category too, if I'm not mistaken. @duaard, thoughts on the proposed solution?

2021-08-17 14:42 UTC, Duaard commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
> edge case where there already exists duplicate categories (created manually)
I'll add the check in the `createOrUpdatePlaybookRunSidebarCategory` function, but please do note this edge case

2021-08-17 15:55 UTC, Duaard commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) createOrUpdatePlaybookRunSidebarCategory(userID, channelID, teamID, categoryName string) error {
Hi @agarciamontoro added in the check, this should prevent this issue. 😄

2021-08-17 19:09 UTC, agarciamontoro approved these changes
Thank you again for all your hard work, @Duaard! I tested this with category names that only differed in the casing and it worked perfect :tada: Approving and merging :)

2021-08-17 19:11 UTC, agarciamontoro commented
Oh, let me fix the conflict here, I caused that one with #684 :)

2021-08-17 20:00 UTC, agarciamontoro commented
Done :) Thanks once again, @Duaard!

2021-08-17 20:00 UTC, merged

2021-08-18 03:40 UTC, Duaard commented on server/app/playbook_run_service.go
> +		if strings.EqualFold(category.DisplayName, categoryName) {
I didn't knew it also, it was the linter who suggested it. 😆