MM-37895 error page rendering
mattermost/mattermost-plugin-playbooks pull request #694
Opened 2021-08-17 15:58 UTC by lieut-data

#### Summary
Fix the error page rendering issues introduced with the global header. Note that the global header currently renders alongside the error page as opposed to going "full white" like the Channels product. This was "easiest" but we can revisit in the future as needed.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-37895

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-08-17 15:59 UTC, lieut-data commented on webapp/src/components/backstage/backstage.tsx
> +            <Switch>
I'm just wrapping with a `Switch` and `Route` so as to avoid rendering our own navbar in the error pages.

2021-08-17 15:59 UTC, lieut-data commented on webapp/src/components/error_page.tsx
> +                <h2 data-testid='errorMessageTitle'>
This is copy-pasta'd from the webapp's updated styling for same.

2021-08-19 03:39 UTC, calebroseland commented
/update-branch

2021-08-19 04:08 UTC, calebroseland requested changes
LGTM! Just one with suggestion for some styling issues in the product switcher and account menu when you hit the error page.

2021-08-19 14:23 UTC, lieut-data commented on webapp/src/components/error_page.tsx
>              document.body.removeAttribute('class');
Oh, thank you, @calebroseland!

2021-08-19 21:35 UTC, calebroseland approved these changes

2021-08-20 17:04 UTC, merged