MM-37634, MM-37483: New Post update dialog with markdown preview
mattermost/mattermost-plugin-playbooks pull request #699
Opened 2021-08-19 14:32 UTC by calebroseland

#### Summary
- Adds new custom dialog for Update Status (/"Post update")
  - Behind `EnableExperimentalFeatures`
  - Adds markdown preview  
- Reuses `Textbox` from webapp
- Adds markdown preview to Edit Task dialog

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-37634
  - https://mattermost.atlassian.net/browse/MM-37483

#### Checklist

~~- [ ] Telemetry updated~~
- [x] Gated by experimental feature flag
- [ ] Unit tests updated

2021-08-19 14:56 UTC, calebroseland commented on webapp/src/slash_command.ts
> +        if (experimentalFeaturesEnabled && message?.startsWith('/playbook update') && isInPlaybookRunChannel) {
There's one more permission that I need to bring forward from https://github.com/mattermost/mattermost-plugin-playbooks/blob/MM-37634/server/command/command.go#L657

2021-08-19 18:28 UTC, agarciamontoro requested changes
Amazing work, @calebroseland! :tada: I always learn a lot about Typescript and web development in general reviewing your PRs, I really enjoy it :)

I left a handful of comments below, mostly questions and nits.

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +    taskCommand: string;
Should we remove the blank line?
```suggestion
    show: boolean;
    onDone: () => void;
    checklistNum: number;
    playbookRunId: string;
    channelId: string;
    itemNum: number;
    taskTitle: string;
    taskDescription: string;
    taskCommand: string;
```

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +type MarkdownTextboxProps = {
Maybe just `Props`?

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +    ...props
I'm still 3/5 on not destructuring the props to actually know what's a prop and what is a value declared inside the component. I queued an item to discuss in our dev meeting, so we can leave this as is and discuss there.

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +        <div className={className}>
Why are we using a `className` here and not a styled component, maybe provided by the caller (with a default one exported in this file, if needed)

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +        updatePreview?.(!showPreview);
Why is `updatePreview` optional? Aren't we always setting it above? I had to read this line twice to understand what was going on, and if `updatePreview` was not optional, it would have been easier.

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +    const hasText = message && message.length > 0;
Can we do this here?

```suggestion
    const hasText = message?.length > 0;
```

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +            </b>
Super nit, feel free to ignore: can we write this (and the next ones) in one line? (or maybe the linter does not like it?)
```suggestion
            <b>{'**bold**'}</b>
```

2021-08-19 18:28 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +                style={{visibility: hasText ? 'visible' : 'hidden', opacity: hasText ? '' : '0'}}
Nit: Maybe I'm too used to styled components now, but I'd write this as a styled component with hasText as prop and write the CSS logic there. Thoughts?

2021-08-19 20:02 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +        updatePreview?.(!showPreview);
TextboxLinks was copy-pasted, with some refactoring afterwards to strip it down a bit and make it work with our styling. I'll look inter making the props type more deterministic.

2021-08-19 20:12 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +    ...props
These non-destructured props need to go to `Textbox` to be able to use or override those properly. The destructuring creates a clear contract that distinguishes between _controlled_ props (that are explicitly handled here in this wrapper component) and _non-controlled_ props (which are implicitly handled via routing directly to `Textbox`)

2021-08-19 20:14 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +        <div className={className}>
Initially because this started as a React.Fragment wrapper, but then I needed to distinguish, and reached for the closest thing that did that, but indeed that would be better—will adjust.

2021-08-19 20:16 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +                style={{visibility: hasText ? 'visible' : 'hidden', opacity: hasText ? '' : '0'}}
Just a result of copy-paste, if easily switched, I'll convert it.

2021-08-19 20:20 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +    ...props
I'm in a bit of a bind re: TS; I wanted to do something with `ComponentProps<typeof Textbox>`, but we don't have the infrastructure in place to import types from mattermost-webapp, so it's technically just `any` here.

2021-08-19 20:34 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +const ID = `${pluginId}_${nameof(UpdateRunStatusModal)}`;
I was having second thoughts/doubts on this. Thanks for confirming! Will go back to a normal string.

2021-08-19 20:35 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +    const team = useSelector((state: GlobalState) => getTeam(state, channel.team_id));
Mmmm, good point 👍

2021-08-19 20:36 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +                        defaultMessage: 'This update will be saved to the <OverviewLink>overview page</OverviewLink>{hasBroadcast, select, true { and broadcast to {broadcastChannel}} other {}}.',
Just using for the ICU conditional formatting! I'm not advocating we start a playbooks translations project! (Yet, anyway—I'd love to see it happen, but it's a lot of community work and maintenance.)

2021-08-19 20:42 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +function UpdateRunStatusModal({playbookRunId, playbookId, channelId, ...props}: Props) {
The typing is a bit loose at the moment, but it is required to route the props that `ModalController` provides so it can work properly with `global.WebappUtils.modals.openModal`.

2021-08-19 20:48 UTC, calebroseland commented on webapp/src/components/rhs/rhs_post_update.tsx
> +    {within: ['second', -45], display: 'just now'},
The default `now` only works with past-time, so it wasn't doing anything for the update reminder and just fell through to "Update due this minute" (which is perfectly accurate), only difference from default here is it'll say "Last update just now" instead of "Last update now"

2021-08-19 20:52 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +                show={this.props.show ?? this.state.show}
This is required in order to be cross-compatible with existing usages (which `show` is managed externally), and `global.WebappUtils.modals.openModal` which expects internal state and function props to work.

2021-08-19 20:54 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +    &&&& {
💯, these overrides were frustrating to deal with—will be great to comeback one day and refactor them.

2021-08-19 20:55 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +    &&&& {
Perhaps even in the polish stage of this feature, if it works out.

2021-08-19 21:00 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +    font-family: Metropolis;
Yep, probably leaked in through init figma styling.

2021-08-19 21:10 UTC, calebroseland commented on webapp/src/components/markdown_textbox.tsx
> +    ...props
renamed for clarity

2021-08-19 21:10 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +    channelId: PlaybookRun['channel_id'];
I like that it points to where it is designed to come from

2021-08-19 21:11 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +function UpdateRunStatusModal({playbookRunId, playbookId, channelId, ...props}: Props) {
renamed for clarity

2021-08-19 21:24 UTC, calebroseland commented on webapp/src/client.ts
> +        reminder?: number},
Indeed

2021-08-20 22:26 UTC, calebroseland commented on webapp/src/slash_command.ts
> +        if (experimentalFeaturesEnabled && message?.startsWith('/playbook update') && isInPlaybookRunChannel) {
Done

2021-08-23 19:45 UTC, lieut-data approved these changes
Looks good -- just a handful of comments :)

2021-08-23 19:45 UTC, lieut-data commented on webapp/src/actions.ts
> +        if (experimentalFeaturesEnabled) {
Is the plan to ship with this flag for v6.0?

2021-08-23 19:45 UTC, lieut-data commented on webapp/src/actions.ts
> +    playbookRunId: PlaybookRun['id'],
nit: Assuming I parse this correctly, this is cool, but feels verbose. Is it valuable to scope this to the same type as the `id` property on `PlaybookRun`, or is it clearer just to write `string`?

2021-08-23 19:45 UTC, lieut-data commented on webapp/src/components/modals/update_run_status_modal.tsx
> +    channelId: PlaybookRun['channel_id'];
Commented above, but this feels really verbose. If all these parameters are truly typed to the `PlaybookRun`, it also suggest that maybe we should just pass the `playbookRun` object directly?

2021-08-23 19:45 UTC, lieut-data commented on webapp/src/components/modals/update_run_status_modal.tsx
> +}
nit: worth writing as an arrow function with implicit return?

2021-08-23 19:45 UTC, lieut-data commented on webapp/src/components/widgets/generic_modal.tsx
> +    handleCancel?: (() => void) | null;
For clarity, why is `| null` required if `handleCancel` is already optional?

2021-08-23 19:53 UTC, calebroseland commented on webapp/src/actions.ts
> +        if (experimentalFeaturesEnabled) {
No, will get removed as soon as https://mattermost.atlassian.net/browse/MM-37637 goes in

2021-08-23 20:02 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +    handleCancel?: (() => void) | null;
For usage over in run update modal
```tsx
handleConfirm={hasPermission ? onConfirm : null}
```
It allows passing an explicit `null` to disable the confirm button. It would otherwise necessitate doing a lot of round about work to not provide the prop at all.

2021-08-23 20:09 UTC, calebroseland commented on webapp/src/actions.ts
> +    playbookRunId: PlaybookRun['id'],
It is verbose, but I think it clarifies where the value is designed to come from. If that's not valuable at this point in time I guess we could just use `string`.

2021-08-23 20:13 UTC, calebroseland commented on webapp/src/actions.ts
> +    playbookRunId: PlaybookRun['id'],
In line with `PlaybookRun -> Run` verbiage, we could perhaps do something like 

```ts
export function promptUpdateStatus(
    id: Run['id'],
    teamId: string,
    playbookId: Run['playbook_id'],
    channelId: Run['channel_id'],
) {//...}
```

2021-08-24 09:50 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_post_update.tsx
> +    {within: ['second', -45], display: 'just now'},
Oh, cool, thanks :)

2021-08-24 09:51 UTC, agarciamontoro commented on webapp/src/components/widgets/generic_modal.tsx
> +                show={this.props.show ?? this.state.show}
I'm ok leaving it as is for now, but maybe we should diverge from `openModal`?

2021-08-24 09:55 UTC, agarciamontoro commented on webapp/src/components/modals/update_run_status_modal.tsx
> +const ID = `${pluginId}_${nameof(UpdateRunStatusModal)}`;
Yay, thanks!

2021-08-24 10:03 UTC, agarciamontoro commented on webapp/src/components/modals/update_run_status_modal.tsx
> +function UpdateRunStatusModal({playbookRunId, playbookId, channelId, ...props}: Props) {
But my question is: as we are already destructuring all fields from the `Props` type, wouldn't `props` (now `modalProps`) be always empty?

2021-08-24 10:08 UTC, agarciamontoro commented on webapp/src/components/markdown_textbox.tsx
> +    ...props
> I'm in a bit of a bind re: TS; I wanted to do something with ComponentProps<typeof Textbox>, but we don't have the infrastructure in place to import types from mattermost-webapp, so it's technically just any here.

This would be really nice.

Thanks for the renaming, it's more clear now!

2021-08-24 10:16 UTC, agarciamontoro approved these changes
Looks great, @calebroseland, thank you!

2021-08-24 14:34 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +                show={this.props.show ?? this.state.show}
Possibly, though given the prompt can be requested from multiple places, I wanted to avoid the complexities of mounting manually wherever it might be invoked, but we could probably make a lighter in-house alternative.

2021-08-24 14:40 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +    channelId: PlaybookRun['channel_id'];
Switched back to string, queued an item for discuission--there's multiple patterns for typing IDs.

2021-08-24 14:48 UTC, merged

2021-08-24 14:57 UTC, lieut-data commented on webapp/src/components/widgets/generic_modal.tsx
> +    handleCancel?: (() => void) | null;
Would it make sense to `: undefined` here instead?

2021-08-24 14:59 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +function UpdateRunStatusModal({playbookRunId, playbookId, channelId, ...props}: Props) {
Sorry for not addressing that… that would be true if the type signature was correct, I corrected it now so that it reads correctly.

2021-08-24 15:00 UTC, calebroseland commented on webapp/src/components/widgets/generic_modal.tsx
> +    handleCancel?: (() => void) | null;
Yes, but I wanted to avoid the ESlint comment for now. We can switch it after allowing undefined