MM-37776 Use query for filtering in run lists.
mattermost/mattermost-plugin-playbooks pull request #704
Opened 2021-08-20 18:05 UTC by crspeller

#### Summary
Use query for filtering as well as fixing the status drop down so it syncs with query parameters. 

This allows flows like:
- Filter down to the runs you want.
- Click on one and view overview
- Click back button
- Back to the filtered list!

As well as sharing links to filtered lists. 

It works for both the main run list and the one for playbooks. 

Example query string:
```
http://localhost:9005/playbooks/runs?page=0&per_page=15&sort=last_status_update_at&direction=asc&statuses=InProgress&statuses=Finished&owner_user_id=mbbpisxh4igi7y3hyqupc8w4eh&team_id=wyqetf4o9jb73c8jx4ns31wchc
```

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37791

#### Checklist
~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
~~- [ ] Unit tests updated~~

2021-08-20 18:07 UTC, crspeller commented on webapp/src/components/backstage/runs_list/status_filter.tsx
> +function statusesToOptions(statuses: string[]) {
I really just forced this to behave the way I wanted. It's not pretty, but I think we are probably going to change this control soon anyway as it's kinda awkward for only the two statuses.

2021-08-20 18:22 UTC, lieut-data approved these changes
Wow, nice! That was easier than I expected -- one comment below, plus the eternal inquiry about e2e tests :p

2021-08-20 18:22 UTC, lieut-data commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        history.goBack();
Does this make sense if I permalink to this page?

2021-08-20 18:26 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        history.goBack();
Really I don't have any clue what that back button means. This preserves the behavior of being able to go back to a filtered run list. 
I tried to see if there is a way to tell if you came from a direct link. There is not reliable way because of security. 
Really 0/5 on what happens here.

2021-08-23 12:57 UTC, iomodo approved these changes

2021-08-24 17:22 UTC, lieut-data requested changes
Requesting changes re: history browsing, but going to effect them myself.

2021-08-24 17:22 UTC, lieut-data commented on webapp/src/hooks/general.ts
> +        history.replace({search: qs.stringify(fetchParams, {addQueryPrefix: false, indices: false})});
Trying this out, and I'm not sure `replace` is the right primitive to use here. It sort of makes sense when filtering, but when I browse to page 2 and then click back, it's very disorienting to be thrown somewhere else completely, only to click forward and end up back on page 2.

I think we should probably just stack the navigation changes normally instead. For better or worse, it's what Jira does, and seems less surprising.

2021-08-24 17:55 UTC, lieut-data commented
Actually, this is proving trickier, since there's no apparent sync between history changes and the params. We'd need to listen to `location` changes as well for this to happen, but then it's awkward having two sources of truth. Maybe the query string should be authoritative?

I'll push the merge conflicts for now, but leaving the requested changes unresolved for now.

2021-08-25 00:59 UTC, crspeller commented on webapp/src/hooks/general.ts
> +        history.replace({search: qs.stringify(fetchParams, {addQueryPrefix: false, indices: false})});
Totally preference here I think because I really disliked the back button controlling the paging and the filtering when I tried it out. It makes way more sense to me for that to not be controlled by history. This is an app, not a webpage. If this where android you wouldn't expect the back button to undo a filter.

2021-08-25 12:38 UTC, lieut-data commented on webapp/src/hooks/general.ts
> +        history.replace({search: qs.stringify(fetchParams, {addQueryPrefix: false, indices: false})});
Right, but the back button is present -- intentionally so, even, on desktop -- and I think the experience using it is worse with this feature than without. If we choose not to integrate with the browser's history navigation, the only benefit here is the ability to permalink to a particular view, and we should probably expose that in some other way instead (i.e. explicit "copy link to this page").

Let's raise with @itao and @abhijit-singh? Maybe we can spin up a cloud test server with this change installed for experimentation?

2021-10-05 13:27 UTC, lieut-data commented
@crspeller, can you sync with @itao on the desired user experience here / tradeoffs?

2021-10-05 13:31 UTC, itao commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        history.goBack();
To confirm, is it this back button?

![Screen Shot 2021-10-05 at 9 30 28 AM](https://user-images.githubusercontent.com/725414/136032797-5a89d34a-2c55-479d-b3f1-74b824fff361.png)

2021-10-05 13:38 UTC, itao commented on webapp/src/hooks/general.ts
> +        history.replace({search: qs.stringify(fetchParams, {addQueryPrefix: false, indices: false})});
It'd be really helpful to click around as a user 🙏

2022-01-12 21:09 UTC, crspeller commented
@lieut-data Solved the awkwardness by having an infinite scroll list. Now there is no page / per_page in the query parameters.

2022-01-13 20:25 UTC, lieut-data approved these changes
:tada: -- is there a good way to e2e test this behaviour?

2022-01-13 20:25 UTC, lieut-data commented on webapp/src/components/backstage/runs_list/runs_list.tsx
> +	width: 100%;
nit: indentation here seems off (and in next component)?

2022-01-13 20:33 UTC, crspeller commented on webapp/src/components/backstage/runs_list/runs_list.tsx
> +	width: 100%;
It was. My vim has been doing some strange things with tabs as of late.

2022-01-13 21:45 UTC, merged