MM-37775 - New run permissions
mattermost/mattermost-plugin-playbooks pull request #708
Opened 2021-08-23 17:33 UTC by cpoile

#### Summary
- Moving to a permissions model where the decision steps are: 
  1. Are you an admin? If so, you can see that run info.
  2. Can you view the playbook the run is based on? (either the original playbook is public to the team and you're a team member, or the playbook is private and you're a member of the playbook) If so, you can view the run.
  3. Are you a guest? If so, you can see that run info only if you a channel member.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-37775

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-08-23 19:56 UTC, lieut-data requested changes
Thanks, @cpoile! A few comments, but also wondering if we can write an e2e test to exercise the permutations here to feel confident about access and such. The mocked unit tests remain unsatisfying for proving correctness :/

2021-08-23 19:56 UTC, lieut-data commented on server/api/playbooks.go
> +	if err2 := app.PlaybookAccess(userID, vars["id"], h.playbookService, h.pluginAPI); err2 != nil {
nit: can we avoid `err2`?

2021-08-23 19:56 UTC, lieut-data commented on server/api/playbooks.go
> +	if err := app.PlaybookAccess(userID, vars["id"], h.playbookService, h.pluginAPI); err != nil {
nit: worth declaring `playbookID := vars["id"]` for clarity?

2021-08-23 19:56 UTC, lieut-data commented on server/app/permissions.go
> +func ViewPlaybookRunFromPlaybookRunID(userID, playbookRunID string, playbookService PlaybookService, playbookRunService PlaybookRunService, pluginAPI *pluginapi.Client) error {
nit: `UserCanViewPlaybookRun`? (Also, accepting the `id` feels like the default case, vs. something like `...FromChannelId`).

2021-08-23 19:56 UTC, lieut-data commented on server/app/permissions.go
> +func ViewPlaybookRunFromChannelID(userID, channelID string, playbookService PlaybookService, playbookRunService PlaybookRunService, pluginAPI *pluginapi.Client) error {
nit: `UserCanViewPlaybookRunFromChannelID`?

2021-08-23 19:56 UTC, lieut-data commented on server/app/permissions.go
> +	return PlaybookAccess(userID, playbookRunID, playbookService, pluginAPI)
Passing `playbookRunID` but `PlaybookAccess` takes a `playbookID`?

2021-08-23 19:56 UTC, lieut-data commented on server/sqlstore/playbook_run.go
> + 			  NOT EXISTS(
Checking for the non-existence of a row to identify a positive permission "feels" weird. It seems accurate, but weird.

2021-08-24 20:03 UTC, cpoile commented on server/api/playbooks.go
> +	if err2 := app.PlaybookAccess(userID, vars["id"], h.playbookService, h.pluginAPI); err2 != nil {
huh, that's weird, don't know how that got in there. Yep, gone. thanks! (Also cleaned up the other err2, err3s etc in the file)

2021-08-24 20:03 UTC, cpoile commented on server/app/permissions.go
> +func ViewPlaybookRunFromPlaybookRunID(userID, playbookRunID string, playbookService PlaybookService, playbookRunService PlaybookRunService, pluginAPI *pluginapi.Client) error {
Yep, good ideas. Done.

2021-08-24 20:03 UTC, cpoile commented on server/app/permissions.go
> +	return PlaybookAccess(userID, playbookRunID, playbookService, pluginAPI)
Oh man... That was a mistype. To be fair, `playbookRunID` and `playbookID` are too similar. 😝  You're right, the mocked tests don't do enough--I was also confusing `playbookID` and `playbookRunID` in the mocks! We need e2e tests for this: https://mattermost.atlassian.net/browse/MM-38136

2021-08-24 20:03 UTC, cpoile commented on server/sqlstore/playbook_run.go
> + 			  NOT EXISTS(
That's how it's designed, sadly. An empty members list means the playbook is public. :). (ask Christopher. I think we all debated about it back then, too.)

2021-08-24 20:04 UTC, cpoile commented
I've assigned myself https://mattermost.atlassian.net/browse/MM-38136 for next week so that I can work on the threaded replies.

2021-08-24 20:38 UTC, lieut-data approved these changes
:+1:

2021-08-25 15:58 UTC, iomodo approved these changes
Wonderful!

2021-08-31 22:15 UTC, cpoile commented
@lieut-data I think this is ready to go now -- #719 verifies the different combinations work as expected. 

We'll need to make announcements on community explaining the new permissions scheme to everyone (hide your sensitive playbook names, checklists, and retros by making the playbook private). Maybe @justinegeffen should work on that, or is it okay if I do it?

2021-09-01 13:13 UTC, lieut-data commented
@cpoile, please do take the lead on drafting and disseminating that information, but feel free to rely on @justinegeffen as needed!

2021-09-01 13:28 UTC, justinegeffen commented
Happy for you to do it, @cpoile! And of course always happy to lend an editorial eye. :)

2021-09-08 14:26 UTC, cpoile commented
@stephenvanhemmen This is an example notification. (Just a test for the checklists notification feature)

2021-09-14 14:01 UTC, merged