MM-37637, MM-38257: Post update reminder timer and revamped FormattedDuration
mattermost/mattermost-plugin-playbooks pull request #724
Opened 2021-09-05 05:08 UTC by calebroseland

#### Summary

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2021-09-14 13:15 UTC, lieut-data approved these changes
A handful of comments, but nothing strictly blocking -- awesome to see some e2e typing improvements too!

2021-09-14 13:15 UTC, lieut-data commented on webapp/package.json
> +    "luxon": "2.0.2",
Separate from this PR, should we consider getting this added to mattermost-webapp and just mark it as an external dependency?

2021-09-14 13:15 UTC, lieut-data commented on webapp/src/types/playbook_run.ts
> +    /** Previous reminder timer as nanoseconds */
Are we actually storing nanoseconds? Does that run into any JavaScript precision issues?

2021-09-14 13:15 UTC, lieut-data commented on webapp/src/utils.ts
> +    return n;
nit: would it be sufficient to just handle `0` in either of the other blocks?

2021-09-14 13:15 UTC, lieut-data commented on webapp/src/components/datetime_input.tsx
> +        -webkit-transition: all 0.15s ease;
Are we required to do the `-webkit` stuff? I had been imagining something in the pipeline would take care of this based on our configured target browsers (but maybe that's a pipedream :p).

2021-09-14 13:15 UTC, lieut-data commented on webapp/src/components/datetime_input.tsx
> +export function infer(query: string, mode: Mode.DateTimeValue): DateTime | null;
Are the three `export function infer` intended here?

2021-09-14 13:15 UTC, lieut-data commented on webapp/src/components/formatted_duration.tsx
> +    return num >= 2 ? plural : singular;
Not blocking, but I'll be interested to see how we transition this re: i18n, where I believe some languages have more complexity than just singular/plural.

2021-09-14 13:15 UTC, lieut-data commented on webapp/src/components/modals/update_run_status_modal.tsx
> +    if (
This block feels brittle, but apart from moving to explicit state management (ala Redux), I don't have any suggestions :)

2021-09-14 14:24 UTC, calebroseland commented on webapp/src/types/playbook_run.ts
> +    /** Previous reminder timer as nanoseconds */
It's a `time.Duration` in the struct. Realistically it's not an issue as we drop down to more common units before processing any official dates. We only use this as the last reminder interval—so unless the last reminder was ~290+ years prior, I think it should be fine. 😛

2021-09-14 14:27 UTC, calebroseland commented on webapp/src/components/datetime_input.tsx
> +export function infer(query: string, mode: Mode.DateTimeValue): DateTime | null;
Yes, they provide the proper return types based on the `mode` provided.

2021-09-14 14:40 UTC, calebroseland commented on webapp/src/components/formatted_duration.tsx
> +    return num >= 2 ? plural : singular;
For this first revision, I didn't want to go too far past what was needed—this will indeed need to be replaced with something. I'm not directly aware of an API that does full-precision duration printing, and Intl.UnitFormat appears to be a decent ways out, so various formatted messags with a `{plural, =0, =1, =2, many {...}}` will probably be needed in the i18n epic.

2021-09-14 14:44 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +    if (
I did not enjoy writing this one in particular 🙃. I think breaking this out to a custom hook at a minimum would be at least for now—we could then reinforce it more easily there.

2021-09-14 18:12 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +    if (
Wrote `useDefaultMessage` below—should be much cleaner now.

2021-09-14 18:13 UTC, calebroseland commented on webapp/src/utils.ts
> +    return n;
simplified

2021-09-14 21:35 UTC, calebroseland commented
/update-branch

2021-09-15 17:22 UTC, calebroseland commented on webapp/package.json
> +    "luxon": "2.0.2",
Yes, that would be good to do! Opened a ticket for that, and an epic to contain smaller efforts. https://mattermost.atlassian.net/browse/MM-38572

2021-09-16 15:17 UTC, cpoile requested changes
Just minor questions, nothing serious. Very nice!

2021-09-16 15:17 UTC, cpoile commented on webapp/src/components/modals/update_run_status_modal.tsx
> +};
I thought we had this in a hook in the old hooks file? or was that deleted?

2021-09-16 15:17 UTC, cpoile commented on webapp/src/components/modals/update_run_status_modal.tsx
> +export const useReminderTimer = (
nit: could this be named better? If it returns the input and the reminder, maybe a different title would be more descriptive?  (I'm mentioning because I had to reread it a few times and then realized what it was doing, and the title may have thrown me off a bit)

2021-09-16 15:17 UTC, cpoile commented on webapp/src/hooks/crud.ts
> +}
shouldn't this be in the store already?

2021-09-16 16:54 UTC, calebroseland commented on webapp/src/components/datetime_input.tsx
> +    makeOptions = (query, datetimes, durations) => {
Yeah, looks like its straightforward to do in this case.

2021-09-16 22:06 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +export const useReminderTimer = (
`useReminderTimerSetting`? I agree something more specific would be more clear

2021-09-16 22:08 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +};
I couldn't find one, but if one exists I would switch it. I skimmed some of this logic from server-side logic that composes the interactive dialog.

2021-09-20 14:58 UTC, calebroseland commented on webapp/src/hooks/crud.ts
> +}
Indeed it is—I started down a line of fixing this, but got dragged into a rabbit trail of fixing types associated with `myPlaybookRunsByTeam`. I propose to leave this as-is for this PR and I'll open those changes as a follow-up PR.

2021-09-20 15:16 UTC, cpoile commented on webapp/src/hooks/crud.ts
> +}
Cool, should we make a ticket to track it?

2021-09-20 15:16 UTC, cpoile approved these changes
Awesome, thanks @calebroseland !

2021-09-20 19:00 UTC, merged