Mm 34850 multiple web hooks
mattermost/mattermost-plugin-playbooks pull request #726
Opened 2021-09-08 16:28 UTC by Duaard

#### Summary

See [issue](https://github.com/mattermost/mattermost-server/issues/18307) description for details

#### Ticket Link

Fixes: mattermost/mattermost-server/issues/18307
JIRA: https://mattermost.atlassian.net/browse/MM-34850

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2021-09-08 16:28 UTC, mattermod commented
Hello @Duaard,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-09-08 16:33 UTC, Duaard commented
There are no tests yet, and there's a lot of cleaning to do but I just wanted to make sure this is the direction you guys wanted to go. 😄 

I tried my best to follow the current codebase in terms of handling arrays for the DB (Concatenated string columns) and also refered heavily to how `mattermost-server` handled their own implementation of this.

2021-09-08 18:08 UTC, agarciamontoro commented
Self-requesting a review here so I don't forget tomorrow. Thank you for this, @Duaard!

2021-09-09 17:15 UTC, agarciamontoro reviewed
I just found some time for taking a quick look at this, sorry for the delay! It looks really good, and I think the approach is sensible, as it replicates what we already have in mattermost-server.

So go ahead with it, I'm looking forward to getting this merged!

2021-09-14 18:48 UTC, lieut-data commented
@cpoile, with @agarciamontoro out at the moment, can you connect with @Duaard on any next steps required here?

2021-09-14 18:51 UTC, cpoile commented
@Duaard If I'm not mistaken, you're still actively developing this, correct? Let me know when you're ready for review, or if there are any outstanding questions!

2021-09-15 02:12 UTC, Duaard commented
@cpoile Yep, will open the PR once I fix the e2e tests. I rebased and it broke a few things so I am currently bug fixing atm. :)

2021-09-15 16:00 UTC, cpoile commented
@Duaard There is a problem with our e2e tests I believe, @lieut-data is working on them. Maybe wait until you see a PR to fix it?

2021-09-15 16:57 UTC, Duaard commented
@cpoile Thanks for the heads up, I'll wait on that. I looked at the fail and I can confirm I have fixed the problems on my end, at least those that resulted in the fails last night. 😆

2021-09-17 14:33 UTC, lieut-data commented
/update-branch

2021-09-17 14:33 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2021-09-27 14:13 UTC, lieut-data commented
/update-branch

2021-09-27 14:13 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2021-09-27 17:08 UTC, lieut-data commented
@Duaard / @cpoile / @agarciamontoro, I took the liberty of resolving the merge conflicts here. The one remaining test failure should be resolved once the upstream server changes are committed in https://github.com/mattermost/mattermost-server/pull/18464.

2021-09-27 17:14 UTC, Duaard commented
Thanks a lot @lieut-data, apologies as I've been busy these past few days. I'll mark this ready for review, so I can work on some revisions while waiting for https://github.com/mattermost/mattermost-server/pull/18464 to be merged. 😄

2021-09-30 17:09 UTC, lieut-data commented
/update-branch

2021-09-30 17:12 UTC, Duaard commented
Looks like there's a failing test that verifies announcement made on failing webhook. Do I just remove that, since the logic is to just log errors now?

2021-09-30 17:44 UTC, lieut-data commented
That makes sense to me, @Duaard!

2021-09-30 18:48 UTC, lieut-data commented
Awesome! I've invited @crspeller to join @cpoile in taking a look and hopefully getting this merged soon :)

2021-09-30 19:10 UTC, cpoile requested changes
Awesome work @Duaard, thank you for the contribution. :)
I've left a few comments and suggestions, please let me know if you have any questions!

2021-09-30 19:10 UTC, cpoile commented on tests-e2e/db-setup/mm534.sql
> +    concatenatedwebhookoncreationurls text DEFAULT ''::text,
I don't think we need to edit this file manually -- the migration will take care of it.

2021-09-30 19:10 UTC, cpoile commented on webapp/src/components/backstage/automation/patterned_text_area.tsx
> +export const PatternedTextArea: FC<Props> = (props: Props) => {
Do you think there's a way to use this new component for the `user-joins-channel-categorize` input, and then get rid of the old `PatternedInput` component?  (If not, no worries -- I'm just wondering.)

2021-10-01 02:53 UTC, Duaard commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) sendWebhooksOnUpdateStatus(playbookRunID string) {
Yes, so the `error` being returned is mostly used to log the error and then post a message saying the webhook failed to send. Since we no longer posts any message and all error logging is done inside, there's no longer any need for returning an error.

2021-10-01 02:57 UTC, Duaard commented on server/app/playbook_run_service.go
> +	for i := range webhooks {
This will fail then since we'll be referencing the iterator value in the go func. See: https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables

2021-10-01 03:07 UTC, Duaard commented on webapp/src/components/backstage/automation/patterned_text_area.tsx
> +export const PatternedTextArea: FC<Props> = (props: Props) => {
Yep, we can set the right rows and disable auto resize and then make it act like a text input, although IMO it's better to have a separate component basing on Text input (`PatternedInput`) than have a Text Area component act as text input. Thoughts?

2021-10-01 03:08 UTC, Duaard commented on tests-e2e/db-setup/mm534.sql
> +    concatenatedwebhookoncreationurls text DEFAULT ''::text,
I'll revert this then, might be when I was frantically trying to make the e2e test to work and just did a whole search and replace. 😄

2021-10-01 15:12 UTC, crspeller requested changes
Great stuff! Just one improvement suggestion.

2021-10-01 15:12 UTC, crspeller commented on server/app/playbook_run_service.go
> +func triggerWebhooks(s *PlaybookRunServiceImpl, webhooks []string, body []byte) {
Could we have a hard cap here on how many webhooks this will send? I thinking of a bit of prevention against someone using this for a DOS attack or spamming. Maybe 64? We can do some validation at the api layer as well so if someone does it this it gives them a reasonable error.

2021-10-01 17:20 UTC, Duaard commented on server/app/playbook_run_service.go
> +func triggerWebhooks(s *PlaybookRunServiceImpl, webhooks []string, body []byte) {
Good call, I see that `mattermost-server` handle it by limiting the entire array string to < 1024, should I follow this or just limit the len of the arr to 64?

2021-10-01 17:27 UTC, crspeller commented on server/app/playbook_run_service.go
> +func triggerWebhooks(s *PlaybookRunServiceImpl, webhooks []string, body []byte) {
0/5 I would say limiting the length of the array seems more clear.

2021-10-04 14:12 UTC, cpoile commented on server/app/playbook_run_service.go
> +	for i := range webhooks {
Ah, missed that part. You could then do:
```
for _, hook := range webhooks {
   url := hook
   ....
}
```
Or, just leave it like this. Up to you. 👍

2021-10-04 14:13 UTC, cpoile commented on webapp/src/components/backstage/automation/patterned_text_area.tsx
> +export const PatternedTextArea: FC<Props> = (props: Props) => {
Sure, it makes sense to keep them separate. 👍

2021-10-04 14:17 UTC, cpoile requested changes
One more comment and a request, otherwise it's looking great @Duaard !

2021-10-04 14:17 UTC, cpoile commented on server/api/playbooks.go
> +		}
I think we should probably do this on the input side (in the Actions menu) -- that's where the user is entering it, and that's where they would be able to fix the error.

2021-10-04 14:51 UTC, crspeller approved these changes

2021-10-04 18:01 UTC, Duaard commented on server/api/playbooks.go
> +		}
Added in the check and also touched up on the Webhook description 😄

2021-10-05 17:49 UTC, cpoile approved these changes
Awesome, looks great @Duaard! I have a couple wording suggestions, otherwise it's good to go.

2021-10-05 17:49 UTC, cpoile commented on webapp/src/components/backstage/automation/settings.tsx
> +                        maxErrorText={'Invalid webhooks, limit to less than 64'}
```suggestion
                        maxErrorText={'Invalid entry: the maximum number of webhooks allowed is 64'}
```

2021-10-06 00:48 UTC, lieut-data commented
Wow, really awesome work @Duaard! @cpoile / @agarciamontoro, I'll leave you to merge when ready.

2021-10-06 08:20 UTC, agarciamontoro approved these changes
Impressive job, @Duaard, thanks again for your amazing contribution. Merging now :tada:

2021-10-06 08:20 UTC, merged