Assorted follow up fixes, typing improvements
mattermost/mattermost-plugin-playbooks pull request #750
Opened 2021-09-20 22:00 UTC by calebroseland

#### Summary
- Fix: `<MarkdownTextbox/>` background color, was hard-white in Playbook Edit
-

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2021-09-22 09:32 UTC, agarciamontoro requested changes
Great work here, @calebroseland! I left a bunch of comments, but most of them nits.

Nice abstraction in useThing, by the way, it's cool :tada:

2021-09-22 09:32 UTC, agarciamontoro commented on webapp/src/reducer.ts
> +type TStateMyPlaybookRunsByTeam = Record<Team['id'], null | Record<Channel['id'], PlaybookRun>>;
What does `TState` mean?

2021-09-22 09:32 UTC, agarciamontoro commented on webapp/src/reducer.ts
> +            }
If `tx` is undefined, don't we want to create a new record there and initialize it with `tx[playbookRun.channel_id] = playbookRun;`? Maybe I'm misunderstanding something.

2021-09-22 09:32 UTC, agarciamontoro commented on webapp/src/reducer.ts
> +export type PlaybooksPluginState = ReturnType<typeof reducer>;
Nice!

2021-09-22 09:32 UTC, agarciamontoro commented on webapp/src/selectors.ts
> +const pluginState = (state: GlobalState): PlaybooksPluginState => state['plugins-' + pluginId as keyof GlobalState] as unknown as PlaybooksPluginState || {} as PlaybooksPluginState;
Type system, yay!

Is `as unknown as PlaybooksPluginState` effectively "clearing" the type information and then prescribing that it should be `PlaybooksPluginState`? Why doesn't Typescript let us do just as `PlaybooksPluginState`?

2021-09-22 09:32 UTC, agarciamontoro commented on webapp/src/selectors.ts
> +            return false;
This is changing the old behaviour, right? If the loop was skipped, the function returned true before.
I don't know exactly what we want here, just bringing up the difference.

2021-09-22 09:32 UTC, agarciamontoro commented on webapp/src/selectors.ts
> +        const tx = playbookRunMapByTeam[teamId];
Nit: can we use a more descriptive name? `runMap`, maybe?

2021-09-22 09:32 UTC, agarciamontoro commented on tests-e2e/cypress/integration/backstage/playbook_run_details_spec.js
> +                expect($img[0].naturalWidth).to.be.greaterThan(0);
Oh, cool!

2021-09-22 14:39 UTC, calebroseland commented on webapp/src/hooks/general.ts
> +function useThing<T extends NonNullable<any>>(
Idk, I think it's okay as I see it as just a continuation of the pattern of `usePost`, `useRun`, `usePlaybook`, etc. 2/5.

If you feel strongly about it, I'm fine switching it to `useSelectOrFetchThing`.

2021-09-22 14:40 UTC, calebroseland commented on webapp/src/reducer.ts
> +type TStateMyPlaybookRunsByTeam = Record<Team['id'], null | Record<Channel['id'], PlaybookRun>>;
"Type of state ..."

2021-09-22 14:53 UTC, calebroseland commented on webapp/src/selectors.ts
> +            return false;
I think you're right 👍

2021-09-22 14:54 UTC, calebroseland commented on tests-e2e/cypress/integration/backstage/playbook_run_details_spec.js
> +                expect($img[0].naturalWidth).to.be.greaterThan(0);
👉 @lieut-data

2021-09-22 15:10 UTC, calebroseland commented on webapp/src/selectors.ts
> +const pluginState = (state: GlobalState): PlaybooksPluginState => state['plugins-' + pluginId as keyof GlobalState] as unknown as PlaybooksPluginState || {} as PlaybooksPluginState;
Because `pluginId` doesn't exist in mattermost-redux's `GlobalState`, it falls back to `{}`'s default signature with a value type of `any`, which can't safely be converted to `PlaybooksPluginState`

This somewhat of a stop-gap—I didn't want to go too far here—but the next step would be to define our own GlobalState which itself defines what PlaybooksPluginState should be.

2021-09-22 16:52 UTC, agarciamontoro commented on webapp/src/hooks/general.ts
> +function useThing<T extends NonNullable<any>>(
Not strongly, we leave it as it is., no problem!

Just to share my point of view: I also see it as a continuation of the pattern of `usePost`, `useRun`, etc. But that explains how you came up with the abstraction, not what the abstraction actually means. But, as I said, let's leave it as it is.

2021-09-22 16:52 UTC, agarciamontoro commented on webapp/src/reducer.ts
> +type TStateMyPlaybookRunsByTeam = Record<Team['id'], null | Record<Channel['id'], PlaybookRun>>;
Oooh, okay. I stlil have to get used to some conventions in Typescript. Thanks!

2021-09-23 15:54 UTC, agarciamontoro commented on webapp/src/reducer.ts
> +            }
@calebroseland, I am still a bit unsure about this one. Thoughts?

2021-09-23 16:57 UTC, calebroseland commented on webapp/src/reducer.ts
> +            }
Sorry @agarciamontoro, I think I forgot to send the comment I had drafted. 

This change was only to make typescript happy. Logically, it is not possible for `newState[teamId]` to not be an object because it is explicitly defined as a new object above, but TS isn't currently able to correctly infer that.

2021-09-24 08:18 UTC, agarciamontoro commented on webapp/src/reducer.ts
> +            }
Oh, ok, perfect then! Thanks for the explanation :)

2021-09-24 08:18 UTC, agarciamontoro approved these changes
Thank you, looks great! :tada:

2021-09-24 13:24 UTC, cpoile approved these changes
This is awesome, thanks @calebroseland!
There's one question for @itao that I'd love to get answered, but otherwise non-blocking questions. I'll approve so I'm not blocking getting this in soon.

2021-09-24 13:24 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
> +            if (sp.delete_at === 0) {
I think we need to confirm whether or not deleting a status post means the status post never happened in the overview. I thought we were moving more towards the overview being a record of what happened in the incident? @itao can you comment?

2021-09-24 13:24 UTC, cpoile commented on webapp/src/hooks/general.ts
> +    return useThing(postId, Client4.getPost, getPostFromState);
This is cool, nice abstraction. 👍

2021-09-24 13:24 UTC, cpoile commented on webapp/src/hooks/general.ts
> +            return runsByTeam[teamId]?.[channelId];
👍

2021-09-24 13:24 UTC, cpoile commented on webapp/src/reducer.ts
> +const reducer = combineReducers({
Is there a difference between the old way and the new way of exporting the default?

2021-09-24 16:15 UTC, calebroseland commented on webapp/src/reducer.ts
> +const reducer = combineReducers({
No, the export should be exactly the same, just available locally now

2021-09-24 16:15 UTC, calebroseland commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
> +            if (sp.delete_at === 0) {
Cross linking for possible relevance https://mattermost.atlassian.net/browse/MM-38832

2021-09-24 17:01 UTC, merged