MM-38566 Updating to new playbooks icon.
mattermost/mattermost-plugin-playbooks pull request #752
Opened 2021-09-21 19:27 UTC by crspeller

#### Summary
Updates icon to new version

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38566

2021-09-22 09:40 UTC, iomodo approved these changes

2021-09-22 09:59 UTC, agarciamontoro requested changes

2021-09-22 09:59 UTC, agarciamontoro commented on assets/plugin_icon.svg
>  </svg>
Can we indent this?

2021-09-22 15:55 UTC, crspeller commented on assets/plugin_icon.svg
>  </svg>
Since it's just an svg file I didn't even look at it after copying it from the ticket. Done.

2021-09-22 15:56 UTC, agarciamontoro approved these changes

2021-09-22 16:04 UTC, merged

2021-09-24 10:21 UTC, agarciamontoro commented
@crspeller, just noticed that this ticket included changing the bot's name to `Playbooks`. Did that in https://github.com/mattermost/mattermost-plugin-playbooks/pull/763