MM-37699: improved finished run semantics
mattermost/mattermost-plugin-playbooks pull request #759
Opened 2021-09-22 20:08 UTC by lieut-data

#### Summary
Improved finish semantics:
* Add a Finished tag next to the run name. 
* Disable the Post update button. 
* Change the icon in the update box to a chequered flag 
* Change text to Run finished X minutes/hours/days ago. 
* Disable the checkbox for all the tasks (checked and unchecked)
* Remove/disable options to Add task, reorder tasks, add/edit assignee, edit task, delete task. 
* Hide the ability to “Run” any associated slash command
* Don't open the RHS by default for finished runs

<img width="488" alt="CleanShot 2021-09-22 at 17 06 59@2x" src="https://user-images.githubusercontent.com/1023171/134414265-f138838f-d79f-427e-89c8-5908c89ce080.png">

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37699

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-09-23 10:39 UTC, agarciamontoro requested changes
Looks great! There's just one comment we need to address.

Also, I wanted to bring up that the disabled button is almost unreadable
![image](https://user-images.githubusercontent.com/3924815/134492591-6b1e6425-a8c2-4209-8235-3dbc916400dc.png)

Should we make it a bit less transparent?

2021-09-23 10:39 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_post_update.tsx
> +        icon = Clock;
The exclamation and clock icons are not visible now, we need to instantiate them. I don't know why Typescript is ok with the current code, by the way, shouldn't it complain?

```suggestion
        icon = <Exclamation/>;
    } else {
        icon = <Clock/>;
```

2021-09-23 16:25 UTC, lieut-data commented on webapp/src/components/rhs/rhs_post_update.tsx
> +        icon = Clock;
Ooh, good catch: didn't even notice that! I think TypeScript doesn't complain since I didn't type the variable, and rendering the function is "ok" but probably results in nothing? Fixed with typing:

<img width="682" alt="CleanShot 2021-09-23 at 13 24 59@2x" src="https://user-images.githubusercontent.com/1023171/134546377-79730d71-c0fd-43fb-ba57-7cd1ae8871e3.png">

2021-09-23 16:26 UTC, lieut-data commented
@agarciamontoro, can you share the theme on which you're seeing the really faded text?

2021-09-23 16:36 UTC, agarciamontoro commented
@lieut-data: Sure, it's the default, Denim.
![image](https://user-images.githubusercontent.com/3924815/134548106-5ab538c2-137a-4cc4-8857-fc05444142b7.png)

2021-09-23 20:29 UTC, lieut-data commented
Thank you for that, @agarciamontoro! Missed that in testing -- looks like `TertiaryButton` needed some improved `:disable` love: fixed! The one failing CI test is unrelated to this PR, but should hopefully be fixed upstream soon.

2021-09-24 06:48 UTC, agarciamontoro approved these changes
Much better, thank you! :tada:

2021-09-24 06:48 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_post_update.tsx
> +        icon = Clock;
Cool!

2021-09-24 14:53 UTC, cpoile approved these changes
Couple of comments, non-blocking. Thanks for fixing this @lieut-data!

2021-09-24 14:53 UTC, cpoile commented on webapp/src/components/checklist_item.tsx
> +                        {!props.disabled &&
I haven't tested it, but if the entire <HoverMenu> is guarded with `!props.disabled`, do you need to put this guard here?

2021-09-24 14:53 UTC, cpoile commented on webapp/src/components/rhs/rhs_about_title.tsx
> +                    <StatusBadgeWrapper status={PlaybookRunStatus.Finished}/>
🙌

2021-09-24 14:53 UTC, cpoile commented on webapp/src/rhs_opener.ts
> +        }
I'm not sure if I like this -- I think I'd want the RHS to open: to remind me that this was an incident, so I know the playbooks product isn't broken, and so I can click on the `Run Details` link to quickly get to the overview/retro screens.

2021-09-24 14:55 UTC, lieut-data commented on webapp/src/rhs_opener.ts
> +        }
Part of this comes from a direct ask from @coreyhulen, but also our general desire to begin a shift away from the tight coupling between channels and playbook runs. If a run could be standalone, or you could start multiple runs in a channel, do you think these semantics begin to make more sense?

2021-09-24 14:57 UTC, lieut-data commented on webapp/src/components/checklist_item.tsx
> +                        {!props.disabled &&
There's two cases being handled: disabled and no description (hide the entire hover menu), and disabled but has a description (show the hover menu, but just the "(i)" icon). I suspect we can find better ways to surface the description in the first place, but I wanted to avoid the "empty" hover menu effect.

2021-09-24 17:41 UTC, lieut-data commented
(Merging, and we can continue discussing asynchronously?)

2021-09-24 17:41 UTC, merged