[MM-37314] Fix the categorization bug
mattermost/mattermost-plugin-playbooks pull request #761
Opened 2021-09-23 19:20 UTC by iomodo

#### Summary
An ugly fix for the categorization bug.
Comment in the code is pretty self-explanatory.
When user starts a run, channel is created, and user added to the channel. At that moment server sends the `user_added` socket event to the webapp. Webapp gets the event and tries to categorize the channel for the user by adding the channel to the default `CHANNELS` category. 
Concurrently we are trying to auto-categorize the channel into our category. Depending on what happens first channel might get stuck in `CHANNELS` category.

Unfortunately we can not reliably detect when webapp finished updating the state, that's why we are waiting for 5 seconds(A very magic number) to let webapp do its job.

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-37314

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2021-09-24 08:38 UTC, agarciamontoro approved these changes
I'm ok merging this if we want it for 1.20, but we should make sure to apply a proper fix as soon as we can. Can we maybe create a follow-up ticket for this and continue the investigation?

2021-09-24 15:01 UTC, lieut-data requested changes
Nice investigation :D

One comment below.

2021-09-24 15:01 UTC, lieut-data commented on server/app/playbook_run_service.go
> +	time.Sleep(5 * time.Second)
Let's not actually block the completion of the hook here, though, and run instead spawn a goroutine that blocks for the required workaround time.

2021-09-27 10:20 UTC, lieut-data approved these changes

2021-09-27 13:57 UTC, lieut-data commented
@iomodo, I /think/ the failures here are due to my requested changes re: making the categorization happen async: I guess the unit tests need to be updated?

2021-09-27 14:24 UTC, lieut-data approved these changes

2021-09-27 17:24 UTC, merged