MM-38668 - Send digest once a day when user logs on
mattermost/mattermost-plugin-playbooks pull request #775
Opened 2021-09-30 15:57 UTC by cpoile

#### Summary
- Refactoring of where the code lives (it belongs in `playbookRunService` because it's used by multiple dependents)
- Totally cribbing how Github plugin knows when to send daily notifications (`onClick` after an hour of inactivity -> server side checks if you've been sent today's message). On the face it seems like this is bad, but after thinking about it it's not that much work on the client (compared to what react does on any single rerender!). Basically a couple of math ops on every click. Only after inactivity for an hour do you get one request to the server, so no big deal.
- The one difficult design decision was making a UserInfo app struct, service, and sqlstore. There were a couple options here:
  - add the struct to the playbookRun file/service/store, but that felt like it completely violated separation of concerns.
  - use the KVStore. Initially I leaned towards this. But then I remembered Jesse's argument that we should keep out of the KVStore, so we know where all our data is.
  - that left it's own service/sqlstore. This seemed the technically "correct" option, even though it's a lot more typing. But I bit the bullet and now it's done. And now we can add fields whenever we need to store user-level information (which we will almost definitely need to in the future).

Slight redesign, now looks like:
![image](https://user-images.githubusercontent.com/1490756/135489539-2d5e5d4d-eb69-4b1c-bb93-bdc9a0c803c8.png)

#### Progress: 
- POC ✅ 
- Include list of ongoing runs ✅ 
- Include list of overdue updates ✅ 
- Send digest once a day when user logs on (<--- we're here)
- Telemetry (total number of in-notification link clicks, unique users who click)
- Design polish (if needed)
- e2e tests (once we have a firmed up design)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-38668

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-10-01 17:00 UTC, crspeller requested changes

2021-10-01 17:00 UTC, crspeller commented on server/app/user_info.go
> +type UserInfoService interface {
Do we need a service here? Maybe a raw store makes more sense since there really won't be any business logic here.

2021-10-01 17:00 UTC, crspeller commented on server/sqlstore/migrations.go
> +						LastDMAt BIGINT
Maybe we should be more specific. Like `LastDailySummaryDMAt`

2021-10-01 17:00 UTC, crspeller commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
There doesn't seem to be an option to turn this off. Should we have a user setting for that? Maybe I don't want these.

2021-10-04 15:33 UTC, cpoile commented on server/sqlstore/migrations.go
> +						LastDMAt BIGINT
Yep, makes sense. Done.

2021-10-04 15:34 UTC, cpoile commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
This is by design. Muting the playbooks bot = turning it off. @stephenvanhemmen for visibility.

2021-10-04 15:41 UTC, crspeller commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
What? How do you mute a bot?

2021-10-04 15:41 UTC, cpoile commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
I meant mute the DM channel

2021-10-04 15:51 UTC, crspeller commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
Oh. I guess that works. You just have to make sure it never mentions the user otherwise it will break the mute. 
I suspect people aren't going to think about using the mute functionality in this way. Also, when we implement the following runs feature people may want to receive those messages but not these ones. So it seems like we will need a setting then?

2021-10-04 15:54 UTC, cpoile commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
I'm 0/5 on which solution. I'm fine with a setting, that's what I suggested originally. But @tao and @stephenvanhemmen wanted to go with the mute. Up to you @tao and @stephenvanhemmen.
Personally, I love github messaging me every day, I rely on it all the time, so I've never thought of muting it.

2021-10-04 18:21 UTC, stephenvanhemmen commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
The current thinking around preventing notifications from being turned off is to always maintain a place where these cross-run notifications can be referenced for each user. Muting the bot may help the user if they do not wish to receive these notifications while still having a reference location for their responsibilities over all runs

2021-10-05 20:35 UTC, crspeller commented on server/api/bot.go
> +func (h *BotHandler) connect(w http.ResponseWriter, r *http.Request) {
I feel like I am going to mute notifications to suppress this, then never turn it back on for the follow feature.

2021-10-05 20:35 UTC, crspeller approved these changes

2021-10-06 13:44 UTC, iomodo approved these changes
Looks great!

2021-10-06 17:46 UTC, merged