MM-38872 - Telemetry for the todo message
mattermost/mattermost-plugin-playbooks pull request #776
Opened 2021-09-30 20:25 UTC by cpoile

#### Summary
- Will record interactions with each of the todo list sections. We can total the number of interactions, group based on unique userId, and by section (to see which section is most useful).
- If found, the search param is removed from the url (leaves other search params untouched)
- I added it to the RHSRunDetails component so that in the future we can use this params method to scroll to and/or highlight specific checklist items (e.g., click on the checklist item due, and we'll take you right to that item -- or as close as possible to that)
- cc @stephenvanhemmen 

#### Progress: 
- POC ✅ 
- Include list of ongoing runs ✅ 
- Include list of overdue updates ✅ 
- Send digest once a day when user logs on ✅ 
- Telemetry (<--- we're here)
- Design polish
- e2e tests (once we have a firmed up design)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-38872

#### Checklist

- [x] Telemetry updated
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-10-01 08:31 UTC, agarciamontoro approved these changes
Looks good!

A nit: is it possible to remove the telemetry params when the user is copying the link? If they copy it and pass it to someone else, we'll track that as a telemetry event, although they did not click on it. This is probably an edge case, so I'm ok merging without that.

2021-10-01 13:10 UTC, lieut-data requested changes
Thanks, @cpoile! I think my feedback is the same as Alejandro's, with just the observation that I think this breaks clicking back.

2021-10-01 13:10 UTC, lieut-data commented on webapp/src/components/rhs/rhs_run_details.tsx
> +        browserHistory.push({pathname: url.pathname, search: url.search});
Should we use `replace` here instead of `push`? I imagine clicking back right now results in this running a second time, making it hard to actually go back to previous locations.

2021-10-04 15:48 UTC, cpoile commented on webapp/src/components/rhs/rhs_run_details.tsx
> +        browserHistory.push({pathname: url.pathname, search: url.search});
It didn't make it run a second time, it would put the query string back into the location url--you could press back again to really go back. But definitely `replace` works better here. One-click to go back. Thanks!!

2021-10-04 15:55 UTC, cpoile commented
@agarciamontoro that's a good point. On the one hand, we don't want to get accidental telemetry if someone posts a copied link. On the other hand, this is probably a very rare edge case.  But just in case, do you know of a way to fix it? These are markdown urls -- is there a way to edit the link if copied, or have the click be different from the copied link? I can't think of a way to do that without javascript.

2021-10-04 16:14 UTC, agarciamontoro commented
@cpoile, I don't know of any way, sorry. And I agree that it's a rare case. I'm ok merging this without it.

2021-10-04 17:10 UTC, lieut-data approved these changes

2021-10-06 18:12 UTC, merged