[GH-17954] migrate profile_button to styled component
mattermost/mattermost-plugin-playbooks pull request #781
Opened 2021-10-01 20:06 UTC by lex111

#### Summary

This will migrate webapp/src/components/profile/profile_button.scss to styled-components

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/17954

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
~~- [ ] Unit tests updated~~

2021-10-01 20:06 UTC, mattermod commented
Hello @lex111,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-10-01 20:11 UTC, lex111 commented
/check-cla

2021-10-04 15:19 UTC, crspeller requested changes
Thanks for the PR!

2021-10-04 15:19 UTC, crspeller commented on webapp/src/components/profile/profile_button.tsx
>  import './profile_button.scss';
Looks like you just forgot to remove the import. That's why the build is failing.

2021-10-04 15:20 UTC, lex111 commented on webapp/src/components/profile/profile_button.tsx
>  import './profile_button.scss';
Oh, that's right, I forgot all about that.

2021-10-04 15:52 UTC, crspeller approved these changes

2021-10-04 15:52 UTC, merged

2021-11-05 17:07 UTC, emilyacook commented
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @lex111