Migrated webapp/src/components/backstage/playbook.scss
mattermost/mattermost-plugin-playbooks pull request #790
Opened 2021-10-05 13:59 UTC by a-sambhab

Migrated webapp/src/components/backstage/playbook.scss to styled-components.

#### Summary
deleted the migrated file without causing any styling regressions.

#### Ticket Link

#### Checklist

- [] ~~Telemetry updated~~
- [] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-10-05 16:45 UTC, crspeller requested changes
Thanks for the PR @a-sambhab!
I think the build isn't passing because the playbook.scss file was also imported in `playbook_edit.tsx`

2021-10-05 16:45 UTC, crspeller commented on webapp/src/components/backstage/playbook_list.tsx
> +                    <ContainerMedium>
There isn't a need for two wrapper divs here I don't think. We can combine the styles.

2021-10-05 16:45 UTC, crspeller commented on webapp/src/components/backstage/playbook_list.tsx
> +    .playbook-item {
It would be nice if these where split out into their own styled components instead of being a part of this component and using a className.

2021-10-07 09:12 UTC, a-sambhab commented
Hey, @crspeller can you help me with the 3 failing checks

2021-10-07 19:36 UTC, a-sambhab commented
Hey, @crspeller i think all the changes requested are taken care of can you please review again

2021-10-12 14:50 UTC, a-sambhab commented
Great will try this

2021-10-31 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-11-01 13:08 UTC, lieut-data commented
Hey @a-sambhab! Just wanted to check in to see if you saw @crspeller's comments above re: potentially missing changes?

2021-11-03 08:52 UTC, a-sambhab commented
Hey, yeah I'm working on it, I will send the pr by tomorrow eod

2021-11-05 17:14 UTC, emilyacook commented
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @a-sambhab

2021-11-10 10:03 UTC, a-sambhab commented
Hey, I am having some trouble finding where it went wrong so can you help me out a bit?

2021-11-11 23:09 UTC, closed without merging

2021-11-11 23:14 UTC, crspeller commented
@a-sambhab Hey. I fixed up your PR and attempted to push my changes to your branch. However I messed it up and somehow closed the PR. Opened a new one here: https://github.com/mattermost/mattermost-plugin-playbooks/pull/881

Thanks for your help!

2021-11-12 10:06 UTC, a-sambhab commented
Thank you so much @crspeller