[MM-39119] Auto complete categories in categorize playbook run
mattermost/mattermost-plugin-playbooks pull request #831
Opened 2021-10-25 14:35 UTC by dunak-debug

#### Summary
When configuring the optional sidebar category into which to categorize a new playbook run channel, it uses react-select `Creatable` component to expose user existing categories and also allow creating non existing category as before.

Before
![image](https://user-images.githubusercontent.com/19434539/138715290-40661e0e-dca7-4d51-b95a-5505ecafe283.png)

After
![image](https://user-images.githubusercontent.com/19434539/138715376-b9666111-4ed4-4442-ae77-93e8d9511620.png)

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/18562
https://mattermost.atlassian.net/browse/MM-39119

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-11-01 13:54 UTC, iomodo requested changes
Looks great @dunak-debug !  Thanks for the contribution.
Couple of suggestions below

2021-11-01 13:54 UTC, iomodo commented on webapp/src/components/backstage/category_selector.tsx
> +const getMyCategories = (state: GlobalState) => getCategoriesForTeam(state, state.entities.teams.currentTeamId);
Could we avoid using redux and use `GetChannelSidebarCategories` from the plugin API instead?

2021-11-01 13:54 UTC, iomodo commented on webapp/src/components/backstage/automation/categorize_playbook_run.tsx
> +);
Enter missing here

2021-11-01 13:54 UTC, iomodo commented on webapp/src/components/backstage/automation/categorize_playbook_run.tsx
> +const MenuList = (props: MenuListComponentProps<ChannelCategory>) => {
It would be ideal to reuse this component

2021-11-01 13:54 UTC, iomodo commented on webapp/src/components/backstage/automation/categorize_playbook_run.tsx
> +const ClearIndicator = ({clearValue}: {clearValue: () => void}) => (
Would be ideal to reuse this as well

2021-11-02 10:54 UTC, iomodo commented on webapp/src/components/backstage/category_selector.tsx
> +const getMyCategories = (state: GlobalState) => getCategoriesForTeam(state, state.entities.teams.currentTeamId);
@dunak-debug My bad. Missed the `fetchMyCategories` on playbook edit. Getting from the redux will actually be Ok here.

2021-11-02 10:55 UTC, iomodo commented on webapp/src/components/backstage/category_selector.tsx
> +const getMyCategories = (state: GlobalState) => getCategoriesForTeam(state, state.entities.teams.currentTeamId);
@agarciamontoro thanks for pointing out ^_^

2021-11-03 13:32 UTC, dunak-debug commented on webapp/src/components/backstage/category_selector.tsx
> +const getMyCategories = (state: GlobalState) => getCategoriesForTeam(state, state.entities.teams.currentTeamId);
Actually yes, we discussed something at mattermost and it would be OK to use redux here.

2021-11-03 13:32 UTC, dunak-debug commented
Thank you for review. I'll get home and look onto requested changes

2021-11-05 17:37 UTC, emilyacook commented
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @dunak-debug

2021-11-15 09:31 UTC, agarciamontoro commented
Hi, @dunak-debug, is there anything we can do to help you with this?

2021-11-15 09:34 UTC, dunak-debug commented
Hi, sorry I had corona and I couldnt really get into work on computer 😏 I feel bad for this big delay on this PR and as soon as I arrive home I will push changes and we can resolve any other reviews. Is that ok? 🙂

2021-11-15 10:04 UTC, agarciamontoro commented
Oh please, don't worry at all! Take all the time you need and get well soon, your health is way more important than any PR. Ping us when you're ready, there's no rush at all. Stay safe :)

2021-11-15 10:23 UTC, dunak-debug commented on webapp/src/components/backstage/automation/categorize_playbook_run.tsx
> +const MenuList = (props: MenuListComponentProps<ChannelCategory>) => {
Do you want to specify explicitly menu header title or inherit from placeholder?

2021-11-15 10:55 UTC, dunak-debug commented
I did some changes. Please @agarciamontoro, take a look and let me know

2021-11-16 11:44 UTC, agarciamontoro requested changes
Thank you, @dunak-debug! I left just a couple of minor comments, otherwise looks great :)

2021-11-16 11:44 UTC, agarciamontoro commented on webapp/src/components/backstage/category_selector.tsx
> +        <StyledCreatable
Could we use `menuPlacement={'top'}`? It is not completely visible when it extends below:

![image](https://user-images.githubusercontent.com/3924815/141974360-6b47880a-3182-4c10-8bcb-fb521d80aae4.png)

2021-11-16 11:44 UTC, agarciamontoro commented on webapp/src/components/backstage/category_selector.tsx
> +            placeholder={props.placeholder || 'Add channel to category'}
Since not that long ago, we can internationalize text in Playbooks, so this is a good opportunity to use it.

You simply just add `const {formatMessage} = useIntl();` at the beginning of the component (the import for this is `import {useIntl} from 'react-intl';`) and change this line to
```suggestion
            placeholder={props.placeholder || formatMessage({defaultMessage: 'Add channel to category'})}
```

2021-11-16 13:43 UTC, dunak-debug commented
Thank you, useful comments ;) Didn't know about intl and menuPlacement.. Updating it

2021-11-16 13:54 UTC, dunak-debug commented on webapp/src/components/backstage/category_selector.tsx
> +            placeholder={props.placeholder || 'Add channel to category'}
Also I had to remove `placeholder` from upper component `categorize_playbook_run` so it use `formatMessage` instead of un-translated `props.placeholder`

2021-11-16 14:50 UTC, iomodo approved these changes
LGTM! Thanks @dunak-debug !

2021-11-16 14:53 UTC, iomodo commented
Could you merge with master @dunak-debug ? Also please run `make i18n-extract` and commit `en.json` file changes <3

2021-11-16 15:01 UTC, dunak-debug commented
Also I wanted to ask where could I push tests for this PR.  It's likely a part of my school assignment :D to do these tests... So if I can push it inside this PR or make a new one with the same ticket number?

2021-11-16 15:36 UTC, iomodo commented
@dunak-debug you can push Tests here.
Squash will happen automatically on merge

2021-11-16 15:41 UTC, dunak-debug commented
> @dunak-debug you can push Tests here. Squash will happen automatically on merge

So if I am right these specific tests should go inside https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/tests-e2e/cypress/integration/playbooks/edit_spec.js

2021-11-18 09:20 UTC, agarciamontoro commented
> So if I am right these specific tests should go inside https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/tests-e2e/cypress/integration/playbooks/edit_spec.js

@dunak-debug, that would a be a great place, yes! Thank you :)

2021-11-27 12:38 UTC, dunak-debug commented
I am experiencing an issue when I run tests on `is disabled in a new playbook`

```
cy.request() failed on:

http://localhost:8065/plugins/playbooks/api/v0/playbooks

The response we received from your web server was:

  > 403: Forbidden
```

2021-11-28 07:23 UTC, iomodo commented
@dunak-debug sometimes tests are a bit flaky. Just fix the lint error, tests should be ok.

2021-11-29 11:43 UTC, dunak-debug commented
> @dunak-debug sometimes tests are a bit flaky. Just fix the lint error, tests should be ok.

I did but I get still this 403 error.

```
 POST /plugins/playbooks/api/v0/playbooks
                        Status: 403 - Forbidden
                        Response body: {
                          "error": "Not authorized"
                        }
                        ```

2021-11-29 11:56 UTC, dunak-debug commented
I saw warning.. `Not authorized; internal details: restricting playbook editing to specific users is not available with your current subscription: not covered by current server license` This may be the issue

2021-11-29 12:26 UTC, dunak-debug commented
Not sure why CI wants from me to extract i18n. Maybe somebody forgot to do?

2021-11-29 12:30 UTC, agarciamontoro commented
> I saw warning.. Not authorized; internal details: restricting playbook editing to specific users is not available with your current subscription: not covered by current server license This may be the issue

Do you have the testing and developer modes enabled? That should fix it

> Not sure why CI wants from me to extract i18n. Maybe somebody forgot to do?

Probaly the merge added some conflicting change to `en.json`. Run `make i18n-extract` and commit whatever comes out of that, it will fix the errors.

2021-11-29 12:38 UTC, dunak-debug commented
> Do you have the testing and developer modes enabled? That should fix it

I have, still 403. `✘  POST /plugins/playbooks/api/v0/playbooks` 

I am really confused 😕

2021-11-29 12:51 UTC, agarciamontoro commented
Oh, I think why this might be. Can you try opening cypress like this?

```
CYPRESS_developerMode=true npm run cypress:open
```

Also, first double-check that the testing and developer modes are indeed enabled, running the Cypress tests without the env var might have overwritten that at some point.

2021-11-29 13:14 UTC, dunak-debug commented
Cypress developerMode fixed 🎊

2021-11-29 13:25 UTC, agarciamontoro commented
> Cypress developerMode fixed :tada: 

Yay! Sorry, should have warned you about that, but it's a relatively new thing and I forgot!

2021-11-29 22:40 UTC, dunak-debug commented
Hope I covered all possible cases 👍 If you can think of any I forgot let me know :)

2021-11-30 17:54 UTC, agarciamontoro commented
I'll get to this tomorrow morning, @dunak-debug, sorry for the late reply! Jesse also added Cass to help review the E2E tests :tada:

2021-11-30 21:37 UTC, Phrynobatrachus requested changes

2021-11-30 21:37 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    cy.get('#root').findByText('Actions').click();
```suggestion
                    cy.findByText('Actions').click();
```
I don't think the `get('#root')` is necessary on any of these. This `visit -> switch to 'Actions'` sequence also happens at the start of all the `it` blocks, so it could probably go in a `beforeEach` for the parent `describe` block.

2021-11-30 21:37 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    cy.get('#user-joins-channel-categorize label input').should(
Going forward we'd like to avoid using this method of selection in favor of [accessible queries] (https://developers.mattermost.com/contribute/webapp/e2e/which-query-to-use/) when possible. In this particular case I'm thinking of an `aria-label` on the `input`, which would enable the use of `cy.findByLabelText` instead (see the last section of the [RTL example](https://testing-library.com/docs/queries/bylabeltext/)) and decouples the test a bit more from the DOM semantics. You don't need to do that in this PR unless you'd like, just something to keep in mind.

2021-11-30 21:37 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                it('does not let select a category when disabled', () => {
```suggestion
                it('prevents category selection when disabled', () => {
```

2021-11-30 21:37 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    cy.visit('/playbooks/playbooks/' + testPlaybook.id + '/edit');
note that here you're using string concatenation, in the other `visit` calls you're using string interpolation. similar to the review comment above, I suggest you pull the `visit -> switch to 'Actions'` sequence out into a `beforeEach` or helper function.

2021-11-30 21:37 UTC, Phrynobatrachus commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    cy.get('#root').findByText('Actions').click();
same note as above

2021-11-30 22:39 UTC, dunak-debug commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    cy.get('#user-joins-channel-categorize label input').should(
I will keep this in mind for future, but honestly I don't have that much time from now so somebody else could take care of this specific reusable toggle component to introduce aria-label

2021-12-01 10:31 UTC, agarciamontoro approved these changes
This is fantastic, @dunak-debug, thank you very much for all your hard work! Also, the coverage on the E2E tests is great, thanks!

2021-12-01 15:55 UTC, Phrynobatrachus approved these changes
Thanks for the changes, LGTM!

2021-12-01 17:18 UTC, dunak-debug commented
Thank you 👍 I am happy

2021-12-01 19:00 UTC, merged