Add restore endpoint to unfinish Playbook Run
mattermost/mattermost-plugin-playbooks pull request #846
Opened 2021-10-29 21:32 UTC by JulienTant

#### Summary
This PR offer a new endpoint `/run/[id]/restore` to un-finish a playbook run.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/18448

#### Checklist
- [x] Telemetry updated
- [ ] Gated by experimental feature flag
- [x] Unit tests updated

2021-10-29 21:32 UTC, mattermod commented
Hello @JulienTant,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-10-30 15:50 UTC, agarciamontoro commented
Thanks for the contribution, @JulienTant! I asked Jesse and Christopher to take a look (I'd do it myself, but I won't have time to do it until Tuesday!).

And let's see if the flaky test passes with the CI re-run :)

2021-10-30 16:45 UTC, agarciamontoro commented
It did not pass, and it also failed locally for me. But it's failing on master, too, so don't worry about it, it seems it's something we need to fix. Filed a ticket to track: https://mattermost.atlassian.net/browse/MM-39765

2021-11-04 15:42 UTC, cpoile requested changes
Thank you @JulienTant, this is great! Just a few minor comments, nothing major. Excellent work!

2021-11-04 15:42 UTC, cpoile commented on server/api/playbook_runs.go
> +	playbookRunRouterAuthorized.HandleFunc("/restore", handler.restore).Methods(http.MethodPost)
Probably we should use a `PUT` for this, because it's and update and idempotent: https://restfulapi.net/rest-put-vs-post/

2021-11-04 15:42 UTC, cpoile commented on server/app/playbook_run_service.go
> +	message := fmt.Sprintf("@%s restored this run.", user.Username)
@abhijit-singh can you review this message for the run's in-channel message?
Secondly, @abhijit-singh do we have a design for the message for the broadcast channels? At the moment it's the same message, so we probably need to change that to make it more meaningful, correct?  (It will be threaded, but there's a chance the root post was deleted and a new thread will be created.)

2021-11-04 15:42 UTC, cpoile commented on server/app/playbook_run_service.go
> +	}
I like that you added the timeline event, thank you! Have you tested to see when it appears (which filters need to be active or not for it to appear)? Do we need to add a new filter?

2021-11-04 15:42 UTC, cpoile commented on server/sqlstore/playbook_run_test.go
> +	allPosts := []*model.Post{post1, post2, post3, post4, post5, post6}
I'm not sure why these posts are being created, they don't seem to be used by the tests?

2021-11-05 19:23 UTC, JulienTant commented on server/app/playbook_run_service.go
> +	}
Hi, I'm not sure where to find the timeline in the UI, but it's present in the API:
![image](https://user-images.githubusercontent.com/785518/140566916-69f20aa1-8d1d-434d-bf9a-ba7ec1565554.png)

Also the run comes back as in progress in the UI:
![image](https://user-images.githubusercontent.com/785518/140566979-2456bd53-5a87-45c6-85b2-879335582127.png)

And the message is correctly posted in the channel:
![image](https://user-images.githubusercontent.com/785518/140567059-95cc20ea-de72-4e91-a3b5-517c9fad81c6.png)

2021-11-05 19:27 UTC, JulienTant commented on server/sqlstore/playbook_run_test.go
> +	allPosts := []*model.Post{post1, post2, post3, post4, post5, post6}
Oops I forgot to drop that from my copy/pasta - my bad it fixed. Thanks!

2021-11-05 21:09 UTC, JulienTant commented on server/app/playbook_run_service.go
> +	}
Okay I just realized the timeline was in the retrospective :) I changed the webapp code to take this event into consideration:

![image](https://user-images.githubusercontent.com/785518/140578745-6df65f09-967c-44db-9a34-ebb14a81c520.png)

It works exactly as the "finish" and "started" event, no need for a new filter.

2021-11-09 18:13 UTC, lieut-data approved these changes
Great work, @JulienTant!

2021-11-09 18:13 UTC, lieut-data commented on server/sqlstore/playbook_run.go
> +		Where(sq.Eq{"ID": playbookRunID})); err != nil {
nit: could we wrap this down one line?
```suggestion
		Where(sq.Eq{"ID": playbookRunID})
	); err != nil {
```

2021-11-09 18:59 UTC, cpoile requested changes
I think there might be some changes from a merge sneaking in here? @JulienTant let me know if you know what's going on, or if you don't I can help to see where the issue is.

2021-11-09 18:59 UTC, cpoile commented on server/app/playbook_run.go
> +
Sorry, I'm not sure why this is here -- was this brought in by a merge?

2021-11-09 18:59 UTC, cpoile commented on server/app/playbook_run_service.go
> +
Same question here?

2021-11-09 21:31 UTC, abhijit-singh commented on server/app/playbook_run_service.go
> +	message := fmt.Sprintf("@%s restored this run.", user.Username)
@cpoile What do you think about `@PersonName changed this run's status from Finished to In Progress.` 

cc @itao 

Also, the same message should be okay since we're threading already and this is not a very common use case. Also, the message posted when someone marks a run as finished has the same issue so I'd say we can tackle it in a separate effort if needed.

2021-11-09 21:33 UTC, JulienTant commented on server/app/playbook_run.go
> +
Hi, I did merge master in this branch because conflicts were preventing this PR from being merged. It's technically not in the `Files changed` for this PR. How do you want me to handle that? I can drop the merge (will have to rebase and force push) but then this PR will be unmergeable.

2021-11-09 21:49 UTC, cpoile commented on server/app/playbook_run.go
> +
Ah, I see that it's not in the Files changed, so we're good. Please ignore my comment then. :)

2021-11-09 21:49 UTC, cpoile commented on server/app/playbook_run_service.go
> +
Same thing -- not in the Files changed, we're good.

2021-11-09 21:51 UTC, cpoile commented on server/app/playbook_run_service.go
> +	message := fmt.Sprintf("@%s restored this run.", user.Username)
@JulienTant Looks like you can make  the change suggested by @abhijit-singh to the message on line 960, and that should be it!

2021-11-09 23:41 UTC, JulienTant commented on server/app/playbook_run_service.go
> +	message := fmt.Sprintf("@%s restored this run.", user.Username)
It's updated

2021-11-10 00:22 UTC, abhijit-singh approved these changes
Looks good! Thanks @JulienTant!

2021-11-10 13:49 UTC, cpoile approved these changes
Looks great, thanks @JulienTant !

2021-11-10 13:49 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-11-10 15:40 UTC, mattermod commented
Trying to auto merge this PR.

2021-11-10 15:40 UTC, mattermod commented
Pull Request successfully merged
SHA: df2a94055064d3502b79cc98ed140fc5e862d8e9

2021-11-10 15:40 UTC, merged