Add useRelative with playbooks
mattermost/mattermost-plugin-playbooks pull request #850
Opened 2021-11-01 03:55 UTC by clovis1122

#### Summary

Changes the way we display dates for playbooks by making them relative.

#### Ticket Link

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [ ] Unit tests updated

2021-11-01 03:55 UTC, mattermod commented
Hello @clovis1122,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-11-02 04:37 UTC, clovis1122 commented
/check-cla

2021-11-02 14:08 UTC, crspeller requested changes
Thanks for the PR! Just one lint fix.

2021-11-02 14:08 UTC, crspeller commented on webapp/src/components/rhs/post_card.tsx
> +                                    useRelative
Linter wants this to be: 
```suggestion
                                    useRelative={true}
```

2021-11-04 00:21 UTC, clovis1122 commented on webapp/src/components/rhs/post_card.tsx
> +                                    useRelative
Thanks! Done!

2021-11-04 14:57 UTC, crspeller approved these changes
Thanks!

2021-11-04 14:57 UTC, merged