MM-39118: Remove export channel action
mattermost/mattermost-plugin-playbooks pull request #851
Opened 2021-11-01 16:38 UTC by cpoile

#### Summary
- Remove the export channel on archive setting & component completely (it's easy to put it back later if we need to)
- I decided to leave the server-side support because that's less easy to remove/put back, but I'm 0/5 -- I can rip that out too if we want to be clean about it

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-38720

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-11-01 18:01 UTC, cpoile commented
Okay, makes sense. May as well get rid of everything then. :) (since the code is dead) We can add it back in when we need it.

2021-11-01 19:02 UTC, calebroseland requested changes
Just the one CSS issue, but otherwise looks great 👍

2021-11-01 19:05 UTC, calebroseland commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +                    <ExportLink playbookRun={playbookRun}/>
Also, just a heads up that @iomodo's https://github.com/mattermost/mattermost-plugin-playbooks/pull/801 touches this area, so perhaps this should be left for now.

2021-11-01 19:08 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +                    <ExportLink playbookRun={playbookRun}/>
Ah, that's a mistake -- I was working on #854 at the same time, sorry. Will revert this.

2021-11-01 19:28 UTC, calebroseland approved these changes

2021-11-02 14:08 UTC, lieut-data approved these changes

2021-11-03 12:23 UTC, merged