[MM-38586] Skip instead of delete playbook run tasks
mattermost/mattermost-plugin-playbooks pull request #862
Opened 2021-11-03 07:08 UTC by shadowshot-x

#### Summary
Added the Skip and Restore Functionality to Playbook tasks. Eliminated the Delete feature. 

1. Users can now Skip the task. This will result in the Task being crossed off from the list. Earlier the user could delete the task which led to the vanishing of the task from the checklist items.

2. The Skipped tasks can be restored by the user. This will lead the tasks to be restored and a normal task title will be displayed.

3. When a task is skipped, the status of the task is changed to "skipped". Also, a LastSkipped field or "deleted_at" is added which contains the current timestamp.
4. When Restoring the task, only the status is updated to "open". The LastSkipped field is not changed.

![Screenshot from 2021-11-03 12-19-58](https://user-images.githubusercontent.com/43992469/140020481-6a9dba7d-2f16-488d-a13e-a10f988a0f5d.png)
![Screenshot from 2021-11-03 12-20-06](https://user-images.githubusercontent.com/43992469/140020479-9273b2b5-009b-4ca1-b8f8-31c0e0d11d0d.png)
![Screenshot from 2021-11-03 12-20-11](https://user-images.githubusercontent.com/43992469/140020476-ba0865d0-8540-4dcf-8aa1-28f6b4c2f4bf.png)
![Screenshot from 2021-11-03 12-19-46](https://user-images.githubusercontent.com/43992469/140020485-ae71d79b-33ce-4778-b40f-491dc6d1645d.png)

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/18596

#### Checklist

- ~[ ]~ Telemetry updated
- ~[ ]~ Store Updated to contain deleted_at
- ~[ ]~ New Routes and Methods added in Server
- [ ] Update the Progress bar based on deletion
- [ ] Add Unit Test Cases

2021-11-03 07:08 UTC, mattermod commented
Hello @shadowshot-x,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-11-08 16:24 UTC, lieut-data commented
Wow, this looks like a pretty comprehensive change! Thank you, @shadowshot-x!! I've invited @cpoile and @crspeller to help review :)

2021-11-09 14:30 UTC, shadowshot-x commented
Thank you @lieut-data. Happy to help. :D

2021-11-09 21:29 UTC, cpoile requested changes
This is awesome work @shadowshot-x , really nicely done, thank you! A few requests for changes (mostly to bring things a bit more in line with our current style/patterns). But otherwise this is almost ready to go. Great work!

2021-11-09 21:29 UTC, cpoile commented on server/app/playbook.go
> +	// been skipped, the empty string otherwise.
That's a good choice!

2021-11-09 21:29 UTC, cpoile commented on server/app/playbook_run.go
> +	RestoreChecklistItem(playbookRunID, userID string, checklistNumber int, itemNumber int) error
Could we add a code comment here (although it's pretty self-explanatory, we should probably be consistent).

2021-11-09 21:29 UTC, cpoile commented on server/app/playbook.go
> +	LastSkipped int64 `json:"deleted_at"`
I was reading the ticket description, and it mentioned setting a `delete_at` field to be consistent with how we model channels -- was that specification changed to this `LastSkipped` field?

2021-11-09 21:29 UTC, cpoile commented on webapp/src/components/checklist_item.tsx
> +                                    className={(props.checklistItem.state === ChecklistItemState.Skip) ? 'icon-refresh icon-16 btn-icon' : 'icon-close-circle-outline icon-16 btn-icon'}
I think you'll have to use `formatMessage`s for `Restore` and `Skip`, for internationalization.

2021-11-09 21:29 UTC, cpoile commented on webapp/src/components/checklist_item.tsx
> +                                {(props.checklistItem.state === ChecklistItemState.Skip) ? <StrikeThrough>{messageHtmlToComponent(formatText(props.checklistItem.title, markdownOptions), true, {})}</S
This is getting a little long, maybe we should refactor it into a const?

2021-11-09 21:29 UTC, cpoile commented on webapp/src/components/checklist_item.tsx
> +                message={'Are you sure you want to skip this task? This will be crossed from this run but will not affect the playbook.'}
We should probably use formatMessages for all these strings.

2021-11-11 05:19 UTC, shadowshot-x commented on server/app/playbook.go
> +	LastSkipped int64 `json:"deleted_at"`
Hi @cpoile, The ticket does mention `delete_at` field. However, I used LastSkipped because we are actually removing the Deletion functionality as a whole for the tasks. Do you want me to change this to `DeleteAt` instead of `LastSkipped`?

2021-11-11 08:06 UTC, shadowshot-x commented on server/app/playbook_run.go
> +	RestoreChecklistItem(playbookRunID, userID string, checklistNumber int, itemNumber int) error
Right, I might have missed it.

2021-11-11 08:45 UTC, shadowshot-x commented on server/app/playbook.go
> +	// been skipped, the empty string otherwise.
Thank You

2021-11-11 08:47 UTC, shadowshot-x commented on webapp/src/components/checklist_item.tsx
> +                                    className={(props.checklistItem.state === ChecklistItemState.Skip) ? 'icon-refresh icon-16 btn-icon' : 'icon-close-circle-outline icon-16 btn-icon'}
Done!

2021-11-11 08:47 UTC, shadowshot-x commented on webapp/src/components/checklist_item.tsx
> +                                {(props.checklistItem.state === ChecklistItemState.Skip) ? <StrikeThrough>{messageHtmlToComponent(formatText(props.checklistItem.title, markdownOptions), true, {})}</S
Refactored it.

2021-11-11 08:48 UTC, shadowshot-x commented on webapp/src/components/checklist_item.tsx
> +                message={'Are you sure you want to skip this task? This will be crossed from this run but will not affect the playbook.'}
Done! Thank You for reminding me.

2021-11-11 22:30 UTC, crspeller approved these changes
Great! Thanks for the contribution! Just the one comment on the outstanding discussion.

2021-11-11 22:30 UTC, crspeller commented on server/app/playbook.go
> +	LastSkipped int64 `json:"deleted_at"`
We should at least be consistent here with the json representation.

2021-11-12 05:17 UTC, shadowshot-x commented on server/app/playbook.go
> +	LastSkipped int64 `json:"deleted_at"`
Sure, I will change this to `LastSkipped int64` `json:"delete_at"`.

2021-11-15 19:04 UTC, Phrynobatrachus commented
hi @shadowshot-x! I [opened a PR](https://github.com/shadowshot-x/mattermost-plugin-playbooks/pull/1) to your branch to add a touch more detail to the Cypress test, but otherwise it's LGTM.

2021-11-16 18:17 UTC, Phrynobatrachus approved these changes

2021-11-16 20:20 UTC, merged