[MM-39857] Add auto-follow playbook runs
mattermost/mattermost-plugin-playbooks pull request #870
Opened 2021-11-08 13:30 UTC by iomodo

#### Summary
This PR adds support of auto-following a playbook run

https://user-images.githubusercontent.com/2340127/140747258-4ed90396-fcc8-4a36-899b-9711a4b73429.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-39857

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [X] Unit tests updated

2021-11-09 12:23 UTC, abhijit-singh reviewed
Thanks @iomodo! A few minor tweaks:
* Can we add the tooltips for when the user hovers on the checkbox-button like in the design? They'll help people understand what the feature is. 
* Can we reduce the left and right spacing within the box to 20px?
![image](https://user-images.githubusercontent.com/14369607/140923364-5490491f-3420-4bf1-b6b7-02e43006773e.png)

* Can we change the colors of the text and the button to the following ([figma link](https://www.figma.com/file/Lep365ubDUjUcgV0757zFF/MM-33880-Run-Overview?node-id=744%3A277092)): 
  * Unchecked state - outline & checkbox color: 24% opacity `center channel text`
  * Unchecked state - text color: 56% opacity `center channel text` 
  * Checked state - outline, checkbox & text color: `button background`
![image](https://user-images.githubusercontent.com/14369607/140922650-2b07a3b0-9423-42e8-9fef-232e9a6d54db.png)

2021-11-09 14:58 UTC, lieut-data requested changes
Thanks, @iomodo! I'm inclined to think we should call the underlying concept, "AutoFollow", as outlined below in a few different comments. Otherwise, looks good!

2021-11-09 14:58 UTC, lieut-data commented on server/sqlstore/migrations.go
> +					CREATE TABLE IF NOT EXISTS IR_Playbook_Participants (
Let's avoid overloading the term participants here, since this concept is currently only defined for a run. Perhaps we simplify to just "PlaybookAutoFollowers" for now?

2021-11-09 15:33 UTC, iomodo commented on server/api/playbooks.go
> +	followersRouter.HandleFunc("/check", handler.isFollower).Methods(http.MethodGet)
`GET` on `/follow` endpoint should return all followers(we will/might need this in the future). Another way to implement this is to introduce filtering on  `GET /follow` endpoint, but I decided to avoid the complexity for now.

2021-11-09 17:00 UTC, lieut-data commented on server/api/playbooks.go
> +	followersRouter.HandleFunc("/check", handler.isFollower).Methods(http.MethodGet)
I could see `/follow` be implicitly for the active user, and `/followers` for the full list. Or maybe `/followers/<user_id>` for the `GET`/`PUT`/`DELETE` with the `/followers`/ for the full list?

2021-11-09 17:17 UTC, cpoile approved these changes
Nice!

2021-11-09 17:17 UTC, cpoile commented on server/api/playbooks.go
> +	followersRouter.HandleFunc("/check", handler.isFollower).Methods(http.MethodGet)
I do like combining `PUT` and `DELETE` to `/followers`, agree with avoiding the complexity of adding a flag for the check.

2021-11-09 17:17 UTC, cpoile commented on server/api/playbooks.go
> +	if isFollower, err = h.playbookService.IsFollower(playbookID, userID); err != nil {
I'm starting to hate this pre-declaring vars -- it's `incidental complexity` noise in the worst way. Can we turn off shadowing linting yet? @lieut-data

2021-11-09 17:47 UTC, lieut-data commented on server/api/playbooks.go
> +	if isFollower, err = h.playbookService.IsFollower(playbookID, userID); err != nil {
This isn't a linting issue, is it? It's that `isFollower` is needed after the conditional? Personally, I'd just lean towards writing all these blocks as:
```go
err := CheckSomething()
if err != nil {
    // ...
}

result, err := DoSomethingElse()
if err != nil {
    // ...
}
```

2021-11-10 17:59 UTC, iomodo commented on server/sqlstore/migrations.go
> +						INDEX IR_Playbook_Participants_PlaybookID (PlaybookID)
There might be a lot of followers so I think it's more scalable approach.

2021-11-10 18:05 UTC, iomodo commented
Take a look @abhijit-singh 
https://user-images.githubusercontent.com/2340127/141168476-dc512c1f-f33f-4342-aadf-61fad3b6eb77.mp4

2021-11-10 18:14 UTC, abhijit-singh approved these changes
Thanks @iomodo! Looks great! A couple of tiny nits:
* The font size for `Auto-follow runs` seems to be bit smaller than the font size for the `Run` button. Can you ensure it is the same as that of `Run`?
* In the tooltip when it is unchecked, there is a comma(",") missing after the word `checked`.
Might be good to have @justinegeffen review this.
![image](https://user-images.githubusercontent.com/14369607/141169699-95f01114-9982-4c66-93f5-56a4ff8e614f.png)

2021-11-10 20:09 UTC, lieut-data approved these changes
Thanks, Shota! A few more thoughts -- mostly wanting to get the schema "right", and we can always iterate on terminology going forward.

2021-11-10 20:09 UTC, lieut-data commented on server/api/playbooks.go
> +	followersRouter.HandleFunc("", handler.autoFollow).Methods(http.MethodPut)
nit: since these operate on the calling user, I'd be inclined to group them all under `/follow` until such time as we expose actions on the set of `/followers`. Thoughts?

2021-11-10 20:09 UTC, lieut-data commented on server/api/playbooks.go
> +	followerRouter := playbookRouter.PathPrefix("/follow").Subrouter()
Looking at this now, I'm wondering if we push through to `/autoFollower` and `/autoFollowers` for completeness?

2021-11-10 20:09 UTC, lieut-data commented on server/app/playbook.go
> +	// AutoFollow method lets user follow a all runs of a specific playbook
Should we push through to terminology too, like:
```suggestion
	// AutoFollow method lets a user automatically follow a all runs of a specific playbook
```

2021-11-10 20:09 UTC, lieut-data commented on server/sqlstore/migrations.go
>  						IsFollower BOOLEAN NOT NULL,
Should we drop `IsFollower` now that this is just a table of auto followers?

2021-11-10 20:09 UTC, lieut-data commented on server/sqlstore/migrations.go
> +						INDEX PlaybookAutoFollowers_PlaybookID (PlaybookID)
Can we rely on the primary key to effectively give us this set? (I believe we can get partial results out of an index when the conditions are specified first.)

2021-11-11 14:02 UTC, justinegeffen reviewed
Two slight rewording suggestions and I also picked up two unrelated nits that would be awesome to resolve. :) 

As an aside, do we have a definition of "follower"? I wonder if I could tighten up the language based on what the role entails.

2021-11-11 14:02 UTC, justinegeffen commented on webapp/i18n/en.json
> +  "8pXxyF": "You'll automatically be added as a follower for all new runs of this playbook.",
```suggestion
  "8pXxyF": "You're automatically added as a follower to all new runs of this playbook.",
```

2021-11-11 14:04 UTC, itao commented on server/api/playbooks.go
> +	followersRouter.HandleFunc("", handler.autoFollow).Methods(http.MethodPut)
I suggest `isFollowing` as opposed to `isFollower` to minimize confusion as we anticipate introducing the concept of specific positions for participants. In general, I'd err towards referring to "following" as an action that someone has taken as opposed to a role that they're fulfilling.

2021-11-11 14:16 UTC, itao requested changes
I propose we intentionally always refer to `following` as an action rather than `follower` role to minimize user confusion. We ourselves already mix up the purpose of `owner`, `participant`, and `followers` as it implies someone can be a combination of those. And it'll only get worse when we introduce customizable roles/positions per playbook run. I can be convinced otherwise but want to raise it for consideration cc @abhijit-singh @justinegeffen 

Sample places where this would need to be addressed: `... automatically added as a follower ...` tooltip would say something like `... receive notification for every run and status updates ... ` Which would make the consequence more clear to user.

I'm 3/5 that `Following` should be consistently referred to as an action/state as opposed to role/position, and 1/5 that developer-facing terms are consistent with user-facing mental model.

2021-11-11 14:43 UTC, justinegeffen commented
> I'm 3/5 that `Following` should be consistently referred to as an action/state as opposed to role/position, and 1/5 that developer-facing terms are consistent with user-facing mental model.

That's a good point, @itao, and I've revised my revisions. I didn't think of it as an implied role and agree that it will make things very tangled. Let me know what you think of the new wording.

2021-11-11 15:03 UTC, abhijit-singh commented on webapp/i18n/en.json
> +  "fRh92E": "If checked you'll automatically be added as a follower for all new runs of this playbook.",
I agree with not using `follower` anywhere but notifications will not be limited to status updates and also cover other run events.

2021-11-11 15:17 UTC, justinegeffen commented on webapp/i18n/en.json
> +  "fRh92E": "If checked you'll automatically be added as a follower for all new runs of this playbook.",
Gotcha, I'll rework these.

2021-11-12 16:54 UTC, lieut-data approved these changes
A handful of comments, though not strictly blocking. Thanks, Shota!

2021-11-12 16:54 UTC, lieut-data commented on server/api/playbooks.go
> +	followID := mux.Vars(r)["followID"]
nit: `followID` makes me think this is a resource for something other than a user. Maybe we just set this to `userID`, while still checking that it's the same as the header value?

2021-11-12 16:54 UTC, lieut-data commented on server/api/playbooks.go
> +	if followID != userID {
Can we allow system admins to do this, though?

2021-11-12 16:54 UTC, lieut-data commented on server/sqlstore/playbook.go
> +		Values(playbookID, userID)); err != nil {
Should we still handle the `ON DUPLICATE KEY` case so that this doesn't error out if the user is already following?

2021-11-12 16:54 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	return returnedPlaybookID == playbookID, nil
It's not obvious why we nee to check `returnedPlaybookID` against `playbookID`, given that's the condition already in the `WHERE` clause. Could we tweak the SQL query to just effectively do `SELECT TRUE FROM ...` and verify that instead?

2021-11-12 16:54 UTC, lieut-data commented on webapp/src/client.ts
> +export const followPlaybook = async (playbookId: string, userId: string) => {
should we name these `autoFollowPlaybook`, etc.?

2021-11-15 13:53 UTC, lieut-data approved these changes

2021-11-15 14:04 UTC, justinegeffen approved these changes

2021-11-15 18:23 UTC, itao approved these changes
Assuming copy has been changed to refer to `following` as an action rather than `follower` as a role, then LGTM!

2021-11-16 06:25 UTC, merged