Accommodate long and multiple keywords
mattermost/mattermost-plugin-playbooks pull request #878
Opened 2021-11-10 18:33 UTC by agarciamontoro

#### Summary
Reword the title of the keywords preview section to read as follows:

- If there is just one keyword: "Prompt to run this playbook when a message contains the keyword `KEYWORD`". Here, the keyword is ellipsized if it's longer than 150 pixels.
- If there is more than one keyword: "Prompt to run this playbook when a message contains one or more of these `N KEYWORDS`".

![image](https://user-images.githubusercontent.com/3924815/141171878-9757a5bf-c227-43f5-8f12-733cba50a59e.png)
![image](https://user-images.githubusercontent.com/3924815/141171826-a40b60f8-269c-4693-bc5b-3d96af1ffc23.png)
![image](https://user-images.githubusercontent.com/3924815/141171983-674d9150-715c-410a-a4d2-670a3b8f16dd.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39954

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-11-11 14:12 UTC, cpoile approved these changes

2021-11-12 22:11 UTC, calebroseland approved these changes

2021-11-12 22:12 UTC, calebroseland requested changes
LGTM, just the plural part would be good

2021-11-15 10:01 UTC, agarciamontoro commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +                    {defaultMessage: '{numKeywords, number} keywords'},
@calebroseland This will be always in plural: this component is only rendered when there is at least one keyword, and the case where there is exactly one keyword is handled above. Do we still need `{plural}` here?

2021-11-15 14:34 UTC, calebroseland commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +                    {defaultMessage: '{numKeywords, number} keywords'},
@agarciamontoro Indeed, for English it’s fine as is, but other locales may have significance for certain categories e.g. ‘few’, ‘many’… (https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#sl)

2021-11-16 12:37 UTC, agarciamontoro commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +                    {defaultMessage: '{numKeywords, number} keywords'},
Oh, I see. Let me change it.

2021-11-16 12:48 UTC, agarciamontoro commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +                    {defaultMessage: '{numKeywords, number} keywords'},
@calebroseland, I only used `other`, but I'm not 100% sure this is right. Is it?

2021-11-16 15:33 UTC, calebroseland commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +                    {defaultMessage: '{numKeywords, number} keywords'},
I believe that's correct 👍

2021-11-16 15:33 UTC, calebroseland approved these changes

2021-11-16 15:34 UTC, merged