[MM-39529] Adding an item in the run's RHS dropdown menu to edit a run summary
mattermost/mattermost-plugin-playbooks pull request #883
Opened 2021-11-12 16:29 UTC by JulienTant

#### Summary
This PR is modifying the hamburger menu of a run in the RHS to add an explicit "Edit run summary" item.

![image](https://user-images.githubusercontent.com/785518/141498100-eee17478-0329-457c-ad4e-5695106f2927.png)

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/18972

#### Checklist
~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

#### Dev note
1) My ReactJS skills are not perfect, so I'm not quite sure that the way I implemented the communication between components is the "state of the art" way to do it. I'm happy to change that to whatever is best!
2) I had to use a bit of trickery to have the hamburger menu open in the e2e tests because it appears only when the mouse goes over the container. I tried using `trigger('mouseover')` on the container but it did not work and [cypress has no implementation of `hover` yet](https://docs.cypress.io/api/commands/hover#Workarounds) was not enough. To remedy that during the test I force the buttons the show.

2021-11-12 16:29 UTC, mattermod commented
Hello @JulienTant,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-11-18 16:06 UTC, crspeller requested changes
Thanks for the contribution! Just one comment to simplify.

2021-11-18 16:06 UTC, crspeller commented on webapp/src/components/rhs/rhs_about_buttons.tsx
> +            <ClosableDotMenu
You don't actually need this workaround. I fixed this issue on a branch of mine. 
If you add this to dot_menu.jsx:122 (In the `<DropDownMenu>` component)  It will automatically close when an item is clicked. 
```jsx
  onClick={(e) => {
      e.stopPropagation();
      setOpen(false);
  }}
```

2021-11-18 16:39 UTC, JulienTant commented on webapp/src/components/rhs/rhs_about_buttons.tsx
> +            <ClosableDotMenu
So much simpler and elegant, thanks @crspeller!

2021-11-18 17:42 UTC, crspeller approved these changes
Looks good :)

2021-11-25 15:45 UTC, iomodo approved these changes
Thanks for the contribution @JulienTant 
Looks great

2021-11-26 16:46 UTC, merged