[MM-40133] Add support for default notifications for followers
mattermost/mattermost-plugin-playbooks pull request #888
Opened 2021-11-16 14:14 UTC by iomodo

#### Summary
Add support for default notifications for followers:
* Run start
<img width="664" alt="Screen Shot 2021-11-16 at 17 27 39" src="https://user-images.githubusercontent.com/2340127/142000975-cb9cb063-7bce-4ee9-89e2-af8056bd3268.png">

* Run finish
<img width="652" alt="Screen Shot 2021-11-16 at 18 02 15" src="https://user-images.githubusercontent.com/2340127/142001060-90b6ea99-dceb-4487-892d-205aac5d316e.png">

* Status update
<img width="866" alt="Screen Shot 2021-11-16 at 18 04 59" src="https://user-images.githubusercontent.com/2340127/142001119-99248a2c-0b7b-4f0e-97b1-dcd66ff34ded.png">

* Status update missed
* Retrospective published
<img width="1152" alt="Screen Shot 2021-11-16 at 18 03 12" src="https://user-images.githubusercontent.com/2340127/142001215-5f81aa95-b064-45e2-9f90-d25ec7ef835e.png">

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-40133

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2021-11-16 14:17 UTC, iomodo commented on server/app/reminder.go
> +	message := fmt.Sprintf("Status update is overdue for run [%s](%s/%s/channels/%s?telem=todo_overduestatus_clicked&forceRHSOpen) (Owner: @%s)\n",
Notice that clicking on the overdue status update will be counted in the telemetry. Not sure if it's the correct behaviour @stephenvanhemmen

2021-11-16 21:30 UTC, stephenvanhemmen commented on server/app/reminder.go
> +	message := fmt.Sprintf("Status update is overdue for run [%s](%s/%s/channels/%s?telem=todo_overduestatus_clicked&forceRHSOpen) (Owner: @%s)\n",
What telemetry event is this measuring? Is it the event for specifically clicking the link in the overdue status update message?

2021-11-17 07:18 UTC, iomodo commented on server/app/reminder.go
> +	message := fmt.Sprintf("Status update is overdue for run [%s](%s/%s/channels/%s?telem=todo_overduestatus_clicked&forceRHSOpen) (Owner: @%s)\n",
That's the one

2021-11-17 07:39 UTC, iomodo commented
Updated messages as per conversation [here](https://community-daily.mattermost.com/core/pl/k5ibhrzm3inadfonxpd73i6m4e)

2021-11-17 12:25 UTC, cpoile approved these changes
Awesome, thanks @iomodo!

2021-11-17 12:44 UTC, stephenvanhemmen approved these changes
Thanks!

2021-11-18 09:19 UTC, agarciamontoro requested changes
Looks great! I just added a couple of comments to use relative URLs instead of absolute ones.

2021-11-18 09:19 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +		} else {
+1

2021-11-18 09:19 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +}
We can use the new functions to build relative URLs (added in https://github.com/mattermost/mattermost-plugin-playbooks/pull/875) here and we can get rid of `siteURL`.

2021-11-18 09:19 UTC, agarciamontoro commented on server/app/reminder.go
> +	message := fmt.Sprintf("Status update is overdue for [%s](%s/%s/channels/%s?telem=todo_overduestatus_clicked&forceRHSOpen) (Owner: @%s)\n",
We can probably use a relative URL here and also get rid of the `siteURL`.

2021-11-18 16:30 UTC, agarciamontoro approved these changes
Looks great, thank you!

2021-11-18 16:50 UTC, merged