Add playbook filter to runs
mattermost/mattermost-plugin-playbooks pull request #894
Opened 2021-11-22 12:03 UTC by iomodo

#### Summary
Adds support of the playbook filter in the run list

https://user-images.githubusercontent.com/2340127/142857373-5fdaaa4d-9b62-4366-b50a-4be88b181b4d.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-38581

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2021-11-22 16:47 UTC, agarciamontoro requested changes
Looks great, thank you! I left a handful of comments, but mostly questions and nits. The only blocking one is the theming issue.

2021-11-22 16:47 UTC, agarciamontoro commented on webapp/src/components/backstage/runs_list/filters.tsx
> +        return playbooks ? playbooks.items : {} as Playbook[];
Nit: can we do this instead? It feels weird to convert an empty object to a `Playbook[]`
```suggestion
        return playbooks ? playbooks.items : [] as Playbook[];
```

2021-11-22 16:47 UTC, agarciamontoro commented on webapp/src/components/backstage/runs_list/playbook_selector.tsx
> +        }
Do we need to fetch the playbooks every time we toggle the menu?

2021-11-22 16:47 UTC, agarciamontoro commented on webapp/src/components/backstage/runs_list/playbook_selector.tsx
> +    }, [playbookOptions, props.selectedPlaybookId]);
If I'm not mistaken, this will probably run in every render, because `playbookOptions` will be a new array every time. I'm not sure this specific case would be a performance problem, but I thought it's worth to point out.

2021-11-22 16:47 UTC, agarciamontoro commented on webapp/src/components/backstage/runs_list/playbook_selector.tsx
> +        const hoverColor = 'rgba(20, 93, 191, 0.08)';
This is not themed. Should it be?

2021-11-22 16:47 UTC, agarciamontoro commented on webapp/src/components/backstage/runs_list/playbook_selector.tsx
> +export default function PlaybookSelector(props: Props) {
The code in this file is very similar to `ProfileSelector` and `TeamSelector`, right? Should we generalize all these components (here or in a future PR)?

2021-11-24 13:54 UTC, iomodo commented on webapp/src/components/backstage/runs_list/playbook_selector.tsx
> +export default function PlaybookSelector(props: Props) {
Created a ticket https://mattermost.atlassian.net/browse/MM-40326

2021-11-24 15:57 UTC, agarciamontoro approved these changes
Great, thank you! :tada:

2021-11-24 17:12 UTC, abhijit-singh approved these changes
This is great @iomodo! A couple of small things:
1. The owner and team filter also expand based on the value selected. Can we ensure the layout doesn't break if all three have values with lots of characters selected? It probably already works perfectly, but just wanted to make sure. 
2. The cursor changes to the hand while hovering on the Owner & Team filters. Can we have the same for the Playbook filter as well?
![image](https://user-images.githubusercontent.com/14369607/143284164-5d1b3754-aa0e-4c22-b900-4a57435eae04.png)
![image](https://user-images.githubusercontent.com/14369607/143284232-74e85562-e68c-4e9c-a77c-33e3e704ddc6.png)

2021-11-26 14:14 UTC, cpoile approved these changes
Nice, thanks @iomodo !!

2021-11-26 14:14 UTC, cpoile commented on webapp/src/components/backstage/runs_list/playbook_selector.tsx
> +    }, [playbookOptions, props.selectedPlaybookId]);
I don't think so -- it's a state object, so the object identity should only change when the state changes (or unmounts-remounts).

2021-11-26 14:46 UTC, merged

2021-11-29 10:17 UTC, agarciamontoro commented on webapp/src/components/backstage/runs_list/playbook_selector.tsx
> +    }, [playbookOptions, props.selectedPlaybookId]);
I thought that using arrays there had the problem of new objects. @cpoile, do you have a link to some docs that explain this? If not, I'll test it and see what happens.