[MM-39140] Add copy URL to run and playbook
mattermost/mattermost-plugin-playbooks pull request #895
Opened 2021-11-22 14:54 UTC by iomodo

#### Summary
This PR adds support of the run and playbook url copy

https://user-images.githubusercontent.com/2340127/142882834-b238d007-6975-4d2a-9f5d-6e8caee2b6aa.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-39140

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2021-11-23 20:16 UTC, cpoile requested changes
This is awesome @iomodo, thanks!

Also, do you think we should make an e2e test for it? (Personally, I'm trying to add e2e tests for anything that isn't highly interactive)

2021-11-23 20:16 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +import {copyToClipboard, getSiteURL} from '../../../../utils';
super nit: this would probably be easier to read as an absolute path

2021-11-23 20:16 UTC, cpoile commented on webapp/src/utils.ts
> +}
I think we should have the `basePath` in the `client.ts`, set when the plugin gets initialized--could we use that instead of new code?

2021-11-23 21:32 UTC, calebroseland approved these changes
Nice! Aside from @cpoile's comments and my own minor nit, this looks good to me!

2021-11-23 21:32 UTC, calebroseland commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        copyToClipboard(siteUrl);
nit: Perhaps `runUrl` or direct param?

2021-11-23 21:32 UTC, calebroseland commented on webapp/src/utils.ts
> +}
+1

2021-11-23 21:33 UTC, calebroseland commented on webapp/src/utils.ts
> +}
+1

2021-11-24 13:50 UTC, cpoile approved these changes
Awesome Shota!

2021-11-24 18:00 UTC, abhijit-singh requested changes
Thanks @iomodo. A couple of requests:
1. Is it possible to make the status tag and the link icon align/be in the same row as the `run name` as in the attached mockup? It looks odd right now if the run name takes less space than the playbook name.
![image](https://user-images.githubusercontent.com/14369607/143289820-2e539fe4-3dfa-4bad-b21b-dd3bbf8d9b4a.png)

(The same problem is there for the playbook page as well, but that'll probably go away with @crspeller's changes for the permissions feature as we're removing the bottom row of text from the playbook page header.)
2. Add 8px space between the status tag and the link icon box.
![image](https://user-images.githubusercontent.com/14369607/143290932-affaeec8-55e1-4407-a6f5-17c9df725224.png)

3. Extremely minor nit, but can we make the hover state background colour and icon colour grey instead of the current blue?
![image](https://user-images.githubusercontent.com/14369607/143291209-6adc7b2a-1ba9-4628-bbf2-0762604d681d.png)
![image](https://user-images.githubusercontent.com/14369607/143291226-a7b28d38-de73-4f22-a450-e68141cc0446.png)

2021-11-25 12:50 UTC, iomodo commented
Is it what you had in mind @abhijit-singh ?

https://user-images.githubusercontent.com/2340127/143444856-dadf386b-872f-445f-af5d-dc4ee2a2ab83.mp4

2021-11-25 13:00 UTC, abhijit-singh commented
@iomodo The placement and spacing is perfect 👌!

For the hover state, it should have a grey background while hovering. The exact colors on-hover would be:
- Background color: 8% opacity of `center-channel-text`
- Icon color: 72% opacity of `center-channel-text`

Also, the icon container that has the background color should have a border radius of 4px.

2021-11-25 15:43 UTC, iomodo commented
@abhijit-singh check it :)


https://user-images.githubusercontent.com/2340127/143470211-0ab2b2ad-a249-452d-aa68-49973ad06db8.mp4

2021-11-25 16:38 UTC, abhijit-singh approved these changes
Perfect! Thank you @iomodo!

2021-11-25 16:39 UTC, iomodo commented
Thanks for your patience @abhijit-singh <3

2021-11-25 16:39 UTC, merged