MM-37531: Make subheaders in RHS sticky
mattermost/mattermost-plugin-playbooks pull request #897
Opened 2021-11-22 16:15 UTC by cpoile

#### Summary
- Subheaders are sticky now

![CleanShot 2021-11-22 at 11 13 12](https://user-images.githubusercontent.com/1490756/142896287-3cccbc39-bc52-4844-8ac2-ad4e1883f1fc.gif)

Nicer version without artifacts: https://cln.sh/g8AZzT

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-37531

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-11-22 16:17 UTC, calebroseland commented
Oooh 😃

2021-11-22 16:55 UTC, agarciamontoro approved these changes
Soooo smooth! I love it, thanks :)

I left a couple of non-blocking comments about using explicit rgba instead of the variables with opacity.

2021-11-22 16:55 UTC, agarciamontoro commented on webapp/src/components/collapsible_checklist.tsx
> +    border: 1px solid var(--center-channel-color-08);
Should we try to always use the rgba ones?
```suggestion
    background-color: rgba(var(--center-channel-color-rgb, 0.04));
    border-radius: 4px 4px 0 0;
    border: 1px solid rgba(var(--center-channel-color-rgb, 0.08));
```

2021-11-22 16:55 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_checklists.tsx
> +    }
Why do we need the curly braces?

2021-11-22 16:55 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_checklists.tsx
> +    border:  1px solid var(--center-channel-color-08);
Same here
```suggestion
    border:  1px solid rgba(var(--center-channel-color-rgb, 0.08));
```

2021-11-22 16:56 UTC, cpoile commented on webapp/src/components/rhs/rhs_checklists.tsx
> +    }
This is the correct eslint-approved way of doing this (it was always showing up in red in my editor, now it doesn't!)

2021-11-22 17:17 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_checklists.tsx
> +    }
Oh :eyes: If eslint approves it, then it must be good.

2021-11-23 20:06 UTC, calebroseland requested changes
LGTM! Just a quick fix for the CSS/parenthesis to fix the theming

2021-11-23 20:06 UTC, calebroseland commented on webapp/src/components/collapsible_checklist.tsx
> +    background-color: rgba(var(--center-channel-color-rgb, 0.04));
```suggestion
    background-color: rgba(var(--center-channel-color-rgb), 0.04);
```

2021-11-23 20:06 UTC, calebroseland commented on webapp/src/components/collapsible_checklist.tsx
> +    border: 1px solid rgba(var(--center-channel-color-rgb, 0.08));
```suggestion
    border: 1px solid rgba(var(--center-channel-color-rgb), 0.08);
```

2021-11-23 20:06 UTC, calebroseland commented on webapp/src/components/rhs/rhs_checklists.tsx
> +    border:  1px solid rgba(var(--center-channel-color-rgb, 0.08));
```suggestion
    border:  1px solid rgba(var(--center-channel-color-rgb), 0.08);
```

2021-11-23 20:09 UTC, calebroseland approved these changes

2021-11-23 20:35 UTC, merged