Action channel name template
mattermost/mattermost-plugin-playbooks pull request #902
Opened 2021-11-23 02:58 UTC by lieut-data

#### Summary
Allow a playbook to specify a template for the channel name to be created, noting that the channel creation itself is disabled since it cannot currently be turned off:

<img width="737" alt="CleanShot 2021-11-22 at 22 50 33@2x" src="https://user-images.githubusercontent.com/1023171/142964495-f20b9db4-acd4-45e7-b4df-b09ef9f9f4d1.png">

When one is configured:

<img width="730" alt="CleanShot 2021-11-22 at 22 51 06@2x" src="https://user-images.githubusercontent.com/1023171/142964517-0197292b-67d9-4232-8428-52f4bc756f1b.png">

it appears in the preview:

<img width="811" alt="CleanShot 2021-11-22 at 22 51 32@2x" src="https://user-images.githubusercontent.com/1023171/142964545-2e539804-339c-4e33-bc9f-9b0bfd7a9c54.png">

Indeed, this section now appears at all times even when no template is specified:

<img width="842" alt="CleanShot 2021-11-22 at 22 52 21@2x" src="https://user-images.githubusercontent.com/1023171/142964596-df403688-cd50-472b-8972-c1d17f814228.png">

The start run dialog automatically fills in when choosing to run this playbook:

<img width="618" alt="CleanShot 2021-11-22 at 22 52 56@2x" src="https://user-images.githubusercontent.com/1023171/142964631-7efcf61f-d649-4da9-b200-a23ed5ee56f5.png">

#### Ticket Link
None?

#### Checklist
- [x] Telemetry updated
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-11-23 02:58 UTC, lieut-data commented
@abhijit-singh, I've been sitting on this one for a while as you might recall. Decided to polish it up -- would love your feedback!

2021-11-23 14:59 UTC, cpoile approved these changes
Nice!

2021-11-23 14:59 UTC, cpoile commented on server/api/urls.go
> +func getAPIBaseURL(pluginAPI *pluginapi.Client) (string, error) {
This is a nice QoL improvement, thank you!

2021-11-23 14:59 UTC, cpoile commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    );
nit: just wondering why these are on separate lines? (automatic wrapping in the editor?)

2021-11-23 14:59 UTC, cpoile commented on webapp/src/components/backstage/playbook_edit.tsx
> +                                    onChannelNameTemplateChange={handleChannelNameTemplateChange}
This whole component feels like it's due for a rewrite. Not an actionable comment, just an observation for later. :)

2021-11-23 20:02 UTC, lieut-data commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    );
Purely copy-pasta in this case -- probably unnecessary, but maybe something to pass over holistically as we keep driving improvements here.

2021-11-24 18:06 UTC, abhijit-singh approved these changes
Looks awesome @lieut-data! 

I was wondering if it makes sense to add the public/private configuration here as a part of this effort?
![image](https://user-images.githubusercontent.com/14369607/143291633-5c00ef84-9328-4bbb-be32-61178a40fad1.png)
Can be done as a separate feature as well but that'll soon be the only thing in the `Permissions` tab as the new permission scheme rolls in.

2021-11-24 18:40 UTC, lieut-data commented
Ooh, that's such an awesome extension @abhijit-singh! I'm going to pull that out as a separate effort, but maybe I can recruit @crspeller to help polish that off :p

2021-11-24 18:40 UTC, lieut-data commented
(Either way, I'll update the copy as per your screenshot.)

2021-11-25 11:41 UTC, agarciamontoro requested changes
Really cool! :tada:

My comments are mostly observations and nits, the only blocking one is the one about the pattern.

2021-11-25 11:41 UTC, agarciamontoro commented on server/sqlstore/playbook.go
> +				1 + -- Channel creation is hard-coded
Good catch!

2021-11-25 11:41 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/settings.tsx
> +                        pattern={'[\\s\\S]{2,}'} // at least two characters
This allows whitespace-only strings, which are not allowed in channel names. We can either come up with a convoluted regex or refactor `PatternedInput` a bit so that `pattern` also accepts a `(string) => boolean` function, and then we can simply pass here `(s) => s.trim().length > 1`. Thoughts?

2021-11-25 11:41 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/toggle.tsx
> +    background: rgba(var(--center-channel-color-rgb), ${(props) => (props.disabled ? '0.08' : '0.24')});
Super nit: we seem to converge on using destructured arguments in styled-components when it's this short:
```suggestion
    background: rgba(var(--center-channel-color-rgb), ${({disabled}) => (disabled ? '0.08' : '0.24')});
```

2021-11-25 11:41 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/toggle.tsx
> +    input:checked + &&::before {
Why do we need the double ampersand here?

2021-11-25 11:41 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/toggle.tsx
> +        background-color: ${(props) => (props.disabled ? 'var(--button-bg-30)' : 'var(--button-bg)')}
Super nit (bis)
```suggestion
        background-color: ${({disabled}) => (disabled ? 'var(--button-bg-30)' : 'var(--button-bg)')}
```

2021-11-25 11:41 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_edit.tsx
> +                                    onChannelNameTemplateChange={handleChannelNameTemplateChange}
Absolutely, yes, this is way too big and complex.

2021-11-25 11:41 UTC, agarciamontoro commented on webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
> +        createChannelEnabled ||
Another good catch :)

2021-11-25 11:41 UTC, agarciamontoro commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                    // * Verify that the toggle is unchecked
Typo
```suggestion
                    // * Verify that the toggle is checked
```

2021-11-25 11:41 UTC, agarciamontoro commented on tests-e2e/cypress/integration/playbooks/edit_spec.js
> +                        // * Verify that the toggle checked
Typo 
```suggestion
                        // * Verify that the toggle is checked
```

2021-11-25 11:41 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/actions_spec.js
> +            });
Just curious: why the test sysadmin everywhere? Is that simply not to depend on existing users?

2021-11-25 13:37 UTC, lieut-data commented on webapp/src/components/backstage/automation/toggle.tsx
> +    input:checked + &&::before {
Hmm, I wrote this part of the PR quite a while back, but I do recall wrestling with specificity issues. I can take a closer look if we think it's an issue?

2021-11-25 13:39 UTC, lieut-data commented on tests-e2e/cypress/integration/channels/actions_spec.js
> +            });
In this case, I think the specific issue was that I didn't have the `id` of the default sysadmin, while creating a custom one guaranteed that. I need the id to make that sysadmin a member of the playbook in order to be able to return it when it's created.

2021-11-25 13:53 UTC, lieut-data commented on webapp/src/components/backstage/automation/settings.tsx
> +                        pattern={'[\\s\\S]{2,}'} // at least two characters
Ooh, good catch. Given we just pass the `pattern` directly to the `input` and rely on CSS thereafter, I'm inclined to stick with the Regular expression for now. I think `[\\S][\\s\\S]*[\\S]` is better?

2021-11-25 14:56 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/settings.tsx
> +                        pattern={'[\\s\\S]{2,}'} // at least two characters
Yeah, that works, it looks we trim the channel name in any case. Thanks! :)

2021-11-25 14:58 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/toggle.tsx
> +    input:checked + &&::before {
Oh, if it's a specificity issue then it makes sense. Styled components are great, but still CSS :sob:

2021-11-25 14:59 UTC, agarciamontoro commented on tests-e2e/cypress/integration/channels/actions_spec.js
> +            });
Sounds good, thanks for the context!

2021-11-25 14:59 UTC, agarciamontoro approved these changes
Thanks!

2021-11-25 18:43 UTC, merged