[MM-38832] Update Run overview automatically
mattermost/mattermost-plugin-playbooks pull request #908
Opened 2021-11-25 08:15 UTC by shadowshot-x

#### Summary

This Pull Request updates the retrospective, set of status posts, description, timeline and status of run in real time for page `playbooks/runs/{run_id}/`

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/18568

#### Checklist

- ~[ ] Status of Run~
- ~[ ] Description~
- ~[ ] Overview~
- ~[ ] Retrospective~
- ~[ ] Timeline~
- [ ] Add Screenshots and gif to pull request
- [ ] Test for Multiple Accounts
- [ ] ASk the team about race conditions during Retrospective Edit. (Currently while editing, the retrospective does not change if a socket action is trigerred.)

2021-11-25 08:15 UTC, mattermod commented
Hello @shadowshot-x,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-11-25 09:45 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
> +        if (!editing) {
We need to think about race conditions. If 2 people are editing the retrospective at the same time, how should we handle that? Currently, if 2 people are simultaneously editing and one saves the retrospective, the retrospective will not be updated for the other editor while in edit mode. This will prevent a race condition when both are editing the same part. [ I am handling race conditions like this. It would be good to know if there is some other technique to handle this. ]

2021-12-03 16:13 UTC, cpoile requested changes
Hey @shadowshot-x, thank you for the contribution! This is awesome. 
There are a couple things that need work, let me know if you have any questions or are confused about what's needed. 
Thanks again!

2021-12-03 16:13 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        } else {
I think this is a good idea, but `useRun` doesn't fetch the `playbookRunMetadata` -- what will happen if we don't have the metadata?

2021-12-04 04:33 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
> +        if (!editing) {
Sure @cpoile.

2021-12-04 04:39 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
> +    // sorting somehow breakes the application
Right, being in place might be an issue that was throwing an error related to changing a constant prop.

2021-12-04 05:00 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        }
I agree, I was testing to minimize data calls and left it here. This has been handled above too. Thank You for reminding :D

2021-12-04 05:45 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        } else {
Whenever the Run Overview page is loaded, the else statement is run first while `useRun` fetches the `currentRun`. So, Metadata is first set to the actual values. If we don't have the metadata, the case will be handled just like it was being handled before in `line 288`. Although the followers are not being dynamically updated because of this, I have not called `fetchMetadata` in the if statement to reduce the number of calls to the server. Do you want me to make the followers dynamic? However, this might increase the server calls.

2021-12-06 11:45 UTC, iomodo reviewed
Awesome! Thanks for the contribution @shadowshot-x 
One minor question below

2021-12-06 11:45 UTC, iomodo commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
> +    if (props.playbookRun.status_posts.length >= 0 && props.playbookRun.summary) {
Could you elaborate on this change?

2021-12-06 12:27 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
> +    if (props.playbookRun.status_posts.length >= 0 && props.playbookRun.summary) {
Hi @iomodo. I saw that Summary(description) was not being displayed when there we no status posts. So, i did this change.

2021-12-14 05:35 UTC, shadowshot-x commented
@cpoile @iomodo Any further review? I have pushed some new commits to match the existing repository changes.

2021-12-15 20:51 UTC, cpoile requested changes
Hey @shadowshot-x Sorry for the delay on reviewing this -- it's almost there, great work thank you!

2021-12-15 20:51 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
> +    if (props.playbookRun.status_posts.length >= 0 && props.playbookRun.summary) {
Then probably it should be:

```suggestion
    if (props.playbookRun.summary) {
```

2021-12-15 20:51 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        } else {
Ideally we would have a useMetadata hook, because then we're using the same logic for runs and metadata. Does that seem like something you'd want to do? The alternative would be to not use `useRun` -- either way I think we should be consistent, because it prevents "future us" from being confused by this section of the code.  :)

2021-12-15 20:51 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
> +
This file has been changed on master, so I think you can remove any changes to `retrospective/report.tsx` in this PR.

2021-12-16 08:53 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
> +    if (props.playbookRun.status_posts.length >= 0 && props.playbookRun.summary) {
Absolutely Right! A Face Palm moment for me :man_facepalming:

2021-12-16 08:54 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
> +
Sure, I will revert changes in the next commit.

2021-12-16 09:09 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
> +
Right, I checked, it updated automatically now. Cool Addition!

2021-12-16 09:17 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        } else {
Sure, I would like to do whatever is best for the code. However, I could not find `useMetadata` hook. Can you guide me how to use this?

2021-12-16 09:20 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        } else {
Sure, I will try to implement a `useMetadata` hook and set the metadata using this.

`
if (currentRun) {
            setPlaybookRun(currentRun);
            setPlaybookRunMetadata(currentMetadata)
        }
`

2021-12-17 09:09 UTC, shadowshot-x commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +        } else {
I tried @cpoile, However, I was not able to implement an additional hook. I think we would have to use `useRun` for this PR.

2021-12-20 10:59 UTC, iomodo approved these changes
Looks good to me! @shadowshot-x thanks a lot!

2021-12-31 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @aspleenic

2022-01-26 16:27 UTC, cpoile approved these changes
Awesome, thanks @shadowshot-x! (sorry for the delay)

2022-01-26 16:28 UTC, merged

2022-01-26 16:30 UTC, shadowshot-x commented
No issues @cpoile. Glad to help :D