Mm 38590 allow disabling retrospective
mattermost/mattermost-plugin-playbooks pull request #911
Opened 2021-11-25 17:06 UTC by gbochora

#### Summary
This pull request will introduce a per-playbook configuration that allows disabling the retrospective functionality for subsequent runs created using that playbook.

- Added **Enable retrospective** toggle to playbook edit form. When disabled, **Retrospective reminder interval** and **Retrospective template** settings are disabled.

https://user-images.githubusercontent.com/4368372/143478922-c2571983-33f2-415d-9a8f-516c29ba4eee.mov

- When a run is finished, no prompt occurs after finishing a run to start a retrospective

https://user-images.githubusercontent.com/4368372/143480152-c7266e72-2605-4c56-96b9-6142defb3a7a.mov

- When viewing the playbook run details, the retrospective field should be replaced with a message indicating, “Retrospectives were disabled for this playbook run.”

https://user-images.githubusercontent.com/4368372/143480250-01a13aca-980c-4312-b212-4ba53f106c7a.mov

- When viewing playbook preview, a retrospective section is omitted

https://user-images.githubusercontent.com/4368372/143480343-f26be205-6ca8-4fdb-8130-2f59d2375869.mov

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-38590

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2021-11-25 17:06 UTC, mattermod commented
Hello @gbochora,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-12-01 17:41 UTC, cpoile commented
@abhijit-singh For the video above labelled `When viewing playbook preview, a retrospective section is omitted` -- I was chatting with @gbochora and we weren't sure if maybe you wanted the section to be there but to say something like "The retrospective step has been disabled" -- so that users might realize that that's a thing and then go and turn it on. 

Let us know, thanks!

2021-12-02 13:07 UTC, abhijit-singh commented
@cpoile @gbochora  That's a good idea but I think it is okay to completely hide retrospective from the preview page for now as not everyone viewing that page might have permission to edit the playbook and the playbook admin will have intentionally disabled it at some point.

This could also be done as a separate effort after we have the enable/disable functionality in place if feel it'll add significant value.

2021-12-03 16:31 UTC, cpoile approved these changes
Again, awesome work @gbochora!
Just one small change, and then a little conflict with master. Otherwise I'll send it to @agarciamontoro for a second look.

2021-12-03 16:31 UTC, cpoile commented on tests-e2e/cypress/integration/channels/actions_spec.js
> +    describe('when a playbook run is finished', () => {
again, this is awesome work on the e2e tests! 👍

2021-12-03 16:31 UTC, cpoile commented on webapp/src/components/backstage/playbooks/playbook_preview_retrospective.tsx
> +                    enabled={props.playbook.retrospective_enabled}
I think this was the bit we can remove, given the response from Abhijit?

2021-12-05 07:35 UTC, gbochora commented on webapp/src/components/backstage/playbooks/playbook_preview_retrospective.tsx
> +                    enabled={props.playbook.retrospective_enabled}
Yes, that's correct. I've removed and pushed changes.

2021-12-06 10:50 UTC, agarciamontoro requested changes
Great work again! There's just one tiny CSS thing below, but otherwise looks fantastic, great job :tada:

2021-12-06 10:50 UTC, agarciamontoro commented on server/app/playbook_run.go
> +// NOTE: When adding a column to the db, search for "When adding a PlaybookRun column" to see where
Good catch :)

2021-12-06 10:50 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/details_spec.js
> +        it('should shows, that retrospectives were disabled message', () => {
Typo
```suggestion
        it('should show the retrospectives were disabled message', () => {
```

2021-12-06 10:50 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
> +    font-weight: normal;
Can we make this a simple div? I think if we do that, we won't need these font rules.

2021-12-06 11:45 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
> +    font-weight: normal;
You mean like this:
```
const RetrospectiveDisabledText = styled.div`
    font-size: 20px;
    color: var(--center-channel-color);
    text-align: left;
`;
```

2021-12-06 12:22 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
> +    font-weight: normal;
Exactly, @gbochora! But I have not tested it, so I'm not sure it's exactly the same. The only concern I have with the current code is that the rules
```css
font-family: Open Sans;
font-style: normal;
font-weight: normal; 
```
are the default ones (probably overridden by the h2 style, and that's why you need them), so we should not need it.

2021-12-06 13:18 UTC, gbochora commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
> +    font-weight: normal;
I've tested, and the text is a little bolder without `font-weight: normal;`, so I've decided to leave this parameter. The rest is fine.

2021-12-06 14:52 UTC, gbochora commented
@agarciamontoro I've merged with master and pushed changes.

2021-12-06 14:56 UTC, agarciamontoro approved these changes
Great, @gbochora, thank you for all your work here :tada:

2021-12-06 14:57 UTC, merged

2021-12-06 14:58 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
> +    font-weight: normal;
That's perfect, thanks for looking into this!