[MM-32517] Disallow archived channels
mattermost/mattermost-plugin-playbooks pull request #915
Opened 2021-11-30 11:47 UTC by iomodo

#### Summary

This PR does couple of three things:
1. Removes archived channels from the suggested list in boradcast
2. If arhived channels are already selected they are shown as "Unknown Channel"
3. Refactors broadcast to channels and broadcast to users who follow, without changeing the behaviour

https://user-images.githubusercontent.com/2340127/144041580-8f6a0dff-7c2f-440c-b250-c93b4f0a0305.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-32517

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2021-12-03 11:02 UTC, agarciamontoro requested changes
Wow, this was an old ticket. Thank you for tackling this! :tada:

Just a question about consistency between the broadcasting functions (and a nit you can forget about if you want to).

2021-12-06 11:46 UTC, iomodo commented on server/app/playbook_run_service.go
> +			return nil, errors.Wrap(err, "failed to broadcast to channels")
Agree

2021-12-06 11:57 UTC, iomodo commented on server/app/playbook_run_service.go
> +			return nil, errors.Wrap(err, "failed to broadcast to channels")
Actually, it throws error when it can't post failure message on the configured channel. So maybe if message posting is failing playbook creation should fail as well?

2021-12-07 15:03 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +			return nil, errors.Wrap(err, "failed to broadcast to channels")
@iomodo: But we don't fail with the other broadcasting messages, right? I guess that if this does fail, there's a bigger problem going on :thinking:

2021-12-08 09:09 UTC, agarciamontoro approved these changes
Thanks, @iomodo! I answered in the thread above about failing on the broadcast errors, but 0/5 on the solution, so approving now :tada:

2021-12-08 21:26 UTC, crspeller requested changes

2021-12-08 21:26 UTC, crspeller commented on webapp/src/components/backstage/channel_selector.tsx
> +    channel.type !== General.ARCHIVED_CHANNEL && channel.delete_at === 0,
Archived channel is not a channel type. I think that constant is for something else. The delete at here is what counts.

2021-12-08 21:26 UTC, crspeller commented on webapp/src/components/backstage/channel_selector.tsx
> +    if (channel && channel.type !== General.ARCHIVED_CHANNEL && channel.delete_at === 0) {
Same with the channel type here.

2021-12-08 21:26 UTC, crspeller commented on webapp/src/components/backstage/channel_selector.tsx
> +    const getChannelFromID = useSelector<GlobalState, GetChannelType>((state) => (channelID) => getChannel(state, channelID));
Since we have our own selector here now can we just combine this inline function with the above?

2021-12-08 21:26 UTC, crspeller commented on server/api/playbook_runs.go
> +			channelIDs := []string{}
This seems like a weird place to check for this since we have to check again anyways and this isn't even user visible.  Maybe remove?

2021-12-08 21:26 UTC, crspeller commented on server/app/broadcast.go
> +// broadcasting to channels
All of these broadcast functions are quite similar. I feel like these should be unified and more generic. With inputs varying per location of use? They also all just use broadcast but go to different places like channels or DMs.

2021-12-13 10:16 UTC, iomodo commented on server/api/playbook_runs.go
> +			channelIDs := []string{}
This is for old playbooks which already have archived channels as a broadcast channel. When we create their run, we filter out the archived channels. Old runs do not change behaviour on the other hand.

2021-12-13 10:22 UTC, iomodo commented on webapp/src/components/backstage/channel_selector.tsx
> +    const getChannelFromID = useSelector<GlobalState, GetChannelType>((state) => (channelID) => getChannel(state, channelID));
Not sure I understood what you mean. `selectableChannels` is the selector for my channels. `getChannelFromID` gets channels from `props.channelIds`, how could we combine these?

2021-12-13 10:25 UTC, iomodo commented on server/app/broadcast.go
> +// broadcasting to channels
Totally agree, that's why I put them in one file to be more visible. Unification will change behaviour though. In this PR messages and when you get what message is not changed. I'll create new PR for that(as well as issue Alejandro mentioned), probably it could be tied to the whole notification settings effort.

2021-12-14 00:28 UTC, crspeller requested changes

2021-12-14 00:28 UTC, crspeller commented on server/api/playbook_runs.go
> +			channelIDs := []string{}
Right, but in that case (or in the case that the channel becomes archived) we do a check when we are about to send the reminder. Shouldn't that cover it?

2021-12-14 00:28 UTC, crspeller commented on server/app/broadcast.go
> +// broadcasting to channels
This file is so confusing that I would suggest fixing it in this pr.

2021-12-14 00:28 UTC, crspeller commented on webapp/src/components/backstage/channel_selector.tsx
> +    const getChannelFromID = useSelector<GlobalState, GetChannelType>((state) => (channelID) => getChannel(state, channelID));
Took a closer look at this, it's stranger then I thought. It doesn't return state, it returns a function that takes a value then calls a selector on the "stolen" state. 
This is bad because this component will re-render every time redux changes. 

The easiest way to fix this would be to just select all the channels then reference the selected array to create the `values` below.

2021-12-20 15:22 UTC, iomodo commented
Adding @calebroseland on a review since @crspeller is OOO

2021-12-23 20:18 UTC, calebroseland approved these changes
LGTM! Just one translatable string if possible

2021-12-23 20:18 UTC, calebroseland commented on webapp/src/components/backstage/channel_selector.tsx
> +            filteredChannel = {display_name: 'Unknown Channel', id} as Channel;
```suggestion
            filteredChannel = {display_name: formatMessage({defaultMessage: 'Unknown Channel'}), id} as Channel;
```

2021-12-23 20:21 UTC, calebroseland commented on webapp/src/components/backstage/channel_selector.tsx
> +            filteredChannel = {display_name: 'Unknown Channel', id} as Channel;
Else 
```suggestion
            filteredChannel = {display_name: '', id} as Channel;
```

With ... down in ChannelSelector
```tsx
                {channel.display_name || formatMessage({defaultMessage: 'Unknown Channel'})}
```

2021-12-24 10:40 UTC, merged