MM-39457: Status update modal, add 'Finish Run' flow
mattermost/mattermost-plugin-playbooks pull request #928
Opened 2021-12-07 15:08 UTC by cpoile

#### Summary
- Added Finish run flow (both for the custom modal and the interactive dialog)
- e2e tests

https://user-images.githubusercontent.com/1490756/145054316-9eca8851-100a-4b6f-ad54-cf38f19a9dea.mp4

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-39457

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

2021-12-07 15:10 UTC, cpoile commented on server/api/playbook_runs.go
> +func (h *PlaybookRunHandler) updateStatus(playbookRunID, userID string, options app.StatusUpdateOptions) (string, error) {
refactored to consolidate the logic between the dialog and api endpoints

2021-12-07 15:10 UTC, cpoile commented on server/api/playbook_runs.go
> +	if options.Reminder <= 0 && !options.FinishRun {
when finishing a run we're allowing any reminder to be entered (because it will be set to 0 below)

2021-12-07 16:44 UTC, cpoile commented on webapp/src/actions.ts
> +                reopenWithState: openUpdateRunStatusModal,
this is where the magic happens :)

2021-12-07 18:08 UTC, stephenvanhemmen approved these changes
This looks great! I'll keep an eye out for feedback around this new flow, especially about runs accidentally finished

2021-12-08 10:15 UTC, iomodo approved these changes
Awesome @cpoile !

2021-12-08 10:17 UTC, iomodo commented on webapp/src/actions.ts
> +                reopenWithState: openUpdateRunStatusModal,
I was just wondering is there any other way implementing this except using the recursion?

2021-12-08 18:22 UTC, calebroseland approved these changes
Really nice! Just a few observations, but nothing major!

2021-12-08 18:22 UTC, calebroseland commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +        it.only('confirms finishing the run, and remembers changes and reminder when canceled', () => {
?
```suggestion
        it('confirms finishing the run, and remembers changes and reminder when canceled', () => {
```

2021-12-08 18:22 UTC, calebroseland commented on webapp/src/components/modals/update_run_status_modal.tsx
> +            />
Should this be bumped down into the footer?

<img width="624" alt="CleanShot 2021-12-07 at 17 07 19@2x" src="https://user-images.githubusercontent.com/11724372/145262013-375728f4-5eb1-4593-acaa-e406bda62e3b.png">

2021-12-08 18:22 UTC, calebroseland commented on webapp/src/components/widgets/confirmation_modal.tsx
> +const uncontrolledConfirmModal = (props: Props) => {
```suggestion
    dialogType: UncontrolledConfirmModal,
    dialogProps: props,
});

const UncontrolledConfirmModal = (props: Props) => {
```

2021-12-08 18:22 UTC, calebroseland commented on webapp/src/components/widgets/confirmation_modal.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
```suggestion
```

2021-12-08 18:22 UTC, calebroseland requested changes
oops

2021-12-08 20:55 UTC, cpoile commented on webapp/src/actions.ts
> +                reopenWithState: openUpdateRunStatusModal,
Yep, we can dispatch it each time directly -- I've changed it to do it that way. I'm not sure if it's cleaner, but it's simpler, so that's good. Thanks for the question!

2021-12-08 21:45 UTC, cpoile commented on tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
> +        it.only('confirms finishing the run, and remembers changes and reminder when canceled', () => {
🤦

2021-12-08 21:45 UTC, cpoile commented on webapp/src/components/modals/update_run_status_modal.tsx
> +            />
Yep, good point, done!

2021-12-08 21:45 UTC, cpoile commented on webapp/src/components/widgets/confirmation_modal.tsx
> +const uncontrolledConfirmModal = (props: Props) => {
ung, /that's/ why... Thanks! Now it makes sense why it kept giving me the rules-of-hooks error.

2021-12-09 23:05 UTC, calebroseland approved these changes

2021-12-10 15:54 UTC, merged