[MM-37629] Include non-members and auto-invite users to owner/assignee dropdowns.
mattermost/mattermost-plugin-playbooks pull request #934
Opened 2021-12-08 19:09 UTC by shadowshot-x

#### Summary
Adds Non-Channel Members to the Channel as Owners. Auto-Invite and add the non channel members.

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/18590

![Screenshot from 2021-12-08 22-13-09](https://user-images.githubusercontent.com/43992469/145268872-dbd3a5e5-8f94-4e64-b028-5065581da9f9.png)
![Screenshot from 2021-12-08 22-13-19](https://user-images.githubusercontent.com/43992469/145268871-cc5a073d-5dbb-47bb-a59d-76aeee9ed0a6.png)
![Screenshot from 2021-12-08 22-16-52](https://user-images.githubusercontent.com/43992469/145268858-97f5d690-d74d-4e8d-a040-587a9d580b15.png)

#### Checklist

- ~[ ] Modify the Modal to add Non-Channel Members~
- ~[ ] Add Modal on non-channel members click~
- ~[ ] Add the added member as owner~

2021-12-08 19:09 UTC, mattermod commented
Hello @shadowshot-x,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-12-09 08:23 UTC, agarciamontoro commented
Thank you for this, @shadowshot-x! Christopher and I will review this as soon as we can :)

Just an early FYI before the review: it seems like there's a conflict in the `rhs_about.tsx` file, could you fix that? Thank you :pray:

2021-12-09 08:54 UTC, shadowshot-x commented
Hi @agarciamontoro. Thanks for the heads up. I just saw and fixed it. PS. Kudos to the team as I can see you guys brought the E2E tests time down! :100:

2021-12-10 16:01 UTC, agarciamontoro commented
> Kudos to the team as I can see you guys brought the E2E tests time down! 100

Kudos to @Phrynobatrachus in particular!

I'll have to review this on Monday, didn't have time today :( Sorry for the inconvenience, @shadowshot-x!

2021-12-13 07:00 UTC, shadowshot-x commented
No issues @agarciamontoro

2021-12-13 13:11 UTC, agarciamontoro requested changes
This is amazing, @shadowshot-x, thank you for all your work! I tested it and worked smoothly, but I left a bunch of comments to make the code a bit simpler.

2021-12-14 04:18 UTC, shadowshot-x commented on webapp/src/components/backstage/runs_list/filters.tsx
> +                getUsersInTeam={fetchOwners}
Good catch! I will update it.

2021-12-14 04:31 UTC, shadowshot-x commented on webapp/src/components/profile/profile_selector.tsx
> +    userObj: UserProfile;
Yes we would still need `userType`. I will eliminate `userId` from here.

2021-12-14 04:33 UTC, shadowshot-x commented on webapp/src/components/profile/profile_selector.tsx
> +        const usersInTeam = await props.getUsersInTeam();
Agreed.

2021-12-14 04:44 UTC, shadowshot-x commented on webapp/src/components/rhs/rhs_about.tsx
> +        singleline: false,
Done, will push in next commit.

2021-12-14 05:01 UTC, shadowshot-x commented on webapp/src/actions.ts
> +
Sure, this is an easier way. I was following the functions in actions.ts and so I took an await based approach. Will change this in the next commit.

2021-12-14 05:01 UTC, shadowshot-x commented on webapp/src/client.ts
> +}
Right.

2021-12-14 05:02 UTC, shadowshot-x commented on webapp/src/components/profile/profile_selector.tsx
> +                    {label: 'NOT IN CHANNEL', options: userNotInChannelOptions}]}
True.

2021-12-14 05:03 UTC, shadowshot-x commented on webapp/src/components/rhs/rhs_about.tsx
> +    const channel = useSelector<GlobalState, Channel>((state) => getChannel(state, channelId));
Right, this simplifies the import. I will change this.

2021-12-15 09:55 UTC, agarciamontoro requested changes
Thank you, @shadowshot-x, it looks amazing! :tada:

I added a couple of comments below, but also when testing I found a minor issue (sorry for not catching it before):
As the `ProfileSelector` component now adds labels to the options, the filter in the runs list also shows `CHANNEL MEMBERS` (see screenshot below). It does not make sense to add the label in that case (there's no channel we can refer to), so what do you think about adding the labels only when the `userNotInChannelOptions` is not empty? If we only have elements in the `userOptions` array, it should show no labels at all.
![image](https://user-images.githubusercontent.com/3924815/146163964-6a80104a-f696-43b4-a32b-b03288363d5a.png)

2021-12-15 09:55 UTC, agarciamontoro commented on webapp/src/client.ts
> +import {GetStateFunc, batchActions} from 'mattermost-redux/types/actions';
We can probably remove this new import, right?
```suggestion
import {GetStateFunc} from 'mattermost-redux/types/actions';
```

2021-12-15 09:55 UTC, agarciamontoro commented on webapp/src/client.ts
> +import {IntegrationTypes, UserTypes, ChannelTypes} from 'mattermost-redux/action_types';
And this one!
```suggestion
import {IntegrationTypes} from 'mattermost-redux/action_types';
```

2021-12-15 09:55 UTC, agarciamontoro commented on webapp/package-lock.json
> -        "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
It looks like your last commit added modifications to this file by accident. Could you remove them?

2021-12-15 14:37 UTC, shadowshot-x commented on webapp/package-lock.json
> -        "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
Sure, I will revert it back.

2021-12-15 14:37 UTC, shadowshot-x commented on webapp/src/client.ts
> +import {GetStateFunc, batchActions} from 'mattermost-redux/types/actions';
Sure, will do in the next commit.

2021-12-15 14:38 UTC, shadowshot-x commented on webapp/src/client.ts
> +import {IntegrationTypes, UserTypes, ChannelTypes} from 'mattermost-redux/action_types';
Yes.

2021-12-15 14:39 UTC, shadowshot-x commented
@agarciamontoro, I totally agree. It does not make sense to show labels in that case. I will update the code for this.

2021-12-15 21:53 UTC, cpoile approved these changes
This is great work @shadowshot-x, very nicely done (and excellent work addressing @agarciamontoro 's comments). Thank you!

2021-12-16 08:38 UTC, shadowshot-x commented
Thank you @agarciamontoro for testing the PR. I also tested a bit on my end. I saw that I was breaking the `filters.tsx` ie. Filters were not being applied based on the owner. I have corrected it now. Also, I did the changes you asked for.

2021-12-16 09:42 UTC, agarciamontoro approved these changes
Incredible work, @shadowshot-x! Thank you again for all your efforts and patience :tada:

2021-12-16 09:42 UTC, merged