MM-40155: Remove Dismiss Prompt
mattermost/mattermost-plugin-playbooks pull request #936
Opened 2021-12-09 15:59 UTC by cpoile

#### Summary
- Removed the dismiss server code and the UI elements
- A more reasonable max-width for the snooze input
- Migrating old runs whose reminder was dismissed. Leaving runs that have an overdue reminder unchanged. (don't want to reset a reminder that recently fired, for ex.)

![image](https://user-images.githubusercontent.com/1490756/145429722-caa6e898-6e97-4a23-847e-fa80246a86a6.png)

#### UX question
- @abhijit-singh I'm making the `Post update` button not wrap. Let me know if you want it back to original

New:
![image](https://user-images.githubusercontent.com/1490756/145430583-3852a713-e87f-46b3-9572-1fa98789e816.png)

Original:
![image](https://user-images.githubusercontent.com/1490756/145429977-05bc5ce8-4e35-4d7b-bb76-931ee6c03bd0.png)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-40155

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-12-14 00:10 UTC, crspeller requested changes
Not sure I get why we are removing this functionality. Maybe we should keep it on as an option? In ether case the migration seems extreme if I am understanding it correctly.

2021-12-14 00:10 UTC, crspeller commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
Should we really do this migration? I am unsure of this decision to not allow dismiss. But resurrecting old reminders seems like it will do way more harm then good. Why not just have this decision effect future reminders?

2021-12-14 12:19 UTC, iomodo commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
I agree with @crspeller here.

2021-12-14 20:58 UTC, abhijit-singh reviewed
Thanks, @cpoile, looks good! You're right, the button text should not wrap. 

0/5 on the migration but I'm leaning towards not resurrecting any old reminders. 

A couple of minor visual points - 
1. In the RHS state, can we make the dropdown open below the input box instead of above it?
2. Can we make the width of the dropdown popup greater than that of the input box?

Current:
<img width="403" alt="Screenshot 2021-12-15 at 2 20 14 AM" src="https://user-images.githubusercontent.com/14369607/146078101-58e8c0ec-ca4a-4c89-bdd2-b8d07fd19f76.png">

Suggested:
![image](https://user-images.githubusercontent.com/14369607/146078049-a80ea325-403a-43da-b7c3-21433f1199d1.png)

2021-12-15 22:28 UTC, cpoile commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
@crspeller we did do almost this same migration earlier, resurrecting old reminders, so this isn't new. But I understand your point. @itao or @lieut-data, can you weigh in on this?

2021-12-16 13:52 UTC, lieut-data commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
Indeed, the intended behaviour of the previous change was to prohibit not having reminders at all so that runs don't just get forgotten. This just "completes" that effort.

@cpoile, one thought though: does this take into account the possibility that status updates might be disabled for a run from @gbochora's changes? We should make sure we don't set reminders for a run which can't then post a status update :)

2021-12-20 11:00 UTC, iomodo approved these changes

2022-01-03 16:41 UTC, crspeller commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
@lieut-data Do we understand that this is on the `IR_Incident` table? It resurrects old incidents and not just updates some default in the playbook? 

If I understand correctly, practical behavior of this migration is one week afterwards a flurry of updates will hit users that dismissed updates.

2022-01-04 15:04 UTC, lieut-data commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
Indeed, the goal here is to find all incidents without an active "reminder" and force them to have one, one week out from today. Hopefully, we caught most of them last time, and this change should only touch the select few that happened to squeak through due to the ability to "ignore" the reminder.

2022-01-04 17:03 UTC, crspeller commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
Alright. If that's what we want to do.

2022-01-06 19:14 UTC, merged