Show and Restore archived playbooks
mattermost/mattermost-plugin-playbooks pull request #937
Opened 2021-12-09 18:12 UTC by JulienTant

#### Summary
This PR allows users to see archived Playbooks in the backstage, and restore them.

###### TLDR:

**Server:**
-The playbook listing API now accepts a `with_archived` query (values: true/false; default false)
- The OpenAPI/Swagger file has been updated accordingly. 

**Webapp:**
- Adds a "With archived" filter
- Adds a restore option for the archived playbooks
- Show an icon+tooltip combo to indicate that a playbook is archived.

###### Screenshots:

<details><summary>Playbook list (new With archived filter + icon bellow archived playbooks)</summary>

![image](https://user-images.githubusercontent.com/785518/145450130-7bab9e21-c1b1-4852-9f42-cae97987f8b8.png)

</details>

<details><summary>Restore menu option on an archive playbook</summary>

![image](https://user-images.githubusercontent.com/785518/145450255-d74f961e-b320-4ad2-896c-60683c1d23c0.png)

</details>
<details><summary>Restore confirmation modal</summary>

![image](https://user-images.githubusercontent.com/785518/145450493-b45942ea-4ac7-4ead-b778-e371254d171e.png)

</details>

#### Ticket Link
N/A

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated
- [x] e2e tests added

2021-12-09 18:12 UTC, mattermod commented
Hello @JulienTant,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-12-20 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @BenLloydPearson @aspleenic

2022-01-12 19:03 UTC, crspeller requested changes
Sorry for the long review cycle here. This kinda got dropped over the holidays. 

The PR looks good overall. It's going to need a bit of merging work given some of the changes. Feel free to reach out to me on community server if you need some help. 

Feel free to wait until Monday to get started on this. Welcome BTW 😄

2022-01-14 00:50 UTC, JulienTant commented
> Sorry for the long review cycle here. This kinda got dropped over the holidays.

No problem!

> The PR looks good overall. It's going to need a bit of merging work given some of the changes. Feel free to reach out to me on community server if you need some help.
> Feel free to wait until Monday to get started on this. Welcome BTW smile

Thank you Christopher! I did it now as I don't quite know yet what's coming for me next week - you probably know I've not been assigned to the Playbooks team but to the Growth team.
I replicated what has been done on the "archive" part (modal on a dedicated `tsx` file).

***Note:*** Just confirmed with @cass.caplinger on the community server that the `archive` button does not refresh the page automatically. I remember hooking up on this to auto-refresh the list when a playbook was restored - so it's not working here anymore.

2022-01-14 15:32 UTC, crspeller approved these changes
Known issue with the list not updating. Need to hook that up to websockets. So not a problem here. 

Thanks!

2022-01-14 15:32 UTC, crspeller commented on webapp/src/components/backstage/playbook_list_row.tsx
> +                        </Fragment>))}
Nicer formatting? 
```suggestion
                        {infos.map((info, i) => (
                            <Fragment key={props.playbook.id + '-infoline' + i}>
                                {i > 0 && ' - '}
                                {info}
                            </Fragment>
                        ))}
```

2022-01-18 15:04 UTC, Phrynobatrachus approved these changes
JS tests seem fine, it might be possible to drop some of the `data-testid`s in favor of accessibility options but I need to look into that more myself. 

Only notable thing for me:

- the modal for "archiving" still asks about "deleting"
- ![Screenshot from 2022-01-18 10-01-38](https://user-images.githubusercontent.com/3723666/149962292-cea918e8-ca42-48c1-9bb4-e68a8be58cd7.png)
- might want change to "archive" for consistency? 
- **edit:** yes to changing the above per team meeting clarification this morning

2022-01-26 16:32 UTC, cpoile commented
Hey @JulienTant, and welcome again! Sorry for the delay on reviewing this. Do you mind merging to master and addressing Cass's comment, then I'll take a look at it? (Let us know if you need help with the merge!)

2022-01-26 18:33 UTC, JulienTant commented
> Hey @JulienTant, and welcome again! Sorry for the delay on reviewing this. Do you mind merging to master and addressing Cass's comment, then I'll take a look at it? (Let us know if you need help with the merge!)

Hi @cpoile, thanks! The wording has been changed archive and master has been merged into the branch.

2022-01-26 19:16 UTC, Phrynobatrachus approved these changes
thank you! sorry for the conflicting approval + textual 'request changes' from me before :face_with_spiral_eyes:

2022-02-01 14:58 UTC, cpoile commented
@JulienTant Sorry again, but it looks like things keep changing underneath this PR. 😅

2022-02-01 17:16 UTC, JulienTant commented
@cpoile Fixed 😅

2022-02-02 16:55 UTC, JulienTant commented on server/api/playbooks.go
> +	withArchived, _ := strconv.ParseBool(u.Query().Get("with_archived"))
[ParseBool only returns an error when the input is not supported](https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/strconv/atob.go#L10), and returns false, which is acceptable in our use case.

2022-02-02 17:06 UTC, cpoile approved these changes
yay, thanks @JulienTant!

2022-02-02 17:07 UTC, merged