MM-38150 Advanced Permissions support for playbooks.
mattermost/mattermost-plugin-playbooks pull request #943
Opened 2021-12-14 00:02 UTC by crspeller

#### Summary
Advanced permissions support for Playbooks. 

- Adding members and roles to playbooks.
- Adding ability in the system console to designate which roles have which permissions.

Permissions:
- PermissionPublicPlaybookCreate
- PermissionPublicPlaybookManageProperties
- PermissionPublicPlaybookManageMembers
- PermissionPublicPlaybookView
- PermissionPublicPlaybookMakePrivate
- PermissionPrivatePlaybookCreate
- PermissionPrivatePlaybookManageProperties
- PermissionPrivatePlaybookManageMembers
- PermissionPrivatePlaybookView
- PermissionPrivatePlaybookMakePublic
- PermissionRunCreate
- PermissionRunManageProperties
- PermissionRunManageMembers
- PermissionRunView

- Adding the full fleged concept of public and private playbooks.
- New playbook creation modal with support for templates and public/private selection.
- New permissions service to handle all permissions related queries.
- Lots of tests being migrated to the new system.

2021-12-14 00:03 UTC, crspeller commented
The cypress tests pass for me locally. Still need to figure out why they don't work on CI.

2021-12-15 19:17 UTC, crspeller commented
Tests are fixed now. Cloud e2e not expected to pass until the server changes reach that branch. (not sure when that will be)

2021-12-16 12:47 UTC, agarciamontoro reviewed
Submitting the first pass, I'll continue later. Some initial thoughts:
- I'm not sure what the differences between `Roles` and `SchemeRoles` are.
- I'd love for the permissions to have an interface that let us do something like `permissions.Playbook.Create()`, instead of `permissions.PlaybookCreate`. But that's just a nice-to-have.

2021-12-16 12:47 UTC, agarciamontoro commented on server/app/permissions_service.go
> +}
Nit: should this return just a bool like `IsSystemAdmin` does?

2021-12-16 12:47 UTC, agarciamontoro commented on server/command/command.go
> -
I guess we got rid away of these because this is centralized in the `playbookRunService`?

2021-12-16 12:47 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +				if err := addColumnToPGTable(e, "IR_PlaybookMember", "Roles", "TEXT DEFAULT 'playbook_member playbook_admin'"); err != nil {
This is a bit different than in MySQL: should we default to null, and then only add `playbook_member playbook_admin` for existing playbooks?
If we keep this and we make a mistake in the future, the default will be that everyone is an admin.

2021-12-16 12:47 UTC, agarciamontoro commented on server/api/bot.go
> +
Nit: Shouldn't this live in the permissions file?

2021-12-16 12:47 UTC, agarciamontoro commented on server/api/bot_test.go
> -package api
Why did we get rid of these tests?

2021-12-16 12:47 UTC, agarciamontoro commented on server/api/error_handler.go
> +// Retruns true if the check passed and false on failure. Correct use is: if !h.PermissionsCheck(w, check) { return }
Some typos
```suggestion
// Automatically does the proper error handling.
// Returns true if the check passed and false on failure. Correct use is: if !h.PermissionsCheck(w, check) { return }
```

2021-12-16 12:47 UTC, agarciamontoro commented on server/api/playbook_runs.go
> +		if !h.PermissionsCheck(w, h.permissions.RunManageProperties(userID, playbookRun.ID)) {
We should maybe add a RunManagePropertiesByRun (probably better named) so that we don't need to retrieve the run again, given that we already have it here.

2021-12-16 20:20 UTC, agarciamontoro reviewed
Second pass, all new code is now reviewed (although I mostly skimmed through the webapp code).
The only missing part are the sqlstore tests and the api tests. I'll get to them tomorrow morning.

2021-12-16 20:20 UTC, agarciamontoro commented on webapp/src/components/backstage/select_users_below.tsx
> +    const teamnameNameDisplaySetting = useSelector(getTeammateNameDisplaySetting) || '';
Typo here:
```suggestion
    const teammateNameDisplaySetting = useSelector(getTeammateNameDisplaySetting) || '';
```

2021-12-16 20:20 UTC, agarciamontoro commented on webapp/src/components/backstage/select_users_below.tsx
> +    color: rgb(var(--link-color-rgb));
We can probably simplify this:
```suggestion
    fill: var(--link-color);
    color: var(--link-color);
```

2021-12-16 20:20 UTC, agarciamontoro commented on webapp/src/components/backstage/public_private_selector.tsx
> +	color: ${(props) => (props.active ? 'rgb(var(--button-bg-rgb))' : 'rgba(var(--center-channel-color-rgb), 0.56)')};
We can simplify this too
```suggestion
	color: ${(props) => (props.active ? 'var(--button-bg)' : 'rgba(var(--center-channel-color-rgb), 0.56)')};
```

2021-12-16 20:20 UTC, agarciamontoro commented on webapp/src/components/backstage/public_private_selector.tsx
> +	color: rgb(var(--button-bg-rgb));
And this:
```suggestion
	color: var(--button-bg);
```

2021-12-16 20:20 UTC, agarciamontoro commented on webapp/src/components/backstage/public_private_selector.tsx
> +    };
We can probably define this as 
```suggestion
    const handleButtonClick = props.setPlaybookPublic;
```

2021-12-16 20:20 UTC, agarciamontoro commented on tests-e2e/cypress/support/index.js
> +        //}
Should we remove if not needed?

2021-12-16 20:20 UTC, agarciamontoro commented on tests-e2e/cypress/integration/runs/permissions_spec.js
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
Only you could catch this error :joy:

2021-12-16 20:27 UTC, agarciamontoro commented
@crspeller: I talked to @cpoile and @lieut-data and we all agreed that it seems too risky to merge this right before a two-week (three for me!) break. The main reasons being:
- We'll definitely miss stuff during the review.
- The main goal of merging this now is to get some soaking time before 6.3, but if there's nobody around, it will be difficult to find bugs, and more difficult to fix them.
- Also, it turns out that 6.3 is an ESR, so if something's broken, we'll have to patch it for the next six months.

So, although I know we wanted this in before the holidays, what do you think about deferring it until after we're back in January? @lieut-data offered to talk to the PMs so the decision to defer to 6.4 is well understood by everyone.

2021-12-17 15:55 UTC, agarciamontoro requested changes
Ok, I think I reviewed *everything* :tada: This is an amazing piece of work, thank you for tackling this, it's incredible!

I left some more comments, and I also have an additional general question:
- What are exacly the `Default{Playbook,Run}{Admin,Member}Role`a fields?

2021-12-17 15:55 UTC, agarciamontoro commented on server/main_test.go
> +	e.CreateAdditionalPlaybooks()
I'm slightly concerned that this `CreateBasic` function will grow indefinitely, taking a lot of time every time we call it.

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +	t.Run("unlicenced servers can't create a private playbooks", func(t *testing.T) {
Typo
```suggestion
	t.Run("unlicenced servers can't create a private playbook", func(t *testing.T) {
```

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +func TestPlaybooksRetrival(t *testing.T) {
Typo
```suggestion
func TestPlaybooksRetrieval(t *testing.T) {
```

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +	})
These tests just check that the request did not error, but we should probably retrieve the playbooks again and check that the description has indeed changed.

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +		}()
We could probably use `t.Cleanup` instead of `defer`

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +			expectedIDs := getPlaybookIDsList([]client.Playbook{*e.BasicPlaybook, *e.BasicPrivatePlaybook})
Should we create the playbooks in the test? I'm concerned we'll have to change these every time we change the basic playbooks (which may not be super frequently, but still)

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_playbooks_test.go
> +			}()
Same comment here, we can use `t.Cleanup`

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_runs_test.go
> +	})
Oh, we can create runs without playbooks?

2021-12-17 15:55 UTC, agarciamontoro commented on server/api_runs_test.go
> +func TestRunRetreval(t *testing.T) {
Typo
```suggestion
func TestRunRetrieval(t *testing.T) {
```

2022-01-03 16:50 UTC, crspeller commented on server/api/playbooks.go
> +	if teamID != "" && !h.PermissionsCheck(w, h.permissions.PlaybookList(userID, teamID)) {
Yes but it handles it with failure which it should. We actually want to succeed here since a blank team ID is valid and permissions are handled differently.

2022-01-03 16:52 UTC, crspeller commented on tests-e2e/cypress/integration/runs/permissions_spec.js
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
Only my automatic linting on save could catch this error. 😆

2022-01-03 16:58 UTC, crspeller commented on server/app/permissions_service.go
> +		}
No "" means use the default role.

2022-01-03 17:07 UTC, crspeller commented on go.mod
> +replace github.com/HdrHistogram/hdrhistogram-go => github.com/codahale/hdrhistogram v1.1.2
The build fails without it.

2022-01-03 17:10 UTC, crspeller commented on server/app/permissions_service.go
> +		return []string{"run_member", "run_admin"}
Done.

2022-01-03 19:11 UTC, crspeller commented on server/app/permissions_service.go
> +func (p *PermissionsService) PlaybookMakePrivate() {}
Good catch. This wasn't being checked properly.

2022-01-03 19:25 UTC, crspeller commented on server/api/bot.go
> +
It's only used in this file and probably unlikely to be used elsewhere.

2022-01-03 20:26 UTC, crspeller commented on server/api/playbook_runs.go
> +		if !h.PermissionsCheck(w, h.permissions.RunManageProperties(userID, playbookRun.ID)) {
https://mattermost.atlassian.net/browse/MM-40793

2022-01-03 23:01 UTC, crspeller commented on server/api/playbooks.go
> +	if !h.PermissionsCheck(w, h.permissions.DeletePlaybook(userID, playbookToRestore)) {
Ya that makes sense I think for it to be symmetric with the ability to archive/delete. We could fracture it into to permissions if we wanted to.

2022-01-03 23:02 UTC, crspeller commented on server/api/stats.go
> +		ParticipantsActive: h.statsStore.TotalActiveParticipants(filters), RunsFinishedPrev30Days: runsFinishedLast30Days,
Somehow gofmt was ok with that.

2022-01-03 23:03 UTC, crspeller commented on server/sqlstore/playbook.go
> +		LeftJoin("Schemes s ON t.SchemeId = s.Id")
We will probably always need to check permissions.

2022-01-03 23:04 UTC, crspeller commented on webapp/src/components/backstage/archive_playbook_modal.tsx
> +const useConfirmPlaybookArchiveModal = (): [React.ReactNode, (pb: Playbook) => void] => {
Its more of a component than a hook and it's very specific not a general purpose tool.

2022-01-03 23:05 UTC, crspeller commented on webapp/src/types/permissions.ts
> +export enum PlaybookPermissionGeneral {
It's entirely for simplification. The easier we make it the less permissions issues we have hopefully :)

2022-01-03 23:06 UTC, crspeller commented on webapp/src/types/playbook.ts
> +        arg.members && Array.isArray(arg.members) && arg.checklists.every((id: any) => typeof id === 'string') &&
It's not used. Deleted.

2022-01-03 23:07 UTC, crspeller commented on webapp/src/components/widgets/generic_modal.tsx
> +	z-index: 1040;
One could say magical. It is the number needed to make it so modals can appear above other modals in sequence.

2022-01-03 23:08 UTC, crspeller commented on tests-e2e/cypress/support/index.js
> +        //}
We could, but I kept it around to show differences between our version and the webapp version.

2022-01-03 23:09 UTC, crspeller commented on server/main_test.go
> +	e.CreateAdditionalPlaybooks()
Me too. It's a trade off between ease of use and speed. If we want to optimize it should be easy enough to decompose later.

2022-01-03 23:14 UTC, crspeller commented on server/api_playbooks_test.go
> +	})
Probably. I was just mindlessly copying the originals which also never tested that. I guess they had the excuse that everything was faked so there really was no point. 
https://mattermost.atlassian.net/browse/MM-40794

2022-01-03 23:17 UTC, crspeller commented on server/api_playbooks_test.go
> +		}()
`t.Cleanup` is only necessary if you are worried about state not getting cleaned up on a test panicking. In these cases I don't think we care.

2022-01-03 23:18 UTC, crspeller commented on server/api_playbooks_test.go
> +			expectedIDs := getPlaybookIDsList([]client.Playbook{*e.BasicPlaybook, *e.BasicPrivatePlaybook})
The solution here is to not change the basic playbooks. If you need a specialized one then create it for the test.

2022-01-03 23:19 UTC, crspeller commented on server/api_runs_test.go
> +	})
Apparently. There was a test for it that I copied.

2022-01-04 19:03 UTC, cpoile approved these changes
👍

2022-01-04 19:03 UTC, cpoile commented on webapp/src/types/playbook.ts
> -export function isPlaybook(arg: any): arg is PlaybookWithChecklist {
yah, I guess we should give up on this.

2022-01-04 22:28 UTC, crspeller commented on build/custom.mk
> -	go install github.com/golang/mock/mockgen
I think it was breaking because of a version mismatch.

2022-01-04 22:30 UTC, crspeller commented on server/api/playbook_runs.go
> +	if !h.PermissionsCheck(w, h.permissions.RunManageProperties(userID, playbookRun.ID)) {
We did change the frontend to say Manage Configurations. We could change it to that? Really 0/5.

2022-01-05 14:25 UTC, lieut-data commented
@crspeller, I've dismissed @agarciamontoro's review to allow us to choose to merge this. Can you help get this deployed to community today so we can use it for bug bash tomorrow?

2022-01-05 15:20 UTC, merged