MM-40305: Reorder checklists in RHS
mattermost/mattermost-plugin-playbooks pull request #944
Opened 2021-12-15 15:52 UTC by agarciamontoro

#### Summary

This PR adds the ability to reorder checklists in the RHS:
- It adds an endpoint to move a checklist (the old `/move` now moves checklists, whereas the one to move items is now called `/move-item`)
- It refactors the `DragDropContext` structure from react-beautiful-dnd:
  - it first contains a `Droppable`, where all checklists can be dropped,
  - every checklist is now a `Draggable`, with a new icon that shows on hover that acts as the handle,
  - each checklist is still a `Droppable`, with every item being a `Draggable`.
- To keep the collapsed state of every checklist in sync, I had to add a new action to the store so that we can overwrite the whole state of `Record<number, boolean>` that keeps track of it: if we move the i-th checklist to the j-th position, we need to update the state of every k-th checklist, with `i <= k <= j` (assuming `i < j`). Otherwise, the checklists would change their collapsed state depending on the position they are in. Maybe it's time to add proper IDs to checklists.

https://user-images.githubusercontent.com/3924815/146217995-a6a09321-7896-41e5-b171-02e2010493b2.mp4

This PR is based off #933, and so it should be merged after that one is merged.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40305

#### Checklist

- [X] Telemetry updated
- [ ] ~~Gated by experimental feature flag~~
- [X] Unit tests updated

2021-12-15 22:26 UTC, cpoile requested changes
This is awesome! Nice work again @agarciamontoro! Only one thing (I think) should be fixed, otherwise great!

2021-12-15 22:26 UTC, cpoile commented on server/api_runs_test.go
> +	moveChecklistTests := []struct {
nice tests (again!)

2021-12-15 22:26 UTC, cpoile commented on server/app/playbook_run_service.go
> +	playbookRunToModify.Checklists = append(playbookRunToModify.Checklists[:sourceChecklistIdx], playbookRunToModify.Checklists[sourceChecklistIdx+1:]...)
This time, because `Checklist` contains `[]ChecklistItem` it's possible that we'll have a memory leak, right? (see: https://github.com/golang/go/wiki/SliceTricks#delete).  Because in the future `checklistMoved` could be deleted from `destChecklist`, but it might still be held by `sourceChecklist`.

2021-12-16 11:04 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +	playbookRunToModify.Checklists = append(playbookRunToModify.Checklists[:sourceChecklistIdx], playbookRunToModify.Checklists[sourceChecklistIdx+1:]...)
Great catch! Please take a thorough look to https://github.com/mattermost/mattermost-plugin-playbooks/pull/944/commits/64ca0f4f575dff82820b545acc755ab67ccfa9a7: I explain in the commit what I did, and I *think* it's correct, but I'd love if you can double-check I'm right.

2021-12-17 14:21 UTC, cpoile requested changes

2021-12-17 14:21 UTC, cpoile commented on server/app/playbook_run_service.go
> +	playbookRunToModify.Checklists[len(playbookRunToModify.Checklists)-1] = Checklist{}
You'll also want to shorten the checklist, right?
```suggestion
	playbookRunToModify.Checklists[len(playbookRunToModify.Checklists)-1] = Checklist{}
	playbookRunToModify.Checklists = playbookRunToModify.Checklists[:len(playbookRunToModify.Checklists)-1]
```

2021-12-17 14:39 UTC, agarciamontoro commented on server/app/playbook_run_service.go
> +	playbookRunToModify.Checklists[len(playbookRunToModify.Checklists)-1] = Checklist{}
@cpoile: Immediately after the deletion we insert the new element, so instead of shortening the checklist and then appending a new item:

```go
// Delete
copy(c[i:], c[i+1:])
c[len(c)-1] = Checklist{}
c = c[:len(c)-1]

// Insert
c = append(c, Checklist{})
copy(c[j+1:], c[j:])
c[j] = checklistMoved
```

I simply keep the same length and copy the elements to their position:

```go
// Delete
copy(c[i:], c[i+1:])
c[len(c)-1] = Checklist{}

// Insert
copy(c[j+1:], c[j:])
c[j] = checklistMoved
```

Does that make sense?

2021-12-17 17:35 UTC, cpoile commented on server/app/playbook_run_service.go
> +	playbookRunToModify.Checklists[len(playbookRunToModify.Checklists)-1] = Checklist{}
ah, I was afraid I overlooked something, and that was it. Thanks!

2021-12-17 17:35 UTC, cpoile approved these changes
Nice work!

2021-12-23 23:01 UTC, calebroseland approved these changes
About as good as DND can get!

2021-12-23 23:02 UTC, merged