MM-40001, MM-40637: playbooks/server i18n runtime-tooling, CI-validation, and first-conversion
mattermost/mattermost-plugin-playbooks pull request #945
Opened 2021-12-15 17:54 UTC by calebroseland

#### Summary
- I18n: server runtime via `mattermost-server/v6/shared/i18n`
- I18n: server tooling
  - `make i18n-extract`
  - `make i18n-check`
- First example conversion: `/playbook todo` DM digest
  - ICU Message Format supports multiple plurals, whereas goi18n by contrast only supports a single plural context. Because of this, I removed `"from N runs"` to simplify the outstanding tasks message.
![CleanShot 2021-12-15 at 11 32 26@2x](https://user-images.githubusercontent.com/11724372/146236886-8a60357c-14e2-42a1-8a34-d71f76c62167.png)

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-38151
  - https://mattermost.atlassian.net/browse/MM-40001
  - https://mattermost.atlassian.net/browse/MM-40637

#### Checklist

Item | Y / N / NA [^1]
---|---
Telemetry updated? | NA
Gated by experimental feature flag? | N
Unit/E2E tests updated? | Y 

[^1]: Yes / No / Not Applicable.

2021-12-16 18:02 UTC, calebroseland commented
I believe an unrelated [failing E2E test](https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-playbooks/5085/workflows/16aff438-b95e-4eaa-bd6a-d3c54b3946cf/jobs/32980) in `playbooks > overview should copy playbook link`

2021-12-16 19:03 UTC, lieut-data approved these changes
Nice work, @calebroseland! A few comments below.

2021-12-16 19:03 UTC, lieut-data commented on Makefile
> +	cd server && $(GOBIN)/mmgotool i18n extract --portal-dir="" --skip-dynamic
Can we avoid the `mkdir` and copying of files if we use `--portal-dir` to specify the path? Of course, that's assuming I'm parsing the following correctly from `mmgotool`: 
https://github.com/mattermost/mattermost-utilities/blob/17ee7abdc0ccaec5d432123fcabc7fe73abe33ac/mmgotool/commands/i18n.go#L148-L159

If not, maybe a quick patch to `mmgotool` to explicitly specify where to write things?

2021-12-21 15:01 UTC, calebroseland commented on assets/i18n/en.json
> +    "translation": "- [{{.LinkName}}]({{.LinkUrl}})"
Removed. Originally for consistency with the other `md_link_item` in case an appended string were added here too, but I agree would be better to keep it free of untranslated strings.

2021-12-22 10:38 UTC, iomodo requested changes
Looks great @calebroseland! Just minor comments below.
When you merge master, e2e tests should be fixed

2021-12-22 10:38 UTC, iomodo commented on server/app/playbook_run_service.go
> +	}
duplicated code

2021-12-22 10:38 UTC, iomodo commented on server/plugin.go
> +	if err := utils.TranslationsPreInit(); err != nil {
could we get rid of the `utils` package? For the context: https://go.dev/blog/package-names

2021-12-22 10:38 UTC, iomodo commented on server/utils/i18n.go
> +	i18nDirectory, found := fileutils.FindDirRelBinary(translationsDir)
+1

2021-12-22 18:10 UTC, calebroseland commented on server/utils/i18n.go
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
File copy-pasta'd; I agree, will change

2021-12-22 18:10 UTC, calebroseland commented on server/utils/i18n.go
> +// this functions loads translations from filesystem if they are not
Wasn't aware, thanks for sharing!

2021-12-22 18:33 UTC, calebroseland commented on Makefile
> +	cd server && $(GOBIN)/mmgotool i18n extract --portal-dir="" --skip-dynamic
I believe `--portal-dir` is for https://github.com/mattermost/customer-web-server, so we'd have to make a change to `mmgotool`—long-term yes that will be better, but I didn't want to open any dependency PRs for this initial round.

2021-12-22 18:33 UTC, calebroseland commented on server/app/playbook_run_service.go
> +	}
ops!

2021-12-22 18:35 UTC, calebroseland commented on server/plugin.go
> +	if err := utils.TranslationsPreInit(); err != nil {
thanks for the link!

2021-12-22 19:09 UTC, calebroseland commented
/update-branch

2021-12-23 14:06 UTC, iomodo approved these changes
Wonderful! Thanks @calebroseland

2021-12-23 14:22 UTC, merged