[MM-40432] Add telemetry for follower notifications
mattermost/mattermost-plugin-playbooks pull request #956
Opened 2022-01-04 13:24 UTC by iomodo

#### Summary
This PR sends following events:
1. On retrospective notification sent to the follower, user clicked on retrospective URL - action is `follower_clicked_retrospective_dm`
2. On Run start notification sent to the follower, user clicked on run link(we have a backstage link) - action is `follower_clicked_run_started_dm`
3. On Run finish notification sent to the follower, user clicked on run link - action is `follower_clicked_run_finished_dm`

#### Ticket Link

  Fixes: https://mattermost.atlassian.net/browse/MM-40432

#### Checklist

- [X] Telemetry updated
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-01-04 17:30 UTC, crspeller reviewed
Concerned about the complexity here.

2022-01-04 17:30 UTC, crspeller commented on server/app/playbook_run_service.go
> +func (s *PlaybookRunServiceImpl) buildPlaybookRunCreationMessage(playbookTitle, playbookID string, playbookRun *PlaybookRun, owner *model.User) (string, string, error) {
Adding telemetry here really makes a mess of this.

2022-01-04 17:30 UTC, crspeller commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
> +    if (searchParams.has('telem') && props.playbookRun) {
This is a cool solution but it involves sticking this sort of thing all over the app. Really making components do more then they should. 

I wonder if we can solve this centrally using history.listen from react router?  https://github.com/remix-run/history/blob/main/docs/getting-started.md#listening

2022-01-11 14:25 UTC, cpoile requested changes

2022-01-11 14:25 UTC, cpoile commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +
Hopefully we can just remove this now:
```suggestion
```
🎉

2022-01-17 12:14 UTC, iomodo commented on webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
> +
removed, tested, worked like a charm. Thanks @cpoile

2022-01-18 21:12 UTC, cpoile approved these changes
🎉

2022-01-18 21:13 UTC, crspeller approved these changes

2022-01-18 21:13 UTC, merged