Mm 40660 enable retros and status updates for test data
mattermost/mattermost-plugin-playbooks pull request #967
Opened 2022-01-07 14:28 UTC by gbochora

#### Summary
This PR will update test data generation logic(`/playbooks test create-playbooks` and `/playbooks test bulk-data`).

**New Logic**:
* `/playbooks test create-playbooks n` command randomly selects unique n dummy playbooks and creates them.

* `/playbooks test bulk-data` command: 
    1. Gets playbooks list for a specific user from DB
    2. If there are no playbooks in DB, it will create dummy playbooks.
    3. Creates each run using a random playbook.

**Before**: In `command.generateTestData` and `command.actionTestGeneratePlaybooks` methods playbooks where cteated without specifying `pb.Members`. Because of that in `command.generateTestData` method, `playbookService.GetPlaybooksForTeam` call result always was empty list. 

**After**: Added playbook creator user to `Members` and `playbookService.GetPlaybooksForTeam` works properly. 

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-40660

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

2022-01-07 14:28 UTC, mattermod commented
Hello @gbochora,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-01-07 19:10 UTC, crspeller requested changes
Wondering what the purpose of the extra changes not specified in the ticket are? Not sure if there was extra context I don't have.

2022-01-07 19:10 UTC, crspeller commented on server/command/command.go
> +		dummyPlaybook := dummyListPlaybooks[randPlaybooksIndexes[i]]
You can simplify this by using https://pkg.go.dev/math/rand#Shuffle instead of the custom function.

2022-01-08 13:59 UTC, gbochora commented
Extra context from the discussion with @lieut-data  is that we agreed it would be better if some of the runs(roughly 25%) had disabled retros and status updates for diversity. 

Regarding other changes, I assumed generating unique random playbooks or choosing a random playbook for each run would give us more diverse test data.

2022-01-10 16:05 UTC, crspeller commented
>  that we agreed it would be better if some of the runs(roughly 25%) had disabled retros and status updates for diversity.

@gbochora Looks like this PR doesn't do that? Maybe I am missing it, but it looks like they all now have it enabled.

2022-01-10 17:08 UTC, gbochora commented
> @gbochora Looks like this PR doesn't do that? Maybe I am missing it, but it looks like they all now have it enabled.
In the dummy playbooks list, one item(`Blank Playbook`) out of five has disabled retros and status updates. So when a run is created, there is a 20% chance to select it. Because exactly 25% was not required, I assumed it was an acceptable approach for test data generation.

2022-01-10 17:54 UTC, agarciamontoro approved these changes
Oof, this code was a bit messy and complex, thanks for tackling these improvements! Approving now, as the code is great, but I do have one question about the PR description:

> After: Added playbook creator user to Members and playbookService.GetPlaybooksForTeam works properly.

I don't fully understand this. The call to `GetPlaybooksForTeam` in `generateTestData` grabs the playbooks the user has already defined. How is that behavior modified by adding the playbook creator user to the dummy playbooks? I suspect I misunderstood something here.

2022-01-10 18:47 UTC, gbochora commented
>I don't fully understand this. The call to GetPlaybooksForTeam in generateTestData grabs the playbooks the user has already defined. How is that behavior modified by adding the playbook creator user to the dummy playbooks? I suspect I misunderstood something here.

Generally, if we create a playbook from the web interface, 'api.playbook.createPlaybook' will be called. If members are not specified, it sets the creator user as sole admin and then calls `app.playbookService.Create` method.
In the case of the `command.generateTestData` method, we directly call `app.playbookService.Create` to create a playbook, which doesn't check/set members.

2022-01-11 10:55 UTC, agarciamontoro commented
> In the case of the command.generateTestData method, we directly call app.playbookService.Create to create a playbook, which doesn't check/set members.

That's exactly what I had missed. Thanks for the thorough explanation, @gbochora :)

2022-01-12 11:47 UTC, merged