Server dependency updates
mattermost/mattermost-plugin-playbooks pull request #969
Opened 2022-01-07 18:44 UTC by crspeller

#### Summary
Update dependencies!

2022-01-07 18:46 UTC, cpoile requested changes

2022-01-07 18:46 UTC, cpoile commented on go.mod
> +	github.com/mattermost/mattermost-plugin-playbooks/client v0.0.0-00010101000000-000000000000
this is updated in https://github.com/mattermost/mattermost-plugin-playbooks/pull/968 :P

2022-01-07 18:46 UTC, cpoile commented on go.mod
> +replace github.com/mattermost/mattermost-server/v6 => github.com/mattermost/mattermost-server/v6 v6.0.0-20220107143254-93a9c6c2931f
hmm, why do we need this separate from below?

2022-01-07 18:48 UTC, crspeller commented on go.mod
> +	github.com/mattermost/mattermost-plugin-playbooks/client v0.0.0-00010101000000-000000000000
Why? The replace line make this line meaningless. Might as well be the 000000 thing right?

2022-01-07 18:49 UTC, crspeller commented on go.mod
> +replace github.com/mattermost/mattermost-server/v6 => github.com/mattermost/mattermost-server/v6 v6.0.0-20220107143254-93a9c6c2931f
Makes updates easier by locking the server version since we need this.

2022-01-07 19:30 UTC, lieut-data approved these changes

2022-01-07 19:30 UTC, lieut-data commented on go.mod
> +replace github.com/mattermost/mattermost-server/v6 => github.com/mattermost/mattermost-server/v6 v6.0.0-20220107143254-93a9c6c2931f
Is there an opportunity to document this somehow? At first glance, it feels like a "broken" usage of the replace directive for something that's supposed to be in the `require` block. Is it an oddity related to how we version the server?

2022-01-07 19:30 UTC, lieut-data commented on go.mod
> +replace github.com/mattermost/mattermost-plugin-playbooks/client => ./client
nit: Why before the `require` instead of after? (Seems slightly weird to start reading replace directives when I haven't even encountered what they replace.)

2022-01-07 19:31 UTC, crspeller commented on go.mod
> +replace github.com/mattermost/mattermost-plugin-playbooks/client => ./client
It's what `go mod tidy` did. 🤷

2022-01-07 19:33 UTC, crspeller commented on go.mod
> +replace github.com/mattermost/mattermost-server/v6 => github.com/mattermost/mattermost-server/v6 v6.0.0-20220107143254-93a9c6c2931f
It's an oddity because there is no released server version. If you try to install anything else it will redo this and grab the most recent server version (which would actually be a downgrade). This just helpfully pins the version so we don't have to worry about it downgrading randomly.

2022-01-07 19:33 UTC, crspeller commented on go.mod
> +replace github.com/mattermost/mattermost-plugin-playbooks/client => ./client
I actually like it because the require stuff is mostly meaningless. The replace stuff is more important.

2022-01-10 17:17 UTC, cpoile commented on go.mod
> +	github.com/mattermost/mattermost-plugin-playbooks/client v0.0.0-00010101000000-000000000000
imo: because you can comment the replace directive out and run the tests to make sure the actual published module is correct

2022-01-10 17:18 UTC, cpoile commented on go.mod
> +replace github.com/mattermost/mattermost-server/v6 => github.com/mattermost/mattermost-server/v6 v6.0.0-20220107143254-93a9c6c2931f
I'm still not sure I understand -- why would the hashed version dependency (that we've always used) be downgraded?

2022-01-10 17:21 UTC, crspeller commented on go.mod
> +	github.com/mattermost/mattermost-plugin-playbooks/client v0.0.0-00010101000000-000000000000
@cpoile But the replace directive is part of the module? There isn't some other version of the module as far as I am aware?

2022-01-10 17:23 UTC, crspeller commented on go.mod
> +replace github.com/mattermost/mattermost-server/v6 => github.com/mattermost/mattermost-server/v6 v6.0.0-20220107143254-93a9c6c2931f
If you do a `go get` and add another module without the replace directive it's going to do it's minimal version selection and likely try to downgrade mattermost-server. With the replace we force it to stay there until we explicitly change it.

2022-01-10 17:31 UTC, cpoile commented on go.mod
> +	github.com/mattermost/mattermost-plugin-playbooks/client v0.0.0-00010101000000-000000000000
I'm not sure what you mean by "the replace directive is part of the module", sorry. There is version v0.7.0 which we just published... Unless you're talking about something else?

2022-01-10 17:47 UTC, cpoile commented on go.mod
> +replace github.com/mattermost/mattermost-server/v6 => github.com/mattermost/mattermost-server/v6 v6.0.0-20220107143254-93a9c6c2931f
ok, if it works it works, but we haven't had a problem with it before, have we?

2022-01-10 17:48 UTC, cpoile approved these changes

2022-01-10 18:04 UTC, crspeller commented on go.mod
> +	github.com/mattermost/mattermost-plugin-playbooks/client v0.0.0-00010101000000-000000000000
Synced offline and figured out what each other where saying. This line is totally ignored by go mod when the replace is active. But you can test mismatched versions when you comment out a replace and fill in a version here.

2022-01-10 18:12 UTC, merged