Mm 40931 playbook edit update playbook metrics backend
mattermost/mattermost-plugin-playbooks pull request #991
Opened 2022-01-22 09:53 UTC by gbochora

#### Summary
This PR adds backend functionality for storing / updating / retrieving Playbook metrics configurations.

**Change Log:**
1) Add two tables([SQL tables spec](https://docs.google.com/document/d/11wzPKfsHesAzEOX_7ljEe7893xywv-239P0J-VJWoqU/edit?usp=sharing)):
-IR_MetricConfig - to store playbooks key metrics configurations
-IR_Metric - to store runs metrics values

2) Introduced PlaybookMetric struct and Add field to playbook struct

3) Add functions to `sqlstore.playbook` for storing / updating / retrieving metrics configs.
4) Add tests for `sqlstore.playbook`. Cleaned metrics IDs in the playbook object to compare the original playbook with one from the database.

5) Add metrics configs validation on API layer:
-Validate if numbers of metrics are not more than 4
-Validate that metrics titles are unique

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40931
Epic Link: https://mattermost.atlassian.net/browse/MM-40926

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [x] Unit tests updated

2022-01-24 20:09 UTC, crspeller requested changes

2022-01-24 20:09 UTC, crspeller commented on server/sqlstore/playbook.go
> +	updateBuilder := sq.Update("IR_MetricConfig").
Nit: Little confusing because we restore them later if they are the same. Maybe add that to the comment?

2022-01-24 21:20 UTC, cpoile requested changes
Looks great, nice first big PR @gbochora! 
Some minor comments, one question about `sort` vs `order` but otherwise look great.

2022-01-24 21:20 UTC, cpoile commented on server/sqlstore/playbook.go
> +		From("IR_MetricConfig mc").
just fyi, if there's no join (and no chance for ambiguity) you don't need to add the `mc.` prefix to the columns here -- I realize it mirrors what we (blame says @crspeller ?) did for the `makeMembersSelect` but I'm not sure why we did that there either. :)
In fact, for both, we can add those selects right to the `playbookStore` struct, like we do for the `playbookSelect` statement, on line 164. That keeps them together so we remember to add new columns to it, like we do with `playbookSelect`

2022-01-25 08:59 UTC, gbochora commented on server/sqlstore/playbook.go
> +	updateBuilder := sq.Update("IR_MetricConfig").
Sure, Good idea.

2022-01-25 10:02 UTC, gbochora commented on server/sqlstore/migrations.go
> +					   Sort TINYINT NOT NULL DEFAULT 0,
I agree Order is much better, but I avoided using it because it's a reserved keyword. 
If we are ok with using reserved keywords, then I'll change. It just needs to be enclosed in backticks/double quotes.

2022-01-25 10:17 UTC, gbochora commented on server/app/playbook.go
> +	Target      int64  `json:"Target"`
Store layer returns metrics list sorted by order value. So I thought there was no need for an additional `order` parameter, Index of each element in the list defines an order. 
Do you think we may still need order value?

2022-01-25 10:27 UTC, gbochora commented on server/sqlstore/playbook.go
> +		From("IR_MetricConfig mc").
I'll remove a prefix to the column. I didn't notice that there is no need for that.
Excellent point keeping selects together.

2022-01-25 14:18 UTC, cpoile commented on server/app/playbook.go
> +	Target      int64  `json:"Target"`
Nope, you're right -- let's use the array ordering, I'll change the frontend code for that.

2022-01-25 14:20 UTC, cpoile commented on server/sqlstore/migrations.go
> +					   Sort TINYINT NOT NULL DEFAULT 0,
Hmm, I just really don't want to use `Sort` -- it's too confusing. Howabout `Ordering`?

2022-01-25 20:01 UTC, cpoile approved these changes
One last suggestion (for the export), otherwise ready to merge. Thanks @gbochora!

2022-01-25 20:47 UTC, cpoile commented on server/app/playbook.go
> +	Target      int64  `json:"Target"`
This caused a bug in the frontend:

```suggestion
	Target      int64  `json:"target"`
```

2022-01-26 04:37 UTC, gbochora commented on server/app/playbook.go
> +	Target      int64  `json:"Target"`
Oh, I missed that : )) Fixed.

2022-01-26 04:37 UTC, gbochora commented on server/app/playbook.go
> +	Metrics                              []PlaybookMetricConfig `json:"metrics" export:"-"`
Fixed, Thanks.

2022-01-26 15:31 UTC, crspeller requested changes
Just one thing for export.

2022-01-26 15:31 UTC, crspeller commented on server/app/playbook.go
> +	Metrics                              []PlaybookMetricConfig `json:"metrics" export:"metrics"`
One more step for the export here since this is a struct. You need to add the `export` struct tag to the `PlaybookMetricConfig` struct and also add it to the GeneratePlaybookExport function here: https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/app/export.go#L53

Sorry this is so complicated. I thought that since there was only one exported struct in all this time they would be rare. Seems like I was wrong 😆

2022-01-26 18:01 UTC, crspeller approved these changes

2022-01-26 19:45 UTC, merged