Export and Import UI
mattermost/mattermost-plugin-playbooks pull request #993
Opened 2022-01-24 18:16 UTC by crspeller

#### Summary
UI for import and export of playbooks

Export Link (downloads on click):
![image](https://user-images.githubusercontent.com/3191642/150840399-1a3086ec-6c44-49fc-905e-55981c1d7422.png)
![image](https://user-images.githubusercontent.com/3191642/150840429-8797b67e-b89f-409d-89fc-5024c1a0e948.png)

Import button (instant select file if you only have one team):
![image](https://user-images.githubusercontent.com/3191642/150840488-1a2741cd-2966-48c4-9cb9-ba951cb4c95d.png)

Import team selection:
![image](https://user-images.githubusercontent.com/3191642/150840560-5cd1af93-d30b-459e-82e8-6eeaa3ab63fc.png)

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-40840
https://mattermost.atlassian.net/browse/MM-40842

2022-01-24 18:22 UTC, crspeller commented
@Phrynobatrachus These jest test failures don't seem related to what I edited here. Have you seen these before? Could you take a look?

2022-01-24 18:41 UTC, Phrynobatrachus commented
I haven't seen this before. `ChecklistItemState` is an enum so it should always be "initialized" right? Some quick searching suggests that it might be a circular dependency issue, I'll keep looking.

2022-01-24 19:16 UTC, Phrynobatrachus commented on webapp/src/types/playbook.ts
> +import {getAPIUrl} from 'src/client';
I think this is the reason for the Jest failures. 

`src/client` imports `src/types/playbook`

2022-01-24 19:31 UTC, crspeller commented on webapp/src/types/playbook.ts
> +import {getAPIUrl} from 'src/client';
Thanks! Weird that it only complains in the tests.

2022-01-24 21:32 UTC, Phrynobatrachus commented on webapp/src/types/playbook.ts
> +import {getAPIUrl} from 'src/client';
Yeah it is a bit odd, there's apparently a decent amount more (23 according to [this Webpack plugin](https://github.com/aackerman/circular-dependency-plugin#basic-usage) I tested with real quick) that don't seem to cause issues.

2022-01-25 16:00 UTC, iomodo approved these changes
Looks great! Just minor nits you can ignore

2022-01-25 16:00 UTC, iomodo commented on webapp/src/components/backstage/playbook_list.tsx
> +                        }
```js
teams.length > 1 ? <TeamSelector...   :  <ImportButton..
```
might be easier to digest.

2022-01-25 16:00 UTC, iomodo commented on webapp/src/client.ts
> +    const href = `${getAPIUrl()}/playbooks/${playbook.id}/export`;
shouldn't we be consistent using `getAPIUrl()` vs `apiUrl`? I'd remove `getAPIUrl()` altogether for consistency

2022-01-25 18:12 UTC, crspeller commented on webapp/src/client.ts
> +    const href = `${getAPIUrl()}/playbooks/${playbook.id}/export`;
Yup. This happened when I fixed the curricular dependency.

2022-01-25 18:12 UTC, crspeller commented on webapp/src/components/backstage/playbook_list.tsx
> +                        }
Personally I think the ternary is more confusing.

2022-01-25 22:46 UTC, calebroseland requested changes
Nice to see the whole flow! Works well, though I have a request or two:
- `accept` attr on the input to make file format more obvious
- after successful import: either refresh playbooks list (mirroring the `duplicate` flow), or preferably—navigate to the imported playbook to see/confirm details (same as what happens after `create -> save`)


Some sort of success message would also be nice, but along with `duplicate`, this would perhaps be better as a follow-up ticket.

2022-01-25 22:46 UTC, calebroseland commented on webapp/src/components/backstage/playbook_list.tsx
> +                            type='file'
```suggestion
                            type='file'
                            accept='*.json,application/JSON'
```

2022-01-26 16:08 UTC, crspeller commented on webapp/src/client.ts
> +}
Maybe, but I don't want to break the current pattern in that file. Maybe we can do that as a holistic change?

2022-01-26 16:08 UTC, crspeller commented
@calebroseland Nice suggestions! I did the redirect to the view page of the new playbook. Feels nicer!

2022-01-26 20:39 UTC, calebroseland approved these changes
Thanks, @crspeller!

2022-01-27 20:13 UTC, abhijit-singh approved these changes
Awesome stuff @crspeller!

A couple of tiny non-blocking nits:
1. Might be valuable to add `playbook` to the name of the exported file? Maybe something like `customer_onboarding_playbook.json` instead of adding `export`. While looking for the file later I'm personally much more likely to search by the word `playbook` than `export` for the playbook I downloaded. Also might help build some brand recognition if that file is shared.
2. Can the team selector dropdown be positioned just below `import` the button instead of overlapping on it?
![image](https://user-images.githubusercontent.com/14369607/151436581-24ceee5b-3617-4d13-8eda-86f8fe3cde33.png)
Thanks!

2022-01-27 21:48 UTC, merged